### ISSUE TITLE
BUG: automcomplete of tab for "cd .." is not 100% working

### ISSUE THREAD

**Issue by willi84** [stackblitz/webcontainer-core#1]
When you are on the command line and want to go folder(s) above and type " cd .." and want to autocomplete with tab, it doesn't give you the "/"

**Comment by SamVerschueren** [comment]
`..` is an actually an alias for `cd ..`. 

What I did notice though is that if you type `../` it doesn't auto complete either. So that's something we need to fix.

**Comment by willi84** [comment]
sry. forgot the "cd"

**Comment by KwintenP** [comment]
It works differently in other shell implementations so for the time being, we'll resort to using the logic that we have and won't implement this.
