### ISSUE TITLE
Add an option to silence console output

### ISSUE THREAD

**Issue by Rich-Harris** [stackblitz/webcontainer-core#1000]
**Is your feature request related to a problem? Please describe:**

When calling `spawn(...)`, the `output` of the returned process is a `ReadableStream` that can be used to simulate a terminal UI:

```js
import { writable } from 'svelte/store';

const logs = writable([]);

// later...
const process = await vm.spawn('turbo', ['run', 'dev']);
process.output.pipeTo(new WritableStream({
  write(chunk) {
    if (chunk === '\x1B[1;1H') {
      // clear screen
      logs.set([]);
    } else {
      const log = converter.toHtml(chunk);
      logs.update(($logs) => [...$logs, log]);
    }
  }
}));
```

But the output is _also_ logged to the console:

https://user-images.githubusercontent.com/1162160/225334859-bfa63d11-09dc-47d2-9817-52d160ff1011.mov

This makes the console much less useful — things we _want_ to see in the console are drowned out by things like HMR updates (exacerbated by the treatment of the 'clear screen' command, which fills up the console with whitespace).

**Describe the solution you'd like:**

An option to `spawn` that silences the console output:

```js
const process = await vm.spawn('turbo', ['run', 'dev'], {
  console: false
});
```

There's an existing `output: false` option but this does the opposite of what we need.

**Describe alternatives you've considered:**

An option passed to `WebContainer.boot(...)` that disables the console globally. (Probably less useful.)

**Comment by jrvidal** [comment]
:wave: Thanks for the report. We might disable devtools output all together. I'll create a ticket internally to track this.

**Comment by Rich-Harris** [comment]
Ah, interesting — the same would presumably apply to all ANSI codes, in which case we'd lose styling, which definitely wouldn't be ideal. Might need to keep using the current `output` stream in that case, and just live with the `stdout`/`stderr` merging

**Comment by jrvidal** [comment]
We've disabled the console output for API consumers for the time being, so this issue should be fixed now!
