### ISSUE TITLE
Generation Issue

### ISSUE THREAD

**Issue by IbrahimFaisal399** [stackblitz/webcontainer-core#1001]
### Describe the bug

The `ng generate component product-alerts` command is not generating the desired files.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-dccmkg?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

1. Go to the following link: 
https://stackblitz.com/edit/angular-dccmkg?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html
2. Click on the project Ygdmgo
3. scroll down to the terminal, where the command has been run
4. spot error

### Expected behavior

I expected that the command would generate a component in 3 parts, a part per file, product-alerts

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 111.0.0.0
Major version = 111
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63806423,
  "usedJSHeapSize": 59377819,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6df6cd42ba0b81666017ec43c5c96e159ca2f943
```

**Comment by SamVerschueren** [comment]
Hi @IbrahimFaisal399 👋 . I tried it and it does seem to generate the files for me?

<img width="952" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/1913805/26c98d2a-7354-4eff-8769-337ec47b6712">

Can you try it again? Maybe I'm missing something 🤔 .

**Comment by SamVerschueren** [comment]
Closing this issue as it got stale. Feel free to create a new issue if you are still running into this.
