### ISSUE TITLE
[@webcontainer/api] when will this package support ESM?

### ISSUE THREAD

**Issue by LarchLiu** [stackblitz/webcontainer-core#1006]
I want to integrate webcontainer into nuxt which recommends using ESM.

Is there any plan about this?

**Comment by privatenumber** [comment]
If you're asking when the `@webcontainer/api` will be distributed in ESM, it looks like it's always been ESM:
- https://unpkg.com/@webcontainer/api/package.json
- https://unpkg.com/@webcontainer/api@1.1.0/dist/index.js

**Comment by d3lm** [comment]
Hey there 👋 Thanks for the report. @privatenumber is right, the WebContainer API is distributed using ESM.

**Comment by privatenumber** [comment]
That looks like a bug then.

ESM doesn't allow directory imports but [L8 is importing the `./vendor` directory](https://unpkg.com/browse/@webcontainer/api@1.1.0/dist/index.js#:~:text=import%20%7B%20Comlink%20%7D%20from%20%27./vendor%27%3B).

Instead, it should be `import { Comlink } from './vendor/index.js'`

**Comment by d3lm** [comment]
We have just published [1.1.2](https://www.npmjs.com/package/@webcontainer/api) which should fix this issue. Let us know if you're running into issues with it. I will close this issue for now but we can reopen if necessary.
