### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by SX-9** [stackblitz/webcontainer-core#1015]
**Is your feature request related to a problem? Please describe:**

Maybe the current shell isnt good enough, maybe people want another runtime instead of nodejs, maybe people want more!

**Describe the solution you'd like:**

A package manager allows more to make with the web containers api

**Describe alternatives you've considered:**

Or maybe ability to import and run linux executables in webcontainers? 

**Additional context:**

**Comment by SX-9** [comment]
can you at least tell me how to do this ![SmartSelect_20230425-205959_Chrome.jpg](https://user-images.githubusercontent.com/90962949/234300791-c24c7af4-0ade-4635-913b-c60f0e2912fb.jpg)

**Comment by so1ve** [comment]
I think they are possible but need lots of extra work :( You have to create many projects like pyodide
