### ISSUE TITLE
React vite is not working 

### ISSUE THREAD

**Issue by Orta12** [stackblitz/webcontainer-core#1017]
### Describe the bug

I am create a react application using vite but app is not working here is a image 

![Screenshot_1](https://user-images.githubusercontent.com/105583437/228190853-8109f637-67ae-436f-8c7c-fd8600d14c29.jpg)

i reload many times 

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-cwstv4?file=index.html&terminal=dev

### Steps to reproduce

Go to main site and create a vite react JavaScript project 
the project was created successfully but 
It says Failed to boot WebContainer 

### Expected behavior

Please fix this 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/105583437/228191274-9b2852a6-0798-4d59-83c8-cbb776ca7a86.jpg)

### Platform

```
Browser name  = Chrome
Full version  = 109.0.0.0
Major version = 109
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60893355,
  "usedJSHeapSize": 58594163,
  "jsHeapSizeLimit": 777781248
}
Hash = 88d3a49b591611919d7d64c44b90ff5f8e939906
```

**Comment by SamVerschueren** [comment]
Hi @Orta12 👋 !

The fact WebContainer wasn't able to boot has nothing to do with the project itself. Could you open DevTools and check if you see some errors there? It should give us an indication of what's going wrong.

Is it possible you already had a couple of WebContainers projects open? If that's the case, Chrome can run out of memory. In that case you need to close some WebContainer projects and reload the page.

**Comment by SamVerschueren** [comment]
Closing this issue as it got stale. Feel free to create a new issue if you are still running into this.
