### ISSUE TITLE
somehow broke ability to update package.json using turbo add

### ISSUE THREAD

**Issue by Pyrolistical** [stackblitz/webcontainer-core#102]
**Describe the bug**
When using `turbo add ...`, the package.json is supposed to be updated. And this does indeed work when creating a new node.js project. But for my project I managed to break this somehow. I forked it and deleted all the files and the problem remains.

**To Reproduce**
1. Open this broken project https://stackblitz.com/edit/package-json-not-updating?file=index.js
2. Run the command `turbo add lodash`
3. Run the command `cat package.json`, see package.json was updated
4. Open package.json in editor, see it hasn't been updated

**Expected behavior**
Expected the editor to reflect the same contents as `cat package.json`
```json
❯ cat package.json 
{
  "name": "node-starter",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "lodash": "^4.17.21"
  },
  "scripts": {}
}
```

**Desktop:**
 - OS: macOS Big Sur 11.4
 - Browser Chrome
 - Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by KwintenP** [comment]
Hi!

🙏 for reporting. This does seem like a bug on our end!

**Comment by jrvidal** [comment]
@Pyrolistical Are you still seeing this? I can't reproduce.

**Comment by Pyrolistical** [comment]
Looks like its been fixed
