### ISSUE TITLE
throw from `boot` in unsupported environments

### ISSUE THREAD

**Issue by Rich-Harris** [stackblitz/webcontainer-core#1021]
**Is your feature request related to a problem? Please describe:**

In environments that don't support WebContainers (i.e. Safari 16.3 and below), `WebContainer.boot()` neither succeeds nor fails — it just hangs. This makes it impossible to add error handling short of kludges involving timeouts. An error is printed to the console:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1162160/229374623-ed21e79d-c89a-4bfa-8fcb-0347db12b9da.png">

Right now on learn.svelte.dev we're [working around this](https://github.com/sveltejs/learn.svelte.dev/blob/b7e2a46a52f50cdb3909acffa3b49490fb098896/src/lib/client/adapters/webcontainer/index.js#L23-L25) by detecting Safari via the UA string, but that's less ideal now that WebContainers work in 16.4.

**Describe the solution you'd like:**

It would be nice if `WebContainer.boot()` threw an error in supported environments.

**Describe alternatives you've considered:**

`WebContainer.isSupported` or `WebContainer.isSupported()` (these aren't mutually exclusive with `boot()` throwing).

**Comment by Nemikolh** [comment]
Hi @Rich-Harris! That sounds pretty reasonable!

**Comment by Rich-Harris** [comment]
hey @Nemikolh — sorry to be That Guy but just wondering if you had any sort of ETA on this? we're trying to figure out how best to redirect people from https://svelte.dev/tutorial to https://learn.svelte.dev. Ideally we'd just redirect, but we can't really do that until `learn` works for everyone, so we're weighing up whether we need to come up with something more convoluted in the meantime. Thanks!

**Comment by Nemikolh** [comment]
Hey! No worries, I completely understand your position. I'm afraid I do not have an ETA on this right now. I'll come back at you as soon as possible :pray:

**Comment by jrvidal** [comment]
`boot()` should now throw in this case. In general, yeah, we'd like to surface all errors either through `boot()` or through the `error` event. So if you find similar behavior again, please feel free to open a bug.

Thanks for the report!

**Comment by Rich-Harris** [comment]
amazing, thank you!
