### ISSUE TITLE
Example crashes when installing

### ISSUE THREAD

**Issue by mittal-shah** [stackblitz/webcontainer-core#1027]
### Describe the bug

import { CodeHighlighterModule } from 'primeng/codehighlighter';

CodeHighlighter module is crashing as it is not part of the package.json. Removing the module from app.module fixes the build.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=package.json

### Steps to reproduce

Install

### Expected behavior

Installation should be successful when opened.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 111.0.0.0
Major version = 111
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66320891,
  "usedJSHeapSize": 58957679,
  "jsHeapSizeLimit": 4294705152
}
Hash = b5037fed
```

**Comment by SamVerschueren** [comment]
Hey @mittal-shah 👋 . Thanks for reaching out.

The link you provided is a dynamic project link which I'm not able to open. Do you know where you clicked that link?

I believe the issue is not on StackBlitz, but the project (probably `primeng`?) which forgot to specify the dependency.

**Comment by SamVerschueren** [comment]
Closing this issue as it got stale. Feel free to create a new issue if you are still running into this.
