### ISSUE TITLE
Project failed to Install Dependencies

### ISSUE THREAD

**Issue by hwong668** [stackblitz/webcontainer-core#1029]
### Describe the bug

This project (https://stackblitz.com/edit/work-status-selector?file=package.json) of mine is working on Chrome but when I try it in Firefox (v111.0.1, macos) , I get the following error when booting up:
~/projects/work-status-selector
❯ yarn install && turbo start
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "too much recursion".
info If you think this is a bug, please open a bug report with the information provided in "/home/projects/work-status-selector/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I've downloaded the project onto my local machine and it is building correctly and launch in Firefox without issues

### Link to the blitz that caused the error

https://stackblitz.com/edit/work-status-selector?file=yarn-error.log

### Steps to reproduce

Go to https://stackblitz.com/edit/work-status-selector?file=package.json with Firefox browser
open the Terminal
see the error 
~/projects/work-status-selector
❯ yarn install && turbo start
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "too much recursion".
info If you think this is a bug, please open a bug report with the information provided in "/home/projects/work-status-selector/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### Expected behavior

project should boot the same across browsers

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 111.0
Major version = 111
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
performance.memory = undefined
Hash = b5037fed
```

**Comment by Nemikolh** [comment]
Hi @hwong668!

Your project contains a `package-lock.json`, so I've tried running:

```bash
turbo install && turbo start
```

and it worked fine in Firefox. Are you still experiencing an issue?

**Comment by SamVerschueren** [comment]
Closing this issue as it got stale. Feel free to create a new issue if you are still running into this.
