### ISSUE TITLE
[CodeFlow] GitHub branch checkout

### ISSUE THREAD

**Issue by dr-vortex** [stackblitz/webcontainer-core#1030]
### Describe the bug

When working with a GitHub repository in CodeFlow, the source control tab exhibits some incorrect behavior.

First, CodeFlow incorrectly claims the user needs to create a new branch to commit changes. While this may be intentional design, it would be much more user friendly in CodeFlow followed VS Code's behavior of allowing the user to push to the current local branch. Below is a screenshot of the current behavior:
![image](https://user-images.githubusercontent.com/75621402/231313696-5187c764-8e3e-4158-8791-d689c051ffaa.png)

The first issue leads to the second. The new branch is created with the name `<user name>/<branch name>`. For example, if the user `octocat` has a repository `example`, CodeFlow will create `octocat/patch-<number>`. This leads to frustration since we do not want the user's name in the branch name.

Note: the "Link to the blitz that caused the error" is redacted since the repository (and blitz) contain some sensitive information.

### Link to the blitz that caused the error

\<Redacted>

### Steps to reproduce

1. open `pr.new/github.com/<user name>/<repo name>`
2. go to source control tab
3. press the "Create & Push Branch" button
4. Observe errors

### Expected behavior

I expect the source control panel to follow the same behavior as VS Code:

- The user should be able to commit and push to the current branch without creating a new one (by default)
- When creating a new branch, the default name should not contain the user's username

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

*See description*

### Platform

```
Version = 1.72.0
Hash = dc4a8026b489e84c4492bef61d05eb0b88b5e30d
WebContainer = b5037fed

Browser name  = Chrome
Full version  = 111.0.0.0
Major version = 111
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 98894571,
  "usedJSHeapSize": 77370055,
  "jsHeapSizeLimit": 2020605952
}
```

**Comment by samdenty** [comment]
this is intended behaviour, you can always use the native vscode UI (aka stuff that we didn't add) to get native behaviour
