### ISSUE TITLE
BUG: pnpx 

### ISSUE THREAD

**Issue by linbudu599** [stackblitz/webcontainer-core#104]
**Describe the bug**

`pnpx` is not working, reporting the error below:
![image](https://user-images.githubusercontent.com/48507806/119805431-d2643b00-bf13-11eb-90fc-a6a3ebb4a122.png)

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-kw3dh7
**To Reproduce**
- `npm add pnpm`
- `pnpx create-react-app` (or any commands by `pnpx`)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KwintenP** [comment]
This seems to be a bug indeed!

🙏 for reporting!

**Comment by jrvidal** [comment]
This is now fixed :tada:

**Comment by okikio** [comment]
How did you get pnpm installed?

**Comment by geromegrignon** [comment]
Hey @okikiom,

Using a WebContainer Stackblitz project, you can use the `npm add pnpm` command in the terminal.

**Comment by okikio** [comment]
@geromegrignon I tried that with but it didn't work, https://stackblitz.com/github/okikio/native/tree/beta

**Comment by geromegrignon** [comment]
> @geromegrignon I tried that but it didn't work, https://stackblitz.com/github/okikio/native/tree/beta

Please provide more details about `it didn't work` part.

**Comment by geromegrignon** [comment]
Btw @okikio, this issue being closed already, I encourage you to open a proper one with details about your current problem.

**Comment by okikio** [comment]
> Hey @okikiom,
>
> Using a WebContainer Stackblitz project, you can use the npm add pnpm command in the terminal.

This is the error I get on StackBlitz
![image](https://user-images.githubusercontent.com/17222836/141355915-16bee341-e626-46aa-a64e-78d287c0cc66.png)

**Comment by okikio** [comment]
I'll create a new PR

**Comment by okikio** [comment]
I've created a new issue #396
