### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by IQ-Thinker** [stackblitz/webcontainer-core#1040]
### Describe the bug

The command does not work!

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-setmvj?file=index.js

### Steps to reproduce

Go to the terminal and type "git clone https://github.com/[user]/[repo_name].git

### Expected behavior

It should clone.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

None

### Platform

```
Browser name  = Chrome
Full version  = 112.0.0.0
Major version = 112
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.39
performance.memory = {
  "totalJSHeapSize": 85626866,
  "usedJSHeapSize": 59885054,
  "jsHeapSizeLimit": 2172649472
}
Hash = 95b70c8d
```

### Additional context

None

**Comment by Nemikolh** [comment]
Hi @IQ-Thinker! :wave: 

You can use `git` (the command line utility) with [CodeFlow](https://stackblitz.com/codeflow) but not with our classic editor. If you want to keep using the classic editor, you [can import your repository](https://developer.stackblitz.com/guides/user-guide/importing-projects#import-from-github).

Let me know if you run into any issues.
