### ISSUE TITLE
How to package the node_modules into the project?

### ISSUE THREAD

**Issue by hurrykee** [stackblitz/webcontainer-core#1042]
**Is your feature request related to a problem? Please describe:**

I am developing a Aliyun Serverless function using StackBlitz. 

However, since online dependency installation is not supported, I need to package the node_modules into the project and upload it to the server. 

**Describe the solution you'd like:**

How can I package the node_modules into the project in StackBlitz?

**Describe alternatives you've considered:**

I don't have any ideas at the moment.

**Additional context:**

There are currently no images available for reference.

**Comment by SamVerschueren** [comment]
Hi @colesse 👋 . Not sure if I understand your question correctly. Do you want to still have the `node_modules` there when reloading a StackBlitz WebContainers project? So you don't have to run `npm install`?

I quickly threw something together here https://stackblitz.com/edit/node-2jxvep?file=package.json,.stackblitzrc. Basically I did an `npm install` and ran `cp -R node_modules modules` and saved the project. Now on boot, it runs `cp -R modules node_modules` to reload the node modules and it seems to work.

More ideally would be if you did `mv -R modules node_modules` so the modules only live on disk once. But if you do that and you save the project, you will loose the `modules` folder because it was renamed.

Anyways, hope this answers your question?

**Comment by colesse** [comment]
> Hi @colesse 👋 . Not sure if I understand your question correctly. Do you want to still have the `node_modules` there when reloading a StackBlitz WebContainers project? So you don't have to run `npm install`?
> 
> I quickly threw something together here https://stackblitz.com/edit/node-2jxvep?file=package.json,.stackblitzrc. Basically I did an `npm install` and ran `cp -R node_modules modules` and saved the project. Now on boot, it runs `cp -R modules node_modules` to reload the node modules and it seems to work.
> 
> More ideally would be if you did `mv -R modules node_modules` so the modules only live on disk once. But if you do that and you save the project, you will loose the `modules` folder because it was renamed.
> 
> Anyways, hope this answers your question?

Thank you for your reply.

I'm using Aliyun's EMAS Serverless, which is different from AWS Lambda.

Lambda supports online dependency installation. You just need to include a `package.json` file in the code folder you upload, and Lambda will automatically run `npm install` to install the dependencies after the code is uploaded.

EMAS Serverless does not support online dependency installation. If you need to use NPM dependencies, you need to package the `node_modules` folder with the project code and upload it to EMAS Serverless.

```
# NO

functionName
├─ index.js
└─ package.json
```

```
# YES

functionName
├─ node_modules
├─ index.js
├─ package-lock.json
└─ package.json
```

The method of copying node_modules to the modules folder using `cp -R node_modules modules` only copies and pastes `node_modules` to the `modules` folder. The folder name `modules` cannot be recognized and used by EMAS Serverless.

1. We hope to directly package `node_modules` into the code.
2. Can we use `@webcontainer/api` to export node_modules and code together?

**Comment by SamVerschueren** [comment]
Hey @colesse. Just to be clear, is this a question regarding WebContainer API? Or a question regarding projects on https://stackblitz.com?

If this is in regards to WebContainer API and you want to export everything out, currently the only thing you can do is use the [`readdir()`](https://webcontainers.io/api#%E2%96%B8-readdir) and [`readFile()`](https://webcontainers.io/api#%E2%96%B8-readfile) methods to loop over all directories and extract the content.

Or if you create a zip artifact inside the container by spawning a command, then you could do a `readFile()` of that zip directory and you have everything immediately.

**Comment by colesse** [comment]
> Hey @colesse. Just to be clear, is this a question regarding WebContainer API? Or a question regarding projects on https://stackblitz.com?
> 
> If this is in regards to WebContainer API and you want to export everything out, currently the only thing you can do is use the [`readdir()`](https://webcontainers.io/api#%E2%96%B8-readdir) and [`readFile()`](https://webcontainers.io/api#%E2%96%B8-readfile) methods to loop over all directories and extract the content.
> 
> Or if you create a zip artifact inside the container by spawning a command, then you could do a `readFile()` of that zip directory and you have everything immediately.

Hi @SamVerschueren . At first, we considered testing on StackBlitz to see if it could meet our needs. But ultimately, We hope to accomplish this through the WebContainer API.

Regarding your suggestion to package the entire project into a zip file using a command, I tried commands like:

 ` await webcontainerInstance.spawn("zip", ["-r", "myProject.zip", "/myProject"])`

 but it gave me an error message saying the command does not exist. May I ask which compression commands are supported by the Node.js environment under WebContainer?Or, which commands are supported by WebContainer in general?

**Comment by SamVerschueren** [comment]
Currently we don't support a `zip` command yet, although that might be a good idea to add.

So one thing I think might be a good workaround for now is if you had a small zip script inside your project (which you can just load or dynamically write into the fs). For example https://stackoverflow.com/questions/15641243/need-to-zip-an-entire-directory-using-node-js.

Then spawn that script and read that zip file to get it out of WebContainer fs.

Would that solve your problem?

**Comment by colesse** [comment]
@SamVerschueren Hello, tar is a built-in module in Nodejs16, but it seems that it is not supported in the WebContainer and needs to be installed manually, although the WebContainer displays that it is using Nodejs16. If WebContainer does not support tar, then I would really appreciate it if WebContainer could support it, as this module is very valuable.

![image](https://user-images.githubusercontent.com/18578249/235240906-4ceb4ab8-c5c5-47bc-83d6-9a0921ed9d53.png)

Also, I am very curious about how the "Download Project" feature in the stackblitz IDE uses a ZIP archive. Was this achieved using the WebContainer API? Can you tell me how it was implemented?

![image](https://user-images.githubusercontent.com/18578249/235243588-bd963356-97a9-4e6d-a7bd-945e81c6be62.png)

**Comment by jrvidal** [comment]
> tar is a built-in module in Nodejs16

FWIW, this is not correct: https://nodejs.org/api/tar.html
