### ISSUE TITLE
Incorrect Event loop callbacks execution order in a node.js project

### ISSUE THREAD

**Issue by zveroboy** [stackblitz/webcontainer-core#1048]
### Describe the bug

nextTick callbacks should be executed between macrotasks.

> …the nextTickQueue will be processed after the current operation is completed, regardless of the current phase of the event loop. Here, an operation is defined as a transition from the underlying C/C++ handler, and handling the JavaScript that needs to be executed.

[source](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick#understanding-processnexttick) 
> Immediately after every macrotask, the engine executes all tasks from microtask queue, prior to running any other macrotasks… 

[source](https://javascript.info/event-loop#macrotasks-and-microtasks)

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-u4nbwx?file=index.js

### Steps to reproduce

1. Launch node.js project
2. Put this code in the index.js
```js
setTimeout(() => {
  console.log('--- Timer 1 ---');
  process.nextTick(() => {
    console.log('--- nextTick 1 ---');
  });
}, 0);

setTimeout(() => {
  console.log('--- Timer 2 ---');
  process.nextTick(() => {
    console.log('--- nextTick 2 ---');
  });
}, 0);

setImmediate(() => {
  console.log('--- setImmediate 1 ---');
});
```
3. Run `node index.js` in the terminal
4. You'll see incorrect execution order
```
~/projects/node-u4nbwx
❯ node index
--- setImmediate 1 ---
--- Timer 1 ---
--- Timer 2 ---
--- nextTick 1 ---
--- nextTick 2 ---
```

### Expected behavior

It should print out
```
--- Timer 1 ---
--- nextTick 1 ---
--- Timer 2 ---
--- nextTick 2 ---
--- setImmediate 1 ---
```
or
```
--- setImmediate 1 ---
--- Timer 1 ---
--- nextTick 1 ---
--- Timer 2 ---
--- nextTick 2 ---
```

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1439" alt="Снимок экрана 2023-04-24 в 23 26 09" src="https://user-images.githubusercontent.com/747609/234108665-308ba247-c12a-4804-bf77-3b7c56fbba69.png">
<img width="504" alt="Снимок экрана 2023-04-25 в 01 18 28" src="https://user-images.githubusercontent.com/747609/234128671-f34d0925-a05c-46e7-8079-aa1cc5acdd33.png">

### Platform

```
Browser name  = Chrome
Full version  = 112.0.0.0
Major version = 112
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63087190,
  "usedJSHeapSize": 58269934,
  "jsHeapSizeLimit": 4294705152
}
Hash = 95b70c8d
```

**Comment by SamVerschueren** [comment]
Hi @zveroboy. Thanks for reaching out! This is indeed a limitation and very hard to fix due to browser limitations. We already track this internally so we can improve the event loop over time.

You can find more information on this topic in this thread https://github.com/stackblitz/webcontainer-core/issues/980.
