### ISSUE TITLE
Race condition when extension tried loading a module before packages install

### ISSUE THREAD

**Issue by FireMasterK** [stackblitz/webcontainer-core#1049]
### Describe the bug

When an extension (in this case unocss) tries looking for a module before it installs, it fails hard.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/TeamPiped/Piped

### Steps to reproduce

1. Open the stackblitz
2. UnoCSS's intellisense won't work (See the output for the extension)

```
🛠 Resolving config for /home/TeamPiped/Piped
⚠️ Error on loading config. Config directory: /home/TeamPiped/Piped
Error: Cannot find module 'unocss'
Require stack:
- /home/TeamPiped/Piped/uno.config.js
➖ No config found, UnoCSS is disabled
```

### Expected behavior

The UnoCSS extension can find the module.

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Linux
- Browser: Brave
- Version: 1.50.125 Chromium: 112.0.5615.165

**Comment by FireMasterK** [comment]
> Is this actually also an issue on local? What if you do a fresh clone of that repository, open the repository with VSCode and then run `npm install`? I assume it's also broken?

I guess you're right, it does happen locally too! But you can open and close VSCode, which fixes the issue. You can't really do that on stackblitz as it has to reinstall the packages again.

**Comment by SamVerschueren** [comment]
What you can do in this case is call the `Reload UnoCSS` command through the command pallette

![image](https://user-images.githubusercontent.com/1913805/234885010-a9461e3b-9b21-4d6e-af4f-69e1cfae0824.png)

This is a bit annoying but I don't think we can do something about it, this is just how extensions work. One thing that might fix this is if UnoCSS uses a file watcher or something to detect new package installations (which might be what others do). Or re-check every time a CSS file is opened.

Would you mind opening an issue in the [`unocss`](https://github.com/unocss/unocss) repository? I know Anthony Fu likes StackBlitz so he might be able to fix this.

**Comment by SamVerschueren** [comment]
Closing this issue as there's not much we can do on our side.
