### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by SampathTharanga** [stackblitz/webcontainer-core#105]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/customers-details?file=index.js

**To Reproduce**

**Expected behavior**

**Version of webcontainer**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86040075,
  "usedJSHeapSize": 75571683,
  "jsHeapSizeLimit": 2172649472
}

**Additional context**

**Comment by SamVerschueren** [comment]
Seems to be working on my end. Feel free to open a new issue or reply with what is not working on your end and we're happy to help.
