### ISSUE TITLE
Safari CORs issue with static assets.

### ISSUE THREAD

**Issue by nicksrandall** [stackblitz/webcontainer-core#1050]
### Describe the bug

I'm using web containers api and unable to do an NPM install command on Safari because the `t.staticblitz.com` domain does not include proper CORs headers, and so Safari errors with:

```txt
Failed to load resource: Origin https://stackblitz.com is not allowed by Access-Control-Allow-Origin. Status code: 200
```

Example failed request: 

```txt
https://t.staticblitz.com/w/v13/h/e/react-dom@18.2.0?o=https://stackblitz.com
```

### Link to the blitz that caused the error

n/a

### Steps to reproduce

Try to start a basic `@webcontainers/api` project using the latest safari browser. 

### Expected behavior

I expect the static resources to include cors headers. 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Safari
- Version: Latest (and technical preview)

**Comment by SamVerschueren** [comment]
Hi @nicksrandall 👋 ! Thanks for reaching out!

The headers should be working correctly though, so not sure what's going wrong. For example, [SvelteLab](https://www.sveltelab.dev) works perfectly fine in Safari, and our own documentation website [webcontainers.io](https://webcontainers.io) works correctly with installing dependencies.

Can you post screenshots of the request and response you see in Safari? That might help to see what's going on here.

**Comment by SamVerschueren** [comment]
Closing this issue as it got stale. Feel free to create a new issue if you are still running into this.
