### ISSUE TITLE
Accessing iFrame HTML

### ISSUE THREAD

**Issue by jackkimball13** [stackblitz/webcontainer-core#1054]
**Is your feature request related to a problem? Please describe:**

I'd like to be able to get the HTML of pages that I'm previewing, so I can do things like see what classes are on different elements. Currently, this is restricted by cross origin policies and the fact that the preview is served by webcontainer.io rather than my own domain.
**Describe the solution you'd like:**

I would like a way to access the page data within the iFrame either by using the document api or postMessage api and sending messages between my page and the preview iFrame.
**Describe alternatives you've considered:**

I've considered just parsing the actual Svelte code that I've written, but then I'd have to do that for any language I'm using.
**Additional context:**

I'm trying to make a program that lets me select an element in the preview and update its class from a component running in the main window (not the preview). The goal is to create something that lets me quickly visualize tailwind classes on my components without having to find the component in my code each time.

**Comment by jrvidal** [comment]
What you're proposing sounds difficult to achieve :sweat_smile: 

> Currently, this is restricted by cross origin policies and the fact that the preview is served by webcontainer.io rather than my own domain

Assuming for a second that this were not an issue (if you could host it in your own domain), how would your project work, exactly?

**Comment by jackkimball13** [comment]
So the idea currently is to get the id of an element within the Iframe that you want to select and then search through the files of code for a matching element. Then I would have a panel of tailwind classes that could be applied to the element which would be changed in the code, triggering the page to rerender that element. 

I can handle selecting the element within the Iframe, but only from a static page I host myself since there are no cross origin issues.

**Comment by jrvidal** [comment]
Giving access to the preview document is very difficult, verging into the impossible.

However, if you are willing to `postMessage` from the content preview window to the editor window, why not `POST` something through the network instead? If you run a tiny node server in WebContainers that listens to those requests and prints something, you can gather all that input and react to it from the editor window.

That's the only workaround I can think for the moment.
