### ISSUE TITLE
Webcontainer in mobile browsers

### ISSUE THREAD

**Issue by VovaSv** [stackblitz/webcontainer-core#1057]
### Describe the bug

Can't open in mobile browsers:
Error:

Unable to read file '/home/yyy/yyy
FileSystemError: undefined is not an object

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/VovaSv/simple-nodejs-server

### Steps to reproduce

1. Open Github repo with Stackblitz via mobile browser

### Expected behavior

Working properly in mobile browsers

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.72.0
Hash = 50e2328de47f53f7bab7286aaab9403877c02e43
WebContainer = d830b1a2

Browser name  = Chrome
Full version  = 112.0.0.0
Major version = 112
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108040584,
  "usedJSHeapSize": 83321460,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by fvsch** [comment]
Hi @VovaSv,

Could you share what mobile browsers you tried (browser name, version, and OS)?
