### ISSUE TITLE
تا

### ISSUE THREAD

**Issue by complexmediacode** [stackblitz/webcontainer-core#1060]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .

**Comment by complexmediacode** [comment]
thank you
