### ISSUE TITLE
Terminal prompt not displaying in Safari browser

### ISSUE THREAD

**Issue by tjacker** [stackblitz/webcontainer-core#1065]
### Describe the bug

In Safari (16.4) on macOS (13.3.1 (a)), the terminal does not display a prompt.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-jxlgkm?file=package.json

### Steps to reproduce

1. Go to a Node.js project.
2. See in Terminal window that prompt and current directory never return.

### Expected behavior

Expect terminal to load to a user prompt.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

There are a number of cross origin errors that are not happening in Chrome.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/13052642/236633511-1c979055-14a9-4bd5-9568-8aa3b9d636fe.png">

### Platform

```
Browser name  = Safari
Full version  = 16.4
Major version = 16
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15
performance.memory = undefined
Hash = 9c984a48
```

**Comment by SamVerschueren** [comment]
Thanks for reporting @tjacker. This is weird, because I'm on the exact same macOS version, and the exact same Safari version. Does no project work at all? Something like https://node.new? Can you try removing your entire StackBlitz cache in Safari and try again? Maybe something weird got cached 🤔 .

**Comment by tjacker** [comment]
@SamVerschueren Thanks for your response. I've since upgraded to MacOS 13.4 and Safari 16.5 and the problem no longer exists. I was having the issue on all new and existing node projects before.

**Comment by SamVerschueren** [comment]
Let's close this issue. We can still come back if someone else runs into the same problem. Thanks for the follow-up!
