### ISSUE TITLE
StackBlitz cannot find Vite

### ISSUE THREAD

**Issue by archiewood** [stackblitz/webcontainer-core#1068]
### Describe the bug

failed to load config from /home/evidence-dev/template/.evidence/template/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /home/evidence-dev/template/node_modules/@sveltejs/kit/src/exports/vite/index.js
    at get (https://template-mbji.w-corp.staticblitz.com/blitz.9c984a48.js:35:344852)
    at <anonymous> (file:///home/.turbo/npx/XmLm3l/node_modules/vite/dist/node/cli.js:799:88)

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/evidence-dev/template/

### Steps to reproduce

Go to link
Wait for boot

### Expected behavior

Container should boot

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.72.0
Hash = 4a5f1e6ad7fbb9ed9022eaff440d64a02b04c3b5
WebContainer = 9c984a48

Browser name  = Firefox [Also Safari, Chrome]
Full version  = 112.0
Major version = 112
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/112.0
performance.memory = undefined
```

**Comment by archiewood** [comment]
Can confirm no vite folder in node_modules:
<img width="295" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/58074498/bd9f3a98-f9a2-4ed6-806a-98296f308f5b">

**Comment by jrvidal** [comment]
See https://github.com/stackblitz/webcontainer-core/issues/1069#issuecomment-1541532006 (different problem, but the same underlying cause).

**Comment by jrvidal** [comment]
Closing as duplicate of https://github.com/stackblitz/webcontainer-core/issues/1070, you can track it there!

**Comment by archiewood** [comment]
Are there any workarounds for this in the meantime?

**Comment by d3lm** [comment]
Hey 👋 The link doesn't work for me and it says "failed to clone". Can you provide a link that works and allows us to reproduce the issue? If it's package manager related, we have just [released native support for npm](https://blog.stackblitz.com/posts/announcing-native-package-manager-support) so you might wanna try it again.

**Comment by archiewood** [comment]
This link?

Opens for me on safari iOS


![image](https://github.com/stackblitz/webcontainer-core/assets/58074498/0570961c-1514-4af7-bb53-bf1cd6e27b6d)

https://stackblitz.com/~/github.com/evidence-dev/template

**Comment by archiewood** [comment]
this appears to be resolved
