### ISSUE TITLE
npm-check fails due to calling `npm ... --color=always`

### ISSUE THREAD

**Issue by wmertens** [stackblitz/webcontainer-core#1069]
### Describe the bug

when you have an npm-based project and run `npx npm-check -u` and update some dependency, it will run a command like `npm install @typescript-eslint/eslint-plugin@5.59.5 @typescript-eslint/parser@5.59.5 vite@4.3.5 @builder.io/qwik@1.1.0 eslint@8.40.0 eslint-plugin-qwik@1.1.0 @types/node@20.1.1 --save-dev --color=always`

This fails with an error from `turbo`. Removing the `--color=always` makes it work

### Link to the blitz that caused the error

https://stackblitz.com/edit/qwik-style9?file=src%2Froutes%2Findex.tsx,node_modules%2Fstyle9%2Fsrc%2Fhelpers%2Fvalidate.js,vite.config.ts,dist%2Fbuild%2Fq-a8c09fbf.js

### Steps to reproduce

`npx npm-check -u`

### Expected behavior

it should accept common npm flags

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 112.0.0.0
Major version = 112
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 223938441,
  "usedJSHeapSize": 205561441,
  "jsHeapSizeLimit": 2172649472
}
Hash = 9c984a48
```

**Comment by jrvidal** [comment]
:wave: Thanks for the report. This is a known limitation of `turbo`, our NPM shim.

We are actually looking into releasing "real" NPM as the default package manager real soon, which would actually solve this. I'll track this issue so we updated it when that happens.

**Comment by jrvidal** [comment]
Actually, I'm closing this in favor of https://github.com/stackblitz/webcontainer-core/issues/1070, so we centralize it a little bit.
