### ISSUE TITLE
NPM doesn't quite work as expected

### ISSUE THREAD

**Issue by jrvidal** [stackblitz/webcontainer-core#1070]
### Describe the bug

This is a tracking issue for "unmodified NPM": once this is solved, `npm` will just run unmodified, vanilla NPM instead of our `turbo` shim.

### Link to the blitz that caused the error

N/A

### Steps to reproduce

* Run `npm`

### Expected behavior

Unmodified NPM

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

**Comment by d3lm** [comment]
We have just [released support for native npm](https://blog.stackblitz.com/posts/announcing-native-package-manager-support) so I am going to close this issue.
