### ISSUE TITLE
Unable to run Embedded Project in latest firefox(114.0b6)

### ISSUE THREAD

**Issue by scarf005** [stackblitz/webcontainer-core#1077]
### Describe the bug

![image](https://github.com/stackblitz/webcontainer-core/assets/54838975/6e16070f-3974-4a18-9ee3-8d440250c105)

embedded edtior in https://tanstack.com/router/v1/docs/examples/react/basic?file=src%2Fmain.tsx fails to load.

### Link to the blitz that caused the error

https://stackblitz.com/edit/tanstack-router-5h9bdr

### Steps to reproduce

1. Visit https://tanstack.com/router/v1/docs/examples/react/basic?file=src%2Fmain.tsx
2. Editor fails to load.
3. Press `fork on stackblitz`: ![image](https://github.com/stackblitz/webcontainer-core/assets/54838975/e6a5e346-39f4-422a-99bc-acc29c7c118f)
4. Forked editor works.
![image](https://github.com/stackblitz/webcontainer-core/assets/54838975/ab072f85-3f13-440c-8ca3-69821387e415)

### Expected behavior

Embedded editor works.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Linux (Ubuntu 23.04)
- Browser: Firefox Developer
- Version: 114.0b6
![image](https://github.com/stackblitz/webcontainer-core/assets/54838975/453b0a7d-ef9b-44e4-b0da-61e96543e9d0)

**Comment by jrvidal** [comment]
Unfortunately, this is expected:

https://developer.stackblitz.com/platform/webcontainers/browser-support#embedding

> we only support embedding WebContainers-based projects in Chromium-based browsers.
