### ISSUE TITLE
Unable to execute binary

### ISSUE THREAD

**Issue by AndrewMD5** [stackblitz/webcontainer-core#1079]
I host a minimal example for [Tempo](https://tempo.im) on Stackblitz (found [here](https://stackblitz.com/edit/node-tempo)), and it is necessary to generate code from a schema during build by calling 'yarn bebopc'.

Upon doing so I receive the following error in the terminal:
```
$ /home/projects/node-tempo/node_modules/.bin/bebopc
/home/projects/node-tempo/node_modules/bebop-tools/tools/linux/x64/bebopc: line 1: a command can only contain words and redirects
```

I'm unsure what this means as we aren't even passing arguments; I verified that the executable supports piping and redirection. Is there any special considerations within the executable I should do to properly support WebContainer?

**Comment by SamVerschueren** [comment]
Hey @AndrewMD5, thanks for reaching out. I notice that `bebopc` runs some arbitrary linux x64 binary, which we don't support. Native binaries can't run in a browser, unless they get compiled to WebAssembly, like [esbuild](https://www.npmjs.com/package/esbuild-wasm) for instance.

So unless `bebopc` gets compiled to WASM, this will not work in WebContainers unfortunately.

**Comment by AndrewMD5** [comment]
Gotcha, thanks for the clarification, I wasn’t sure if there was some NIX like virtualization happening behind the scenes.
