### ISSUE TITLE
failed swc error

### ISSUE THREAD

**Issue by sridhram** [stackblitz/webcontainer-core#1082]
### Describe the bug

tried the same with code sandbox working as expected

### Link to the blitz that caused the error

https://stackblitz.com/github/sridhram/spotify-clone?file=README.md

### Steps to reproduce

run npm run dev

### Expected behavior

server should start

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 113.0.0.0
Major version = 113
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 74787679,
  "usedJSHeapSize": 60811631,
  "jsHeapSizeLimit": 4294705152
}
Hash = fc9e1a28
```

**Comment by kirjavascript** [comment]
hi :wave: thanks for reporting this!

adding `@next/swc-wasm-nodejs` as an explicit dependency fixes the install issue

the project still fails to run because of a bug with Next 13.4 in webcontainer

we're looking at it and should have a fix soon-ish

**Comment by d3lm** [comment]
Hey 👋 We fixed the issue with SWC so I am going to close this issue. Feel free to open a new ticket in case you still experience an issue.
