### ISSUE TITLE
Report an error using the git command

### ISSUE THREAD

**Issue by DingkeXue** [stackblitz/webcontainer-core#1084]
### Describe the bug

when i use webcontainerInstance.spawn('git ', ['-v']), or  webcontainerInstance.spawn('git ', ['clone', '[https://github.com/[user]/[repo_name].git']) api, return error(exit code 127).
![image](https://github.com/stackblitz/webcontainer-core/assets/43240658/a5257443-bc94-4bc4-93e4-bace6975fe86)

### Link to the blitz that caused the error

local dev, no link

### Steps to reproduce

local dev

### Expected behavior

exit code 0

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SamVerschueren** [comment]
Hi @DingkeXue 👋 ! That's correct, the `git` binary is not exposed in WebContainer API and is currently only a feature that you can use in [Codeflow](https://stackblitz.com/~).

If you want to clone code from GitHub, the best option for now might be to run a script in WebContainer API which downloads the tarball and extracts it.
