### ISSUE TITLE
Support for Node v18?

### ISSUE THREAD

**Issue by renhiyama** [stackblitz/webcontainer-core#1086]
Node v18 brought some cool features, which we much needed in our js ecosystem. APIs like `fetch` and functions like `structuredClone` are some of the cool features which is much needed in webcontainers. Removing fetch polyfill from my code removes 20kb of data (minified node fetch). I know there might be some restrictions atm, but some APIs like the above could be easily added to webcontainers?

**Comment by renhiyama** [comment]
For reference, my web framework `reejs@0.9.12` can't run here because its missing structuredClone.

**Comment by renhiyama** [comment]
I have currently included `core-js` to polyfill APIs.

**Comment by kirjavascript** [comment]
hi :wave: @renhiyama, thanks for asking this!

this issue is being tracked here: https://github.com/stackblitz/webcontainer-core/issues/560

we're planning on releasing node 18 in the next quarter or two
