### ISSUE TITLE
Support 3P SharedArrayBuffer Origin Trial

### ISSUE THREAD

**Issue by steve8708** [stackblitz/webcontainer-core#1088]
**Is your feature request related to a problem? Please describe:**
I am trying to load a webcontainer inside an iframe of a non-coep site. We think our [playground]() built with webcontainers could be an essential part of the Builder.io onboarding, but currently cannot use it because we can't safely make our entire Builder.io COEP to allow embedding our playground in an iframe due to how customers need to use us.

<img width="674" alt="Screenshot 2023-05-30 at 9 31 03 AM" src="https://github.com/stackblitz/webcontainer-core/assets/844291/74f84c16-488d-40c5-baa5-0e40a06e6231">

**Describe the solution you'd like:**
Origin-Trials fix this, but we setup an Origin Trial for SharedArrayBuffer for both Builder.io and playground.builder.io, but this isn't solving our problem because the SharedArrayBuffer script comes from a stackblitz origin, so we need a stackblitz 3p origin trial to be inserted by that script [programatically](https://developer.chrome.com/en/docs/web-platform/third-party-origin-trials/#provide-token)

```js
const otMeta = document.createElement('meta');
otMeta.httpEquiv = 'origin-trial';
otMeta.content = 'TOKEN_GOES_HERE';
document.head.append(otMeta);
```

**Describe alternatives you've considered:**
The only other option is to make all of Builder.io COEP, but that isn't possible because we need to load our users sites in our visual editor, and those sites need to embed cross origin resources through iframes (e.g. to embed a youtube video) without changes to their code, which will nor currently use things like `credentiallless`

**Additional context:**
In theory this is a very minor code change (as little as 4 lines of code)  - I would be happy to send a PR if anyone can point me in the right direction

**Comment by jrvidal** [comment]
:wave: Thanks for the report!

I think we might be able to add a new mode to the `coep` parameter ([line 88](https://www.unpkg.com/browse/@webcontainer/api@1.1.3/dist/index.d.ts)), say, `"none"`, that forgoes cross-origin headers completely and servers our _own_ origin trial (which we still use for certain embeds).

It goes without saying that this would only be a temporary, Chrome-only solution while origin trials exist...

**Comment by jrvidal** [comment]
This is now ready to give it a spin in [version 1.1.4](https://www.unpkg.com/browse/@webcontainer/api@1.1.4/dist/index.d.ts). Please feel free to open more issues if needed :pray:

**Comment by steve8708** [comment]
Incredible, thanks @jrvidal!!

**Comment by steve8708** [comment]
Just gave it a spin and am having trouble with `boot()` not succeeding when using `coep: 'none'`. Filed [this issue](https://github.com/stackblitz/webcontainer-core/issues/1094) around it. Thanks again for looking into all of this!
