### ISSUE TITLE
Headers is not defined when fetch

### ISSUE THREAD

**Issue by kecrily** [stackblitz/webcontainer-core#1093]
### Describe the bug

When I run `node index.js`, throw a error:

```
Error: Headers is not defined
    at async ESMLoader.import (https://httpsstackblitzwebcontainerapi-xmpu.w-corp.staticblitz.com/blitz.e0a2bd6c.js:35:1312908)
    at async i.loadESM (https://httpsstackblitzwebcontainerapi-xmpu.w-corp.staticblitz.com/blitz.e0a2bd6c.js:35:315880)
    at async handleMainPromise (https://httpsstackblitzwebcontainerapi-xmpu.w-corp.staticblitz.com/blitz.e0a2bd6c.js:35:1079787)
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-with-terminal-g5jtqs?file=files.js

### Steps to reproduce

1. Run `pnpm i && node index.js` in Terminal

### Expected behavior

Normal output fetch results

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 113

**Comment by thescientist13** [comment]
I think https://github.com/stackblitz/webcontainer-core/issues/560 is being used a top level tracking issue for Node 18 support in WebContainers (including `fetch` and friends), so might be worth following along there.

**Comment by Nemikolh** [comment]
Hi @kecrily ! 

@thescientist13 is correct. This does not work because we currently only support node version `v16.4.2` where `Headers` is not defined.
