### ISSUE TITLE
WebContainer.boot() never resolves when using `coep: 'none'`

### ISSUE THREAD

**Issue by steve8708** [stackblitz/webcontainer-core#1094]
### Describe the bug

I'm trying out the new `coep: 'none'` option, but it seems that `boot()` never resolves for me when using that option

E.g. in the code 
```tsx
await WebContainer.boot({ coep: 'none' })
console.log('done')
```

'done' will never log, and I will get no errors either

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-fqp6y5?file=main.js,package.json

### Steps to reproduce

1. Attempt to boot a webcontainer with `coep: 'none'`
2. Notice the promise returned will never resolve

### Expected behavior

Promise resolves with the webcontainer instance

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOs
- Browser: Chrome
- Version: 1.1.4

**Comment by jrvidal** [comment]
:wave: Thanks for the report!

I'm afraid `coep: "none"` cannot work within StackBlitz itself. The `coep` parameter is, after all, a way to let the API consumer/embedder set the appropriate cross-origin policy according to their preferences/setup to serve their application.

When embedding a WebContainer API usecase in StackBlitz itself, the embedder _is_ StackBlitz. And we've chosen to always (*) server our content with cross-origin isolation enabled, which prevents the API from working at all (regardless of origin trials!).

Is this a random test you created to test the waters? Or does it correspond to a "real" use case you had in mind?

In any case, I'm going to add this to our internal tracker, b/c I think at least it merits a warning  from the API library if/when we detect that the user is trying something that _cannot_ work (e.g. `coep: "none"` with `crossOriginIsolated: true`).

(*) With some exceptions.

**Comment by steve8708** [comment]
Thanks for the prompt reply Roberto! So this is happening in my real project too, but if I understand correctly this may be because we still have that project in crossOriginIsolated mode.

The full setup is we have a crossOriginIsolated page, and when we embed it in an iframe on a non crossOriginIsolated site we would get errors, hence we needed the origin-trial (for chrome to at least work).

If I understand correctly, what we need to do now is make the page that loads in the iframe *not* cross origin isolated when using “coep: none” and things should work.

If that’s correct I can give that a try in a bit, and thanks again!

**Comment by steve8708** [comment]
confirmed, works now, huge thanks @jrvidal!
