### ISSUE TITLE
detect if in WebContainer

### ISSUE THREAD

**Issue by andrewmd5** [stackblitz/webcontainer-core#1095]
I'm porting a native program to run under WASM so it can be used within Stackblitz (and other web environments). Does WebContainer currently expose any environment variables or some means of detecting of 'node' is actually running within a WebContainer?
```
const arch = process.arch;
const platform = process.platform;
```

reports Linux x64 rather than the expected WASM

**Comment by Nemikolh** [comment]
Hey @AndrewMD5 ! :wave:  You might want to use [`@webcontainer/env`](https://www.npmjs.com/package/@webcontainer/env) which is a package we maintain that expose `isWeContainer()`, a function indicating whether the program is running in WebContainer or not.

**Comment by SamVerschueren** [comment]
Closing this as `@webcontainer/env` is the package you should use to detect te WebContainer environment.
