### ISSUE TITLE
`SyntaxError: Unexpected token '.'` in minimatch and unplugin-auto-importer

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#1097]
### Describe the bug

When using a unplugin-auto-importer in a module project, a syntax error is encountered.
https://stackblitz.com/edit/vitejs-vite-wdpmc4?file=vite.config.ts,package.json,tsconfig.json&terminal=dev

![image](https://github.com/stackblitz/webcontainer-core/assets/876076/e3be9c3f-1821-4a10-acee-18b31e6ff1e9)

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-wdpmc4?file=vite.config.ts,package.json,tsconfig.json&terminal=dev

### Steps to reproduce

use unplugin in any esm project or with mjs.

### Expected behavior

don't crash.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

all

### Additional context

Something in "unplugin-auto-import" "0.15.3" is causing the issue... in "unplugin-auto-import": "0.15.2" it was okay but caused some strange warnings.

workaround, with pnpm you can use 

```
// package.json
...
  "pnpm": {
    "overrides": {
      "minimatch": "7"
    }
  }
...
```

**Comment by cplepage** [comment]
@FossPrime I found the culprit! although I have no idea why it throws... 

https://github.com/isaacs/minimatch/pull/212

Hopefully my ugly fix can be merged into minimatch and fix our issues here.

**Comment by Nemikolh** [comment]
Hi @cplepage and @FossPrime ! Thanks for investigating this issue!

I think you might have found a bug in our ESM implementation. I'll add this issue to our internal tracker. In the meantime I'm glad that you've found a workaround :+1:

**Comment by SamVerschueren** [comment]
We looked into it and identified and fixed the issue. The fix is now live and I confirmed that the provided example works now. Thanks for reporting 🙏 !
