### ISSUE TITLE
Bug when renaming a file

### ISSUE THREAD

**Issue by 18jad** [stackblitz/webcontainer-core#1098]
### Describe the bug

So, I wanted to create a file named "scrap.js" but I accidentally placed a comma instead of a period and named it "scrap,js" Everything seemed fine until I tried to rename it back to "scrap.js" and remove the comma. The website kept crashing and didn't allow me to make the changes.

Project template: Empty NodeJS template

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-hv4ruh

### Steps to reproduce

1. Create a nodejs project
2. Create a file with a comma and file extension instead of a dot
3. Try to change the comma to a dot

### Expected behavior

The website crash and everything disappears

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

https://github.com/stackblitz/webcontainer-core/assets/74220144/024f1ffb-284e-4f1d-a843-c4b2296caf65

### Platform

```
Browser name  = Chrome
Full version  = 114.0.0.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43
performance.memory = {
  "totalJSHeapSize": 88590557,
  "usedJSHeapSize": 83789173,
  "jsHeapSizeLimit": 4294705152
}
Hash = a12d8c69
```

**Comment by AleksandrSl** [comment]
Hi, @18jad 

Thanks for reporting this, I reproduced the bug. We will fix it as soon as possible

**Comment by 18jad** [comment]
> Hi, @18jad
> 
> Thanks for reporting this, I reproduced the bug. We will fix it as soon as possible

Yeah weird error, I keep pressing the comma key instead of the dot key sometimes because they are close to each other on the keyboard. It's a funny mistake, but I'll make sure to be more careful next time, hopefully this get fixed soon!

**Comment by AleksandrSl** [comment]
Should be fixed by now!

**Comment by 18jad** [comment]
> Should be fixed by now!

Yes it's working fine thank you!
