### ISSUE TITLE
github authentication broken in codeflow

### ISSUE THREAD

**Issue by seonglae** [stackblitz/webcontainer-core#1100]
### Describe the bug

```
remote: Permission to owner/repo.git denied to seonglae.
fatal: unable to access 'https://github.com/owner/repo.git': The requested URL returned error: 403
```

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/owner/repo

### Steps to reproduce

1. click codeflow
2. commit
3. git push or sync

### Expected behavior

push commit to github

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/27716524/d71d6a08-d73e-4e93-9a78-312ccb437bb3)

### Platform

```
Version = 1.72.0
Hash = 6c2c7cfd162308040dc465c7509ebe9b0cee1e6b
WebContainer = a12d8c69

Browser name  = Chrome
Full version  = 114.0.0.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 107469283,
  "usedJSHeapSize": 99273599,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by seonglae** [comment]
![image](https://github.com/stackblitz/webcontainer-core/assets/27716524/914d6ede-44ca-4e7b-a3d7-d962930e8a61)
logged in correctly

**Comment by SamVerschueren** [comment]
Hey @seonglae 👋 . Thanks for reaching out.

Are you 100% certain you have push permissions to that repository? I just tested it with a repo I own and I was perfectly able to push my changes.

Also, what happens if you press the `fork` button?

**Comment by seonglae** [comment]
@SamVerschueren I realized that I can push to my personal repositories like `seonglae/repo`. However I can't push to my organization's repository that I own. Also I installed codeflow app to my organizations and accessed from PR's comment. I'm not sure this bugs happens to all organizations.

And this is errors when I press `fork` button
![image](https://github.com/stackblitz/webcontainer-core/assets/27716524/5afc827f-4575-47d7-8064-edf8d2d05b6a)
![image](https://github.com/stackblitz/webcontainer-core/assets/27716524/cf8b88b3-c17e-417a-b0fb-4fd414838286)

**Comment by SamVerschueren** [comment]
@seonglae Can you check if our StackBlitz app has access to your organisation? https://github.com/settings/connections/applications/edf57e21e7a45ecb97d2

Regarding the `rename`, we have it tracked internally https://github.com/stackblitz/webcontainer-core/issues/967

**Comment by seonglae** [comment]
@SamVerschueren After granting organization access to the app, It works Thank you. But why is this happening? Git config indicate using same user `seonglae` and it could push to organizations authored in my thought.

**Comment by seonglae** [comment]
maybe the token's access range or something? anyway my problem solved! thank you.

**Comment by SamVerschueren** [comment]
The thing with oAuth is that access is restricted

> When OAuth App access restrictions are enabled, organization members and outside collaborators cannot authorize OAuth App access to organization resources.

More information [here](https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/about-oauth-app-access-restrictions).

This means that you can't push to organisations by default, unless the organisation grants permissions for it.
