### ISSUE TITLE
Cannot connect to Mongo Atlas

### ISSUE THREAD

**Issue by larhou** [stackblitz/webcontainer-core#1106]
### Describe the bug

Seems like Stackblitz do not support Mongo Atlas?

I get this error:

Operation `books.countDocuments()` buffering timed out after 10000ms
MongooseError: Operation `books.countDocuments()` buffering timed out after 10000ms
    at Timeout.eval (file:///home/projects/stackblitz-starters-mmvnoi/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-mmvnoi?file=package.json,app.js

### Steps to reproduce

Just let the application start up using : npm run devstart

The error shows in the browser window.

### Expected behavior

![Screenshot 2023-06-21 at 14 46 42](https://github.com/stackblitz/webcontainer-core/assets/55982196/45347914-c507-4c54-91b5-3fc31fd25745)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 114.0.0.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67303865,
  "usedJSHeapSize": 64988405,
  "jsHeapSizeLimit": 2172649472
}
Hash = 9ff9f275
```

**Comment by larhou** [comment]
ThanksYes would be a great feature Sent from my iPhoneDen 22. jun. 2023 kl. 10.31 skrev Roberto Vidal ***@***.***>:﻿
@larhou Thanks for the report. Unfortunately, we don't support databases like Mongo out of the box, b/c that would require something akin to low-level networking in the browser (e.g. TCP/UDP sockets, DNS, etc.), which don't currently exist.
We are thinking about ways around this, but we don't have any concrete roadmap about it. If you're interested, we can leave this open as a venue for updates in case anything changes.

**Comment by kc0tlh** [comment]
I'm consolidating all of the database feature support requests into issue #749 for ease of tracking and due to @d3lm's excellent [explanation of the current state](https://github.com/stackblitz/webcontainer-core/issues/749#issuecomment-1460205393).
