### ISSUE TITLE
filesystem not resolving symlinks

### ISSUE THREAD

**Issue by userquin** [stackblitz/webcontainer-core#1107]
**Is your feature request related to a problem? Please describe:**
I have a project using `pnpm` and symlinks not being resolved, there is no way to hint readdir to follow links. `.pnpm` folder is there but then we need to read it manually.

I'm configuring monaco editor using `addExtraLib`.

**Describe the solution you'd like:**
Add option to follow symlinks

**Describe alternatives you've considered:**
Read `.pnpm` folder

**Additional context:**
I have no idea if `npm` and `yarn` use symlinks.

**Comment by jrvidal** [comment]
:wave: Thanks for the report.

> I have a project using pnpm and symlinks not being resolved

Is this project a StackBlitz project? If so, can you provide a link to it?

**Comment by userquin** [comment]
Upps sorry, it is not public yet, I will try to provide a repro in StackBlitz next weekend, it is basically the interactive example in the webcontainers docs using pnpm (monorepo), I install deps with spwan command and reading the node_modules folder 99% of libs inside .pnpm folder.

**Comment by userquin** [comment]
@jrvidal it seems StackBlitz is broken:

![imagen](https://github.com/stackblitz/webcontainer-core/assets/6311119/2308a69c-52cd-47ea-8017-74a554e0c83c)

**Comment by userquin** [comment]
ok, forgot it, seems to be working properly, the `@`  suffix for symlinks and org. packages with `/`.

**Comment by userquin** [comment]
ok, found what's the problem, in the following screenshot we have the list of `/node_module/`, you can see `vite` dependency, but if I filter taht list with `isDirectory()`, it is missing, check second list:

![imagen](https://github.com/stackblitz/webcontainer-core/assets/6311119/7c5f2bd3-e18f-4286-bff6-7aebec229619)

**Comment by userquin** [comment]
I'm preparing a reproduction in GitHub ready to be opened in StackBlitz...

**Comment by userquin** [comment]
@jrvidal Here the GitHub repo with link to open it in StackBlitz: https://github.com/userquin/stackblitz-pnpm-fs-symlinks-issue-1107

**Comment by userquin** [comment]
Since the list comes from the web worker, maybe we cannot filter the list, it will lost some field in the entries.

**Comment by jrvidal** [comment]
Hey, thank you for that reproduction link.

So is the issue is that `isDirectory() === false` for symlinks? This behavior is expected and matches the Node API (see for instance [Dirent](https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#class-fsdirent)). I don't think there's any Node API for reading directories that would "auto-follow" symlinks.

**Comment by userquin** [comment]
No, the issue is about filtering directories that are symlinks, if you check the `forEach` loop it is working, but using `filter` all symlinks are missing.

**Comment by userquin** [comment]
`src/main.ts`  lines 69 and 75 respectivelly

**Comment by jrvidal** [comment]
> but using `filter` all symlinks are missing

Yes, I think that is working correctly. For instance, `node_modules/vite` is a symlink, ergo `isDirectory()` returns `false` and the `filter()` call in line 75 discards it.

**Comment by userquin** [comment]
ok, thanks

**Comment by userquin** [comment]
@jrvidal how about xterm https://github.com/userquin/stackblitz-pnpm-fs-symlinks-issue-1107#additional-problem ?

**Comment by jrvidal** [comment]
You're attaching 2 processes to the same terminal: a long running interactive `jsh` shell, and then a 1-off `pnpm install`. It's not hanging, it's just that printing `\n` to the terminal once you're done is not the same as a user hitting Enter on their keyboard.

**Comment by userquin** [comment]
it is there but seems to be not working: https://github.com/userquin/stackblitz-pnpm-fs-symlinks-issue-1107/blob/main/src/setup-container.ts#L64

**Comment by jrvidal** [comment]
That line prints to the terminal. That's not the same as user input, that will end up triggering your `terminal.onData()` callback. You might want to write to the long-running `jsh` process manually yourself, maybe?
