### ISSUE TITLE
do not work any repo

### ISSUE THREAD

**Issue by Ruslan-Suvorov** [stackblitz/webcontainer-core#1108]
### Describe the bug

![image](https://github.com/stackblitz/webcontainer-core/assets/69644275/c13e7a08-8678-472a-a4e6-05975d64a56d)

### Link to the blitz that caused the error

https://stackblitz.com/github/OlegBozhesku/resume?file=index.js

### Steps to reproduce

![image](https://github.com/stackblitz/webcontainer-core/assets/69644275/7e2992de-26ef-4b79-ad15-15f268e6f968)

### Expected behavior

![image](https://github.com/stackblitz/webcontainer-core/assets/69644275/7791829b-3ae1-4117-901b-40c21d5b6013)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/69644275/bdae806b-1f64-4dc7-80cb-a2f828475295)

### Platform

```
Browser name  = Chrome
Full version  = 114.0.0.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116673179,
  "usedJSHeapSize": 92975603,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8203611
```

**Comment by Ruslan-Suvorov** [comment]
Don`t work terminal. Don`t deploy projects

**Comment by SamVerschueren** [comment]
Hey @Ruslan-Suvorov 👋 . We're currently already deploying a fix for this issue. Will keep you posted once it's live.

**Comment by fvsch** [comment]
This is now fixed. Thanks for the report!
