### ISSUE TITLE
Framework support for NestJs

### ISSUE THREAD

**Issue by mehulbaid** [stackblitz/webcontainer-core#111]
**Describe the solution you'd like:**
Add support for NestJs

**Provide a link to a github repo containing an example of the framework:**
https://github.com/nestjs/nest

**Comment by SamVerschueren** [comment]
Hi @mehulbaid ! Luckily, NestJS already is in the list of supported frameworks https://github.com/stackblitz/webcontainer-core/blob/main/Supported_frameworks.md ;).
