### ISSUE TITLE
Webcontainers in Codeflow Freeze When Fetching Last Package 

### ISSUE THREAD

**Issue by WilsontheWolf** [stackblitz/webcontainer-core#1115]
### Describe the bug

In my project, when downloading the last dependency, the entire web container appears to freeze. VSCode cannot open files and the terminal freezes.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/josh-development/website/pull/150

### Steps to reproduce

1. Go to the linked blitz
2. Wait for it to install

### Expected behavior

Should properly install

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.72.0
Hash = 93111c64aac6cfd1cd0481904cb37c21693aa7f3
WebContainer = a19575a2

Browser name  = Firefox
Full version  = 114.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0
performance.memory = undefined
```

**Comment by jrvidal** [comment]
@WilsontheWolf :wave: Thanks for the report! I've tried running it in both Chrome and Firefox and I was able to go through installation and run the project.

Do you have any extensions installed? Do you see any suspicious-looking message in the devtools console?

**Comment by WilsontheWolf** [comment]
So I tried it again today, twice, and it seems to work just fine. Not sure what happened before, but I'll close this as I can no longer reproduce.
