### ISSUE TITLE
New SvelteKit project template uses `@sveltejs/kit@next` when it should be `@latest`

### ISSUE THREAD

**Issue by theetrain** [stackblitz/webcontainer-core#1117]
### Describe the bug

When starting a new SvelteKit project from the New Project > Fullstack > SvelteKit template, it seems to install a legacy version found at `@sveltejs/kit@next`, which is a pre-v1 release. 

It should use `@sveltejs/kit@latest` or the 'Skeleton' template returned from `npm create svelte@latest` for the latest documented version.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-ccyj4h?file=README.md

### Steps to reproduce

Template issue describe above

### Expected behavior

Should use latest version of SvelteKit not on the `next` tag.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS 12.6.7
- Browser: Chrome 114.0.5735.198

**Comment by SamVerschueren** [comment]
Hi @theetrain! Thanks for letting us know. I think you are correct based on the data on npm

![image](https://github.com/stackblitz/webcontainer-core/assets/1913805/092e1f66-55ac-48b4-b357-67418c8821de)

Would you mind sending a PR to https://github.com/stackblitz/starters/tree/main/sveltekit? It will automatically update the starter on the home page.

**Comment by theetrain** [comment]
Thanks for pointing me in the right direction. PR ready ☝️
