### ISSUE TITLE
Github sync repository is no longer working

### ISSUE THREAD

**Issue by ghisleouf** [stackblitz/webcontainer-core#1122]
### Describe the bug

Hi there,

I'm working on a blitz since around a month with no issue ... which was great.
But since 1 hour, I cannot sync the blitz with my github repository anymore.

I tried to disconnect, re-connect and re-import but nothing works.

If you have any idea, that would be great.

Thanks a lot.

Best

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-ge7qn2?file=src%2Fscripts%2Fnavigation.js,src%2Fcomponents%2FNavigation.twig,src%2Fstyles%2Fnavigation.scss,src%2Fcomponents%2FHeader.twig

### Steps to reproduce

1. go to the project
2. save
3. commit
4. you'll see the fetch issue with github repository

### Expected behavior

Synch to work!

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 114.0.0.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72977367,
  "usedJSHeapSize": 68065287,
  "jsHeapSizeLimit": 4294705152
}
Hash = e809191e
```

**Comment by skryukov** [comment]
Hey, @ghisleouf thanks for the issue, it should be fixed now, can you confirm?

**Comment by Nemikolh** [comment]
Hey @ghisleouf I'm going to close this issue but if this wasn't fixed for you, feel free to reopen. Thanks again for the report!
