### ISSUE TITLE
Monorepo Intellisense Broken

### ISSUE THREAD

**Issue by SpencerDuball** [stackblitz/webcontainer-core#1123]
### Describe the bug

There appears to be a bug where the Intellisense features with TypeScript are not loading correctly in a monorepo project. In this monorepo I have a package which has two folders: `src/` and `scripts/`. Each folder has it's own `tsconfig.json` and I expect to get intellisense specific to the `tsconfig.json` of the respective folder - but I am getting issues where it looks like the `tsconfig.json` is not being read. I have confirmed that locally on VSCode this works as I would expect, but the discrepancy seems to be on StackBlitz.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-ef2fkg?file=packages%2Fconsumer%2Fsrc%2Fmain.ts

### Steps to reproduce

1. Visit the example linked.
2. Open the `packages/say-hello/scripts/top-level-await-test.ts` file and notice that the `await` keyword has a TypeScript intellisense error hint - this should not be an error.
3. Download the package from StackBlitz and open this project locally in VSCode, notice the typehint error does not appear.

### Expected behavior

I expect the `tsconfig.json` in each folder to be read and used for the files within that directory (as the TypeScript spec specifies).

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![Error on StackBlitz](https://github.com/stackblitz/webcontainer-core/assets/22606045/4e8650e4-39e2-47e7-8648-8e12bc6498da)
<img width="917" alt="Error Not on VSCode" src="https://github.com/stackblitz/webcontainer-core/assets/22606045/4aa313c0-bb1d-49f9-b416-146bf56f8a13">

### Platform

```
Browser name  = Chrome
Full version  = 114.0.0.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 117525786,
  "usedJSHeapSize": 112991902,
  "jsHeapSizeLimit": 4294705152
}
Hash = e809191e
```

**Comment by Nemikolh** [comment]
Hi @SpencerDuball :wave: Thanks for the report!

I think you are facing the same issue described here: https://github.com/stackblitz/core/issues/2564. This is a limitation of our classic editor but it should work if you try it in CodeFlow.

To try it in CodeFlow, you'll need to add that code to a repository on github first and then visit:

```
https://stackblitz.com/~/github.com/<owner>/<repo>
```

Let me know if you run into any issues!
