### ISSUE TITLE
NextJS routing problem

### ISSUE THREAD

**Issue by KaliAir** [stackblitz/webcontainer-core#1124]
### Describe the bug

Unhandled Runtime Error
Error: Connection closed.

Call Stack
close
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js (1836:0)
progress
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js (1851:0)

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-5prvnd

### Steps to reproduce

just click the sidebar menu

### Expected behavior

it will go to expected routes

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 114.0.0.0
Major version = 114
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92900029,
  "usedJSHeapSize": 87344449,
  "jsHeapSizeLimit": 2172649472
}
Hash = e809191e
```

**Comment by SamVerschueren** [comment]
The project linked doesn't seem to exist anymore. Can you provide with a failing example?
