### ISSUE TITLE
How does webcontainer send a message to the main thread to get data

### ISSUE THREAD

**Issue by YeomanYe** [stackblitz/webcontainer-core#1129]
**Is your feature request related to a problem? Please describe:**

I have a logical program running in webcontainer, but I need to get context information from the main thread, so I want to know how webcontainer sends messages to the main thread

**Describe the solution you'd like:**

webcontainer can send messages to the main thread

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kirjavascript** [comment]
Hi! :wave: Thanks for the question!

WebContainer uses MessagePort to communicate with the main thread internally, but none of this is exposed in the public API.

To communicate with the main thread from WebContainer, you can use [spawn()](https://webcontainers.io/api#%E2%96%B8-spawn) to create a new process that will transfer the required data, and use [WebContainerProcess.output](https://webcontainers.io/api#%E2%96%B8-output-readablestream-string) to read this information in the main thread as a `ReadableStream<string>`

Feel free to open another issue if you need any more info!

**Comment by YeomanYe** [comment]
> Hi! 👋 Thanks for the question!
> 
> WebContainer uses MessagePort to communicate with the main thread internally, but none of this is exposed in the public API.
> 
> To communicate with the main thread from WebContainer, you can use [spawn()](https://webcontainers.io/api#%E2%96%B8-spawn) to create a new process that will transfer the required data, and use [WebContainerProcess.output](https://webcontainers.io/api#%E2%96%B8-output-readablestream-string) to read this information in the main thread as a `ReadableStream<string>`
> 
> Feel free to open another issue if you need any more info!

Is there a demo for reference?

**Comment by YeomanYe** [comment]
> Hi! 👋 Thanks for the question!
> 
> WebContainer uses MessagePort to communicate with the main thread internally, but none of this is exposed in the public API.
> 
> To communicate with the main thread from WebContainer, you can use [spawn()](https://webcontainers.io/api#%E2%96%B8-spawn) to create a new process that will transfer the required data, and use [WebContainerProcess.output](https://webcontainers.io/api#%E2%96%B8-output-readablestream-string) to read this information in the main thread as a `ReadableStream<string>`
> 
> Feel free to open another issue if you need any more info!

Is there a way to synchronize the communication with the master? For example, webworker can synchronize the communication with the master through synchronization request and serviceworker interception request and forward to the master
