### ISSUE TITLE
Most Stackblitz examples are broken

### ISSUE THREAD

**Issue by notchris** [stackblitz/webcontainer-core#1146]
### Describe the bug

Whenever I try to view an Stackblitz at work or at home, it almost never loads. I'm trying most of the examples on [Angular Material](https://material.angular.io/components/categories) and cant get them to load. I have multiple machines with Windows, OSX. Why doesn't Stackblitz work for every project and resolve every module correctly?

### Link to the blitz that caused the error

https://material.angular.io/components/categories

### Steps to reproduce

Go to any Stackblitz

### Expected behavior

It should wor

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SamVerschueren** [comment]
We resolved an issue yesterday where WebContainer didn't seem to boot. This issue should be resolved now. I'm wondering if that was the one you where running into.

Can you try again and let us know if it's fixed?

**Comment by notchris** [comment]
@SamVerschueren Simple example: 
![image](https://github.com/stackblitz/webcontainer-core/assets/1944433/246b6ff7-8143-486c-bfcf-166c7c9f5354)

**Comment by notchris** [comment]
Can you resolve and confirm when every Angular Material example is working in Stackblitz?  @SamVerschueren

**Comment by notchris** [comment]
My coworker has confirmed that they ran into the same issue, is this possibly a firewall issue?

**Comment by notchris** [comment]
@SamVerschueren So turns out, it's something internally. Something at work is preventing the fetch call from resolving because of the  stackblitz-protocol urls.  "URL scheme "stackblitz" is not supported."

**Comment by notchris** [comment]
With some more investigation, we found that it works in Edge, but not Chrome. There is also another open issue related to this.

**Comment by notchris** [comment]
@SamVerschueren Any ideas on how to resolve the URL Scheme issue?

**Comment by notchris** [comment]
@SamVerschueren This is now resolved! The issue is that StackBlitz will only work on 64bit Chrome (everyone at work was on 32bit) - and updating Chrome doesn't change between 32/64.
