### ISSUE TITLE
imma try to create a new project or template nuxt3 but the console show me an error

### ISSUE THREAD

**Issue by uno0uno** [stackblitz/webcontainer-core#1147]
### Describe the bug

imma try to create a new project or template nuxt3 but the console show me an error

[8:07:39]  ERROR  The requested module '@vue-macros/common' does not provide an export named 'getTransformResult'

  getTransformResult,
  ^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module '@vue-macros/common' does not provide an export named 'getTransformResult'
  at async ESMLoader.import (https://nuxtstartermrskgd-jcwq.w-credentialless.staticblitz.com/blitz.a9bdb71e.js:35:1347715)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2613:37)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:46:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:64:20)

npm ERR! code 1
npm ERR! path /home/projects/nuxt-starter-mrskgd
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-08-03T13_07_21_624Z-debug-0.log

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-mrskgd?file=README.md

### Steps to reproduce

1. start new project and select nuxt3 template
2. web container run npm install && npm run dev
3. console show this error:

Nuxi 3.6.5                                                                   8:07:35

[8:07:39]  ERROR  The requested module '@vue-macros/common' does not provide an export named 'getTransformResult'

  getTransformResult,
  ^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module '@vue-macros/common' does not provide an export named 'getTransformResult'
  at async ESMLoader.import (https://nuxtstartermrskgd-jcwq.w-credentialless.staticblitz.com/blitz.a9bdb71e.js:35:1347715)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2613:37)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:46:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:64:20)

npm ERR! code 1
npm ERR! path /home/projects/nuxt-starter-mrskgd
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-08-03T13_07_21_624Z-debug-0.log

### Expected behavior

that the project start with any problems

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/90988855/dc5b8e9c-cf9c-46e7-a89b-b9cefdb1cf56)

### Platform

```
Browser name  = Chrome
Full version  = 115.0.0.0
Major version = 115
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 127669358,
  "usedJSHeapSize": 106734950,
  "jsHeapSizeLimit": 1878261760
}
Hash = a9bdb71e
```

**Comment by HeyGarrison** [comment]
👋 Hey!

I tried to debug the project attached to the issue, but it looks like the project is private or was deleted.

I just tested the nuxt starter and it seems to work though. Linking here in case it helps.

https://stackblitz.com/github/nuxt/starter/tree/v3/?file=package.json

**Comment by uno0uno** [comment]
thanks for the quick response, i already generate a new template nuxt3 project and didns works but when i open the the project that you send works really good.

this is the  project with the issue https://stackblitz.com/edit/nuxt-starter-q2vqvp?file=package.json

i only click in start new project and select the meta framework.

**Comment by SamVerschueren** [comment]
That's weird. I removed your `package-lock.json` and reinstalled the project and it seemed to do the trick. But I also just picked a Nuxt 3 starter from the starter list and it worked out of the box. Can you try this again? 🤔 

![image](https://github.com/stackblitz/webcontainer-core/assets/1913805/c2ef796d-7dd4-4be8-b42c-18fc18fb84a6)

@HeyGarrison Maybe we need to update the `package-lock.json` in our Nuxt 3 starter?

**Comment by uno0uno** [comment]
hi!

the issue was fixed and already working, thx a lot @HeyGarrison and @SamVerschueren 

![image](https://github.com/stackblitz/webcontainer-core/assets/90988855/2c06d64b-795e-4f22-aa7a-0fe0d70a4dce)
