### ISSUE TITLE
Codeflow: Can't push a commit [remote rejected] main -> main (push declined due to email privacy restrictions)

### ISSUE THREAD

**Issue by danielduckworth** [stackblitz/webcontainer-core#1148]
### Describe the bug

My github account enforces privacy for the email address. In codeflow, the git config email is tied to my stackblitz email which cannot be chaged.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/danielduckworth/langchain-vue3-app

### Steps to reproduce

1. Enable email privacy on github: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github
2. Import a github repo in Codeflow
3. Commit a change and push

### Expected behavior

Using git config --global user.email "my-private-github-email" should enable the commit to work.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.72.0
Hash = eb830b448d6f85984cc7a6d3a21311b5d6640759
WebContainer = d5d65229

Browser name  = Chrome
Full version  = 115.0.0.0
Major version = 115
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188
performance.memory = {
  "totalJSHeapSize": 187129046,
  "usedJSHeapSize": 178440878,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by SamVerschueren** [comment]
Hey @danielduckworth 👋 . Thanks for reaching out. We're already tracking this issue as it was reported in #933. Closing it in favour of that one. Feel free to leave a 👍 on that issue.
