### ISSUE TITLE
BUG: No way to start terminal

### ISSUE THREAD

**Issue by qsaad** [stackblitz/webcontainer-core#115]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-q7jf7u?file=index.js

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 143122870,
  "usedJSHeapSize": 138169802,
  "jsHeapSizeLimit": 2027683840
}

**Additional context:**

**Comment by KwintenP** [comment]
Hi, 

It seems like you removed the blitz? Can you also clarify what you mean with 'no way to start terminal'

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
