### ISSUE TITLE
【@webcontainer/api】SharedArrayBuffer transfer requires self.crossOriginIsolated

### ISSUE THREAD

**Issue by strugglinglee** [stackblitz/webcontainer-core#1154]
### Describe the bug

I use @webcontainer/api in my own project. It works fine during local debugging, but after deploying it online, it throws an error like this. What should I do to make it work properly in this case?

webcontainer.d5d65229.js:1 Uncaught (in promise) Error: Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.
    at blitz.d5d65229.js:329:181546
    at new Promise (<anonymous>)
    at _0x118c17 (blitz.d5d65229.js:329:180943)
    at Object.apply (blitz.d5d65229.js:329:178849)
    at _0x1710fa.init (blitz.d5d65229.js:334:521914)

### Link to the blitz that caused the error

my own project

### Steps to reproduce

1. use @webcontainer/api in my own project
2. It works fine during local debugging, but after deploying it online, it throws an error 

### Expected behavior

I want use @webcontainer/api in my own project and It works fine online.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by hongrunhui** [comment]
I am using webpack-dev-server to develop  my project , how to config crossOriginIsolated in webpack-dev-server?
I config like this 
<img width="871" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/9162319/962abe17-23aa-4a9f-a418-fa2a3629e6a9">
But not work

**Comment by xun082** [comment]
> I am using webpack-dev-server to develop my project , how to config crossOriginIsolated in webpack-dev-server? I config like this <img alt="image" width="871" src="https://user-images.githubusercontent.com/9162319/262265968-962abe17-23aa-4a9f-a418-fa2a3629e6a9.png"> But not work

请问这个问题解决了嘛

**Comment by xun082** [comment]
> ### Describe the bug
> I use @webcontainer/api in my own project. It works fine during local debugging, but after deploying it online, it throws an error like this. What should I do to make it work properly in this case?
> 
> webcontainer.d5d65229.js:1 Uncaught (in promise) Error: Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated. at blitz.d5d65229.js:329:181546 at new Promise () at _0x118c17 (blitz.d5d65229.js:329:180943) at Object.apply (blitz.d5d65229.js:329:178849) at _0x1710fa.init (blitz.d5d65229.js:334:521914)
> 
> ### Link to the blitz that caused the error
> my own project
> 
> ### Steps to reproduce
> 1. use @webcontainer/api in my own project
> 2. It works fine during local debugging, but after deploying it online, it throws an error
> 
> ### Expected behavior
> I want use @webcontainer/api in my own project and It works fine online.
> 
> ### Parity with Local
> * [x]  I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.
> 
> ### Screenshots
> _No response_
> 
> ### Platform
> * OS: [e.g. macOS, Windows, Linux]
> * Browser: [e.g. Chrome, Safari, Firefox]
> * Version: [e.g. 91.1]
> 
> ### Additional context
> _No response_

我也遇到了相同的情况，请问解决了吗
