### ISSUE TITLE
Safari not compatible to cross web

### ISSUE THREAD

**Issue by sammyfilly** [stackblitz/webcontainer-core#1156]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

@sammyfilly 
@stackblitz-gitops <search > solutions to issues for review

**Comment by sammyfilly** [comment]
Can you look for possible solutions that allows safari cross other website or platforms

**Comment by kc0tlh** [comment]
@sammyfilly it is not clear what you are asking/how it is related to StackBlitz. I will close this issue for now, but feel free to add more information and a reproduction/video of the StackBlitz issue if possible!
