### ISSUE TITLE
Fails to fetch express endpoint in a web container

### ISSUE THREAD

**Issue by tmokmss** [stackblitz/webcontainer-core#1159]
### Describe the bug

Hi, I recently tried this tutorial: https://webcontainers.io/tutorial/4-running-dev-server

This tutorial accesses to the express endpoint via iframe and it successes. Now is it possible to access the endpoint by fetch API?

When I tried that, it failed with the following error:

```
Access to fetch at 'https://httplocalhost5173-b5wu--3111--d5d65229.local-corp.webcontainer.io/' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

GET https://httplocalhost5173-b5wu--3111--d5d65229.local-corp.webcontainer.io/ net::ERR_FAILED 404

Uncaught (in promise) TypeError: Failed to fetch
```

Any help is really appreciated, thanks!

### Link to the blitz that caused the error

n/a

### Steps to reproduce

1. Deploy this tutorial: https://webcontainers.io/tutorial/4-running-dev-server
2. Modify `startDevServer` function as the below:

```ts
async function startDevServer() {
  // Run `npm run start` to start the Express app
  await webcontainerInstance.spawn('npm', ['run', 'start']);

  // Wait for `server-ready` event
  webcontainerInstance.on('server-ready', (port, url) => {
    iframeEl.src = url;
    fetch(url); // add this!
  });
}
```

3. open the browser and see developer console.

### Expected behavior

fetch API successfully returns the content.

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

For some reason, CloudFront returns 404 error even though `/` has its content:

```js
  app.get('/', (req, res) => {
    res.send('Welcome to a WebContainers app! 🥳');
  });
```

![image](https://github.com/stackblitz/webcontainer-core/assets/7490655/52cd9880-aa1a-4f5a-ab03-e223de74db7f)

### Platform

- OS: macOS
- Browser: Edge
- Version: 115.0.1901.203

**Comment by Nemikolh** [comment]
Hi @tmokmss! 👋

URLs of the form `https://*.webcontainer.io` are served by a [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers). This service worker is used to serve content from your express app.

One important thing to note about service workers is that they are never used in cross origin requests. They only see requests from the same origin.

So when you do a `fetch` from `localhost` to `https://httplocalhost5173-b5wu--3111--d5d65229.local-corp.webcontainer.io/ `, this request is crossorigin and thus sent (as you've noticed) to Cloudfront and not to the service worker. It also fails because of CORS, but if it didn't it still wouldn't have what you want. 

For the iframe it works because the origin of the iframe match it's `src`.

Hope this helps! Let me know if you need more clarification.

**Comment by tmokmss** [comment]
@Nemikolh Hi, thanks for the detailed explanation!

So, is it impossible to access the endpoint something like fetch or axios? I'm not sure how the endpoint can be used only via iframe. Is it even an expected use case?

**Comment by Nemikolh** [comment]
No worries! There are no stupid questions.

This is where the "container" part comes into play. You can do a GET with `axios` but only if you do it from within webcontainer or from the iframe. The express app is isolated from the rest of the world or "containerized". 

In WebContainer or in the iframe the express app is reachable via `http://localhost:3111/` (or just `/` for the iframe).

This is what we've got:

```
┌──────────────────────────────────────────────┐
│                                              │
│            Main page                         │
│                                              │
└────────┬─────────────────────────────────────┘
         │ WebContainer API
         │
┌────────▼─────────────────────────────────────┐                   ┌────────────────┐
│                                              │   Service Worker  │                │
│           WebContainer                       │◄──────────────────┤    iframe      │
│                                              │                   │                │
│                                              │                   │                │
│                               localhost      │                   │                │
│                               :3111          │                   │                │
│ ┌───────────────────┐        ┌─────────────┐ │                   │                │
│ │                   │        │             │ │                   │                │
│ │ Node.JS           │        │ Express app │ │                   │                │
│ │                   │  GET   │             │ │                   │ axios.get('/') │
│ │ axios.get(        ├───────►│             │ │                   │                │
│ │  'localhost:3111' │   /    │             │ │                   │                │
│ │ )                 │        │             │ │                   │                │
│ └───────────────────┘        └─────────────┘ │                   │                │
│                                              │                   │                │
└──────────────────────────────────────────────┘                   └────────────────┘
```

With the webcontainer API, you can spawn that node.js worker by doing the following steps:
 1. Add another file (e.g `test.js`) inside webcontainer (so in [the tutorial](https://webcontainers.io/tutorial/2-setting-up-webcontainers#_3-create-the-files), add another entry to `const files`) that import axios and call `axios.get('http://localhost:3111/').then(console.log)`.
 2. Modify the `package.json` to contains `"axios"` in `dependencies`.
 3. Run your node.js process via the WebContainer API: `await webcontainerInstance.spawn('node', ['./test.js']);`
 4. You should see the output in the console :)

**Comment by tmokmss** [comment]
@Nemikolh 
Got it, so we have to use some "proxy" to talk with express via stdin/out. That makes sense a lot, thanks!
