### ISSUE TITLE
BUG: webconcainer stop working after signing in and forking the node demo project

### ISSUE THREAD

**Issue by oe** [stackblitz/webcontainer-core#116]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-server-stackblitz-webcontainer-demo-q2xifs

**Steps to reproduce:**
1. Go to <https://stackblitz.com/edit/node-server-stackblitz-webcontainer-demo>
2. Click on `sign in` on the top right then sign in with github
3. the project automatically forked 
4. preview stop working

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**
![image](https://user-images.githubusercontent.com/1655294/120015322-cbbdec80-c015-11eb-905e-5b0e35fc0963.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 89.0.4389.114
Major version = 89
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68327615,
  "usedJSHeapSize": 66275031,
  "jsHeapSizeLimit": 4294705152
}

**Comment by oe** [comment]
reloading the forked page, everything works fine again

**Comment by SamVerschueren** [comment]
Could this be the same as #114? Basically, if you have another tab/window open running a StackBlitz project on the same port, that will not work. We have to handle this more gracefully though.

**Comment by oe** [comment]
seems like the same problem, I'm not sure
