### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by htilssu** [stackblitz/webcontainer-core#1166]
### Describe the bug

when i run npm i react-redux it has an error 

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-5xuhbu?file=README.md

### Steps to reproduce

1. go to create new terminal
2. run command npm i react-redux

### Expected behavior

install complete react-redux

### Parity with Local

- [x] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 116.0.0.0
Major version = 116
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54
performance.memory = {
  "totalJSHeapSize": 125743200,
  "usedJSHeapSize": 110091092,
  "jsHeapSizeLimit": 2172649472
}
Hash = 33975f1d
```

**Comment by Nemikolh** [comment]
Hey @htilssu! Thanks for opening this issue!

I think you might have hit a temporary failure. I managed to do `npm i react-redux` on your project without running into any issues:

![image](https://github.com/stackblitz/webcontainer-core/assets/4008156/8ad3e293-cdd3-4161-8578-414f0c38cb26)

I'm going to close this but feel free to reopen if the issue persists for you!
