### ISSUE TITLE
Cloning large repositories fails

### ISSUE THREAD

**Issue by james-pre** [stackblitz/webcontainer-core#1168]
### Describe the bug

When cloning very large git repositories from GitHub, StackBlitz fails to clone it after some time.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/BabylonJS/babylon.js

### Steps to reproduce

1. Open the blitz
2. "Cloning [BabylonJS/babylon.js](https://github.com/BabylonJS/babylon.js) on branch [master](https://github.com/BabylonJS/babylon.js/tree/master)"
3. "Could not clone [BabylonJS/babylon.js](https://github.com/BabylonJS/babylon.js). Please check that this repository exists and try again."

### Expected behavior

It should clone the repository, but fails to do so. I presume this is because the repository in questions is over 5GB is size for a full clone. 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/75621402/d377859f-be9a-4e5a-b9ad-94987f4b53b2)

### Platform

```
Version = 1.72.0
Hash = 27729c2178447b5efac2fb0da8e0c65b16a43747
WebContainer = 33975f1d

Browser name  = Chrome
Full version  = 115.0.0.0
Major version = 115
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 67637472,
  "usedJSHeapSize": 64924804,
  "jsHeapSizeLimit": 2066219008
}
```

### Additional context

I can clone other repositories fine, but not BabylonJS or my fork of it ([dr-vortex/babylon.js](https://github.com/dr-vortex/babylon.js)).

**Comment by Nemikolh** [comment]
Hi @dr-vortex! :wave: Thanks for opening this issue! 

I've created an internal ticket and we'll keep you posted :+1:

**Comment by dr-vortex** [comment]
@Nemikolh  Any updates on this?
