### ISSUE TITLE
Extension host terminated unexpectedly.. 100% of the times

### ISSUE THREAD

**Issue by maxmars** [stackblitz/webcontainer-core#1175]
### Describe the bug

After message "Extension host terminated unexpectedly.." you can't push modifications to the github project.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/maxmars/dmwhisper

### Steps to reproduce

Let it load, wait a few minutes, watch the error come out and you're not able to use the github features (you can't push anything, making this project useless).

![immagine](https://github.com/stackblitz/webcontainer-core/assets/6041074/5c0eb7f7-725f-4bdf-8bfb-d573a359b118)

### Expected behavior

I expected to be able to use the github features to push stuff after modifying code and assets.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.72.0
Hash = 15d5ac11f8b479fce83fb269037a1ec1679e55ab
WebContainer = 33975f1d

Browser name  = Firefox
Full version  = 117.0
Major version = 117
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
performance.memory = undefined
```

**Comment by samdenty** [comment]
Hi there @maxmars, thank you for finding and reporting this bug. I'll look into this 👀

**Comment by samdenty** [comment]
Hi there sorry for the delay, we've fixed the issue with webcontainer process incorrectly crashing when an uncaught promise is thrown.
