### ISSUE TITLE
Unable to run the webcontainer example using webpack

### ISSUE THREAD

**Issue by shibisuriya** [stackblitz/webcontainer-core#1176]
### Describe the bug

Hi, I cloned the webcontainer example which used vite and migrated it to webpack... I added the dev server headers etc... The project is building and serving... But webcontainer is not working...
This is the repo -> https://github.com/shibisuriya/webpack-webcontainer

### Link to the blitz that caused the error

https://github.com/shibisuriya/webpack-webcontainer

### Steps to reproduce

Just run the project.

### Expected behavior

The express server should run.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/69033713/02c83396-b45d-4d90-b242-0f5f5555813b)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kirjavascript** [comment]
hi! :wave: thanks for your question!

It looks like in the example you posted webpack is injecting a script tag in the `<head>` section. Since it already exists in the markup the `main.js` bundle is loaded twice, causing the error.

If you remove the additional script tag from the markup it works!
