### ISSUE TITLE
BUG: Possible Unexpected Project Caching

### ISSUE THREAD

**Issue by Vandivier** [stackblitz/webcontainer-core#118]
**Describe the bug:**
seems like stackblitz caches a deleted project so that new projects from same origin do not have latest code on origin

**Link to the blitz that caused the error**
https://stackblitz.com/github/Vandivier/gotrue-js

**Steps to reproduce:**

1. use the stackblitz URL to generate a project from the github branch
2. locally clone the github branch, make a code change and push it
3. quickly (for me within 5 min) delete your stackblitz project, then immediately recreate it per step 1

**Expected behavior:**
generate a fresh stackblitz project with the latest upstream code

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 134170588,
  "usedJSHeapSize": 124437100,
  "jsHeapSizeLimit": 4294705152
}

**Comment by HeyGarrison** [comment]
@Vandivier we adjusted our cache to go off of commit SHA so there might still be some delay, but should ultimately be better now! Thanks for the feedback. ❤️❤️❤️
