### ISSUE TITLE
please add rename file to file system

### ISSUE THREAD

**Issue by pratham15541** [stackblitz/webcontainer-core#1183]
**Is your feature request related to a problem? Please describe:**
Please make an inbuilt function to rename files

If there is any other method let me know!

**Comment by Nemikolh** [comment]
Hi @pratham15541! 👋

You can rename a file with `mv`. For instance, in the terminal on stackblitz you can execute:

```
mv index.js newname.js
```

Assuming you have a file named `index.js` in your current folder, it will be renamed to `newname.js`.

If you want to do that programmatically from node, you can use [`fs.renameSync`](https://nodejs.org/api/fs.html#fsrenamesyncoldpath-newpath) for instance.

**Comment by pratham15541** [comment]
@Nemikolh  same for folder too?
and fs.renameSync can u provide some more information
means how can we do that in filesystem of webcontainer?

**Comment by Nemikolh** [comment]
Hey @YeomansIII and @pratham15541,

I wanted to give a quick update. I had misunderstood the original issue which was talking about the WebContainer API which I only got thanks to @YeomansIII's comment (Thanks a lot ! :smiley:)

I have a fix in the pipeline, so this should land soon-ish. I'll keep you posted!

**Comment by Nemikolh** [comment]
Version `1.1.6` has been published an contains the `fs.rename` function! :partying_face: 

The docs [will be updated soon too](https://github.com/stackblitz/webcontainer-docs/pull/43).

**Comment by pratham15541** [comment]
@Nemikolh thanks man!
