### ISSUE TITLE
`Process is not defined` when setting `workdirName` or mounting files to a specific directory

### ISSUE THREAD

**Issue by YeomansIII** [stackblitz/webcontainer-core#1187]
### Describe the bug

Using Vivaldi (Chromium) on MacOS, upon setting a `workdirName` during WebContainer boot or attempting to mount a FileSystemTree to a `mountPoint`, the browser console outputs the following error and either fails to boot the WebContainer or fails to mount the FileSystemTree.

Error is reproducible on the WebContainer starter StackBlitz.

StackBlitz:
https://webcontainer.new/

Replace `boot` line with:
`webcontainerInstance = await WebContainer.boot({ workdirName: 'test' });`

or replace `mount` line with:
`await webcontainerInstance.mount(files, {mountPoint: 'myFolder'});`

Both result in the following error:
```
Uncaught (in promise) ReferenceError: process is not defined
    at Object.resolve (webcontainer.023ad0e3.js:1:106318)
    at _0x2c9c53._unsynchronizedBuild (webcontainer.023ad0e3.js:1:158741)
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-uwntrk?file=main.js

### Steps to reproduce

StackBlitz:
https://webcontainer.new/

Replace `boot` line with:
`webcontainerInstance = await WebContainer.boot({ workdirName: 'test' });`

or replace `mount` line with:
`await webcontainerInstance.mount(files, {mountPoint: 'myFolder'});`

### Expected behavior

Should properly set workdirName and properly mount FileSystemTree to mountPoint

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Vivaldi (Chromium)
- Version: 6.2.3105.48

**Comment by kirjavascript** [comment]
hi! :wave: thanks for reporting this!

we are working on a fix and it should be available soon!

**Comment by YeomansIII** [comment]
Hello, thanks. Just to add it looks like this is affecting ALL `webcontainer.fs` operations.

**Comment by Nemikolh** [comment]
@YeomansIII, yes definitely! The fix should probably land in 3-4 hours at most (maybe less). It's one of those "I screwed up big time" moment. Really sorry for the inconvenience caused.

We'll keep you posted!

**Comment by YeomansIII** [comment]
Thank you! I'm curious is this some remote code that is loaded? It looks like the @webcontainer/api package hasn't been updated in 3 months, so obviously the issue wasn't a result of the code in that package? Or I just haven't tested this bit in that long :)

**Comment by Nemikolh** [comment]
The fix has just been deployed! :tada: 

So sorry for the inconvenience caused!

> I'm curious is this some remote code that is loaded? It looks like the @webcontainer/api package hasn't been updated in 3 months, so obviously the issue wasn't a result of the code in that package?

Correct, the code loaded in the iframe is remote. The `@webcontainer/api` package contains the code that gets bundled in your application.

It hasn't been updated in 3 months, but it will see updates as we expose more features in the near future! :smiley:

(can't say much more just yet, but it's something that has been requested a couple of times :grin:)

**Comment by YeomansIII** [comment]
Working great, thanks! Seems like the functionality of `mount` may be slightly different as it now requires the directory to exist in the fs, which is easy to fix on my end. Is there anywhere these changes are documented?

**Comment by Nemikolh** [comment]
@YeomansIII Do you have a small repro of the breaking change regarding `mount`?
