### ISSUE TITLE
Wrong TypeScript types

### ISSUE THREAD

**Issue by philkunz** [stackblitz/webcontainer-core#1189]
### Describe the bug

The package states that it is of type "module"
Compare here: https://unpkg.com/browse/@webcontainer/api@1.1.5/package.json

Yet it fails to use proper TypeScript ESM types resulting in the following error:

@webcontainer+api@1.1.5/node_modules/@webcontainer/api/dist/index.d.ts (9,62): Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './entities.js'?

### Link to the blitz that caused the error

not needed

### Steps to reproduce

none

### Expected behavior

Should be acceptable

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Nemikolh** [comment]
Hi @philkunz ! Seems like an easy fix! Will let you know when we have a new version with the correct typings.

**Comment by Nemikolh** [comment]
We published a new version! Let us know if you still encounter type issues. 😃
