### ISSUE TITLE
Terminal broken. Won't run commands, clears screen.

### ISSUE THREAD

**Issue by Umisyus** [stackblitz/webcontainer-core#119]
**Describe the bug:**
The terminal won't work properly if  at all on mobile version of Stackblitz.

**Link to the blitz that caused the error:**

https://stackblitz.com/edit/node-tf67bg

**Steps to reproduce:**

2. Click the Stackblitz link on a mobile device. 
3. Enter anything into the terminal
4. See nothing!

**Expected behavior:**
I was expecting some terminal output but I got nothing.

**Screenshots:**

![Screen_Recording_20210529-111728_Samsung Internet_1.gif](https://user-images.githubusercontent.com/47287517/120075615-0e141780-c070-11eb-80f6-f6ccf82057fb.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy Note 10+]
 - OS: [Android 11]
 - Browser [Samsung Internet]
 - Version
 [14.0.35]

**Additional context:**

**Comment by SamVerschueren** [comment]
Hi @Umisyus, thanks for trying out StackBlitz! Please fill in the required information because without it it's very hard for us to know exactly what's going on 🙏 .

**Comment by SamVerschueren** [comment]
Awesome, thanks for filling in the information, this is very helpful! 

Currently WebContainers do not work on mobile. We detect this and show a message but apparently doesn't work for your device.

![image](https://user-images.githubusercontent.com/1913805/120093472-d6ae7500-c11a-11eb-9f48-dd0fef79f842.png)

**Comment by SamVerschueren** [comment]
I’m closing this as it shouldn’t work either. We probably aren’t going to invest time in showing an appropriate message as we want to get this fixed rather sooner than later that it also works on Android Chome.
