### ISSUE TITLE
GIT CLI SUPPORT

### ISSUE THREAD

**Issue by pratham15541** [stackblitz/webcontainer-core#1196]
Please add git cli support such that we can work with remote repo also

**Comment by SamVerschueren** [comment]
You can if you use Codeflow at [https://stackblitz.com/~](https://stackblitz.com/~). For reasons, this is currently not available in the classic editor.

Hope this helps.

**Comment by pratham15541** [comment]
@SamVerschueren  i was telling in  webcontainer api ?

**Comment by SamVerschueren** [comment]
See #1190 as a duplicate. I'll answer there.
