### ISSUE TITLE
Preview section Not working at all

### ISSUE THREAD

**Issue by SKuwatada** [stackblitz/webcontainer-core#1199]
### Describe the bug

I can't see my output of the code in the preview scetion.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Steps to reproduce

any page for preview

### Expected behavior

preview option is suppose to show the output of the code that i write.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 117.0.0.0
Major version = 117
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43
performance.memory = {
  "totalJSHeapSize": 70497361,
  "usedJSHeapSize": 62335649,
  "jsHeapSizeLimit": 4294705152
}
Hash = 49a3680d
```

**Comment by SamVerschueren** [comment]
Hey @SKuwatada 👋 . Thanks for reaching out. I notice that you posted a `/run` URL, which is a dynamic project which only exists the moment you click the link. Where did you click the link? So I can test this for myself?

**Comment by SKuwatada** [comment]
***@***.***

**Comment by SamVerschueren** [comment]
Can you check if there are any errors in the Chrome DevTools? It seems to work for me if I click the `ready-made sample project in StackBlitz` link at https://angular.io/start 🤔 .

**Comment by SKuwatada** [comment]
How do i check that?
