### ISSUE TITLE
Unable to clone Ask Izzy GitHub repo

### ISSUE THREAD

**Issue by callumgare** [stackblitz/webcontainer-core#1207]
### Describe the bug

When attempting to open this github repo https://github.com/ask-izzy/ask-izzy/ stackblitz will hang on the "Cloning from GitHub" step.

### Link to the blitz that caused the error

https://stackblitz.com/github/ask-izzy/ask-izzy/

### Steps to reproduce

Open the above link and observe that it never gets part the GitHub clone step.

### Expected behavior

To finish cloning

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1512" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/346340/6529c085-e022-4d26-9d50-8dcd79a9f2d5">

### Platform

```
Browser name  = Firefox
Full version  = 118.0
Major version = 118
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
performance.memory = undefined
Hash = 7a1fe16d
```

I've also tried it on the latest version of Chrome on macOS

### Additional context

Sorry if this is the wrong place to report this issue. I clicked the "Something broken? File a bug!" link in the IDE.

**Comment by bcrhbrhcdb** [comment]
me too...

**Comment by fvsch** [comment]
@bcrhbrhcdb It looks like your comment might be about https://github.com/stackblitz/core/issues/2990, and not about this specific issue which is about importing the `ask-izzy/ask-izzy` repository in the StackBlitz classic editor (via the URL https://stackblitz.com/github/ask-izzy/ask-izzy/).

**Comment by callumgare** [comment]
Having this issue bumped has prompted me to check to see if this is still an existing bug and I can see that the repo is now imported which is good. However now that it's being imported I'm running into a new bug. I've opened a separate ticket for that (https://github.com/stackblitz/core/issues/2992) and will close this one as it appears to be resolved.
