### ISSUE TITLE
gettign started angular tutorial starting a terminal does not work in firefox

### ISSUE THREAD

**Issue by jasonblewis** [stackblitz/webcontainer-core#1208]
### Describe the bug

i was following the Angular tutorial, it asks me to open a new terminal and enter `ng generate component product-alerts`

however pressing the + sign, when the terminal opens it doesn't give me a prompt.
![image](https://github.com/stackblitz/webcontainer-core/assets/129165/3fac27ba-984a-453a-ba4f-8177d20f01c5)

### Link to the blitz that caused the error

https://stackblitz.com/edit/exswkh?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

click plus to create a new terminal - note you don't get a prompt in that terminal in firefox (but it does work in chrome)

### Expected behavior

i expect to get the terminal prompt

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 118.0
Major version = 118
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0
performance.memory = undefined
Hash = 7a1fe16d
```

**Comment by SamVerschueren** [comment]
Can you try again and maybe take a screenshot of the DevTools? So we can see if there's an error going on.

**Comment by sergiuser1** [comment]
I get the same error, and the console says `ENOENT`:

![image](https://github.com/stackblitz/webcontainer-core/assets/36699660/17f733a8-b9dc-462c-98eb-37b5c6d57500)

**Comment by sergiuser1** [comment]
I've reloaded the page, and it works now.
