### ISSUE TITLE
After commiting changes in the forked repos data's are not saving to the forked repository.

### ISSUE THREAD

**Issue by kumar007ambi** [stackblitz/webcontainer-core#1218]
### Describe the bug

When I am trying to commit the chnages in my forked repo. The commiting button keep rotating and not updating the commit changes to the forked repo and not updating the forked repo.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/kumar007ambi/ahento

### Steps to reproduce

It may save the commit and push the code to forked repo.
![StalkBiltzError](https://github.com/stackblitz/webcontainer-core/assets/60788663/c488c604-895c-4aed-9724-062da6d23a0c)

### Expected behavior

I must save the commit and push the code to forked repo to the github

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![StalkBiltzError](https://github.com/stackblitz/webcontainer-core/assets/60788663/f6548188-a445-487a-8af5-4b3e388fbd45)

### Platform

```
Version = 1.80.0
Hash = 7c78d6545a12810536b51c710366e3b0c51f18f8
WebContainer = cd1aec28

Browser name  = Chrome
Full version  = 118.0.0.0
Major version = 118
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 99339616,
  "usedJSHeapSize": 92045844,
  "jsHeapSizeLimit": 2172649472
}
```

### Additional context

Please resolve this issue

**Comment by samdenty** [comment]
Hi there @kumar007ambi 

I believe it takes forever because you are committing your entire node_modules folder. You should add a .gitignore
