### ISSUE TITLE
`Open in new window` link stops working

### ISSUE THREAD

**Issue by userquin** [stackblitz/webcontainer-core#1224]
### Describe the bug

There is no way to open the app in a new window

### Link to the blitz that caused the error

https://stackblitz.com/edit/vite-pwa-astro-9ugxbo

### Steps to reproduce

Just open the linked repo, await dev server starts and then click `Open in new window`, there is an error, check attached screenshot.

### Expected behavior

The app should open in the new window.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![imagen](https://github.com/stackblitz/webcontainer-core/assets/6311119/bc109407-6ee0-42e7-8b45-ca9fdd0847b2)

### Platform

- OS: Windows 10 PRO
- Browser: Chrome
- Version: 118.0.5993.89 (Build oficial) (64 bits)

### Additional context

Parity with Local: I cannot reproduce in my local since the problem in SB site, just checked to allow submit issue.

**Comment by Nemikolh** [comment]
Hey @userquin ! Thanks for the report! 

Sorry for the inconvenience caused! I have a fix that should have landed by now, if you still see the issue you might need to clear your `webcontainer.io` cache.
