### ISSUE TITLE
cannot start angular project in CodeFlow

### ISSUE THREAD

**Issue by linubik** [stackblitz/webcontainer-core#1225]
### Describe the bug

Hi,
I have cloned angular default project in stackblitz
usually it works fine, but since stackblitz try to open it in CodeFlow, it dosnt work anymore
- I cannot see dependencies
- there is no url in preview

 

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/linubik/ngCdiAct

### Steps to reproduce

1 create new project in stablitz using angular template
--> dependencies OK, preview OK
2 connect this project to a new gihub repository
-->https://stackblitz.com/~/github.com/linubik/bugreport
3 stablitz automacally opens webcontainer IDE 'codeflow'
--> terminal says : ng serve --> 
An unhandled exception occurred: require() of ES Module /home/linubik/bugreport/node_modules/@angular/compiler/fesm2022/compiler.mjs not supported.
Instead change the require of /home/linubik/bugreport/node_modules/@angular/compiler/fesm2022/compiler.mjs to a dynamic import() which is available in all CommonJS modules.
See "/tmp/ng-UBKVjB/angular-errors.log" for further details.

### Expected behavior

![CaptureStackblitz](https://github.com/stackblitz/webcontainer-core/assets/12217673/ccc41f32-296b-44ac-b895-3764d1fbc514)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.80.0
Hash = 929c34be5994dc215aa95c43273c2099e204d6fd
WebContainer = 1f9496ab

Browser name  = Chrome
Full version  = 117.0.0.0
Major version = 117
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109626282,
  "usedJSHeapSize": 100366614,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by jrvidal** [comment]
> I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

I get the same error on my local machine:

```
$ ngCdiAct git:(main) ✗ npm start

> stackblitz-starters-7mfhvk@0.0.0 start
> ng serve

An unhandled exception occurred: require() of ES Module /tmp/ngCdiAct/node_modules/@angular/compiler/fesm2022/compiler.mjs not supported.
Instead change the require of /tmp/ngCdiAct/node_modules/@angular/compiler/fesm2022/compiler.mjs to a dynamic import() which is available in all CommonJS modules.
See "/tmp/ng-CeqADn/angular-errors.log" for further details.
```

**Comment by kirjavascript** [comment]
Closed due to inactivity and lack of info
