### ISSUE TITLE
Angular Start does not compile in web container

### ISSUE THREAD

**Issue by ohmnoms** [stackblitz/webcontainer-core#1227]
### Describe the bug

Running ng serve on a project that has been converted into a repository and run in the vs code web IDE does not start, and generates this error:

An unhandled exception occurred: require() of ES Module /home/ohmnoms/stackblitz-signals/node_modules/@angular/compiler/fesm2022/compiler.mjs not supported.
Instead change the require of /home/ohmnoms/stackblitz-signals/node_modules/@angular/compiler/fesm2022/compiler.mjs to a dynamic import() which is available in all CommonJS modules.
See "/tmp/ng-ExM6jA/angular-errors.log" for further details.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/ohmnoms/stackblitz-signals

### Steps to reproduce

Try running the stackblitz in the vs code IDE (ng serve after all dependencies have been installed).

### Expected behavior

The project should run. This project runs fine when not in the vs code IDE.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.80.0
Hash = 32a9f1885f032ec54cc5c6bf38df070d1de42169
WebContainer = a35c7542

Browser name  = Chrome
Full version  = 118.0.0.0
Major version = 118
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 127150022,
  "usedJSHeapSize": 109445846,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by jrvidal** [comment]
See https://github.com/stackblitz/webcontainer-core/issues/1225
