### ISSUE TITLE
Documentation Algolia Search isn't working

### ISSUE THREAD

**Issue by oodavid** [stackblitz/webcontainer-core#1228]
Every search term on the docs site returns no results:

<img width="587" alt="Screenshot 2023-10-27 at 11 22 51" src="https://github.com/stackblitz/webcontainer-core/assets/46879/e830e9a9-89b9-463f-bcc5-4d51362ba7fb">

It's been like this for a few days (to my knowledge).

**Comment by jrvidal** [comment]
Did you mean developer.stackblitz.com? We just released a fix.

Thanks for reporting!

**Comment by oodavid** [comment]
No worries, thanks!
