### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by YukeshM** [stackblitz/webcontainer-core#123]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-wk8pgg?file=package-lock.json

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 OPR/76.0.4017.154
performance.memory = {
  "totalJSHeapSize": 54467877,
  "usedJSHeapSize": 46405125,
  "jsHeapSizeLimit": 2172649472
}

**Additional context:**

**Comment by SamVerschueren** [comment]
@YukeshM could you provide more information and fill in the required fields as well as a decent title? Otherwise it's hard for us to help you out.

**Comment by YukeshM** [comment]
![image](https://user-images.githubusercontent.com/76556005/120076777-ef8c3b80-c0c4-11eb-9768-b9b595bd6563.png)



> @YukeshM could you provide more information and fill in the required fields as well as a decent title? Otherwise it's hard for us to help you out.

here I found the bug

**Comment by SamVerschueren** [comment]
Thanks for the screenshot, unfortunately this is not enough information. When you click the report bug button we expect everyone to describe what bug you encounter, steps to reproduce the issue and last but not least, a decent issue title.

I'm not on my computer right now so I will have a look if I can quickly see if there goes something wrong when I open the project.

**Comment by YukeshM** [comment]
here after I will describe the issue sir, thanks for your reply
