### ISSUE TITLE
Vue Syntax highlighting is broken in my pre-existing project

### ISSUE THREAD

**Issue by harlan-zw** [stackblitz/webcontainer-core#1231]
### Describe the bug

The syntax highlighting doesn't work in a pre-existing StackBlitz project.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-pxs3wk?file=package.json,nuxt.config.ts,pages%2Findex.vue

### Steps to reproduce

1. open index.vue

### Expected behavior

Syntax highlighting works. Previously this worked without any issues :thinking: Only something recent I've noticed.

What's interesting is that it only seems to be effecting legacy projects. New Nuxt projects work without issue.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/5326365/21266e00-03fa-409f-8f4f-6d86ba6891d7)

### Platform

```
Browser name  = Chrome
Full version  = 118.0.0.0
Major version = 118
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 105153512,
  "usedJSHeapSize": 100469460,
  "jsHeapSizeLimit": 4294705152
}
Hash = 09144545
```

**Comment by reslear** [comment]
after shift+cmd+r works again

**Comment by harlan-zw** [comment]
Seems to be fixed :+1:
