### ISSUE TITLE
no such file or directory, mkdir '/home/httplocalhost5173-b5wu-tvakwd39/src/test.json'

### ISSUE THREAD

**Issue by yangdaxian-is-cool** [stackblitz/webcontainer-core#1238]
### Describe the bug

i want to test this way of   await webcontainerInstance.fs.mkdir("./src/test.json"), 
window.addEventListener('load', async () => {

  webcontainerInstance = await WebContainer.boot();

  await webcontainerInstance.fs.mkdir("./src/test.json")

  await webcontainerInstance.mount(files);

  const exitCode = await installDependencies();
  if (exitCode !== 0) {
    throw new Error('Installation failed');
  };

  startDevServer();
});

### Link to the blitz that caused the error

using way of( await webcontainerInstance.fs.mkdir("./src/test.json") ) is error with no such file or directory, mkdir '/home/httplocalhost5173-b5wu-tvakwd39/src/test.json'

### Steps to reproduce

using way of( await webcontainerInstance.fs.mkdir("./src/test.json") ) is error with no such file or directory, mkdir '/home/httplocalhost5173-b5wu-tvakwd39/src/test.json'

### Expected behavior

using way of( await webcontainerInstance.fs.mkdir("./src/test.json") ) is error with no such file or directory, mkdir '/home/httplocalhost5173-b5wu-tvakwd39/src/test.json'

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. Windows]
- Browser: [e.g. Chrome]
- Version: [e.g. 119]

**Comment by jrvidal** [comment]
Is `test.json` supposed to be a folder? Maybe you want to call `mkdir('./src')`? Or `mkdir('./src/test.json', { recursive: true })`, if you really want to create a `test.json` folder.
