### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by adrianlula** [stackblitz/webcontainer-core#124]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/graphql-sjkygx

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62675897,
  "usedJSHeapSize": 53681949,
  "jsHeapSizeLimit": 1791754240
}

**Additional context:**

**Comment by SamVerschueren** [comment]
Please fill in all required information and a decent issue title. We try to help everyone but we expect people to provide as much information as possible, otherwise it might be hard for us to find out what goes wrong. 🙏

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
