### ISSUE TITLE
Connect to a project when trying to see the preview in a standalone project

### ISSUE THREAD

**Issue by paoloricciuti** [stackblitz/webcontainer-core#1242]
### Describe the bug

We are using the webcontainer api package at https://sveltelab.dev and we are also providing the ability to open the preview in a separate tab. This was mostly working fine before (Firefox being the onyl exception) but now i can't open any project in the other tab because it ask me to connect this to a stackblitz project (which obviously doesn't exist since we are not stackblitz).

### Link to the blitz that caused the error

https://sveltelab.dev

### Steps to reproduce

1. go to https://sveltelab.dev
2. wait for the preview to appear
3. try to open the preview in another tab with the button near the url bar
4. observe it requires you to link it to a stackblitz project 

### Expected behavior

having the preview in a standalone tab should work

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1510" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/26281609/b7fc0297-287d-4a9b-94e7-d081bf245fca">

### Platform

- OS: macOS
- Browser: Chrome, Arc

**Comment by jrvidal** [comment]
@paoloricciuti Thanks for the report. Correct me if I'm wrong, but I think we can close this in favor of https://github.com/stackblitz/webcontainer-core/issues/1087

**Comment by paoloricciuti** [comment]
> @paoloricciuti Thanks for the report. Please correct me if I'm wrong, but I think we can close this in favor of #1087

It's fine, I opened a new one because there the answer was that "It works on chrome but not on Firefox and Safari"
