### ISSUE TITLE
Could you share how to build node as webassembly target using emscripten or some other tools.

### ISSUE THREAD

**Issue by liudonghua123** [stackblitz/webcontainer-core#1246]
**Is your feature request related to a problem? Please describe:**

Hi, I am curious about how to build node as webassembly target. Maybe webcontainer already did.
Could you share the patches and instructions on how to do it. 

I want to execute some demonstration node code in browser without a server locally. `webcontainer`, `stackblitz` are good choices except they could not run self-hosted locally or offline.

**Describe the solution you'd like:**

N.A.

**Describe alternatives you've considered:**

N.A.

**Additional context:**

N.A.

**Comment by Nemikolh** [comment]
Hey there! :wave: 

We don't compile nodejs to webassembly. The best way to start would probably be using the [`wasi-sdk`](https://github.com/WebAssembly/wasi-sdk) or [`emscripten`](https://emscripten.org/).

However, if you only want to run node inside the browser, then maybe you might be interested in trying out [`@webcontainer/api`](https://www.npmjs.com/package/@webcontainer/api) which allows you to run a webcontainer inside your page and from there you can run `node`. You can find more documentation at:

https://webcontainers.io

Hope this helps!
