### ISSUE TITLE
invalid array length

### ISSUE THREAD

**Issue by SX-9** [stackblitz/webcontainer-core#1248]
### Describe the bug

doing the ls command outputs "invalid array length"

### Link to the blitz that caused the error

https://codedit.is-an.app/

### Steps to reproduce

1. open terminal
2. type ls
3. get the error now?

### Expected behavior

ls lists files

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![2023-11-12-064723_1366x768_scrot](https://github.com/stackblitz/webcontainer-core/assets/90962949/17a60f79-7e24-4dab-b9cb-b5f6b1528911)

### Platform

- OS: Arch Linux
- Browser: Thorium Browser (chromium fork), also tested on a regular chromium browser but same thing happens
- Version: 117.0.5938.157

### Additional context

ls doesnt work but using nodejs with fs I was able to list the life contents

**Comment by SX-9** [comment]
source code if needed: https://github.com/SX-9/codedit-web

**Comment by SamVerschueren** [comment]
Hey @SX-9, thanks for reaching out! I looked at your code, and I think the problem is that [on this line], you use `t.columns` while it should be `t.cols`.

We do have an issue with the `resize()` method not properly propagating the dimensions. We'll track that, but in the mean time, you should be unblocked.

**Comment by SamVerschueren** [comment]
> We do have an issue with the resize() method not properly propagating the dimensions. We'll track that, but in the mean time, you should be unblocked.

This is now fixed. So when opening your app, initially `ls` will still print the `Invalid array length` (because of the `t.columns` <-> `t.cols` mistake in the codebase), but after resizing the window it works.

**Comment by SX-9** [comment]
thanks
