### ISSUE TITLE
Framework support for [BUN]

### ISSUE THREAD

**Issue by arcadeJHS** [stackblitz/webcontainer-core#1249]
### Describe the solution you'd like

Ok, I know that Bun is not a framework.
But: Is there a plan to use Bun as a runtime for webContainers? Would it be possible?

Thanx!

### Provide a link to a GitHub repo containing an example of the framework

https://bun.sh/

**Comment by kirjavascript** [comment]
Hi! :wave:

We don't have any immediate plans to support the Bun runtime. This might or might not change in the future, but I'm closing this issue for now, as it's not really actionable/trackable. If/when that happened, I'm pretty sure that we would make a lot of noise in https://blog.stackblitz.com/ and other venues.

Thanks for the suggestion!

**Comment by arcadeJHS** [comment]
Thank you for your reply!

**Comment by rtritto** [comment]
@kirjavascript as alternative, can be added the support for the [bun](https://www.npmjs.com/package/bun) dependency?
