### ISSUE TITLE
WebContainer gets corrupted on second install.

### ISSUE THREAD

**Issue by mhevery** [stackblitz/webcontainer-core#1250]
### Describe the bug

1. Navigate: https://stackblitz.com/edit/qwik-starter-tlhhfa?file=src%2Froutes%2Findex.tsx
2. ctrl-C the server 
3. run `npm install && npm run dev` Does not work..

### Link to the blitz that caused the error

https://stackblitz.com/edit/qwik-starter-tlhhfa

### Steps to reproduce

1. Navigate: https://stackblitz.com/edit/qwik-starter-tlhhfa?file=src%2Froutes%2Findex.tsx
2. ctrl-C the server 
3. run `npm install && npm run dev` Does not work..

### Expected behavior

it should restart the application

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kirjavascript** [comment]
Hi! :wave: Thanks for reporting this issue!

This appears to be a bug in webcontainer, we are tracking it internally and will update this issue when we have fixed it.

In the meantime, you can workaround this by manually adding `@emnapi/runtime` to your `package.json`

**Comment by Nemikolh** [comment]
Hey @mhevery ! We have fixed the underlying issue with `npm` so this should no longer happen.
