### ISSUE TITLE
Hangs on Booting Container

### ISSUE THREAD

**Issue by jmc420** [stackblitz/webcontainer-core#1257]
### Describe the bug

it never gets beyond "Booting Container"

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/jmc420/graphql_scalar

### Steps to reproduce

Go to the url

### Expected behavior

Should Boot Container, install dependencies 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 89ac2eda2442b1f81682ad2a5dd682d8621aae36
WebContainer = 9e24d36e

Browser name  = Chrome
Full version  = 119.0.0.0
Major version = 119
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84449925,
  "usedJSHeapSize": 53974841,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by SamVerschueren** [comment]
Hi @jmc420 👋 ! Thanks for reporting! This is a bug indeed on our side. It does work in Firefox and Safari, and we have a fix ready for Chrome. The reason was the `_` in the repository name that caused a bug in Chrome. We will also report this bug in the Chrome issue tracker as it shouldn't have happened in the first place.

**Comment by SamVerschueren** [comment]
@jmc420 The fix is deployed and I checked that your repository loads now, which it does 👍 . Thanks again for reporting!

**Comment by jmc420** [comment]
thanks
