### ISSUE TITLE
No font rendering in terminal in Firefox

### ISSUE THREAD

**Issue by lakshits11** [stackblitz/webcontainer-core#1259]
### Describe the bug

<img width="450" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/54276661/6de84e28-c814-47a9-8577-7406d8fa08f1">

I am using firefox. This is how text is rendered in terminal. I saw that support for firefox is in alpha stage so just thought to give it a headsup.

### Link to the blitz that caused the error

https://stackblitz.com/edit/daisyui-nextjs/?file=package.json

### Steps to reproduce

Open above url in firefox/librewolf

### Expected behavior

Correct text rendering in terminal. 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 105730410,
  "usedJSHeapSize": 85406854,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6843a59c
```

I am issuing this bug in Chrome since I am not logged into Github in my firefox

**Comment by SamVerschueren** [comment]
Hey @lakshits11 👋 . Do you happen to see the same on the website of https://xtermjs.org/?

**Comment by lakshits11** [comment]
I guess it was some problem with my Firefox since I have hardened it for privacy purposes. Thank You anyways.
