### ISSUE TITLE
BUG: Unknown error when building

### ISSUE THREAD

**Issue by Krutsch** [stackblitz/webcontainer-core#126]
**Describe the bug:**
Does not execute npm command. (Running bundlers)
`TypeError: Cannot read property 'constants' of undefined`

**Link to the blitz that caused the error**
https://stackblitz.com/github/Krutsch/hydro-starter

**Steps to reproduce:**

1. Go to https://stackblitz.com/github/Krutsch/hydro-starter
2. Run `npm run dev`
3. See error

**Expected behavior:**
Execute the command without error, just like local.

**Version of webcontainer:**
Hash: 

**Screenshots:**
![image](https://user-images.githubusercontent.com/45216083/120121290-81b24380-c19a-11eb-99fc-2dc246e2e8b9.png)

**Desktop (please complete the following information):**
Browser name  = Chrome
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
jsHeapSizeLimit: 4294705152
totalJSHeapSize: 13385444
usedJSHeapSize: 11787528
}

**Additional context:**

**Comment by jrvidal** [comment]
This seems to fail now due to the lack of http2. @Krutsch We're tracking this issue internally now, but unfortunately I can't offer a timeline for the fix.

**Comment by SamVerschueren** [comment]
This project seems to work now. I had to remove `--secure` from the `start` command though, because it tried to load a `.pem` file.

![image](https://github.com/stackblitz/webcontainer-core/assets/1913805/7403b9e0-ecfe-48b5-ac1f-304739780da0)
