### ISSUE TITLE
[major, blocking] push declined due to user privacy reasons

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/webcontainer-core#1277]
repro:
- configure GH settings such that on https://github.com/settings/emails under your primary email it says something like this
  ```
  Not visible in emails
  
  This email will not be used as the 'from' address for web-based Git operations, e.g., edits and merges. We will instead use 199018+NullVoxPopuli@users.noreply.github.co
  ```
  I believe it's these settings:
  
  ![image](https://github.com/stackblitz/webcontainer-core/assets/199018/a6f76234-d571-4b36-bb8e-1db01cd38038)

- open a PR (to do work on) via `pr.new/github.com/stackblitz/docs/tree/BRANCH-NAME`
  docs: https://developer.stackblitz.com/codeflow/using-pr-new

- make some changes
- try pushing
- see that it hangs forever
- use CLI
- observe:
  ```
  ~/NullVoxPopuli/ember-page-title/test-types add-types ⇡ 1s
  ❯ git push
  To https://github.com/nullvoxpopuli/ember-page-title.git
   ! [remote rejected] add-types -> add-types (push declined due to email privacy restrictions)
  error: failed to push some refs to 'https://github.com/nullvoxpopuli/ember-page-title.git'
  ``` 
  I believe the email privacy reasons are why stackblitz doesn't push via the sync changes button

To resolve, I tried the CLI:

```bash
git config --global user.email 199018+NullVoxPopuli@users.noreply.github.com
# but no difference occurred in git push outcome
git config user.email 199018+NullVoxPopuli@users.noreply.github.com
# but no difference occurred in git push outcome
```

this tells me that the git client in stackblitz does not read any git config, and instead uses the email for oauth, making it impossible to use pr.new to make changes if you have privacy settings turned on.

In the CLI,
```bash
❯ git config -l

init.defaultBranch=main
user.name=NullVoxPopuli
user.email=199018+NullVoxPopuli@users.noreply.github.com
core.repositoryformatversion=1
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/nullvoxpopuli/ember-page-title.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.promisor=true
remote.origin.partialclonefilter=blob:limit=1024
branch.add-types.github-pr-owner-number=ember-cli#ember-page-title#272
branch.add-types.remote=origin
branch.add-types.merge=refs/heads/add-types
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
remote.upstream.url=https://github.com/ember-cli/ember-page-title.git
pull.rebase=true
```

oh, no my conclusion is probably the wrong, the commits made using the UI have my actual email, I need to amend them.

```bash
❯ git rebase -i HEAD~2
git: 'rebase' is not a git command. See 'git --help'.
```
oh no. lol

not that rebase is a new command, but why is the git version behind so far?
```bash
❯ git --version
git version 2.32.0
```
current is 2.43 (nov 19, https://github.com/git/git/releases/tag/v2.43.0)
but stackblitz is using [2.32.0](https://github.com/git/git/releases/tag/v2.32.0), which is from June 2021

other techniques to try to delete commits, but keep their changes:
```bash
❯ git reset HEAD^
fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

however, doing 
```bash
❯ git reset most-recent-sha
❯ git reset second-most-recent-sha
```
seems to do the trick.

Another goofiness... could/should probably be a separate issue
```bash
git commit -am"Add test-types project"
hint: Waiting for your editor to close the file... 
```
opening an editor shouldn't happen if `m` is provided

### And then!!!

`git push` succeeded. yay!

_However_

the UI is now out of date
![image](https://github.com/stackblitz/webcontainer-core/assets/199018/797a1f68-296b-4ea2-9aea-9c9d7cc3f8ce)

so I will refresh the page

**Comment by SamVerschueren** [comment]
Closing in favour of https://github.com/stackblitz/webcontainer-core/issues/933.

We have an internal ticket to track this and it is on our list to fix in the coming weeks. Thanks for the report and for letting us know how important this feature is for users 🙏 !
