### ISSUE TITLE
Editor is just loading, never completes

### ISSUE THREAD

**Issue by Fank1** [stackblitz/webcontainer-core#1282]
### Describe the bug

Hi! The editor has frozen in some perpetual loading state, can you please help me? I suspect some issue with the Github integration, or corrupted image files. I can't seem to delete files either, it's just loading. 

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/Fank1/3d-preview

### Steps to reproduce

Open the editor, and see the Preview just keep loading. 

### Expected behavior

That the preview and the deletion of files actually works. 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = a5b1ce2088a8c48a3bfda4a131ef20e00b36d9eb
WebContainer = a2aabdd9

Browser name  = Chrome
Full version  = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 94024958,
  "usedJSHeapSize": 87199742,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by Nemikolh** [comment]
Hi @Fank1 ! Thanks for the report.

I have opened your project (pretty cool by the way :star_struck:), and it seems to load fine for me. Are you still running into this issue? Do you also run into this issue with Firefox?

[screencast](https://github.com/stackblitz/webcontainer-core/assets/4008156/023eb8f8-17e9-4ab7-bb6c-10877a733a06)

If you have any additional information or if you could provide a screencast that would be extremely useful :pray:

**Comment by Fank1** [comment]
Haha, thank you Jòan!

It worked itself out just by letting it rest a few days :)

All the best,
Erik
