### ISSUE TITLE
Errors on stackblitz

### ISSUE THREAD

**Issue by thusmiley** [stackblitz/webcontainer-core#1285]
### Describe the bug

On this page: https://angular.io/start
- Section: Pass data to a child component. The bug occurred at step 7 on stackblitz
_The generator automatically added the ProductAlertsComponent to the AppModule to make it available to other components in the application._
It did not automatically added the component to 'src/app/app.module.ts'. I managed to manually added it and got these errors:
"TS2304: Cannot find name 'Product'.
src/app/product-alerts/product-alerts.component.ts:12:20"
and
"TS-996008: Component ProductAlertsComponent is standalone, and cannot be declared in an NgModule. Did you mean to import it instead?
src/app/app.module.ts:21:4"

Therefore, I cannot proceed to step 8 either.

### Link to the blitz that caused the error

https://stackblitz.com/edit/hcfvp1?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html,src%2Fapp%2Fproduct-list%2Fproduct-list.component.ts,src%2Fapp%2Fproduct-alerts%2Fproduct-alerts.component.ts,src%2Fapp%2Fproduct-alerts%2Fproduct-alerts.component.html,src%2Fapp%2Fapp.module.ts&file=src%2Fapp%2Ftop-bar%2Ftop-bar.component.ts,src%2Fstyles.css

### Steps to reproduce

1. Go to https://angular.io/start and log in to stackblitz
2. Go to Section: Pass data to a child component.
3. Follow the instructions and see the results on stackblitz
4. On Stackbliz: src/app/app.module.ts, the productalertscomponent wasn't automatically added. However you'll get errors if you try to add it manually

### Expected behavior

_The generator automatically added the ProductAlertsComponent to the AppModule to make it available to other components in the application._

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/81765707/677a34bc-aed1-4725-a7db-eb61c27e01c8)

### Platform

```
Browser name  = Chrome
Full version  = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 102039465,
  "usedJSHeapSize": 94390309,
  "jsHeapSizeLimit": 2172649472
}
Hash = a2aabdd9
```

**Comment by kirjavascript** [comment]
hi! :wave:  thanks for asking about this!

It seems that you can make this work by making `product-alerts.component.ts` match the text provided in the guide:

![angular](https://github.com/stackblitz/webcontainer-core/assets/4498266/630bfd89-b78f-420c-bd9f-0fc4cddf35f6)

I'm closing this for now because it's not an issue with WebContainer specifically. Feel free to open another issue if you have any other queries!
