### ISSUE TITLE
Using fs.watch recursively

### ISSUE THREAD

**Issue by samyung0** [stackblitz/webcontainer-core#1287]
### Describe the bug

When I try to run `fs.watch` with option `{resursive: true}` in chrome, the console shows the following error:
![image](https://github.com/stackblitz/webcontainer-core/assets/41984660/1c98fd27-2bc6-440b-b865-26cf6cab966e)

Although it is mentioned in the docs that only some platforms support the recursive option, I am not exactly sure how should I get it to work. I don't think I can _change_ the platform I am running webcontainer on.

### Link to the blitz that caused the error

-

### Steps to reproduce

Initialize a webcontainer instance and call fs.watch on it with recursive option set to true.

### Expected behavior

Fs.watch works recursively out-of-the-box.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 120.0.6099.130
- webcontainer/api: 1.1.8

**Comment by kirjavascript** [comment]
hi! :wave: thanks for reporting this issue

Recursive `fs.watch` is not supported in WebContainer currently, but I have opened a ticket on our internal tracker for it.

We will update here when progress is made on it!

**Comment by kirjavascript** [comment]
After looking into this more, it seems that recursive watch is not supported for Node.js for Linux on version 18.

Stackblitz is currently running node 18 and simulates an linux environment, so it is not available there either.

It looks like the feature has been added in node 20 and should be available once we upgrade to that version.

**Comment by samyung0** [comment]
Thank you for the clarification. I would love to see this feature gets rolled out soon. I am currently manually injecting a chokidar script to detect file changes which is not very ideal and is more of a hack than a real solution.
