### ISSUE TITLE
Shown files don't match `ls` command in the terminal

### ISSUE THREAD

**Issue by LuisTovar0** [stackblitz/webcontainer-core#1290]
### Describe the bug

The "files" menu is showing this:
![image](https://github.com/stackblitz/webcontainer-core/assets/72473883/45a3b177-6299-4e67-9783-71ee8b6239e6)

But the terminal `ls -la` command outputs this:
![image](https://github.com/stackblitz/webcontainer-core/assets/72473883/367cefc0-db3a-497a-b738-cc1707a02e93)

Even the `npm start` command works.

However, after I save, exit, and reopen, the terminal will only list the files that are shown in the menu. This makes the project lose relevant files.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-whhznj?file=package-lock.json

### Steps to reproduce

1. Create Node project
2. `cd ..`
3. `rm -rf stackblitz-starters-whhznj` (use project ID)
4. `npx @angular/cli@14 new stackblitz-starters-whhznj` (use project ID)
5. `cd stackblitz-starters-whhznj` (use project ID)
6. `ls`

### Expected behavior

The "files" menu should show the files generated by the CLI app.

When I save and reopen the project, the "files" menu should reflect the VM's file system too.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 121.0
Major version = 121
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
performance.memory = undefined
Hash = f7aa08df
```

**Comment by SamVerschueren** [comment]
Hey @LuisTovar0 👋 ! Thanks for reporting. I can confirm this is an issue. I'll create an internal ticket to track this.

**Comment by SamVerschueren** [comment]
I can now confirm this issue is fixed. It happened to be I was working on that area of the codebase and found the bug quite quickly. Let us know if there's still something you run into.
