### ISSUE TITLE
event loop behaves differently in stackblitz nodejs app and local nodejs app

### ISSUE THREAD

**Issue by prafullpd2** [stackblitz/webcontainer-core#1298]
### Describe the bug

if we try to run this code in stackblitz node js app

```
setTimeout(() => {
    console.log("setTimeout 1");
    Promise.resolve("Promise 1").then(console.log);
    Promise.reject("Promise 2").catch(console.log);
    queueMicrotask(() => console.log("queueMicrotask 1"));
    process.nextTick(console.log, "nextTick 1");
  }, 0);
  setTimeout(console.log, 0, "setTimeout 2");
  setTimeout(console.log, 0, "setTimeout 3");
```

the output will be this - 

```
setTimeout 1
nextTick 1
setTimeout 2
setTimeout 3
Promise 1
Promise 2
queueMicrotask 1
```
the actual output should be like this - 

```
setTimeout 1
nextTick 1
Promise 1
Promise 2
queueMicrotask 1
setTimeout 2
setTimeout 3
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-sg6jt1?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js&title=node.new%20Starter

### Steps to reproduce

1. go to stack blitz and create a node app
2. put this above code in index.js and run it
3. create a node application on local dev machine and run the same code
4. compare the outputs.the 

### Expected behavior

the output should be like this - 
```
setTimeout 1
nextTick 1
Promise 1
Promise 2
queueMicrotask 1
setTimeout 2
setTimeout 3
```

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
performance.memory = {
  "totalJSHeapSize": 84796469,
  "usedJSHeapSize": 76618817,
  "jsHeapSizeLimit": 2172649472
}
Hash = babcaeac
```

**Comment by SamVerschueren** [comment]
Hey @prafullpd2 👋 . I'm closing this in favour of https://github.com/stackblitz/webcontainer-core/issues/1150.

We are aware of it and have a fix which should fix every event loop case which is currently incorrect. But due to some internal priorities we pushed this back a bit. I hope I can share some news soon.
