### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by vashistaarav1611** [stackblitz/webcontainer-core#130]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/http-server-fuziza

**Steps to reproduce:**

4. See an error

**Expected behavior:**

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 146956427,
  "usedJSHeapSize": 108103571,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
