### ISSUE TITLE
package installation freezes

### ISSUE THREAD

**Issue by TomerEternal** [stackblitz/webcontainer-core#1306]
When I try to install `npm i react-spring`
It just says it's loading and it doesn't stop
I tried running it multiple times for about half an hour
just says "Installing Dependencies"

**Comment by jrvidal** [comment]
Hi all! This issue seems to be related to the WebContainer runtime itself. That's why it was moved to this repo.

We need more info for this to be actionable. We have a [bug report template](https://github.com/stackblitz/webcontainer-core/issues/new?assignees=&labels=&projects=&template=bug_report.yml). If you can still observe this, I recommend that you open a new issue and give us as much detail as you can. Thanks!

**Comment by SamVerschueren** [comment]
I am not able to reproduce this issue anymore. I've also tested in Safari which installs the packages just fine.

**Comment by webdiscus** [comment]
@jrvidal, @SamVerschueren 

I have tested in new safari `version 17.3.1`.
No more freeze by `npm install`.
But by run the `webpack serve` occurs the ERROR:
```
> webpack serve

[webpack-cli] [callSiteLocation@
depd@
@
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:14872
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:15558
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:13457
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:10539
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:13780
@
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:14872
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:15558
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:13457
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:10539
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:13780
@
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:14872
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:15558
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:13457
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:10539
@https://webpackmultiplepages-ol5s.w-corp.staticblitz.com/blitz.a9c8a5a3.js:54:13780
@
setupApp@
@
initialize@
@]
```

> **Note**
>
> In Firefox the `webpack serve` command works fine.

_package.json_
```
{
  "name": "hello-world",
  "stackblitz": {
    "startCommand": "npm start"
  },
  "scripts": {
    "start": "webpack serve",
    "build": "webpack build --mode=production"
  },
  "devDependencies": {
    "css-loader": "^6.10.0",
    "html-bundler-webpack-plugin": "^3.4.12",
    "sass": "^1.64.2",
    "sass-loader": "^13.3.2",
    "webpack": "^5.90.1",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^5.0.1"
  }
}
```


The reproducible [example](https://stackblitz.com/edit/webpack-multiple-pages?file=package.json).

**Comment by SamVerschueren** [comment]
It does seem to work on Safari 17.1 for me. However, when I used Safari TP (17.4), it did indeed break. Could you create a new issue with this information so we can close this one?

![image](https://github.com/stackblitz/webcontainer-core/assets/1913805/59c3a7a7-b247-4065-af55-51c414845648)

![image](https://github.com/stackblitz/webcontainer-core/assets/1913805/72555330-c9d8-459f-8ff7-c0d481ac3c9b)

**Comment by SamVerschueren** [comment]
Thank you! 🙏
