### ISSUE TITLE
BUG: workspaces don't install with included version of turbo

### ISSUE THREAD

**Issue by dylang** [stackblitz/webcontainer-core#131]
**Describe the bug:**
I'm trying to create a monorepo scenerio using Yarn workspaces

```
└ 𐄂 Failed
ERR!: Failed to resolve dependencies

error Command failed with exit code 1
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/projects-and-typescript?file=package.json

**Steps to reproduce:**
`turbo install`

**Expected behavior:**
Installs everything.

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57993921,
  "usedJSHeapSize": 52719849,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**
Amazing work on Webcontainers!

**Comment by jrvidal** [comment]
This now fails with a linking error. @dylang We are aware of this limitation, we'll notify any updates in this thread. Thanks for reporting.
