### ISSUE TITLE
Yarn Berry not supported

### ISSUE THREAD

**Issue by airtonix** [stackblitz/webcontainer-core#1314]
### Describe the bug

```
warning Ignoring 'yarnPath' from '.yarnrc' because it's currently not supported.
```

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/airtonix/vike-vanilla-extract-onRenderHtml-bug-538

### Steps to reproduce

open the above repo in stackblitz

### Expected behavior

yarn berry should work

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 1b55df34465d453466c44626898f18b5de432e70
WebContainer = 69a3aa37

Browser name  = Chrome
Full version  = 121.0.0.0
Major version = 121
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92662542,
  "usedJSHeapSize": 85320486,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by Nemikolh** [comment]
Hey @airtonix ! Thanks for sharing what you need. 

As you've already seen, there's already another issue regarding support for yarn berry (#1235).

I'm going to close this issue, feel free to subscribe to the other one to get notified of when we add support! :smiley:
