### ISSUE TITLE
BUG: Failing at Linking dependencies

### ISSUE THREAD

**Issue by kutec** [stackblitz/webcontainer-core#132]
**Describe the bug:**

❯ npm install
warn preInstall No repository field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 48.403s
┌ [2/3] 🚚  Fetching dependencies
└ Completed in 15.799s
┌ [3/3] 🔗  Linking dependencies
└ 𐄂 Failed
Error: EIO: failed to link packages

error Command failed with exit code 1

**Link to the blitz that caused the error**
https://stackblitz.com/edit/github-a6vpe7?file=package.json

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76546176,
  "usedJSHeapSize": 69299980,
  "jsHeapSizeLimit": 1098907648
}

**Comment by SamVerschueren** [comment]
@kutec Can you recreate the blitz and update the URL? It looks like you removed it which makes it hard for us to reproduce.

**Comment by kutec** [comment]
Thanks, @SamVerschueren . But that issue was fixed with a fresh repo.

**Comment by Splaktar** [comment]
I'm seeing this too, example here: https://stackblitz.com/edit/ng-webcontainer-material-cdk-experimental-mdc?file=package.json
