### ISSUE TITLE
BUG: Turbo Unknown syntax error when handling arguments

### ISSUE THREAD

**Issue by corradin** [stackblitz/webcontainer-core#133]
**Describe the bug:**
Unknown Syntax Error: Command not found; did you mean one of:

  0. turbo exec [-p,--package #0] [-c,--call #0] [--cwd,--prefix #0] [-s,--silent] [--quiet] [-V,--verbose] [--loglevel #0] ...
  1. turbo exec [-p,--package #0] [-c,--call #0] [--cwd,--prefix #0] [-s,--silent] [--quiet] [-V,--verbose] [--loglevel #0] ...
  2. turbo exec [-p,--package #0] [-c,--call #0] [--cwd,--prefix #0] [-s,--silent] [--quiet] [-V,--verbose] [--loglevel #0] ...

While running exec create-react-app my-app --template typescript

**Link to the blitz that caused the error**
https://stackblitz.com/edit/webcontainers?file=_tmp_29_3e37e27786d1f81442677490e0c12103

**Steps to reproduce:**

1. In the terminal type: npx create-react-app my-app --template typescript
2. See error

**Expected behavior:**
Command should run without errors, since it is syntactically correct.

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Desktop (please complete the following information):**
Browser name  = Chrome (Brave)
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66943508,
  "usedJSHeapSize": 62186144,
  "jsHeapSizeLimit": 4294705152
}

**Comment by SamVerschueren** [comment]
After investigation we fixed this issue. There's currently a fix being deployed which will fix the issues with `create-react-app`.

CRA does try to init the git repo though, which we don't have support for yet. So you will see an error being logged to the console but it's not blocking.

![image](https://user-images.githubusercontent.com/1913805/122983471-576c3400-d39c-11eb-9eb0-dd8cc4ee2133.png)
