### ISSUE TITLE
Console disappeared in Vite based projects

### ISSUE THREAD

**Issue by ironmanromeo** [stackblitz/webcontainer-core#1336]
### Describe the bug

I can't find console window anymore.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-evwjxk?file=.vscode%2Fsettings.json

### Steps to reproduce

1) go into the project
2) find for console...

### Expected behavior

To find the console.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Safari
Full version  = 17.3.1
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
performance.memory = undefined
Hash = a9c8a5a3
```

**Comment by sulco** [comment]
Hey @ironmanromeo 👋 . Thanks for reaching out!

We used to have a mix of projects running on two different environments among our starters: EngineBlock and WebContainers – you can read more on the differences in our docs [here](https://developer.stackblitz.com/guides/user-guide/available-environments#frontmatter-title). 

Recently we have sunsetted the EngineBlock starters (I wrote some more context on this in the "[Starters Upgrade: WebContainers and Vite](https://blog.stackblitz.com/posts/webcontainers-starters-update/)" post). The new starters don't have Console any longer, on the plus side they have access to the terminal and more capabilities that were not possible before.

If you tend to work with console a lot, you might want to open the preview in new window 
<img width="461" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/1511906/4fa0a0d9-c720-40c8-8611-723e30156055">
and open the browser devtools for that window
<img width="1385" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/1511906/b7342aa8-5f13-4674-90f1-14c22a826c24">
