### ISSUE TITLE
BUG: npm version 0.0.2 causes create-react-app to fail

### ISSUE THREAD

**Issue by corradin** [stackblitz/webcontainer-core#134]
**Describe the bug:**
Create-react-app cannot succeed, because it checks the version of NPM in the webcontainer and gets 0.0.2 back. CRA tries to fall back to a different version and breaks, because the arguments by the react scripts cannot be parsed by Turbo.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/webcontainers?file=_tmp_29_3e37e27786d1f81442677490e0c12103

**Steps to reproduce:**

1. In the terminal type: `npx create-react-app my-app`
2. See error

**Expected behavior:**
Command should see an npm version of 6.x.x and succeed without errors. The folder my-app should be created. 

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**
![image](https://user-images.githubusercontent.com/13624131/120233367-f39b9300-c255-11eb-9dcd-8e325c99e3ae.png)

**Desktop (please complete the following information):**
Browser name  = Chrome (Brave)
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65931521,
  "usedJSHeapSize": 62093549,
  "jsHeapSizeLimit": 4294705152
}

**Comment by SamVerschueren** [comment]
Thanks for reporting 🙏 ! This looks like a bug indeed and we should return a proper version for yarn and npm so tools like this work properly.

**Comment by SamVerschueren** [comment]
There's currently a fix being deployed which will fix the issues with `create-react-app`.

CRA does try to init the git repo though, which we don't have support for yet. So you will see an error being logged to the console but it's not blocking.

![image](https://user-images.githubusercontent.com/1913805/122983471-576c3400-d39c-11eb-9eb0-dd8cc4ee2133.png)
