### ISSUE TITLE
403 Permission Denied. Only websockets are allowed here.

### ISSUE THREAD

**Issue by tnylea** [stackblitz/webcontainer-core#1350]
### Describe the bug

Hey there 👋

Webcontainers are pretty amazing. Thanks for creating this open source project. I am building a project where I use WASM to bootup PHP (Laravel) applications via NodeJS. I'm using webcontainers to boot-up a Node app in the browser and then proxying the express JS requests to a PHP Wasm application running inside the webcontainer.

I have been able to get everything working successful, until a few weeks ago, when it stopped working. I have a demo you can check out at https://sandbox.devdojo.com, but as you'll see the Webcontainer is always loading a message that says: `403 Permission Denied. Only websockets are allowed here.`

![CleanShot 2024-02-28 at 09 45 32@2x](https://github.com/stackblitz/webcontainer-core/assets/601261/997012bf-2f37-4f7c-8e83-0d1025b152b4)

This was actually working a few months back, but has since stopped working. When I open the URL that is inside of the iframe into a new URL, I get a url similar to this [https://httpssandboxdevdojocom-2wap--62690--c9a8a620.local-corp.webcontainer.io/](https://httpssandboxdevdojocom-2wap--62690--c9a8a620.local-corp.webcontainer.io/), the page looks like this:

![CleanShot 2024-02-28 at 09 47 06@2x](https://github.com/stackblitz/webcontainer-core/assets/601261/4453ef7c-3a7a-4cf6-9071-15dc6a0e306b)

When I click on the link, I get a message that says: **Could not find project**. I think this issue is similar to this https://github.com/stackblitz/webcontainer-core/issues/1025.

Here are my questions.

- Is there anything that I can do to resolve the 403 permissions denied?
- Has something changed recently with the project that would cause this to stop working?
- Are you guys still maintaining this project? I just want to know if I should continue down the Webcontainers route or possibly try an alternate solution.

### Link to the blitz that caused the error

https://sandbox.devdojo.com/

### Steps to reproduce

Go to the page and wait for it to load. In the iframe you'll see the error that I am getting

### Expected behavior

I expect it to output the HTML response from the webcontainer.

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

n/a

### Platform

- OS: MacOS
- Browser: Chrome, Safari, and Firefox
- Version: 121.0

### Additional context

Thanks again for this awesome project and I hope to hear back from you.

**Comment by Nemikolh** [comment]
Hey @tnylea ! :wave: Thank you so much for your kind words about WebContainers. We really appreciate it! :heart: 

Your project sounds really exciting! :star_struck: 

From what you've described, my initial guess would be that you have multiple servers running and the one displayed in your browser is a websocket server because that event fired last.

Given you probably already know which port you want to show, you should ignore `'server-ready'` events for other ports:

```ts
webcontainerInstance.on('server-ready', (port, url) => {
    if (port === expectedPort) {
        iframeEl.src = url;
    }
});
```

where `expectedPort` would be the port that you expect to serve your application.

**Comment by tnylea** [comment]
You sir! You rock.

Thank you. I used what you recommended and that was indeed the issue. Super appreciate it, and keep up the great work!
