### ISSUE TITLE
Render Whitespaces in Stackblitz Editor Filetree

### ISSUE THREAD

**Issue by samydoesit** [stackblitz/webcontainer-core#1354]
### Describe the bug

Hello, I encountered a rather rare issue that nearly gave me a few grey hairs. 😅

I attempted to create a Nuxt reproduction but struggled to render my pages until I identified my error.

<img width="401" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/15785987/dcf63e8b-ac27-42a2-9b6c-c7bec19e6666">

It turns out I inadvertently included a whitespace in the directory name, which wasn't visible, causing me a significant delay in diagnosing the problem.
<img width="397" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/15785987/d2b60a09-9132-4bdf-9e68-36cfb8e541d8">

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-om7hsq-kbhgm2

### Steps to reproduce

1. Go to the provided Stackblitz.
2. Look at the Filetree (./apps/web/) and look at the pages dir's.
3. You cannot see the used whitespace

### Expected behavior

Whitespaces should be rendered similiar to vscode.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Additional context

Interestingly, in the isolated StackBlitz environment for this issue, the Nuxt terminal output was helpful. However, when I initially created the correct reproduction, there was no such message indicating the problem. This was making it even harder to find the issue.

**Comment by fvsch** [comment]
The fix for this issue is rolling out and should be live soon.
