### ISSUE TITLE
Command failed with exit code 1.

### ISSUE THREAD

**Issue by Rameeztanzilite** [stackblitz/webcontainer-core#1356]
### Describe the bug

![image](https://github.com/stackblitz/webcontainer-core/assets/154970310/e7c45238-9a99-465b-a1c7-6e865adfb014)

### Link to the blitz that caused the error

https://stackblitz.com/edit/vue3-script-setup-with-vite-qojcwy?file=package.json

### Steps to reproduce

when i save som e thing so error occours 

### Expected behavior

what i do

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 122.0.0.0
Major version = 122
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 124818403,
  "usedJSHeapSize": 110260359,
  "jsHeapSizeLimit": 4294705152
}
Hash = c9a8a620
```

**Comment by HeyGarrison** [comment]
👋 hey there!

I was able to take a look at your project and figure out what was going on. You can take a look at my fork here: https://stackblitz.com/~/edit/vue3-script-setup-with-vite-xfm4qx?file=package.json

It looks like the `components` folder didn't exist so I created the components specified. It also looks like bootstrap wasn't included in the `package.json` so I added it as a dependency (I think it could be included as a `devDependency`, but up to you).

Anyway, it looks like this resolves the issue I saw with the project itself. Feel free to reply or open a new issue if you have any additional questions or issues!
