### ISSUE TITLE
Terminal is not responding

### ISSUE THREAD

**Issue by asananddevsingh** [stackblitz/webcontainer-core#1357]
### Describe the bug

I've created a new node js app and when I am trying to run it from terminal, it is not allowing me to type anything and run the file.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-eul7hy?file=index.js

### Steps to reproduce

Try typing `node index` in the terminal to run the code.

### Expected behavior

It should allow to type in the terminal.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 121.0.0.0
Major version = 121
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80895484,
  "usedJSHeapSize": 66829628,
  "jsHeapSizeLimit": 4294705152
}
Hash = c9a8a620
```

**Comment by eatplaysleep** [comment]
Having same issue. Been using [this](https://stackblitz.com/fork/github/udplabs/cic-app-template?file=config.js&view=editor&title=auth.rocks&efr=1) URL to generate new projects for **months** without issue. Haven't changed a thing and it just stopped working.

**Comment by eatplaysleep** [comment]
I'm noticing this only happens on a work laptop where Chrome is managed. I have followed the [browser config guide](https://developer.stackblitz.com/platform/webcontainers/browser-config) but it still does not work on my work laptop. However, it works just fine on my personal laptop.

**Comment by eatplaysleep** [comment]
FWIW this seems to be related to our corporate VPN. @asananddevsingh are you connected to a VPN? If so, try disconnecting to see if it works. Still working with our IT team to see what exactly is blocking it.

**Comment by asananddevsingh** [comment]
Hi @eatplaysleep , 

Thanks for swift response. I also feel this is my network issue. I am able to run it on different machine.

Closing the issue.
