### ISSUE TITLE
Preview connection broken

### ISSUE THREAD

**Issue by rhernandog** [stackblitz/webcontainer-core#1358]
### Describe the bug

I'm getting the following message in the preview if I hit the refresh button in the preview:
```
Connection broken
Looks like a new Service Worker was installed by your browser when it shouldn't have. Refreshing the page should fix this issue.
```
Of course refreshing the page does solves the issue but is far from ideal, to not say annoying

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-3bthoh?file=app%2Fpage.tsx

### Steps to reproduce

1. Load the blitz
2. Make some change on the code
3. Hit the refresh button in the preview

### Expected behavior

The preview should refresh as expected.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Ubuntu 22
- Browser: Chrome
- Version: 121.0.6167.139 (Official Build) (64-bit)

**Comment by Nemikolh** [comment]
Hey @rhernandog! Thanks for the report.

We are aware of this issue and have a plan for a better fix that should get rid of that fix entirely. A temporary alternative to do a full page refresh is to restart your dev server. It's not ideal either but at least you don't loose other changes.
