### ISSUE TITLE
Connection broken in View mode

### ISSUE THREAD

**Issue by Prana2580** [stackblitz/webcontainer-core#1361]
### Describe the bug

Connection broken
Looks like a new Service Worker was installed by your browser when it shouldn't have. Refreshing the page should fix this issue. this issue is facing when I want to open side view of web container [ project : Node Js]

If this issue persists, please [file an issue](https://github.com/stackblitz/webcontainer-core).

![image](https://github.com/stackblitz/webcontainer-core/assets/95032574/a3d46ca4-2701-48a6-9a5e-2a382173ebfc)

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-tmcieb?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js,src%2Findex.html&title=node.new%20Starter

### Steps to reproduce

1. Open project 
2. Open side view in web container 
3. Make changes in files
4. then reload the side view 
5. this error is showing.

### Expected behavior

Expected behaviour that I want that show the run in side view without any problem.  

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/95032574/0365102e-5444-411b-8e9a-a6ac12795e68)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

nothing

**Comment by Nemikolh** [comment]
Hey @Prana2580! Sorry for the inconvenience.

We are aware of this issue and have a plan for a better fix that should get rid of that screen entirely.

I'm going to close this issue as this is already tracked in #1358

**Comment by Prana2580** [comment]
Thanks
