### ISSUE TITLE
Could not clone repo after click "create repo" button inside stackblitz projects

### ISSUE THREAD

**Issue by glink25** [stackblitz/webcontainer-core#1365]
### Describe the bug

I created a project in stackblitz, and then click "create repository" button, I can see a new repo with new files showed in my github account successfully, but when i entering the repo from stackblitz workspace, it shows "Could not clone repo"

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/glink25/modern-spa

### Steps to reproduce

1, create a new project
2, connect repo to github
3, open repo in stackblitz, couldnt open repo

### Expected behavior

can open repo

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = cb3c5872d838650fa710504267727c89c0b45070
WebContainer = c9a8a620

Browser name  = Chrome
Full version  = 122.0.0.0
Major version = 122
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56459258,
  "usedJSHeapSize": 53430118,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by SamVerschueren** [comment]
Hey @glink25 👋 ! This was an issue on our side and is fixed in the mean time. I just confirmed that your repository is now working.
