### ISSUE TITLE
Can't run `pip` at Python Environment

### ISSUE THREAD

**Issue by luannzin** [stackblitz/webcontainer-core#1366]
### Describe the bug

I cannot install any Python lib at Stackblitz.

### Link to the blitz that caused the error

https://stackblitz.com/edit/secret-python-tdnpfs?title=Python%20Starter

### Steps to reproduce

try to install some lib

### Expected behavior

not working

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 122.0.0.0
Major version = 122
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 75467954,
  "usedJSHeapSize": 70457514,
  "jsHeapSizeLimit": 2172649472
}
Hash = c9a8a620
```

**Comment by kirjavascript** [comment]
Hi :wave: thanks for reporting this issue!

Python support is currently very experimental. Support for `pip` is not currently on the roadmap as we focus on other areas of WebContainer. 

I will close this issue for now, but if/when we do add `pip` support in the future, we will certainly make an announcement about it!
