### ISSUE TITLE
Project won't compile. The terminal isn't working.

### ISSUE THREAD

**Issue by lrtico** [stackblitz/webcontainer-core#1367]
### Describe the bug

Projects are not compiling. The server isn't running. The terminal won't work and won't let me type anything when I'm in a new Angular project or if I open one of my existing projects (that ran perfectly normal yesterday).

### Link to the blitz that caused the error

https://stackblitz.com/edit/c3ywfu?file=package.json

### Steps to reproduce

1. Go to Dashboard
2. Click on create new project (or if I open one of my existing projects)
3. Click on Angular
4. Try to type on the terminal (won't work)
5. Project doesn't compile (no preview)

### Expected behavior

 I expected the server starts and compiles the code, renders a preview, and I can begin to edit and see changes.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1727" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/11882454/37f529d5-640b-4a2a-a253-b3acb56a427d">

### Platform

```
Browser name  = Chrome
Full version  = 122.0.0.0
Major version = 122
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66852063,
  "usedJSHeapSize": 63326975,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8e1c3ef8
```

**Comment by lrtico** [comment]
I tried restarting Chrome and it had no effect.

**Comment by lrtico** [comment]
The issue is resolved. My company's VPN was blocking the server from starting.

**Comment by coder0107git** [comment]
Possibly related: #1351
