### ISSUE TITLE
mount with snapshot doesnt work 

### ISSUE THREAD

**Issue by dorakadri** [stackblitz/webcontainer-core#1369]
so im working with web container with react and i have a mini express app i did to test the snapshot so the arraybuffer is coming from the backend i console.log it  but when i put it in the mount function it doesnt mount any one have a solution i did like in the docs exactly

**Comment by dorakadri** [comment]
well i found the solution in case anyone need it  u need to convert it in Uint8Array
 const snapshot = await snapshotResponse.arrayBuffer();
 const snapshotUint8Array = new Uint8Array(snapshot);
 console.log(snapshotUint8Array)


 await webcontainerInstance.mount(snapshotUint8Array);

**Comment by kirjavascript** [comment]
Hi :wave: thanks for opening this issue!

It looks like you have the solution so I will close this issue. 

Feel free to open another if you have any other questions!
