### ISSUE TITLE
Connection broken

### ISSUE THREAD

**Issue by evinhad** [stackblitz/webcontainer-core#1377]
### Describe the bug

Looks like a new Service Worker was installed by your browser when it shouldn't have. Refreshing the page should fix this issue.

If this issue persists, please [file an issue](https://github.com/stackblitz/webcontainer-core).

### Link to the blitz that caused the error

https://r71m3yrun-cj0i--4200--810981ba.local-credentialless.webcontainer.io

### Steps to reproduce

1. Go to https://primeng.org/ripple
2. Edit ripple example in StackBlick

### Expected behavior

After previous step 2 it is expected that the ripple example is loaded.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by evinhad** [comment]
I used Chrome

**Comment by SamVerschueren** [comment]
Thanks for reporting 🙏 ! This issue should be fixed now. Let us know if you still run into this.
