### ISSUE TITLE
Connection broken

### ISSUE THREAD

**Issue by pravins24021988** [stackblitz/webcontainer-core#1378]
### Describe the bug

Looks like a new Service Worker was installed by your browser when it shouldn't have. Refreshing the page should fix this issue.

If this issue persists, please [file an issue](https://github.com/stackblitz/webcontainer-core).

### Link to the blitz that caused the error

https://stackblitz.com/edit/salesforce-lwc-gk5xm4?file=src%2Fmodules%2Fx%2FmyComponent%2FmyComponent.html,src%2Fmodules%2Fx%2FmyComponent%2FmyComponent.js,src%2Fmodules%2Fx%2Fapp%2Fapp.html,package.json&title=LWC%20playground

### Steps to reproduce

na

### Expected behavior

na

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 122.0.0.0
Major version = 122
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84765772,
  "usedJSHeapSize": 80510880,
  "jsHeapSizeLimit": 2172649472
}
Hash = 810981ba
```

**Comment by SamVerschueren** [comment]
Thanks for reporting 🙏 ! This issue should be fixed now. Let us know if you still run into this.
