### ISSUE TITLE
Nuxt is broken "statusCode": 500

### ISSUE THREAD

**Issue by chasebank** [stackblitz/webcontainer-core#1384]
### Describe the bug

I've had various issues making Nuxt unusable on Stackblitz for the last month, including their examples on nuxt.com

The current error is 
```
{
  "statusCode": 500,
  "stack": []
}
```

### Link to the blitz that caused the error

https://nuxt.com/docs/examples/hello-world

### Steps to reproduce

This occurs on any Nuxt project, as far as I can tell. Both in spinning up a fresh one and existing ones.

### Expected behavior

 No errors on a new project.

### Platform

Updated Chrome 122 and Firefox 123.

Stackblitz remains completely broken on Safari....

**Comment by manniL** [comment]
This is a bug in Nuxt, not in StackBlitz, and will be fixed in 3.11.1 ☺️
