### ISSUE TITLE
BUG: user session issue

### ISSUE THREAD

**Issue by oe** [stackblitz/webcontainer-core#139]
**Link to the blitz that caused the error**
https://stackblitz.com/edit/github-fshd7k?file=package.json

**Steps to reproduce:**
1. stay log out of stackblitz.com
2. open <https://stackblitz.com/edit/github-fshd7k?file=package.json>
3. sign in via my github account(owner of project above)  by clicking the *sign* button on the top right. 
4. edit some code in the project
5. then save(via cmd + s), webpage stuck, i save it again...
6. it jumps to <https://stackblitz.com/edit/github-fshd7k-c1psoj-xtd4gl-mpwmqf?file=package.json>, I just forked my own project

**Version of webcontainer:**
Hash: 12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08

**Screenshots:**
![image](https://user-images.githubusercontent.com/1655294/120460729-f6b88f80-c3cb-11eb-86c1-316a0b2fe26d.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96746021,
  "usedJSHeapSize": 80642725,
  "jsHeapSizeLimit": 4294705152
}

**Comment by HeyGarrison** [comment]
@oe I'm having trouble recreating this. We recently updated our auth settings, etc. Is this still an issue for you?

**Comment by oe** [comment]
Just tried, it seems this bug has been fixed.

I believe it's an issue related to #116
