### ISSUE TITLE
 uncaughtException Caught stack:  TypeError: "list" argument must be an Array of Buffers     at Function.Buffer.concat (https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:116:14723)     at https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:352:389537

### ISSUE THREAD

**Issue by ChaseRay1989** [stackblitz/webcontainer-core#1390]
### Describe the bug

 uncaughtException Caught stack:  TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:116:14723)
    at https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:352:389537

### Link to the blitz that caused the error

 uncaughtException Caught stack:  TypeError: "list" argument must be an Array of Buffers     at Function.Buffer.concat (https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:116:14723)     at https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:352:389537

### Steps to reproduce

 uncaughtException Caught stack:  TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:116:14723)
    at https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:352:389537

### Expected behavior

 uncaughtException Caught stack:  TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:116:14723)
    at https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:352:389537

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

 uncaughtException Caught stack:  TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:116:14723)
    at https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:352:389537

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

 uncaughtException Caught stack:  TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:116:14723)
    at https://httplocalhost3000-fnmy.w-corp-staticblitz.com/blitz.810981ba.js:352:389537

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
