### ISSUE TITLE
I am unable to see or open the console in my preview

### ISSUE THREAD

**Issue by VanshSh** [stackblitz/webcontainer-core#1396]
### Describe the bug

Whenever I create new project whether of simple javascript or new project react in my preview which open on side I am unable to see the console screen. So I could see my console log.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-c6c4qr?file=README.md,src%2FApp.jsx,src%2FApp.css,src%2FShowNameList.jsx

### Steps to reproduce

1. Just write the console.log("Print") in any of the JSX file.
2. But now you will not see the console screen to open so that you can see you console.log

### Expected behavior

To see the conosle screen so that i can see my consoles.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/81517284/4c023283-335c-4d2b-82d2-b45dc39b0f5a)

### Platform

```
Browser name  = Chrome
Full version  = 123.0.0.0
Major version = 123
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116771347,
  "usedJSHeapSize": 112197627,
  "jsHeapSizeLimit": 2172649472
}
Hash = 7dbe22a9
```

**Comment by kirjavascript** [comment]
hi! :wave: thanks for reporting this issue!

You need to open your browser console window and the logs will appear there!

![Screenshot_2024-04-05_15-48-52](https://github.com/stackblitz/webcontainer-core/assets/4498266/22ca419a-e7c7-4d8f-9c42-1b45f5322aaa)
