### ISSUE TITLE
Third-Party Service Worker Registration and Brave

### ISSUE THREAD

**Issue by jonathansampson** [stackblitz/webcontainer-core#14]
**Describe the bug**
For a user running [Brave](https://www.brave.com) under normal settings, the service worker registration for stackblitz.io fails, as it is a _third party domain_. This failure prevents the localhost server from being stood up for the user's blitz. To remedy the issue, a user can modify their shields (via the lion icon to the right of the address bar) in Brave to permit third-party cookies (this setting also controls third-party service workers).

**Link to the blitz that caused the error**

**To Reproduce**
1. In Brave, visit https://stackblitz.com/edit/web-platform-kaxdum

**Expected behavior**

The "localhost" connection is established, and the content is shown.

**Screenshots**

![service-workers-registration](https://user-images.githubusercontent.com/815158/119045714-70d72600-b981-11eb-8676-50af24832949.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.24.85

**Additional context**

If you catch the registration failure, you can inform the user that their security settings may have prevented the feature from working. For Brave users (there are over 30 million monthly active users at the time of this writing), you can can inform them that relaxing the shield settings for cookies (and other third-party storage) will resolve the issue. This is what I did in the GIF above. Brave can be detected via its `navigator.brave.isBrave` function (which returns a promise).

**Comment by SamVerschueren** [comment]
Thanks for reporting this. It's a very good point and we should definitely work on improving the experience for Brave users. I'm looping it back to the team.

**Comment by fvsch** [comment]
@jonathansampson We now have a warning component shown in Brave when the Service Worker registration fails, linking to https://github.com/stackblitz/webcontainer-core/blob/main/browsers/brave/brave.md

It actually shipped in July, but I forgot to update this issue!
