### ISSUE TITLE
[Bug] stuck in `Downloading swc package @next/swc-wasm-nodejs...` when using Next js starter

### ISSUE THREAD

**Issue by ishowman** [stackblitz/webcontainer-core#1401]
### Describe the bug

![image](https://github.com/stackblitz/webcontainer-core/assets/16897283/01a8239c-a7a4-4f55-bcae-554272667f42)
stuck in `Downloading swc package @next/swc-wasm-nodejs...` when using Next js starter

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-uhfxzu?description=The%20React%20framework%20for%20production&file=app%2Flayout.tsx&title=Next.js%20Starter

### Steps to reproduce

1. click next.js to create new project
![image](https://github.com/stackblitz/webcontainer-core/assets/16897283/17fbd284-0d86-4053-b663-e703dd5bfc80)

2. stuck in downloading  swc package @next/swc-wasm-nodejs...
![image](https://github.com/stackblitz/webcontainer-core/assets/16897283/80e505b9-bf85-4d39-91b9-a733f12492b8)

### Expected behavior

It should not stuck in downloading, and no errors happens

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/16897283/80e505b9-bf85-4d39-91b9-a733f12492b8)

### Platform

```
Browser name  = Chrome
Full version  = 123.0.0.0
Major version = 123
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
performance.memory = {
  "totalJSHeapSize": 109997133,
  "usedJSHeapSize": 103903353,
  "jsHeapSizeLimit": 2172649472
}
Hash = 7dbe22a9
```

**Comment by kirjavascript** [comment]
hi 👋 thanks for reporting this issue!

I'm afraid I cannot seem to reproduce the issue.

Could you try accessing the page from an alternative network connection to ensure these URLs are not being blocked by a VPN or other network restrictions?
