### ISSUE TITLE
BUG: Next.js images don't load

### ISSUE THREAD

**Issue by nicholaschiang** [stackblitz/webcontainer-core#141]
**Describe the bug:**

The Next.js optimized images don't ever load (see below screenshots).

**Link to the blitz that caused the error**
https://stackblitz.com/github/nicholaschiang/website

**Steps to reproduce:**

1. Open https://stackblitz.com/github/nicholaschiang/website
2. Wait for web container and development server
3. Notice how none of the images load

**Expected behavior:**

The Next.js optimized images should load.

**Version of webcontainer:**
Hash: 12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08

**Screenshots:**

If you open the `/photo` page, you'll see that none of them load:

![image](https://user-images.githubusercontent.com/20798889/120521125-7113f000-c389-11eb-994d-a2c76702c0c5.png)

Then, if you right-click on one of those photos and click "Open image in new tab", you'll see this:

![image](https://user-images.githubusercontent.com/20798889/120521359-b9cba900-c389-11eb-8536-b3d9c8f69987.png)

Clearly, the Next.js `/_next/image` route ☝️  isn't working properly.

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.218
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 13816.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.218 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 113348028,
  "usedJSHeapSize": 105239080,
  "jsHeapSizeLimit": 2172649472
}

**Comment by SamVerschueren** [comment]
@nicholaschiang Thanks for trying out StackBlitz 🙏 ! We are aware of issues with images and are working on it. I'll keep you posted when I have updates regarding this topic.

**Comment by SamVerschueren** [comment]
Hi @nicholaschiang. Could you try removing the StackBlitz project and clone from GitHub again? We fixed some issues on our side with regards to images.

// cc @KwintenP

**Comment by SamVerschueren** [comment]
@nicholaschiang Seems to work now 🎉 

![image](https://user-images.githubusercontent.com/1913805/121234066-9c1fa780-c893-11eb-897d-5e7e70d094b7.png)
