### ISSUE TITLE
Angular dev server can't finish rebuild

### ISSUE THREAD

**Issue by LuisTovar0** [stackblitz/webcontainer-core#1411]
### Describe the bug

When an Angular 17 project is opened, it runs `pnpm install && pnpm start` like normal. But when there's a file change, the dev server will detect it and start rebuilding, but it won't finish rebuilding. Basically it seems like the hot-reload is broken. I have to `^C pnpm start` every time i want to see how it looks

### Link to the blitz that caused the error

https://stackblitz.com/edit/mat-ripple-breaking-mat-table

### Steps to reproduce

1. Create new Vanilla JS project
2. `cd ..`
3. `rm -rf <project-name>/*`
4. `npx @angular/cli new <project-name> --force --minimal --package-manager pnpm --routing false --skip-git --skip-tests --ssr false --style scss`, wait for install to finish
5. Save project
6. Exit Stackblitz and enter the project again, or reload page/link
7. Wait for install, run `pnpm start`, wait for the app to render
8. Edit the template of `src/app/app.component.ts`

### Expected behavior

After the change is saved (either by typing or by manual save), the dev server detects the change and starts rebuilding the app. It should rebuild it successfully, and then reload the app served from port 4200.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Windows 10
- Browser: Firefox
- Version: 124.0.2 (64-bit)

### Additional context

I tried to replicate in Chromium and the problem doesn't happen there

**Comment by LuisTovar0** [comment]
I forgot to add that this problem is not present in Chrome, the only alternative I tested on

**Comment by seeplusplus** [comment]
+1 having the same issue on Firefox on macOS. Angular projects don't hot reload ever, I have to kill the dev server and rerun for changes to work.

**Comment by LuisTovar0** [comment]
I've noticed that this issue is a duplicate of [this one](https://github.com/stackblitz/webcontainer-core/issues/1317), so @seeplusplus @BojanKogoj please go support that
