### ISSUE TITLE
Do not support decorator in editor

### ISSUE THREAD

**Issue by yunnysunny** [stackblitz/webcontainer-core#1412]
### Describe the bug

![image](https://github.com/stackblitz/webcontainer-core/assets/734818/a835511b-7a5f-4131-94ea-123ec4439ba8)
TS deorator is not recognized on editor.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-ewicp7?file=package.json,index.ts,tsconfig.json

### Steps to reproduce

Create a blank project, install class-validator and typescript, then create index.ts:
```typescript
import { IsEmail, IsString, MinLength, MaxLength, Contains, IsNotEmpty } from 'class-validator';
import { validate } from 'class-validator';

class BaseContent {
  @IsEmail()
  email: string;

  @IsString()
  password: string;
  myProperty?: string;
}

class User extends BaseContent {
  @MinLength(10)
  @MaxLength(20)
  name: string;

  @Contains('hello')
  welcome: string;

  @MinLength(20)
  password: string;

  @IsNotEmpty()
  myProperty: string;
}
```

### Expected behavior

The ts decorator will be recognized correctly.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 123.0.0.0
Major version = 123
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
performance.memory = {
  "totalJSHeapSize": 129058191,
  "usedJSHeapSize": 125098623,
  "jsHeapSizeLimit": 4294705152
}
Hash = 7dbe22a9
```

**Comment by SamVerschueren** [comment]
Hey @yunnysunny. I just tested your project and it seems to work for me. Can you try again? Maybe something didn't loaded yet in regards to the editor?

**Comment by yunnysunny** [comment]
> Hey @yunnysunny. I just tested your project and it seems to work for me. Can you try again? Maybe something didn't loaded yet in regards to the editor?

Yes, it works ok now.
