### ISSUE TITLE
Terminal got stucked

### ISSUE THREAD

**Issue by Richie2900** [stackblitz/webcontainer-core#1420]
### Describe the bug

while try to do ng generate component product-alerts the terminal gets stucked.

### Link to the blitz that caused the error

https://stackblitz.com/edit/sgyubm-de8dkd?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html,src%2Fapp%2Fproduct-list%2Fproduct-list.component.ts

### Steps to reproduce

1.go to https://stackblitz.com/edit/sgyubm-de8dkd?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html,src%2Fapp%2Fproduct-list%2Fproduct-list.component.ts
2. In terminal try to do ng generate component product-alerts it will give no response

### Expected behavior

Should create a component named  product-alerts.component.ts  

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![issue](https://github.com/stackblitz/webcontainer-core/assets/125335667/33583005-0742-4e7e-95bc-4a9694465c16)

### Platform

```
Browser name  = Chrome
Full version  = 124.0.0.0
Major version = 124
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91248880,
  "usedJSHeapSize": 85068560,
  "jsHeapSizeLimit": 2172649472
}
Hash = 7dbe22a9
```

**Comment by jrvidal** [comment]
@Richie2900 Did you try to kill the process first with Ctrl+C? Or to open a second terminal to run `ng generate` (with the `+` symbol on the upper right corner of the terminal panel)?
