### ISSUE TITLE
UI5 sample app doesn't work - Can't load UI5 Core.js

### ISSUE THREAD

**Issue by marcelschork** [stackblitz/webcontainer-core#143]
**Describe the bug:**
I tried the UI5 sample app after #101 was fixed. The UI5 Core.js file which is loaded via the ui5loader as a synchronous XHR can't be loaded (404).

**Link to the blitz that caused the error:**
https://stackblitz.com/github/SAP/openui5-sample-app

**Steps to reproduce:**

1. npm start
2. Open index.html

**Expected behavior:**
The UI5 sample app should run

**Screenshots:**
<img width="834" alt="Screenshot 2021-06-03 at 20 34 06" src="https://user-images.githubusercontent.com/63337737/120697042-86823a80-c4ad-11eb-9228-e29f82a8370a.png">
<img width="761" alt="Screenshot 2021-06-03 at 20 43 45" src="https://user-images.githubusercontent.com/63337737/120697122-a0bc1880-c4ad-11eb-99d4-4212fa2fd9fa.png">

**Desktop (please complete the following information):**
 
<img width="821" alt="Screenshot 2021-06-03 at 20 53 38" src="https://user-images.githubusercontent.com/63337737/120697289-d3661100-c4ad-11eb-8952-2e90e5564c8f.png">

**Comment by EricSimons** [comment]
Interesting... I can open up the JS file in a new tab and it loads, but it seems that the synchronous XHR always is getting a 404.

@KwintenP @d3lm  do you know if localservice has any limitations with sync XHRs? It appears this request is skipping the service worker and directly hitting the 404 page from s3 (unless I'm mistaken).

**Comment by d3lm** [comment]
Yes that's correct. Synchronous XHR request are not intercepted by a SW, it's not localservice. As you said yourself, that's a bug in Chrome but it's been open for a long time (2016) and apparently has not been fixed since then.

**Comment by HeyGarrison** [comment]
@marcelschork @d3lm I'm coming back around to this issue and it looks like it might be resolved? Can someone confirm for me?
