### ISSUE TITLE
Container Webview doesn't load on Firefox Desktop

### ISSUE THREAD

**Issue by GeorgeWL** [stackblitz/webcontainer-core#1433]
### Describe the bug

Seems to affect all frontend apps, the webview panel of the app doesn't load the preview, only showing the lightning symbol

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-51rwbg?file=index.html&terminal=dev

### Steps to reproduce

1. Go to Dashboard
2. Create a new Frontend Project
3. Enter the project
4. See that webview does not load on Firefox

### Expected behavior

Webview does load on Firefox

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/5931248/a56e1c78-8b3c-4243-9c30-bd21cb9b9c57)
(work PC so covered up some internal-use only bookmarks)

### Platform

```
Browser name  = Firefox
Full version  = 125.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0
performance.memory = undefined
Hash = 34455753
```

### Additional context

[console-export-2024-5-3_15-10-2.txt](https://github.com/stackblitz/webcontainer-core/files/15201053/console-export-2024-5-3_15-10-2.txt)
export of console.log

**Comment by GeorgeWL** [comment]
I also tried disabling uBlock on the site, this made no difference

**Comment by GeorgeWL** [comment]
Just checked the same page at home, seems to be a issue with the work VPN specifically?

**Comment by kirjavascript** [comment]
hi 👋 thanks for reporting this issue!

Yeah, this is likely an issue with the VPN

Could you try and use `curl -v https://foobar.w-credentialless-staticblitz.com/iframe.7dbe22a9.html` to check if you correctly have access to the resources you need via the work VPN? If it fails we know it's that for sure.

It would be ideal to show a better message in this case, and we have plans to improve on this in future.

**Comment by GeorgeWL** [comment]
> curl -v https://foobar.w-credentialless-staticblitz.com/iframe.7dbe22a9.html

I've tried that now, seeing a 200 status, I'll put the message here in a `<details>`

<details>
<summary> cURL response</summary>

```sh
Trying 172.67.187.137:443...
* Connected to foobar.w-credentialless-staticblitz.com (172.67.187.137) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=w-credentialless-staticblitz.com
*  start date: Apr 13 01:23:06 2024 GMT
*  expire date: Jul 12 01:23:05 2024 GMT
*  subjectAltName: host "foobar.w-credentialless-staticblitz.com" matched cert's "*.w-credentialless-staticblitz.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1P5
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x23a567d1980)
> GET /iframe.7dbe22a9.html HTTP/2
> Host: foobar.w-credentialless-staticblitz.com
> user-agent: curl/7.78.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< date: Wed, 15 May 2024 11:25:15 GMT
< content-type: text/html; charset=utf-8
< last-modified: Wed, 27 Mar 2024 09:34:02 GMT
< x-amz-server-side-encryption: AES256
< cache-control: public, max-age=31557600
< accept-ranges: bytes
< x-cache: Miss from cloudfront
< via: 1.1 a332ecb068a370997b5e7bc811ff54ea.cloudfront.net (CloudFront)
< x-amz-cf-pop: LHR62-C5
< alt-svc: h3=":443"; ma=86400
< x-amz-cf-id: bTVq9Hntm2f_sFj1smabeB7zXbW0ACkxmqZ1rFk3-0l09WjAK9m7vg==
< cross-origin-embedder-policy: credentialless
< cross-origin-opener-policy: same-origin
< cross-origin-resource-policy: cross-origin
< vary: Origin, Accept-Encoding
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=gMYHXfj%2FjyPNSERFQ6QtXlYttLIReYjD%2BQw9tS2nkyrcda1XrLWNTSzyl%2BqsqnWw7TLEF5n5JRAZCXq8o3dyhIG9TCi1Piawub17CBfSLEL2BirsTRxLQhytZw37rQybCb5K1A5sQa3Bt0OOTVRxrhj1QRXwZJQo6mY%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< origin-agent-cluster: ?1
< server: cloudflare
< cf-ray: 8842c42609e39527-LHR
<
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<script src="iframe.main.7dbe22a9.js"></script>
</head>
<body></body>
</html>* Connection #0 to host foobar.w-credentialless-staticblitz.com left intact
```
</details>

**Comment by GeorgeWL** [comment]
not sure what's changed, but now it loads in fine

**Comment by kirjavascript** [comment]
fantastic! I'll close this issue then. feel free to open another if there are any other issues!
