### ISSUE TITLE
`npm serve` does not work, "Running start command" fails

### ISSUE THREAD

**Issue by mirko314** [stackblitz/webcontainer-core#1444]
### Describe the bug

We have a rather simple example code directory where we want to `serve` a bunch of static files. Upon booting the project up, the start command fails.

Also running `npm start` exits directly without any error message.

<img width="1043" alt="Screenshot 2024-05-16 at 09 29 00" src="https://github.com/stackblitz/webcontainer-core/assets/13023567/74481338-40b6-4c51-91b7-9d055c579800">

### Link to the blitz that caused the error

https://stackblitz.com/edit/imgly-cesdk-web-examples-z9bygx?file=index.js&title=IMG.LY%27s%20CE.SDK:%20Configure%20Ui%20Elements

### Steps to reproduce

Simply open the stackblitz link. It does not start.
Alternativly you can also try to run `npm start` manually and should see an immediate quiet exit.

### Expected behavior

`npm start` serves the directory.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 124.0.0.0
Major version = 124
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 70598003,
  "usedJSHeapSize": 67371271,
  "jsHeapSizeLimit": 4294705152
}
Hash = 1d4c3cdd
```

**Comment by SamVerschueren** [comment]
Hey @mirko314 👋 . Thanks for reaching out. Can you try this again? I just ran the project and it seems to work. Maybe we fixed something in the mean time which made it work.
