### ISSUE TITLE
web3-m

### ISSUE THREAD

**Issue by Yakuza-3301** [stackblitz/webcontainer-core#1456]
### Describe the bug

~/projects/vitejs-vite-n8wxpp 13m 19s
❯ npm install web3modal @walletconnect/web3-provider ethers

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-06-02T06_40_37_950Z-debug-0.log
jsh: spawn npm ENOENT

~/projects/vitejs-vite-n8wxpp 44s
❯ npm install web3modal @walletconnect/web3-provider ethers
 
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-06-02T06_41_49_958Z-debug-0.log
jsh: spawn npm ENOENT

~/projects/vitejs-vite-n8wxpp 1s

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-xhqscz?file=index.html,vite.config.js,src%2FApp.jsx,src%2Findex.css,.vscode%2Fsnippets.json&terminal=dev

### Steps to reproduce

import all the required

### Expected behavior

imported

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 125.0.0.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 200543852,
  "usedJSHeapSize": 189840472,
  "jsHeapSizeLimit": 4294705152
}
Hash = 12d46890
```

**Comment by SamVerschueren** [comment]
Our classic editor doesn't support `git`. If you want to use `git` commands, you have to use Codeflow by using https://stackblitz.com/~ instead. You can open your project in Codeflow (our new editor) by adding a `~` in between the URL. https://stackblitz.com/~/edit/vitejs-vite-xskm5x

In that editor you can install those dependencies.
