### ISSUE TITLE
How to adjust the font size of the code?

### ISSUE THREAD

**Issue by masx200** [stackblitz/webcontainer-core#146]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

How to adjust the font size of the code?
**Describe alternatives you've considered:**

**Additional context:**

**Comment by SamVerschueren** [comment]
Hi @masx200 

You can open your user-settings and change the `editor.fontSize` property.

![image](https://user-images.githubusercontent.com/1913805/120778236-6478ce80-c526-11eb-900e-a988460878f0.png)

User settings can be found under `Settings` (cog icon) at the left.
![image](https://user-images.githubusercontent.com/1913805/120778274-7195bd80-c526-11eb-8a15-60d8f77b3a8e.png)
