### ISSUE TITLE
[Request] Support for nodejs addons

### ISSUE THREAD

**Issue by alshdavid** [stackblitz/webcontainer-core#1460]
When trying to use an npm package that uses a Nodejs addon (like `parcel`, `rspack`, etc), Nodejs fails with:

```
❯ npx mach version
Error: Cannot load native addon because loading addons is disabled: [...]
```

**Describe the solution you'd like:**
Enable the use of napi modules

**Describe alternatives you've considered:**
N/A

**Comment by SamVerschueren** [comment]
Hey @alshdavid 👋 . Given we are still running everything in a browser context, it's impossible to run arbitrary binaries. For that reason, loading native addons is disabled.

You can find more information here https://developer.stackblitz.com/platform/webcontainers/troubleshooting-webcontainers#cannot-load-native-addon.

**Comment by alshdavid** [comment]
Thanks! I have a question. My project is currently a Rust project compiled to a native addon and I'd love to support web containers as it's the perfect environment to use as a "playground" environment. 

I already build to a wasm binary, using `wasm-bindgen` for wasm bindings for web targets. 

To avoid having the main npm package distribute binaries for every platform, I am using `optionalDependencies` in conjunction with the package.json `os` and `arch` properties to allow `npm` to determine which binary package to install.

```json
{
  "name": "parcel",
  "optionalDependencies": {
    "@parcel/linux-amd64",
    "@parcel/linux-arm64",
    "@parcel/macos-amd64",
    "@parcel/macos-arm64",
    "@parcel/windows-amd64",
    "@parcel/windows-arm64",
  }
}
```
Where each package specifies:
```json
{
  "name": "@parcel/linux-amd64",
  "os": ["linux"],
  "cpu": ["x64"]
}
```
npm uses `process.arch` and `process.platform` [to determine what package is eligible for installation](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#os).

I could publish a `@parcel/wasm` package with the appropriate bindings, however I am unsure what to use for `os` and `arch`.

Running this in the web container:
```
node -e "console.log(process.arch, process.platform)"
```
Gives me 
```
x64 linux
```

Are you able to build Nodejs with a custom process.arch? Perhaps setting it to `wasm`?
