### ISSUE TITLE
SWC error on Next.js app router projects

### ISSUE THREAD

**Issue by Prisaca** [stackblitz/webcontainer-core#1463]
### Describe the bug

Cannot run any newer nextjs projects because of swc.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/Prisaca/admin-dashboard?file=.env.example

### Steps to reproduce

pnpm i -> npx next dev

### Expected behavior

expecting the dev server to work

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

-

### Platform

```
Version = 1.84.0
Hash = 5f55b358bd53b196a59d6d290be4ab842509ed00
WebContainer = c3e5e364

Browser name  = Chrome
Full version  = 125.0.0.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 121156057,
  "usedJSHeapSize": 115227489,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

-

**Comment by saadh393** [comment]
I am also facing the same issue, is there any update ?

**Comment by mdsalahuddin2001** [comment]
I am also facing the same issue

**Comment by SamVerschueren** [comment]
This is fixed in Next.js 14.2.5, so you have to upgrade to that version.
