### ISSUE TITLE
Error creating a new app from template React TypeScript (Cannot use JSX unless the '--jsx' flag is provided.(17004))

### ISSUE THREAD

**Issue by luisjunco** [stackblitz/webcontainer-core#1465]
### Describe the bug

Hi, 

when you create a new app with the template "React TypeScript", the app runs but the editor is showing this TypeScript error (screenshot attached):

> Cannot use JSX unless the '--jsx' flag is provided.(17004)

This error appears right from the beginning (i.e., without making any changes to the code or configuration).

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-gfg6bq?file=src%2FApp.tsx

### Steps to reproduce

- Go to https://stackblitz.com/
- Create a new app with the template React TypeScript

### Expected behavior

I'd expect the template to work without errors from the beginning and without having to touch ts config files.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/38411763/3f57d641-d45f-42e6-8992-76cbaa758a7c)

### Platform

```
Browser name  = Chrome
Full version  = 125.0.0.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 349900517,
  "usedJSHeapSize": 336120645,
  "jsHeapSizeLimit": 2172649472
}
Hash = 9e2d28a3
```

### Additional context

Note: I had to mark the checkbox "I have run the project in my local machine" (it seems to be a required field, can not submit the form template without marking it). However, I have only tested on the web version.

**Comment by MrZhouZh** [comment]
same issue~
![image](https://github.com/stackblitz/webcontainer-core/assets/24643748/27db7fcd-2ea0-4261-b9b0-1ed28b6c177a)

**Comment by BlessYAHU** [comment]
The tsconfig.json file in default Reactjs project template references tsconfig.app.json which has the compiler option, but doesn't seem to pick it up.  When I put the the jsx compiler option in tsconfig.tsx, the issue was resolved.

[Here](https://stackblitz.com/edit/vitejs-vite-jrf7yw?file=src%2FApp.tsx) is a fresh empty project with the compiler option added to the tsconfig.json.  
 
I'm not saying this is the solution, just what I discovered.   Hopefully this helps shed some light on the issue.

**Comment by alexalannunes** [comment]
it works for me
 
```json
 "compilerOptions": {
    "jsx": "react-jsx"
  },
```

**Comment by SamVerschueren** [comment]
We are aware of this issue and we have a fix for it. I will try to get it released today.

**Comment by SamVerschueren** [comment]
This is now released. If you run into any other issues with the fix, let us know so we can address them.

**Comment by andyhasit** [comment]
Just to add information here. I had this issue in [my stackblitz](https://stackblitz.com/edit/wallace-ts) (Using a different JSX framework, not React) after updating the version in `package.json` and it went away after a hard page refresh (I'm pretty sure I did a normal refresh first and and it didn't work, but perhaps its a timing issue).
