### ISSUE TITLE
I cant see the app url with my account

### ISSUE THREAD

**Issue by danilodiez** [stackblitz/webcontainer-core#1474]
### Describe the bug

![image](https://github.com/stackblitz/webcontainer-core/assets/50375875/ba878fec-efe9-490e-91bc-b9d1882ab8e4)

I can't see the application URL to share a "deployed" version of my app

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-kjnyqx?file=src%2FApp.tsx

### Steps to reproduce

1 - open the project
2 - click share
3 - can't see the app url

### Expected behavior

should show the app url in order to share my app

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/50375875/e0b02404-bad1-42d0-affd-9d5baafa24a1)

### Platform

```
Browser name  = Chrome
Full version  = 125.0.0.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 133218026,
  "usedJSHeapSize": 130600506,
  "jsHeapSizeLimit": 4294705152
}
Hash = dc4d7514
```

**Comment by SamVerschueren** [comment]
Hey @danilodiez 👋 . Thanks for reaching out. WebContainer projects don't have a shareable URL for the app itself, you can only share the project.
