### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by vanloi-dev** [stackblitz/webcontainer-core#148]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/http-server-jjca4u?file=package-lock.json

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 89.0.4389.150
Major version = 89
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/95.0.150 Chrome/89.0.4389.150 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91793561,
  "usedJSHeapSize": 72222101,
  "jsHeapSizeLimit": 1098907648
}

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
