### ISSUE TITLE
editor with jsx warnings

### ISSUE THREAD

**Issue by alexalannunes** [stackblitz/webcontainer-core#1480]
### Describe the bug

I just created a new react project and I got this warnings

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-8pfgsb?file=src%2FApp.tsx&terminal=dev

### Steps to reproduce

1. create a new project
2. wait for installation
3. Observe

### Expected behavior

No warning should display with correct tsconfig about jsx

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/16847836/e50ada9d-2595-439e-a689-24d53e923b36)

### Platform

```
Browser name  = Chrome
Full version  = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109901867,
  "usedJSHeapSize": 107615847,
  "jsHeapSizeLimit": 2172649472
}
Hash = 70dbe416
```

**Comment by BlessYAHU** [comment]
This issue is being discussed in [#1465](https://github.com/stackblitz/webcontainer-core/issues/1465).

**Comment by alexalannunes** [comment]
thanks @BlessYAHU .
