### ISSUE TITLE
When I take a new Angular project from Dashboard, I am unable to use Angular CLI commands to generate components an other elements.

### ISSUE THREAD

**Issue by sudheer219** [stackblitz/webcontainer-core#1482]
### Describe the bug

I have created a new project from Stackblitz dashboard.

I am unable to use Angular CLI to generate components.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-ukigyr?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fglobal_styles.css,src%2Fmain.ts&template=node&title=Angular%20Starter

### Steps to reproduce

1. Go to Stackblitz
2. create a new Angular project
3. you can see the code editor 
4. but there is no scope for generating components using Angular-cli or other way.
5. to Do this manual is error prone and a drawback to Stackblitz rapid application building

### Expected behavior

I should be able to use CLI or other mean to generate components, services and other essentials.
Also how to install other dependencies of node modules, like if I want to add PrimeNg or other modules. It should be easy.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89353441,
  "usedJSHeapSize": 85427381,
  "jsHeapSizeLimit": 4294705152
}
Hash = 70dbe416
```

### Additional context

This I cannot run locally as it's online platform

**Comment by SamVerschueren** [comment]
Hey @sudheer219 👋 . Thanks for reaching out!

I'm not entirely sure if I understand your question entirely. The way how you would do things in StackBlitz is identical to how you would do it on local. Just type the commands in the terminal.

![image](https://github.com/user-attachments/assets/972509ed-eb47-4459-aeea-08b2ffc92784)

Same for installing a package.

![image](https://github.com/user-attachments/assets/fceb51c0-8939-49d6-a9f6-8327cd3c6f39)

Let us know if you have any additional questions!
