### ISSUE TITLE
Initialization on a nested route is broken (Angular)

### ISSUE THREAD

**Issue by ilyakonrad** [stackblitz/webcontainer-core#1483]
### Describe the bug

When I'm on a nested route, every time I make a change in the code, it starts to reload but never resolves.
So I have to stop the process manually and rerun `npm start`.

It turns out, the initialization on a nested route is broken, there's an error in the console:
`Refused to apply style from 'https://stackblitzstartersq5q7wx-e423--4200--70dbe416.local-credentialless.webcontainer.io/dashboard/styles.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

I also noticed that nested routes are not reflected in the address bar at all in the editor mode and there's another error in the console on initialization, even though everything functions fine: `Uncaught (in promise) TypeError: Cannot navigate to URL: https://stackblitzstartersq5q7wx-e423--4200--70dbe416`.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-q5q7wx

### Steps to reproduce

- click on "One" to go to the nested route and trigger a page reload

or

- open a [direct link to a nested route](https://stackblitzstartersq5q7wx-e423--4200--70dbe416.local-credentialless.webcontainer.io/dashboard/route1) and compare it to the [parent route](https://stackblitzstartersq5q7wx-e423--4200--70dbe416.local-credentialless.webcontainer.io/dashboard)

### Expected behavior

Stackblitz doesn't care on which route I initialize my Angular app.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93288048,
  "usedJSHeapSize": 89064732,
  "jsHeapSizeLimit": 4294705152
}
Hash = 70dbe416
```

**Comment by SamVerschueren** [comment]
Hey @ilyakonrad 👋 ! Thanks for reaching out. I tested this on local, and it also doesn't work for me on local, so you might need to report this to the Angular project instead.

![image](https://github.com/user-attachments/assets/42a80e4c-6ce6-4004-847c-f541a4bff751)

Or does it work for you on local? I noticed you checked the box `I have run the project in my local machine and I could not reproduce the issue.`

**Comment by ilyakonrad** [comment]
I'm sorry, I was missing the `<base href="/">` in `index.html` 🙈

**Comment by ilyakonrad** [comment]
But I think this should be included in your Angular template by default.

**Comment by SamVerschueren** [comment]
Done @ilyakonrad https://github.com/stackblitz/starters/pull/34.
