### ISSUE TITLE
Unable to move files in the folder to the root directory.

### ISSUE THREAD

**Issue by MaLuns** [stackblitz/webcontainer-core#1491]
**Is your feature request related to a problem? Please describe:**

Unable to move files in the folder to the root directory.

**Describe the solution you'd like:**

Can move files or folders in a folder to the root directory.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by kirjavascript** [comment]
Hi! :wave: thanks for reporting this issue!

can you provide a little more information on what you've tried to do? it seems to work for me

```~/projects/node
❯ mv index.js /index.js

~/projects/node
❯ ls /
bin/      dev/      etc/      home/     index.js  tmp/      usr/     ```

**Comment by MaLuns** [comment]
> Hi! 👋 thanks for reporting this issue!
> 
> can you provide a little more information on what you've tried to do? it seems to work for me
> 
> ```shell
> ~/projects/node
> ❯ mv index.js /index.js
> 
> ~/projects/node
> ❯ ls /
> bin/      dev/      etc/      home/     index.js  tmp/      usr/     ```
> ```

Thanks for your reply.

Sorry for the lack of clarity, the above refers to UI operations. But commands do work.

**Comment by MaLuns** [comment]
https://github.com/user-attachments/assets/964a7ce5-e288-4044-b557-b042d5192eff

**Comment by MaLuns** [comment]
> Microsoft.Edge.2024-08-01.20-44-56.-.Trim.mp4

_posts moving to scaffolds is OK, but moving to root doesn't work

**Comment by kirjavascript** [comment]
try dragging it onto another top level file:


https://github.com/user-attachments/assets/862d451e-13ff-484d-b47f-c1d932caa20f
