### ISSUE TITLE
StackBlitz server crashed

### ISSUE THREAD

**Issue by ThirdGearDev** [stackblitz/webcontainer-core#1492]
### Describe the bug

I went on one of my repositories, and clicked Learn more on the thing that talked about the github bot. and it crashed. Also webcontainer/ output area just stays loading so I never see my output
![Screenshot 2024-08-01 10 54 08](https://github.com/user-attachments/assets/bf8a3ef8-113a-4ce3-a04e-f78cbc2f7f4e)
 

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/ThirdGearDev/XML-tutorial-example

### Steps to reproduce

open a github respository via stack blitz and click on learn more when it asks if you want to enable GitHub bot.

### Expected behavior

It would show me the benefits of the github bot.

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![Screenshot 2024-08-01 10 57 33](https://github.com/user-attachments/assets/d22ade99-9ef1-4a38-a081-6dab5ad27843)
 
Also i did not actually attempt to run the project in my"local machine", because idk what the heck that is

### Platform

```
Version = 1.84.0
Hash = 499be3932f50ab06349575b1c9042f95bc072a8b
WebContainer = 41692973

Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14816.131.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 47420122,
  "usedJSHeapSize": 43862982,
  "jsHeapSizeLimit": 1017905152
}
```

### Additional context

TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at registerModule (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:161:1216)
    at registerImportModuleDynamically (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:266:529)
    at internalCompileFunction (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:266:1091)
    at wrapSafe (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:144:13497)
    at Module._compile (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:144:13881)
    at Module._extensions..js (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:144:14855)
    at Module.load (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:144:12820)
    at Module._load (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:144:10273)
    at Function.executeUserEntryPoint [as runMain] (https://xmltutorialexample-h0q2.w-credentialless-staticblitz.com/builtins.1003299b.js:165:1641)

Node.js 18.20.3

**Comment by kirjavascript** [comment]
Hi! :wave: thanks for reporting this issue!

we are tracking it internally and will update here when it's fixed!

**Comment by ThirdGearDev** [comment]
> Hi! 👋 thanks for reporting this issue!
> 
> we are tracking it internally and will update here when it's fixed!

Did you get the part about how webcontainer is just saying that it is booting?

**Comment by kirjavascript** [comment]
Yeah, the issue is the same as ones reported by other users

**Comment by ThirdGearDev** [comment]
> Yeah, the issue is the same as ones reported by other users

so fix it then?

**Comment by SamVerschueren** [comment]
There's no reason to be rude or pissed about this. So instead of giving answers which don't really help the conversation, think twice the next time you comment in a thread.

The problem is that you are using an older version of Chrome which doesn't support `Symbol()` as key in a `WeakMap`. We worked around that issue for Firefox (as Firefox also doesn't support it, not even in the latest version). However, Chrome does support in since Version 109 which was released January 10th of 2023 so we assumed we would be fine.

We will take a look at supporting this for older versions of Chrome.

**Comment by ThirdGearDev** [comment]
> There's no reason to be rude or pissed about this. So instead of giving answers which don't really help the conversation, think twice the next time you comment in a thread.
> 
> The problem is that you are using an older version of Chrome which doesn't support `Symbol()` as key in a `WeakMap`. We worked around that issue for Firefox (as Firefox also doesn't support it, not even in the latest version). However, Chrome does support in since Version 109 which was released January 10th of 2023 so we assumed we would be fine.
> 
> We will take a look at supporting this for older versions of Chrome.

I added a question mark, wasn't being rude or pissed. You're angrier than me. And I wasn't even mad. That's your perception.  Just curious why if it is known it hasn't been fixed. I'd get a different version of chrome, or a different device if I wasn't living under parents who think coding=hacking and scamming.

**Comment by SamVerschueren** [comment]
This issue is now resolved. Thanks for reporting!

If you run into other issues, please let us know.

**Comment by ThirdGearDev** [comment]
![Screenshot 2024-08-07 11 08 15 AM](https://github.com/user-attachments/assets/4b288472-6f2c-4a0f-9571-5a0330ba5405)
There is progress, but sadly no output.

**Comment by SamVerschueren** [comment]
Can you share the link of your project? I assume the project you run is just a Node.js script so then you need to run `node index.js` in the terminal for instance.

**Comment by ThirdGearDev** [comment]
> Can you share the link of your project? I assume the project you run is just a Node.js script so then you need to run `node index.js` in the terminal for instance.

My projects aren't just node.js scripts, i don't use them. I don't even know javascript in the first place. The issue is on every project I open.

**Comment by ThirdGearDev** [comment]
> Can you share the link of your project? I assume the project you run is just a Node.js script so then you need to run `node index.js` in the terminal for instance.

I found a replacement, VS code.dev . I guess i should be thanking you guys for building this so I can find a replacement. I'll never forget StackBlitz though.

**Comment by SamVerschueren** [comment]
So are these just some html and css files? In that case you can use something like [servor](https://www.npmjs.com/package/servor) or [lite-server](https://www.npmjs.com/package/lite-server) to start the project. Here's an example.

https://stackblitz.com/edit/node-efzgn5?

**Comment by ThirdGearDev** [comment]
> So are these just some html and css files? In that case you can use something like [servor](https://www.npmjs.com/package/servor) or [lite-server](https://www.npmjs.com/package/lite-server) to start the project. Here's an example.
> 
> https://stackblitz.com/edit/node-efzg
It works! It'll be a bit of a hassle to paste the js script in everytime but it works!

**Comment by ThirdGearDev** [comment]
> So are these just some html and css files? In that case you can use something like [servor](https://www.npmjs.com/package/servor) or [lite-server](https://www.npmjs.com/package/lite-server) to start the project. Here's an example.
> 
> https://stackblitz.com/edit/node-efzgn5

It'll be a bit of a hassle to paste that script in everytime but it works!

**Comment by ThirdGearDev** [comment]
> So are these just some html and css files? In that case you can use something like [servor](https://www.npmjs.com/package/servor) or [lite-server](https://www.npmjs.com/package/lite-server) to start the project. Here's an example.
> 
> https://stackblitz.com/edit/node-efzgn5

I think the problem is because I don't use json and js files.

**Comment by ThirdGearDev** [comment]
The default json script made it work 
![image](https://github.com/user-attachments/assets/3052967a-f1ac-4d99-bdca-803ec1b465aa)
