### ISSUE TITLE
BUG: GraphQL starter returns error EOF

### ISSUE THREAD

**Issue by blankey1337** [stackblitz/webcontainer-core#15]
---
name: Bug report
about: Create a report to help us improve
title: 'GraphQL starter returns error EOF'
labels: 'graphql'
assignees: ''

---

**Describe the bug**
The GraphQL starter seems to have a minor misconfiguration issue.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/graphql-s4wnmh

**To Reproduce**
1. Go to 'stackblitz.com'
2. Click on 'GraphQL'
3. Scroll down to 'Click "Play"' on GraphiQL

**Expected behavior**
Should see "Hello World!"

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**
![image](https://user-images.githubusercontent.com/42594751/119050660-0325fc80-b977-11eb-97e3-4e114840709f.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 87.0.4280.141
Major version = 87
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
performance.memory = {
  totalJSHeapSize: 63021506,
  usedJSHeapSize: 59189210,
  jsHeapSizeLimit: 2172649472
}

**Additional context**

**Comment by janpio** [comment]
When you send a query like `query {hello}` the expected is returned.

**Comment by blankey1337** [comment]
hmm not for me 
![image](https://user-images.githubusercontent.com/42594751/119062089-ba783e80-b98a-11eb-9c48-f438172d1b83.png)
