### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by samsepfs** [stackblitz/webcontainer-core#150]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-6dry4c

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62180099,
  "usedJSHeapSize": 55666563,
  "jsHeapSizeLimit": 2171863040
}

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
