### ISSUE TITLE
BUG: Embedding's "view" property does not work correctly.

### ISSUE THREAD

**Issue by TheMrZZ** [stackblitz/webcontainer-core#151]
**Describe the bug:**

When embedding a StackBlitz, the "view" property only work when set to "preview" - in which case it sets the preview.
Any other value will be like specifying "both".

Therefore, "view=editor" does not show only the editor.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/sandstone-example?view=editor&embed=1&file=src/greet.ts&

**Steps to reproduce:**
Create a Blitz, and try to embed it in another web page, with `view=editor`. For example:
https://stackblitz.com/edit/sandstone-example?view=editor&amp;embed=1&amp;file=src/greet.ts&amp;

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots**
![image](https://user-images.githubusercontent.com/30944236/120867848-10580380-c593-11eb-90f4-1818103d3471.png)

**Comment by SamVerschueren** [comment]
I believe we fixed this and it should work now. Can you try it out? 🙏
