### ISSUE TITLE
webview wont open/cant preview my site

### ISSUE THREAD

**Issue by vassilisssssss** [stackblitz/webcontainer-core#1514]
### Describe the bug

![image](https://github.com/user-attachments/assets/df128645-a8d8-4fb3-b9bf-9682aaf50e25)
just shows that

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-jxixak?file=404.html

### Steps to reproduce

1. go on your project, 2. you will see that the webview doesnt open

### Expected behavior

should show the site

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/user-attachments/assets/275751a0-7a24-42e4-ad5e-3abb00ce0d46)

### Platform

```
Browser name  = Chrome
Full version  = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87683233,
  "usedJSHeapSize": 78767681,
  "jsHeapSizeLimit": 2172649472
}
Hash = e60eb5c9
```

**Comment by SamVerschueren** [comment]
See https://github.com/stackblitz/webcontainer-core/issues/1501#issuecomment-2334186926 for an answer.
