### ISSUE TITLE
Support "Vim Mode"

### ISSUE THREAD

**Issue by despairblue** [stackblitz/webcontainer-core#155]
In the old repo this issue was closed, saying that vim mode is supported now: https://github.com/stackblitz/core/issues/20#issuecomment-846327858

Given the comments below, it seems not obvious how to enable it. Maybe that issue was closed by accident. 

If vim mode is supported, how do we enable it?
If vim mode is not supported see this as a feature request :)

Nice work otherwise, I just can't edit code without vim key bindings anymore 😖

**Comment by SamVerschueren** [comment]
Hi @despairblue! Thanks for reporting this 🙏 . Yes, you are right, VIM mode does not exist and it was closed by mistake. Let me re-open that one and close this one instead. We want to keep this repo for WebContainer issues only.
