### ISSUE TITLE
BUG: Atocompletion does not work for imported libraries

### ISSUE THREAD

**Issue by TheMrZZ** [stackblitz/webcontainer-core#157]
**Describe the bug:**

When importing from a library, autocompletion does not work on:
- Exported members
- Automatic imports
- Arguments

Just like there was no typing at all. What's weird, is that it sometimes work. I caught it in a video. The video starts by showing a classical project, which autocompletes everything perfectly. Then it shows a web container project, where autocompletion works. After a refresh, it doesn't work anymore.

Aucompletion also never works in webcontainer snippets, in my experience.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/sandstone-example?view=editor&embed=1&file=src/greet.ts&

**Link to a working blitz (using the old tech, not web containers)**
https://stackblitz.com/edit/typescript-bdpxgj?view=editor&embed=1&file=src/greet.ts&

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**
https://user-images.githubusercontent.com/30944236/120895548-b6505000-c61d-11eb-9a66-700e19eeb640.mp4

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64110263,
  "usedJSHeapSize": 57974695,
  "jsHeapSizeLimit": 4294705152
}

**Comment by KwintenP** [comment]
Hi, 

You are correct. We need to wire some things internally so the editor is aware of installed modules. We are currently working on this issue and it should be shipped pretty soon!

**Comment by SamVerschueren** [comment]
Hi @TheMrZZ 👋 . We fixed quite some things regarding type definition resolution. Testing your project now again does seem to pick up the type definitions of `sandstone` correctly. Closing this issue as I think it is resolved. If you stil run into bugs with it, feel free to create a new issue.
