### ISSUE TITLE
BUG: installing dependencies fails

### ISSUE THREAD

**Issue by aheissenberger** [stackblitz/webcontainer-core#158]
**Describe the bug:**

Trying to install any dependenc with `yarn` or  `nom` fails.

```
yarn add ylq
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ 𐄂 Failed
ERR!: Failed to resolve dependencies

error Command failed with exit code 1

~/projects/node-h6n33x
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-h6n33x

new created empty nodejs project

**Steps to reproduce:**

1. create new empty nodejs project
2. write in Terminal `yarn add ylq`

**Expected behavior:**

install dependencies :-)

**Version of webcontainer:**
Hash: node-xbebwg

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory ={
jsHeapSizeLimit: 4294705152
totalJSHeapSize: 63201213
usedJSHeapSize: 56440405
}

**Additional context:**

**Comment by SamVerschueren** [comment]
Hi @aheissenberger, thanks for trying out WebContainer. Have you tried other packages, and do they work? It doesn't look like the package you try to install exists https://www.npmjs.com/package/ylq. Could that be the problem?

**Comment by aheissenberger** [comment]
you are right there is a typo in the package. But I tested again and it does not work:
```
npm install vlq
or
npm install lodash
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ 𐄂 Failed
ERR!: Failed to resolve dependencies

error Command failed with exit code 1
```

**Comment by SamVerschueren** [comment]
Can you open your devtools and look at the network requests? Do you run into CORS perhaps? Try hard refreshing your browser and try it again.

**Comment by SamVerschueren** [comment]
It looks like because you misspelled `vlq` in your `package.json`, that it now fails on installing any package. Rename `ylq` in the dependency list in `package.json` to `vlq` and it will work.

@d3lm Is this intended behaviour? If you haven't run `npm install` yet, and then you run `npm install lodash`, that it also installs all other dependencies?

**Comment by d3lm** [comment]
Yes that's intended behavior and it's the same with `npm 7.x` and `yarn`. Only older versions of npm (< 7) did not install all dependencies.

**Comment by aheissenberger** [comment]
you are right - all my fault :-). great product

**Comment by SamVerschueren** [comment]
No worries, glad we figured this out 🙏 😄
