### ISSUE TITLE
BUG: keyboard doesn't work

### ISSUE THREAD

**Issue by Jamelle-Boose** [stackblitz/webcontainer-core#159]
**Describe the bug:**
keyboard doesn't work

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-jqc1z2

**Steps to reproduce:**
1. Go to `index.js`
2. Try editing any line

**Expected behavior:**
keys should work

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 141395499,
  "usedJSHeapSize": 122843167,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**
i can edit `package,json` but not another file
![image](https://user-images.githubusercontent.com/19831942/120906250-9f553200-c60c-11eb-9667-7b0586d7b711.png)

**Comment by Jamelle-Boose** [comment]
I just noticed if I create a new file and copy the contents from `index.js` to the new file, then I can edit that file. I guess that works...

**Comment by Jamelle-Boose** [comment]
Works fine in Firefox as well

**Comment by SamVerschueren** [comment]
Seems to work fine here 🤔 . Is this still an issue for you?

**Comment by Jamelle-Boose** [comment]
Hi Sam. Thanks for looking into this. This is no longer an issue for me as a Chrome extension was causing me to be unable to edit files. I am going to close this issue.
