### ISSUE TITLE
FireFox support

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/webcontainer-core#162]
**Describe the bug:**
I opened a link in my primary browser, firefox, got told my browser was "Incompatible"

**Link to the blitz that caused the error:** n/a

**Steps to reproduce:**

1. have firefox
2. open any link for stackblitz v2 beta

**Expected behavior:**

it works

**Screenshots:**

![image](https://user-images.githubusercontent.com/199018/120924539-37512b00-c6a2-11eb-9d8f-b7445043c93b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox
 - Version: 90.0b3 (64-bit)

Is there a particular feature that is missing? a JS API?
if so, imo, it'd be good to check for those specific things and list those on the incompatible messaging, rather than just flat "this browser is not supported". With feature checks/lists, there is something actionable to do... there is not currently

**Comment by SamVerschueren** [comment]
Yes, we should communicate this a bit better. 

Firefox does work technically, but it requires some extra security headers that we are not looking into. So Firefox does not have technical limitations. Unlike Safari, which misses SharedArrayBuffer for instance.

It is coming for sure, but we're working hard on different fronts so can't give you an exact estimate. From Chrome 92 or 93, not sure anymore, Chrome will require these headers as well, so we have to fix this for sure before that.

**Comment by NullVoxPopuli** [comment]
that's fantastic news!!!!

**Comment by SamVerschueren** [comment]
Fixed a typo 😂 ! We are looking into it. At first I stated that we aren't 🤦 .

**Comment by NullVoxPopuli** [comment]
I somehow didn't see it 🙃

**Comment by jrvidal** [comment]
Closing in favor of #437
