### ISSUE TITLE
Cannot export variables (in CLI)

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/webcontainer-core#163]
**Describe the bug:**
I was trying to create a bug report for a different thing, but ran in to this:

in any blitz, running this code in the terminal causes an error:
```bash
 export NODE_OPTIONS='--trace-warnings --unhandled-rejections=strict'
 ```
 ```
e.Assigns is not iterable
 ```

**Link to the blitz that caused the error:** n/a

**Steps to reproduce:**

1.  go to any blitz
2. paste the above export code in the terminal
3. observe error

**Expected behavior:**
no error, environment variable assigned

**Screenshots:**
![image](https://user-images.githubusercontent.com/199018/120924925-1ee21000-c6a4-11eb-8065-954cb80d57f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77 (Official Build) (64-bit)

**Comment by SamVerschueren** [comment]
Hi @NullVoxPopuli! Yes, this is not yet supported by the shell yet. We mainly focussed on supporting most of the things npm scripts use at first, and then add more syntax over time.

It's always good to know what people try, or how people use these tools as it will help us improve based on the feedback 🙏 !

**Comment by jrvidal** [comment]
I'm going to close this one in favor of https://github.com/stackblitz/webcontainer-core/issues/97
