### ISSUE TITLE
Bind must be called on a function

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/webcontainer-core#165]
**Describe the bug:**
When trying to boot up an Ember app, I get this error: `Bind must be called on a function`
The stack in the log points at some minified file, so I'm not sure how to best see what is going on -- but on a real machine, the same code runs just fine.

```
 - stack: TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at Object.eval [as bind] (/home/projects/gqaimkxpv.github/node_modules/esm/esm.js:3:33198)
    at eval (/home/projects/gqaimkxpv.github/node_modules/esm/esm.js:3:37215)
    at Object.eval (/home/projects/gqaimkxpv.github/node_modules/esm/esm.js:3:37490)
    at r (/home/projects/gqaimkxpv.github/node_modules/esm/esm.js:3:613)
    at eval (/home/projects/gqaimkxpv.github/node_modules/esm/esm.js:3:805)
    at eval (/home/projects/gqaimkxpv.github/node_modules/esm/esm.js:3:815)
    at D (/home/projects/gqaimkxpv.github/node_modules/esm/esm.js:1:821)
    at Object.eval (/home/projects/gqaimkxpv.github/node_modules/esm/esm.js:1:1479)
    at Object.function (https://gqaimkxpv--github.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:11:15318)
```

**Link to the blitz that caused the error:** https://stackblitz.com/github/ember-cli/ember-new-output/tree/stable?file=package.json

**Steps to reproduce:**
1. Go to the linked blitz
2. run `npm start`
3. See error

**Expected behavior:**
dev server boots (there may be other errors between now and then, as the previous error was https://github.com/stackblitz/webcontainer-core/issues/53, so we'll see what we run in to next!)

**Desktop (please complete the following information):**

   - OS: Windows 10
   - Browser: Chrome
   - Version: 91.0.4472.77 (Official Build) (64-bit)

**Comment by SamVerschueren** [comment]
I'm not entirely sure, but it looks like something ESM related. We don't support ESM yet unfortunately. But the Node.je ecosystem is adapting so it's definitely on the radar as one of the big first things we have to tackle.

The `node-esm` package, which looks like it's the one that's failing, doesn't work either. I haven't looked into why that is though so can't give you feedback yet on that front.

**Comment by NullVoxPopuli** [comment]
any updates? I'm very excited to try this out, but node ESM is pretty much a requirement for all my work <3

**Comment by d3lm** [comment]
Hey there! Thanks for reporting this issue. It's indeed related to some internals on our end. I am actually working on ESM built-in support and part of this effort, I have fixed some issues that break the esm package you're using. So I'd say stay tuned and hang in for a bit longer. ESM is cooking 🧑‍🍳

**Comment by NullVoxPopuli** [comment]
Here is a minimal reproduction https://stackblitz.com/edit/node-fofpws?file=index.js

**Comment by NullVoxPopuli** [comment]
Sorry to bother, but any updates? This is the current known blocker for emberjs folks to use stackblitz ❤️

**Comment by SamVerschueren** [comment]
I believe you tweeted it yourself, but this works now 🎉. Let us know if you run into any issues 🙏 .

**Comment by NullVoxPopuli** [comment]
Thank youuuuuu!
