### ISSUE TITLE
BUG: `npm install @builder.io/qwik --save-prod` fails

### ISSUE THREAD

**Issue by mhevery** [stackblitz/webcontainer-core#166]
**Describe the bug:**
Trying to install `npm install @builder.io/qwik --save-prod` results in error:

```
❯ npm install @builder.io/qwik --save-prod
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ 𐄂 Failed
ERR!: Failed to resolve dependencies

error Command failed with exit code 1
```

manually adding it to `package.json` as :
```
  "dependencies": {
    "@builder.io/qwik": "0.0.6"
  },
```

also fails with:
```
❯ npm install
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ 𐄂 Failed
ERR!: 404 OK - GET https://nr.staticblitz.com/@builder.io%2fqwik - Not found

error Command failed with exit code 1
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/qwik-todo-demo?file=package.json

**Steps to reproduce:**
1. https://stackblitz.com/edit/qwik-todo-demo?file=package.json
2. `npm install` or `npm install @builder.io/qwik --save-prod`
4. Observe that the above command failed with an error.

**Expected behavior:**
Ability to install `@builder.io/qwik` package on stackblitz.

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78310879,
  "usedJSHeapSize": 71194391,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**

**Comment by SamVerschueren** [comment]
Hi @mhevery, thanks for trying out StackBlitz 🙏 !

This might be a bug in our backend. Something that triggers me is the `.` in the package name, that might be the culprit 🤔 .

I'll have a look tomorrow to see if I can find what goes wrong.

**Comment by mhevery** [comment]
Found it! The issue is that the package was published as private. Switching it to public visibility fixed the issue. The error message could have been more helpful. :-)
