### ISSUE TITLE
BUG: Stackblitz webcontairn fails silently with node in `module` mode.

### ISSUE THREAD

**Issue by mhevery** [stackblitz/webcontainer-core#167]
**Describe the bug:**
This repo demonstrates a bug with stackblitz where the node can't be switched over to 'module' format and it fails silently with no error.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-hhghtv?file=README.md

**Steps to reproduce:**
1. run: `node index.js` observe that code fails silently with no error.
2. Switche `package.json`'s `type` from `module` => `common`
3. run: `node index.js` observe that code now works as expected.

**Expected behavior:**
Either work or fail with error explaining the problem.

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72894689,
  "usedJSHeapSize": 66648753,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**

**Comment by mhevery** [comment]
After digging more into this it seems that if a promise gets rejected the node just silently exits without printing out the error.

**Comment by SamVerschueren** [comment]
This is interesting 🤔 . Thanks for the nice and detailed reproduction case 🙏 !

ESM is currently not yet supported, but at least it should throw an error which like you pointed out, seems like it's swallowed.

**Comment by SamVerschueren** [comment]
We just announced support for ESM so this is no longer an issue 🎉 https://twitter.com/stackblitz/status/1422960937129086976?s=21
