### ISSUE TITLE
BUG: ipaddr: the address has neither IPv6 nor IPv4 format

### ISSUE THREAD

**Issue by chenxsan** [stackblitz/webcontainer-core#170]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-6mxtcw?file=package.json

**Steps to reproduce:**

1. Go to terminal
2. Run `npm start`

**Expected behavior:**
`webpack serve` to run without the error.

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**
<img width="698" alt="CleanShot 2021-06-07 at 21 50 25@2x" src="https://user-images.githubusercontent.com/1091472/121028430-679be500-c7da-11eb-8b15-29e8d81e0c7a.png">

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.41

**Additional context:**

**Comment by KwintenP** [comment]
Seems like a bug indeed! thanks for reporting 🙏

**Comment by chenxsan** [comment]
@KwintenP Was it fixed?

**Comment by KwintenP** [comment]
Whoops, seems like I accidentally closed it. My bad!

**Comment by d3lm** [comment]
I am on it.

**Comment by d3lm** [comment]
This is fixed.
