### ISSUE TITLE
BUG: Failed to load '/home/projects/node-kg7djp/webpack.config.js' config

### ISSUE THREAD

**Issue by doriansmiley** [stackblitz/webcontainer-core#171]
**Describe the bug:**

Webpack fails to load webpack.cofnfig when running `npm run build`

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-kg7djp?file=package.json

**Steps to reproduce:**

1. Go to https://stackblitz.com/edit/node-kg7djp?file=package.json
2. Enter the Terminal
3. run `npm run build`
4. See the error

**Expected behavior:**
Webpack builds without error

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96706724,
  "usedJSHeapSize": 79149412,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**

Running `eslint src/** --quiet && tsc` succeeds. Running `webpack` will manifest the issue.

**Comment by SamVerschueren** [comment]
It does seem to work on my end. Can you try it again maybe?

![image](https://user-images.githubusercontent.com/1913805/121154475-4b825d00-c847-11eb-98e4-018133e3e27d.png)

**Comment by doriansmiley** [comment]
Appears to be working now. That is strange. Closing.
