### ISSUE TITLE
BUG: JWT-generating jsonwebtoken

### ISSUE THREAD

**Issue by mefaba** [stackblitz/webcontainer-core#175]
**Describe the bug:**
Installed jsonwebtoken library. Tried to create a token with jwt.sign() function. It throws an error starts with "TypeError: Cannot read property 'toLowerCase' of undefined"

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-hfhmh5?file=index.js

**Steps to reproduce:**

1. Go to 'Link of blitz'
2. Open Terminal
3. Run following command in terminal -> node index.js

**Expected behavior:**
Server should run normally.

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88641875,
  "usedJSHeapSize": 85220759,
  "jsHeapSizeLimit": 2172649472
}

**Additional context:**

**Comment by SamVerschueren** [comment]
It's probably something crypto related. Crypto is currently not fully implemented but we're working to get this fixed. Can't give you any ETA though.

// cc @jrvidal

**Comment by jrvidal** [comment]
@mefaba I think this is fixed now! :tada:
