### ISSUE TITLE
BUG: After reporting an error, repair the normal code graphql tools  Unable to restore

### ISSUE THREAD

**Issue by ZouHuaYi** [stackblitz/webcontainer-core#177]
**Describe the bug:**
when After reporting an error, repair the normal code graphql tools  Unable to restore

**Link to the blitz that caused the error**
https://stackblitz.com/edit/graphql-69aa8y

** first step
error in my code 
graphql tools export 
```
{
  hello,
  world
}
{
  "message": "Unexpected token < in JSON at position 0",
  "stack": "SyntaxError: Unexpected token < in JSON at position 0"
}
```
after I repair error code 
```
{
  hello,
  world
}
{
  "message": "Unexpected token < in JSON at position 0",
  "stack": "SyntaxError: Unexpected token < in JSON at position 0"
}
```
Here I want to read the correct answer, graphql tools status can not restart

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.85
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116376328,
  "usedJSHeapSize": 111970084,
  "jsHeapSizeLimit": 4294705152
}

**Comment by SamVerschueren** [comment]
I don't really understand what you're running into. If I copy-paste the query

```
{
  hello,
  world
}
```

And execute it, it works. Could you clarify what goes wrong or setup the project so that I hit the error when I run this query.

**Comment by ZouHuaYi** [comment]
When the error was reported, I corrected the error, but the running state was not refreshed. graphql env not run.
