### ISSUE TITLE
BUG: Possible issue with nodemon

### ISSUE THREAD

**Issue by sportelance** [stackblitz/webcontainer-core#179]
**Describe the bug:**

I spun up a very basic node site then started adding my preferred modules to check for issues. Everything was working as intended until I changed my 'npm start' script to call nodemon instead of node. The next time I started the app, nodemon was called on my server file and compiled, printing out the message that the server was live in port 3000. However, the in-site view showed an error screen, saying nothing was live on 3000 and offering me the options to go back to my project or reload. 

I used '^c' to end the process, but now when I try to spin up my server again with Nodemon or Node I get the " code: 'EADDRINUSE'" error message. I know that you hit this error when using nodemon on vsCode when you fail to close out of a process in a different terminal. 

Let me know if I could provide any more info!

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-tlwmwb?file=views%2Findex.html

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89172396,
  "usedJSHeapSize": 82197724,
  "jsHeapSizeLimit": 2172649472
}

**Additional context:**

**Comment by SamVerschueren** [comment]
I investigated this issue, and the problem is that you installed `path` as a dependency. This means that `nodemon` will use that dependency instead of the native `node:path` package and I assume it's not compatible. Removing that dependency and restarting everything does the trick.

![image](https://user-images.githubusercontent.com/1913805/122066665-3c754f00-cdf3-11eb-83f7-c9b42ad1591c.png)

**Comment by sportelance** [comment]
Hi Sam,

Path and Nodemon are compatible packages in Node.JS. This file runs as-is
on my local. And again, it runs in stack blitz, but the processes that are
getting started aren’t being terminated.
