### ISSUE TITLE
BUG: Vue 3 project starter crashes with Vue 2

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#184]
**Describe the bug:**

Using the Vue 3 project starter, switching to Vue 2 causes the following error when importing a `.vue` file:

```
Error: vue_1.createVNode is not a function
```

I understand that it's a Vue 3 starter, I was hoping to make it a Vue 2 starter with single file component support (there currently is no such starter available).

**Link to the blitz that caused the error:**
https://stackblitz.com/edit/vue-qd2aze?file=src%2Fmain.js

**Steps to reproduce:**

1. Open [Vue 3 starter](https://stackblitz.com/fork/vue).
2. In the `Dependencies` panel on the left, add `vue@^2.6.14`.
3. In `src/main.js`, edit the code to bootstrap a Vue 2 app:

```js
import Vue from 'vue'
import App from './App.vue'

new Vue({
  el: '#app',
  render: h => h(App)
})
```

4. See error in browser preview or console:

```
Error in /~/src/App.vue (8:40)
vue_1.createVNode is not a function
```

**Expected behavior:**
The `App` component should render in the browser preview window.

**Screenshots:**

<img width="590" alt="Screen Shot 2021-06-10 at 5 06 05 PM" src="https://user-images.githubusercontent.com/26580/121603335-3572c900-ca0e-11eb-8229-d118453fffa2.png">

**Desktop:**
 - OS: macOS BigSur 11.2.3
 - Browser: Chrome
 - Version 91.0.4472.77 (Official Build) (x86_64)

**Smartphone:**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context:**
*none*

**Comment by SamVerschueren** [comment]
Hi @tony19! I don't think that could work. As we do some Vue 3 magic under the hood. Someone else seems to have created a `vue2-starter` https://stackblitz.com/edit/vue2-starter. Guess this should get you going.

**Comment by tony19** [comment]
@SamVerschueren Thanks for the response. I've seen that starter, but it has no SFC support like the Vue 3 Starter does. I have my own Vue CLI + Vue 2 starter for it [here](https://stackblitz.com/edit/vue2-vue-cli), but that's a Node project. I prefer the quick startup of the official Vue 3 Starter.

Where can I find the source for the Vue 3 Starter? I see most of the templates in GitHub, but not for the Vue 3 Starter. I would  be happy to help create a template for Vue 2 (or a starter that allows Vue version selection).

**Comment by Slluxx** [comment]
I have exactly the same "issue". I've tried several days to convert a Vue 3 to a Vue 2 template because some modules i use will not or have not updated yet. Please create or let tony or/and me help to create a starter & make clear that special templates have things under the hood going, so people like me and Tony don't waste time trying to convert them.

**Comment by EricSimons** [comment]
@Slluxx @tony19 absolutely- if someone could make a Vue2 starter template by forking https://stackblitz.com/fork/node that would be awesome. Feel free to post it back here and I'll make sure it gets included in our upcoming 'community templates' section.

**Comment by tony19** [comment]
@EricSimons I've actually created a Node based Vue 2 starter [here](https://stackblitz.com/edit/vue2-vue-cli), but I'm actually looking for something like the Vue 3 starter (not Node based), so that there is no startup delay (from the npm installation, etc). How do I create that kind of starter project?

**Comment by datainvestor** [comment]
Any progress on this issue? Wanted to try stackblitz but seems it does not support Vue 2 out of the box. Cant find any typical template that you get when doing "vue create app" or similar. Most of them are not single component based templates or have some extra things like typescript.
