### ISSUE TITLE
BUG: [turbo] `npm install` command also installs `install` package

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#189]
**Describe the bug:**

Running `npm install -S packageName` also installs `install@^0.13.0` as a dependency. Similarly, `npm i -S packageName` also installs the `i` package.

**Link to the blitz that caused the error:**
https://stackblitz.com/edit/turbo-install-bug?file=package.json

**Steps to reproduce:**

1. Open [Node.js starter](https://stackblitz.com/fork/node).
2. In Terminal, enter `npm install -S vue`.
3. See `install` listed under `dependencies` in `package.json` (in addition to the intended `vue` package).
4. See the `install` package installed in `node_modules/install`.

**Expected behavior:**

Only the package specified on the command line (i.e., after the `install` or `i` command) is installed.

**Screenshots:**

<img width="260" alt="Screen Shot 2021-06-12 at 3 27 00 PM" src="https://user-images.githubusercontent.com/26580/121788410-b22eb000-cb92-11eb-9c84-d7a259759eb8.png">

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Browser Chrome
 - Version 91

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser n/a
 - Version n/a

**Additional context:**
*none*

**Comment by SamVerschueren** [comment]
Hi @tony19 ! We are aware of this bug and it will be fixed soon. Thanks for reporting 🙏 !

**Comment by SamVerschueren** [comment]
This is fixed now.
