### ISSUE TITLE
WebContainer is in BETA \ check this out and solve

### ISSUE THREAD

**Issue by anujkrp** [stackblitz/webcontainer-core#192]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-ufbrii?file=pages%2Findex.js

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Firefox 
Full version  = 89.0
Major version = 89
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.3; rv:89.0) Gecko/20100101 Firefox/89.0
performance.memory = undefined
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
