### ISSUE TITLE
importing project with a master branch different than "master" instantly breaks

### ISSUE THREAD

**Issue by blainekasten** [stackblitz/webcontainer-core#195]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-ppzt4b

**Steps to reproduce:**
1. Try to import an existing github nextjs project that does not have a master branch

**Expected behavior:**
1. It should respect the repositories master branch and use that as the default.

**Version of webcontainer:**
Hash: b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 90.0.4430.93
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111794609,
  "usedJSHeapSize": 104256781,
  "jsHeapSizeLimit": 4294705152
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Hi @blainekasten, thanks for reporting! This seems like a bug. Can you share the repository you tried to import and the URL you used to import it? Just to make sure I reproduce it the exact same way as you did?

**Comment by SamVerschueren** [comment]
I just tried importing a repository with a `main` branch and it seemed to work.

**Comment by tony19** [comment]
@SamVerschueren Here's a demo StackBlitz: https://stackblitz.com/edit/stackblitz-bug-cant-import-main-branch?file=index.js

The key is to use the `Connect repository` button, then `import an existing repository`. There seems to be no issue when importing the repo via appending the GitHub URL to `stackblitz.com`: https://stackblitz.com/github/tony19-sandbox/stackblitz-bug-main-branch-name

**Comment by deadcoder0904** [comment]
> `appending the GitHub URL to stackblitz.com`

I tried this for https://stackblitz.com/github/deadcoder0904/mdx-bundler-next-themes-error/ & it kept reloading forever & now shows me this:

![image](https://user-images.githubusercontent.com/16436270/124224152-bc552600-db22-11eb-9293-ed3ecce8df69.png)

**Comment by thetaPC** [comment]
This is also happening to me with a private repo. I even tried to do a workaround my making a new branch called master. This hack allows for the files to be imported but when I try to switch to any branch then it just loads forever.

**Comment by Nemikolh** [comment]
I think this issue was solved. (Trying to import a repository with a non-master branch is working).

@tony19 do you still experience this issue?

**Comment by tony19** [comment]
@Nemikolh No, this is no longer reproducible for me.
