### ISSUE TITLE
Tweetsak

### ISSUE THREAD

**Issue by tweetsakchutanee** [stackblitz/webcontainer-core#197]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-trbyoi

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.101
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 9; SMART TAB 4G e-Biz PRO) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60300000,
  "usedJSHeapSize": 60300000,
  "jsHeapSizeLimit": 793000000
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
