### ISSUE TITLE
Renaming a file deletes the contents of the file

### ISSUE THREAD

**Issue by kallenkortuem** [stackblitz/webcontainer-core#198]
**Describe the bug:**

Renaming a file deletes the contents of the file

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-pztdkr?file=pages%2Fapi%2Fasdf.js

**Steps to reproduce:**

1. Go to https://stackblitz.com/fork/nextjs
1. Open file `pages/api/hello.js`
1. Rename the file `hello.js` to `test.js`
1. Notice that all the contents of the file are removed.

**Expected behavior:**

All file contents should remain unchanged

**Version of webcontainer:**
Hash: b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.101
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109708008,
  "usedJSHeapSize": 102472732,
  "jsHeapSizeLimit": 4294705152
}
```

**Additional context:**

**Comment by d3lm** [comment]
Hey there! Thanks for reporting this issue 🙏 . It's indeed a bug.

**Comment by SamVerschueren** [comment]
Thanks for reporting this @kallenkortuem ! We are aware of this issue and it's the same as #199. We're working on it.

**Comment by SamVerschueren** [comment]
We believe this issue should be resolved now after we deployed an update. Feel free to open a new issue if you experience this behaviour again!
