### ISSUE TITLE
File doesn't updates even after saving

### ISSUE THREAD

**Issue by amaan-ahmad** [stackblitz/webcontainer-core#199]
**Describe the bug:**
I was working on a new node project, It was working all good initially but after few changes, the files weren't updating. 
I came to know about the problem when my current code changes didn't reflect when I ran `cat index.js` to see the contents on index file. It still printed the old code.

**Steps to reproduce:**

1. Create any node project
2. write some code and execute it.
3. now make more changes and save. then try to `cat <file_name>`
4. check if the changes you made, actually did update in the filesystem or not.

**Expected behavior:**
the changes should update in Files instantly.

**Screenshots:**
![image](https://user-images.githubusercontent.com/27350808/122556498-397b9800-d059-11eb-9414-30f1d0e424a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 91

**Additional context:**
It may or may not be reproduced in a single try, need to do it multiple times to actually notice the problem.

**Comment by SamVerschueren** [comment]
Hi @amaan-ahmad ! We are aware of an issue with the synchronisation between WebContainer and the editor and we almost have a fix ready. Not sure when it will land though. Sorry for the incovenience.

**Comment by SamVerschueren** [comment]
We just released a fix and we believe this issue should be resolved. Feel free to open a new one if you see this behaviour again. We try to address this kind of bugs asap.
