### ISSUE TITLE
BUG: Extraneous positional argument when running `npm init foo`

### ISSUE THREAD

**Issue by Rich-Harris** [stackblitz/webcontainer-core#2]
Congrats on the launch! Very exciting.

**Describe the bug**
`npm init foo` downloads the `create-foo` package and runs the `"bin"` specified in its package.json. It's commonly used to scaffold new projects.

It looks like `turbo init` behaves similarly to `npm init`, but `turbo init foo` (and by extension `npm init foo`) fails:

![image](https://user-images.githubusercontent.com/1162160/119020106-d91b0d00-b96b-11eb-83c7-ed1c85858c10.png)

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-qcu4bd

**To Reproduce**
1. Go to https://stackblitz.com/edit/node-qcu4bd
2. Click into the terminal
3. Type `npm init foo` or `turbo init foo`

**Expected behavior**
The same behaviour as `npm init foo`

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.93
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
performance.memory = {
  totalJSHeapSize: 55442824,
  usedJSHeapSize: 51747536,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by d3lm** [comment]
Yep, this is indeed a bug. Thanks for reporting.

**Comment by SamVerschueren** [comment]
@Rich-Harris A small update from our side. There's an internal PR for it so it shouldn't take too long before it lands. Keep you posted 🙏 .

**Comment by SamVerschueren** [comment]
@Rich-Harris So we fixed the `npm init` thing and it seems to work. BUT, some `create-*` packages uses `git` under the hood, like `npm init svelte-app`. We are working on our `git` internals and expose a `git` CLI as well, but right now that causes other issues.

![image](https://user-images.githubusercontent.com/1913805/120434648-06f54e00-c37d-11eb-86f1-2640c0ea7a1b.png)

**Comment by d3lm** [comment]
I am closing this because it's the error remaining is not related to extraneous positional arguments as this particular issue has been fixed.
