### ISSUE TITLE
Chutani

### ISSUE THREAD

**Issue by tweetsakchutanee** [stackblitz/webcontainer-core#201]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-yjkne4

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 7dcae10d1d70d34e54e08009f68977bb89962b8f

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64000000,
  "usedJSHeapSize": 53500000,
  "jsHeapSizeLimit": 793000000
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
