### ISSUE TITLE
npm start is not firing automatically after npm install

### ISSUE THREAD

**Issue by fedir-indutnyi** [stackblitz/webcontainer-core#202]
**Describe the bug:**
I have an app:
https://stackblitz.com/edit/sfrontend-devbox-20210623
It successfuly installs dependensies, but then:
npm start is not happening automatically,
and if i am running it manually, webpage on the right side of container - is not opening.

Open:
https://stackblitz.com/edit/sfrontend-devbox-20210623
Wait until npm intall finishes
First bug - nothing happens.
Executing npm start
Console says successfully compiled, but page is not appearing

**Link to the blitz that caused the error**
https://stackblitz.com/edit/sfrontend-devbox-20210623?file=src%2Ftest.ts

**Steps to reproduce:**

https://stackblitz.com/edit/sfrontend-devbox-20210623
Wait until npm intall finishes
First bug - nothing happens.
Executing npm start
Console says successfully compiled, but page is not appearing

**Expected behavior:**

**Version of webcontainer:**
Hash: 82080794cabf87e5630cd7deb9f8d7067a2f5758

**Screenshots:**
-

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.106
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 158418581,
  "usedJSHeapSize": 148617229,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by fedir-indutnyi** [comment]
Update: I see in half of cases when opening in new tabs - issue is dissapearing, and sometimes appearing again.

**Comment by SamVerschueren** [comment]
Hi @fedir-indutnyi. If you want to start your project automatically, you can add a `.stackblitzrc` file with the following contents:

```json
{
	"startCommand": "npm start"
}
```

The reason you might experience this behaviour is if you have StackBlitz open in another tab or window which is running an application (or that specific application) on the same port. That doesn't work. We have an internal ticket to address this and notify users if that's the case.

That could also explain why you sometimes see it and sometimes you don't. So if you test it again, make sure you aren't running the same application in another tab/window.

**Comment by fedir-indutnyi** [comment]
Thank you very much @SamVerschueren  that helps. You can mark issue resolved.
Have a great day.
