### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sanjanaraut03** [stackblitz/webcontainer-core#203]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-dj4nj7?file=1.c

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 82080794cabf87e5630cd7deb9f8d7067a2f5758

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.106
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60823588,
  "usedJSHeapSize": 55608880,
  "jsHeapSizeLimit": 1016070144
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
