### ISSUE TITLE
StackBlitz v2 Beta currently works in Chrome and Chromium-based browsers. We’re hoping to add support for more browsers as they implement the necessary Web Platform features.

### ISSUE THREAD

**Issue by Rishabh-creator601** [stackblitz/webcontainer-core#204]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/http-server-9fmg5w

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 82080794cabf87e5630cd7deb9f8d7067a2f5758

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.101
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 5.0.1; 8080) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53500000,
  "usedJSHeapSize": 50400000,
  "jsHeapSizeLimit": 269000000
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
If it's because of the error you're seeing in Android Chrome. Yes this is correct, we're working on fixing it but currently it's only for desktop Chrome.

We will have it fixed soon.
