### ISSUE TITLE
indexb.html

### ISSUE THREAD

**Issue by olivier021** [stackblitz/webcontainer-core#206]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/github/vercel/next.js/tree/canary/examples/api-routes?file=README.md

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 82080794cabf87e5630cd7deb9f8d7067a2f5758

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65828268,
  "usedJSHeapSize": 62247724,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
