### ISSUE TITLE
Images are not loaded from local assets folder.

### ISSUE THREAD

**Issue by fedir-indutnyi** [stackblitz/webcontainer-core#208]
**Describe the bug:**
Application compiles and starts successfully, hovewer images are not loaded from local assets folder

**Link to the blitz that caused the error**
https://stackblitz.com/edit/sfrontend-devbox-20210623-bgharj?file=.stackblitzrc

**Steps to reproduce:**

1. Open worspace https://stackblitz.com/edit/sfrontend-devbox-20210623-bgharj 
2. Wait until application starts;
3. See on webpage of application that images are broken, especially src/assets/images/default.jpg

**Expected behavior:**
Application runs without issues on localhost and in Docker, images are working on those systems, but not in StackBlitz

**Version of webcontainer:**
Hash: 82080794cabf87e5630cd7deb9f8d7067a2f5758

**Screenshots:**
![image](https://user-images.githubusercontent.com/31389180/123512290-ede37280-d686-11eb-9197-8c17e31c263f.png)

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 102626546,
  "usedJSHeapSize": 97754646,
  "jsHeapSizeLimit": 4294705152
}
```

**Additional context:**

**Comment by jrvidal** [comment]
@fedir-indutnyi Can you provide an updated link?

**Comment by jrvidal** [comment]
@davidstevenrojas Thanks for the comment. I would suggest you open a different issue, to make sure we're really talking about the same problem.

**Comment by davidstevenrojas** [comment]
@jrvidal, thanks for looking into this, here the new ticket: https://github.com/stackblitz/webcontainer-core/issues/465

**Comment by kc0tlh** [comment]
@fedir-indutnyi thanks for submitting this report! This is the same underlying issue as #677 so I will close this report, and we can follow #677 for updates. Cheers!
