### ISSUE TITLE
Editing client side files doesn't change anything in the page viewer

### ISSUE THREAD

**Issue by quinton-ashley** [stackblitz/webcontainer-core#209]
**Describe the bug:**
When I make changes to the app.js file and save it, nothing changes when I run it again using `>node app.js` I have to commit the changes and reload for it to work.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/quintos?file=app.js

**Version of webcontainer:**
Hash: 82080794cabf87e5630cd7deb9f8d7067a2f5758

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 269214879,
  "usedJSHeapSize": 250379151,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by Pyrolistical** [comment]
node doesn't auto restart on file change. you need a watcher to do that, like pm2

**Comment by quinton-ashley** [comment]
No, when I manually restart "node app.js" after doing file changes it
doesn't work. Runs just like before the changes.

**Comment by Pyrolistical** [comment]
ya sounds like a bug. but i can't repo it.

do you have github repository hooked up?

**Comment by quinton-ashley** [comment]
yeah I do, quintos on my github

**Comment by quinton-ashley** [comment]
@Pyrolistical I would love to use this app with my students but this bug makes stackblitz unusable for this use case. Please let me know when this is fixed!

**Comment by Pyrolistical** [comment]
Sorry, but i'm not a contributors. I'm just trying to be helpful

**Comment by quinton-ashley** [comment]
@apai4 @EricSimons @fvsch please fix this!

**Comment by fvsch** [comment]
It seems to work in my tests. Maybe I’m missing some step to reproduce.

You do have to save the modified file, if your changes are unsaved they won't be seen by the Node process (same as when working with Node on your computer).

<img width="539" alt="Screenshot 2021-07-07 at 09 45 26" src="https://user-images.githubusercontent.com/243601/124720114-1598cd00-df08-11eb-90cb-eefe6b027897.png">

**Comment by quinton-ashley** [comment]
yeah the server itself can update but then when I try to refresh the webpage it does not work
<img width="1440" alt="Screen Shot 2021-08-06 at 20 57 27" src="https://user-images.githubusercontent.com/20031683/128588255-d4554337-5ef8-4904-845b-37369b29a100.png">

**Comment by quinton-ashley** [comment]
sorry maybe should've put this in a new issue

**Comment by quinton-ashley** [comment]
okay now if I restart the server the webpage will refresh but it will not reflect changes

**Comment by quinton-ashley** [comment]
<img width="173" alt="Screen Shot 2021-08-06 at 21 58 07" src="https://user-images.githubusercontent.com/20031683/128588491-01818f77-540f-4805-87f7-06a1f8f719d8.png">
<img width="541" alt="Screen Shot 2021-08-06 at 21 58 02" src="https://user-images.githubusercontent.com/20031683/128588495-34433a03-0317-4c29-b8b1-a56666ef23bb.png">

I tried typing it as fast as I could while the project was loading and didn't quite get it in time but this proves that it will not respond to changes in the webpage.

**Comment by quinton-ashley** [comment]
For my use case I think the Javascript template will be better actually

**Comment by jrvidal** [comment]
@quinton-ashley I can't reproduce it either:

https://user-images.githubusercontent.com/1636604/128867134-dc629605-5233-4c30-8624-4e86e81187af.mp4

**Comment by quinton-ashley** [comment]
@jrvidal When I try to do what you did in that video it doesn't work. Also I think the client side changes should be reflected just by refreshing the web container page without having to restart the server.

**Comment by quinton-ashley** [comment]
Opening the site in a guest page didn't work either. The web container should switch to work with the user's version of the project with their edits but it doesn't do that.

https://user-images.githubusercontent.com/20031683/128914291-08e75bec-5599-4d5e-972d-04bba4a4b581.mov

**Comment by quinton-ashley** [comment]
Here's what I get when I load the page then fork it using the fork button.

<img width="1440" alt="Screen Shot 2021-08-10 at 11 37 25" src="https://user-images.githubusercontent.com/20031683/128916193-7c75c7b6-18ab-4427-a179-2ae98fa9e548.png">

If I refresh the entire page after forking it, then it will load changes!

<img width="1440" alt="Screen Shot 2021-08-10 at 11 39 25" src="https://user-images.githubusercontent.com/20031683/128916451-53f133e6-fe3a-4c46-8cf0-b948420078fd.png">

But as soon as I make another change it disconnects again.

<img width="1440" alt="Screen Shot 2021-08-10 at 11 39 50" src="https://user-images.githubusercontent.com/20031683/128916521-f50c90e0-ae9e-47c0-a167-5f0238ac9175.png">

**Comment by quinton-ashley** [comment]
@apai4 @EricSimons @fvsch Please help getting issues fixed so I can have all my students use Stackblitz! 😄

**Comment by quinton-ashley** [comment]
Thought I might add that I'm using the Apple M1 chip Macbook Air 2021, maybe some of these issues are platform specific?

**Comment by quinton-ashley** [comment]
I think I will have to use repl.it instead unless these issues are fixed. It works in repl.it:

https://replit.com/@quintonashley/quintos-template-test0

**Comment by quinton-ashley** [comment]
Thank you!

**Comment by quinton-ashley** [comment]
I found out this is more of a problem with the browser caching these files. If the files still have the same name it doesn't matter that I make changes cause it just loads from the cache. I think I'll be able to fix this by using the ol' trick of adding an argument question mark to the url followed by the Date.now() time in ms. I will update y'all with my progress later.

**Comment by quinton-ashley** [comment]
I made a fix for this, check it out!
https://stackblitz.com/edit/quintos-template

Could I get a job at StackBlitz? I'd really like to help you guys solve problems like these. I like the StackBlitz platform a lot, there's a lot of potential here.

**Comment by quinton-ashley** [comment]
I made some changes and thought I had fixed it but it only works sometimes:
https://stackblitz.com/edit/quintos-template

I'd like to work on StackBlitz and solve problems like this! I'm going to apply for a job with you guys so please look out for my application. :)

**Comment by jrvidal** [comment]
@quinton-ashley We recently fixed an issue where forking a blitz using WebContainer would leave make it unusable. After this change, forking will always hard-reload the document so the issue you were experiencing should not occur.

Thanks for reporting! Feel free to open more issues if you still find anything off.
