### ISSUE TITLE
Issue File a bug

### ISSUE THREAD

**Issue by jvinhit** [stackblitz/webcontainer-core#211]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-fc8skp

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 82080794cabf87e5630cd7deb9f8d7067a2f5758

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 89.0.4389.90
Major version = 89
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109958512,
  "usedJSHeapSize": 97891072,
  "jsHeapSizeLimit": 4294705152
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
