### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by 15971372942** [stackblitz/webcontainer-core#212]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/github/webpack/webpack.js.org/tree/master/examples/getting-started?terminal=

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: ed9672a3e8d5b719017191dac2dba042f373a0d7

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 90.0.4430.72
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 41027401,
  "usedJSHeapSize": 21056637,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by d3lm** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
