### ISSUE TITLE
PNCK DEV APP

### ISSUE THREAD

**Issue by lottostock** [stackblitz/webcontainer-core#213]
**Describe the bug:**
สวัสดี ครับผม

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-ymc5qp?file=index.js

**Steps to reproduce:**

**Expected behavior:**
OK รู้เรื่อง

**Version of webcontainer:**
Hash: ed9672a3e8d5b719017191dac2dba042f373a0d7

**Screenshots:**
![Captdddure](https://user-images.githubusercontent.com/85630215/123665273-563a7b80-d862-11eb-98a6-f94b50b77f30.PNG)

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88921030,
  "usedJSHeapSize": 80152418,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by d3lm** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
