### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sukantajana** [stackblitz/webcontainer-core#216]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/http-server-pmgmcc?file=package-lock.json

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: ed9672a3e8d5b719017191dac2dba042f373a0d7

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61972556,
  "usedJSHeapSize": 56816376,
  "jsHeapSizeLimit": 948174848
}
```

**Additional context:**

**Comment by d3lm** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
