### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by aljasmi25** [stackblitz/webcontainer-core#217]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/github/webpack/webpack.js.org/tree/master/examples/getting-started?file=webpack.config.js&terminal=

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 93.0.4544.0
Major version = 93
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4544.0 Safari/537.36 Edg/93.0.936.0
performance.memory = {
  "totalJSHeapSize": 74566356,
  "usedJSHeapSize": 70636560,
  "jsHeapSizeLimit": 4294705152
}
```

**Additional context:**

**Comment by d3lm** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
