### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by PatelDevanshu** [stackblitz/webcontainer-core#218]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-gtyes9?file=index.html

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59617980,
  "usedJSHeapSize": 55115716,
  "jsHeapSizeLimit": 2124677120
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
