### ISSUE TITLE
Bug: WASM-based npm package works only when stepping through in debugger

### ISSUE THREAD

**Issue by rajsite** [stackblitz/webcontainer-core#22]
**Describe the bug**

Using a library that loads and runs WASM does not seem to run (a terminating log statement is not hit or error logged) unless the dev tools are open and you explicitly step through execution to the end.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-vireo-hello-world

**To Reproduce**
1. Open the blitz and run `node index.js` with devtools closed
2. Note that the output shows `Hello Node.js v14.16.0!` but does not show an ascii art mandelbrot or the output `done :D`
    
    ![image](https://user-images.githubusercontent.com/1588923/119078227-69347300-b9bb-11eb-803d-809f4c17f5d0.png)
3. Open the blitz and run `node index.js` with devtools open. Meticulously step through the code stepping into functions and stepping into async tasks (not running to a breakpoint).
4. Note that everything seems to work correctly and print the above mentioned output 🤯

    ![runsfinedevtools](https://user-images.githubusercontent.com/1588923/119078313-8ff2a980-b9bb-11eb-9f02-c4f50b39e136.PNG)

**Expected behavior**
Expect the mandelbrot ascii art and completion message to print without meticulously stepping through the code in the chrome debugger.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Win 10 20H2 (OS Build 19042.985)
 - Browser Chrome 
 - Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**
If I had to guess maybe there is an issue with async and waiting for tasks in the event queue to complete? How the heck would that even work without plugs into V8 itself or something funny like shimming zone.js into everything? **(goes to mess with the example)** I actually think this might be the issue, if I add a setInterval to keep the event queue alive it seems to print everything reliably: https://stackblitz.com/edit/node-vireo-hello-world-event-queue-keepalive

Edit: This is really freakin cool ♥

**Comment by KwintenP** [comment]
That definitely seems like a bug in our event loop being closed to soon. 

Thanks for reporting 🙏

**Comment by d3lm** [comment]
@rajsite I looked at this and I cannot seem to reproduce this on my end. I forked your project and tested it again and it works for me https://stackblitz.com/edit/node-vireo-hello-world-tqhdjy. Can you try it again?

**Comment by rajsite** [comment]
Hmm I still see the same issue, my current machine configuration is different:
macOS Big Sur 11.5.1
Chrome Version 92.0.4515.107 (Official Build) (x86_64)

Both my example and the fork show the behavior of the first screenshot (only "Hello Node" is printed and not the Mandelbrot ascii art). I tried in incognito mode. Also tried with clean profile and all extensions disabled:

```bash
open /Applications/Google\ Chrome.app --args --disable-default-apps --disable-extensions --user-data-dir=/tmp/testprofile2 --no-first-run
```

**Comment by jrvidal** [comment]
@rajsite We were able to reproduce the issue, and are currently looking into a fix.

**Comment by jrvidal** [comment]
@rajsite This now works :tada:

**Comment by rajsite** [comment]
@jrvidal I  confirmed on my machine too, ty!
