### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SHUBV92** [stackblitz/webcontainer-core#224]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/order-sheet

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 119622188,
  "usedJSHeapSize": 102809664,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by d3lm** [comment]
Can you please describe what's not working? I am afraid that without a proper description and more information we'll have to close this issue.

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
