### ISSUE TITLE
cannot create a strapi project

### ISSUE THREAD

**Issue by ryan-reach** [stackblitz/webcontainer-core#226]
**Describe the bug:**

running `yarn create strapi-app` fails with error:

```
e.Assigns is not iterable
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Command failed: ( cat /var/lib/dbus/machine-id /etc/machine-id 2> /dev/null || hostname ) | head -n 1 || :
e.Assigns is not iterable

    at checkExecSyncError (https://next-strapi-cloudinary.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:611757)
    at execSync (https://next-strapi-cloudinary.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:612961)
    at u (/home/.turbo/npx/tJh3iB/node_modules/node-machine-id/dist/index.js:1:7886)
    at module.exports (/home/.turbo/npx/tJh3iB/node_modules/strapi-generate-new/lib/index.js:44:15)
    at generateApp (/home/.turbo/npx/tJh3iB/node_modules/create-strapi-app/create-strapi-app.js:42:10)
    at initProject (/home/.turbo/npx/tJh3iB/node_modules/create-strapi-app/create-strapi-app.js:67:10)
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/next-strapi-cloudinary?file=package.json

**Steps to reproduce:**

run `yarn create strapi-app` or `npx create-strapi-app` and follow the prompts. error is thrown after selecting a template

**Expected behavior:**

creating a strapi project would work

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56909579,
  "usedJSHeapSize": 47889619,
  "jsHeapSizeLimit": 4294705152
}
```

**Additional context:**

**Comment by d3lm** [comment]
Thanks for reporting this issue. It does look like a bug indeed. Not sure what it is from the top of my head. We'll add this to our list.

**Comment by jrvidal** [comment]
@ryan-reach the underlying issue is that `create-strapi-app` is attempting to run a non-trivial shell script:

```shell
( cat /var/lib/dbus/machine-id /etc/machine-id 2> /dev/null || hostname ) | head -n 1 || :
```

that is not supported by the jsh shell. We could:

1. Add better diagnostics, so jsh reports a clean "unsupported syntax" error.
2. Extend jsh to support the needed features (subshells, pipes, redirects) for that script.

(1) is pretty simple and we might do it soon. (2) is a longer term feature that we desire, but we can't make promises about.

Hope that helps!

**Comment by d3lm** [comment]
Subshells and redirects are now supported so I am going to close this issue. There is still another issue related to permissions when using `yarn create strapi-app` and we are tracking this internally and should be fixed soon.
