### ISSUE TITLE
Webpack Mode and loader error

### ISSUE THREAD

**Issue by ETeah** [stackblitz/webcontainer-core#227]
**Describe the bug:**

There are three error - 1:  mode have not been set to dev or prod, 2: there is not loader to parse your (index.js) file,
finally, 3: when I run webpack it doesn't generate the bundle.js file --it does create the dist file however...just not the bundle.js

I found these while learning at LinkedIn and then I went to the website to see how I can do it myself, and then I went to the demo and the bug was also there.
-----My script (config for webpack is here---the file name is .webpack.config.js)
-----I was using babel as my loader option
import { path } from 'path';
export default {
  entry: './app.js',
  output: {
    path: path.resolve('public'),
    filename: 'bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        },
      },
    ],
  },
  mode: 'development',
};

**Comment by d3lm** [comment]
Can you please provide a reproducable and format your code so it becomes a bit more readable? Otherwise I am afraid we have to close this issue. Without a live example there is not much we can do. Thanks!

**Comment by SamVerschueren** [comment]
Closing this issue for now. Please create a new issue if you still experience issues and try to adhere to our format. That will allow us to better help you in the future 🙏 .
