### ISSUE TITLE
Failed. Error: EIO: failed to link packages

### ISSUE THREAD

**Issue by Splaktar** [stackblitz/webcontainer-core#228]
**Describe the bug:**
I’m trying to get the latest `@angular/material-experimental` and `@angular/cdk-experimental` to run on StackBlitz, but I’m hitting some issues.

For webcontainers, I’ve run into linking issues ([3/3] :link: Linking dependencies└ 𐄂 Failed. Error: EIO: failed to link packages). 

Then I noticed that the `package-lock.json` was out of date, so I’m been trying to regenerate that w/o luck. I removed the contents of `package-lock.json` and ran `npm i --package-lock-only`, but it’s just been hanging there for 15+ minutes. `Ctrl-C` doesn’t kill it either.

Is there some way to force regeneration of the lock file in a webcontainer?

**Link to the blitz that caused the error:**
https://stackblitz.com/edit/ng-webcontainer-material-cdk-experimental-mdc?file=package.json

This one works: https://stackblitz.com/edit/ng-webcontainer-material-experimental-mdc?file=package.json. But I can’t update it to 12.1.0 without the linking breaking.

**Steps to reproduce:**
1. Go to https://stackblitz.com/edit/ng-webcontainer-material-cdk-experimental-mdc?file=package.json
2. Update `@angular/material-experimental` to `12.1.0` from `12.1.0-next.1`
3. Save and reload

**Expected behavior:**
Linking should complete and `npm start` should be run.

**Screenshots:**
![Screen Shot 2021-07-02 at 14 21 03](https://user-images.githubusercontent.com/3506071/124314672-c259ff80-db40-11eb-9e5d-dcd014193919.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Catalina 10.15.7 (19H1217)
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 91.0.4472.114 (Official Build) (x86_64)

**Additional context:**
Related issue, but it doesn't have much useful info in it: https://github.com/stackblitz/webcontainer-core/issues/132

**Comment by d3lm** [comment]
Hey! Thanks for reporting your issue. When I click on your repro it seems works for me actually.

![image](https://user-images.githubusercontent.com/12571019/124331518-a29df800-db8f-11eb-959d-19686fb901ad.png)

I removed the lock file and ran `npm i` again. It then starts the dev server and it all works just fine. I am not sure why it didn't work for you. Maybe try it again? Where did the lock file actually come from? Is that something you uploaded or was that generated by a previous installation on StackBlitz?

**Comment by Splaktar** [comment]
It came from this fork: https://stackblitz.com/edit/ng-webcontainer-material-experimental-mdc?file=package.json.

**Comment by Splaktar** [comment]
I just tried https://stackblitz.com/edit/ng-webcontainer-material-cdk-experimental-mdc?file=package.json again on another laptop and it also failed with the same errors. When you mention "try again", I'll note that I have tried over 30 times during the course of ~4 days now, it's never once worked.

How long did it take for `npm i` to give you some output? I removed the lock file and ran `npm i` again and it did the same thing I saw before... nothing for minutes...

**Comment by d3lm** [comment]
It installs almost instantly for me. I am not sure why it doesn't work for you because I can try as often as I want but it never fails.

**Comment by Splaktar** [comment]
@d3lm and you are using Chrome 91 on macOS Catalina? What else could impact this? How can I debug or resolve this?

I cleared all site data, cache, and cookies but it didn't help.

**Comment by d3lm** [comment]
I am on Chrome 91 yes but on Big Sur. But I don't think this should matter. I honestly have no idea why it works for me but it consistently doesn't work for you. If you open your DevTools, do you see any errors besides the linking error?

**Comment by d3lm** [comment]
Maybe try this one? https://stackblitz.com/edit/ng-webcontainer-material-cdk-experimental-mdc-rpxgw3?file=package-lock.json

**Comment by Splaktar** [comment]
I tried being logged into GH and logged out, but got the same result.

I get this console output before linking:
```js
[@blitz/registry] [INFO] Successfully initialized
5 - [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See <URL> for more details.
constants.js:66 [Contextify] [WARNING] running source code in new context (anonymous) @ constants.js:66
``` 

During/after linking there is no output.

**Comment by Splaktar** [comment]
> Maybe try this one? https://stackblitz.com/edit/ng-webcontainer-material-cdk-experimental-mdc-rpxgw3?file=package-lock.json

This one works for me. Thanks!

**Comment by Splaktar** [comment]
I was even able to fork and rename it and it still works: https://stackblitz.com/edit/material-cdk-experimental-mdc?file=package.json

**Comment by d3lm** [comment]
Ok perfect! So I am closing this one. Really strange that the other one didn't work. Maybe it was locked to some older version of WebContainer and there was some incompatibility. Really strange. If you run into a similar issue, feel free to open a new issue.

**Comment by eng-dibo** [comment]
I also face the same issue when I try to install a single package `npm i @angular/cli`

**Comment by jrvidal** [comment]
@eng-dibo Would you mind opening a new issue with a repro link?
