### ISSUE TITLE
Very large WebSocket messages are unsupported

### ISSUE THREAD

**Issue by modderme123** [stackblitz/webcontainer-core#232]
**Describe the bug:**

When trying to do HMR with Rollup, I ran into an issue where certain ws messages were being dropped. It seems that all large websocket messages don't reach the client at all which means that large bundles sent via ws for hot module reloading break. Maybe this means that when messages are chunked over multiple frames they silently error?

**Link to the blitz that caused the error:**

https://stackblitz.com/edit/ws-bug

https://stackblitz.com/edit/solid-nollup

**Steps to reproduce:**

1. Go to https://stackblitz.com/edit/ws-bug
2. Observe that only first is logged in the browser console

**Expected behavior:**

I would expect this to either send the full message and not prevent messages from going through afterward or for there to be an error and documentation on how to get around it.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 91

**Additional context:**

**Comment by d3lm** [comment]
Hey there! Thanks for reporting this issue. I think this is most likely not related to the size of your bundles and might be something else, maybe the fact that it's being chunked. This could be an issue in our TCP implementation. Thanks so much for creating a very minimal reproduction. I ll make sure to look into this.

**Comment by d3lm** [comment]
Hey there 👋 Sorry for the late response. This doesn't seem to be an issue anymore and I think it's been fixed in the meantime. If I open your project I can see that all messages are logged in the console. Can you verify that it works as expected?
