### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fuckyouhoe3** [stackblitz/webcontainer-core#233]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/http-server-j1jsd2?file=.vscode%2Fsettings.json

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Safari 
Full version  = 604.1
Major version = 604
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.80 Mobile/15E148 Safari/604.1
performance.memory = undefined
```

**Additional context:**

**Comment by d3lm** [comment]
Closing this issue because it's missing the required information.
