### ISSUE TITLE
iOS can't hold down delete for too long

### ISSUE THREAD

**Issue by ChiefChippy2** [stackblitz/webcontainer-core#234]
**Describe the bug:**

Usually, if you hold down delete, it will start deleting text at a pretty fast speed, and then start to delete 1 word at once, then 1 sentence at once... etc., On stackblitz, it deletes a lot slower at the 1 word at once part ( so it only deletes 1 character every like second ).

**Link to the blitz that caused the error:**
Any

**Steps to reproduce:**

1. Go to stackblitz on ios
2. hold down delete
4. See issue after 10 seconds or so

**Expected behavior:**
faster code deletion 

**Not tested on desktop**

**Smartphone (please complete the following information):**
 - Device: iPad Air 2
 - OS: iOS 14.6
 - Browser [e.g. chrome, safari] chrome (latest) / firefox (latest)
 - Version [e.g. 22] both latest - 91.0.x and 34.2

**Additional context:** none

**Comment by SamVerschueren** [comment]
Hi @ChiefChippy2! We use the Monaco editor under the hood so this is not something we can easily fix or control. I'd suggest opening an issue in the Monaco repository itself https://github.com/microsoft/monaco-editor.
