### ISSUE TITLE
Gzip compression with servor broken

### ISSUE THREAD

**Issue by modderme123** [stackblitz/webcontainer-core#235]
**Describe the bug:**

Servor enables gzip compression by default on all .http files (source here https://github.com/lukejacksonn/servor/blob/master/servor.js#L86), and it seems that stackblitz injects a non gzip encoded header at the front that confuses the browser. The browser shows the response to the http request as: 
```
<script src="/.localservice@runtime.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js"></script>�M���0��<E�L(��!���HL0�cH��R~
5E�=-`���;�V��as�K^S�S����J��`���s���y�@Z�O;���&j$ܟ�iq��ܤ��m��o�K
���^4��^Mz��BG�vС�S�	���5t>����C�M����F�T6���-��@�����b٧�;`��tK2
```
**Link to the blitz that caused the error:**
https://stackblitz.com/edit/servor-bug

**Steps to reproduce:**

1. Go to https://stackblitz.com/edit/servor-bug
4. See `‹M½Â0„÷›‹ÉC±MöúªÊFÍT6ÞÎÔ-¹÷@´„±âùbÙ§£;ÃïtK2`

**Expected behavior:**

I would expect this to show a page with `testing 123` displayed

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 91

**Comment by modderme123** [comment]
This might be related to https://github.com/stackblitz/webcontainer-core/issues/48. However, it seems slightly different because it errors silently

**Comment by d3lm** [comment]
Yea this seems to be a big. Thanks for reporting 🙏 But it's unrelated to crypto.

**Comment by HeyGarrison** [comment]
Looks like this is solved now! Thanks for reporting! ❤️ ❤️ ❤️
