### ISSUE TITLE
bug-1

### ISSUE THREAD

**Issue by ProAke** [stackblitz/webcontainer-core#238]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/manee-apps?file=pages%2Findex.js

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61675206,
  "usedJSHeapSize": 59235558,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
