### ISSUE TITLE
Container is not booting BUG: 

### ISSUE THREAD

**Issue by mohit-sojitra** [stackblitz/webcontainer-core#24]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-bxeuqr

**To Reproduce**

**Expected behavior**

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 65061278,
  usedJSHeapSize: 58711870,
  jsHeapSizeLimit: 2172649472
}

**Additional context**

**Comment by rajsite** [comment]
The web container seems to load for me. I see a check next to Booting WebContainer and I was able to run the script in the terminal like the following screenshot shows:

![image](https://user-images.githubusercontent.com/1588923/119083809-4b204000-b9c6-11eb-9bb7-89474a8a733f.png)

Do you see different behavior?

**Comment by rajsite** [comment]
This may be worth keeping open. I agree that the screen does not seem to make it clear that everything has finished loading. The title `Booting WebContainer` makes it sound like it is still working.

**Comment by mohit-sojitra** [comment]
Yup why not

**Comment by SamVerschueren** [comment]
It's a good point. We should stop the spinner and mark it in red if that happens just to let the user know that something happened and is not waiting indefinitely 👍 .

**Comment by AMerkuri** [comment]
That screen is indeed misleading 🙂

**Comment by HeyGarrison** [comment]
We dramatically adjusted the webcontainer loading states. Thanks again for the feedback!
