### ISSUE TITLE
Running start command takes forever and does not work

### ISSUE THREAD

**Issue by lemarcgagnon** [stackblitz/webcontainer-core#240]
**Describe the bug:**

nothing happens, only get a 

Running start command spinning wheel, that's it

**Link to the blitz that caused the error**
https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-context-api?file=pages%2Fabout.js

**Steps to reproduce:**

1. Go to https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-context-api?file=pages%2Fabout.js
2. the wait forever

**Expected behavior:**
 the app would open and work

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111545244,
  "usedJSHeapSize": 108384608,
  "jsHeapSizeLimit": 4294705152
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Just a wild guess because I'm on my phone, but is it possible you already had this project open in another tab or was the port already occupied by another project in another tab? Because that's usually the issue in these scenario's. Try to run it again and make sure no other StackBlitz project is open.

**Comment by SamVerschueren** [comment]
Closing this as it seems to be working fine on my end so I do believe it was the issue I describe above that you ran into.

![image](https://user-images.githubusercontent.com/1913805/126141643-b323572d-a107-4b6c-9829-31fb9c4ef591.png)
