### ISSUE TITLE
Unable to start a Strapi project

### ISSUE THREAD

**Issue by Mcastres** [stackblitz/webcontainer-core#241]
**Describe the bug:**

Trying to run a simple Strapi application on Stackblitz. 
However the sharp module can't be found:

```
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /home/projects/node-ao8hjy/node_modules/sharp/lib/constructor.js
- /home/projects/node-ao8hjy/node_modules/sharp/lib/index.js
- /home/projects/node-ao8hjy/node_modules/strapi-plugin-upload/services/image-manipulation.js
- /home/projects/node-ao8hjy/node_modules/strapi/lib/load/load-files.js
- /home/projects/node-ao8hjy/node_modules/strapi/lib/core/load-apis.js
- /home/projects/node-ao8hjy/node_modules/strapi/lib/core/load-modules.js
- /home/projects/node-ao8hjy/node_modules/strapi/lib/Strapi.js
- /home/projects/node-ao8hjy/node_modules/strapi/lib/index.js
- /home/projects/node-ao8hjy/node_modules/strapi/lib/commands/develop.js
- /home/projects/node-ao8hjy/node_modules/strapi/bin/strapi.js

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues
```

The recommendation at the end of the message doesn't work as:

`Unknown Syntax Error: Invalid option name ("--ignore-scripts=false")`

Can you confirm that it will needs the `sharp` module [to be compiled to WebAssembly](https://github.com/lovell/sharp/issues/1476) to work? Or maybe there is a workaround 😃 

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-ao8hjy

**Steps to reproduce:**

1. Go tohttps://stackblitz.com/edit/node-ao8hjy
2. Wait for dependencies to install
3. Run `yarn develop`
4. Wait for application to build
5. See error

**Expected behavior:**

The Strapi server should start.

**Version of webcontainer:**
Hash: ded7c1cfbe6b33641b5f3c9265989f8bd71ed771

**Desktop (please complete the following information):**
```
Browser name  = Chrome
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53356034,
  "usedJSHeapSize": 51956122,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by SamVerschueren** [comment]
Hi @Mcastres! Thanks for trying out WebContainers. Yes, in order for this to work properly, Sharp should be swapped out with the WASM version instead, native binaries will not work.

Chiming in @d3lm, I believe we already looked into WASM for Sharp right? But we didn't release it yet?

**Comment by d3lm** [comment]
Yes that is correct. We have a sharp polyfill but it's not yet published.

**Comment by Mcastres** [comment]
Hey 👋  Thanks for taking the time to answer this! 
That is some good news! Do you have any public roadmap or something I can look at? I'd like to know when this will be published 😃 

Can't wait to be able to start some Strapi projects on Stackblitz 🚀
