### ISSUE TITLE
1

### ISSUE THREAD

**Issue by lucianojunnior17** [stackblitz/webcontainer-core#243]
**Describe the bug:**

**Link to the blitz that caused the error**
https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-styled-components

**Steps to reproduce:**

**Expected behavior:**

**Version of webcontainer:**
Hash: ded7c1cfbe6b33641b5f3c9265989f8bd71ed771

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.67
performance.memory = {
  "totalJSHeapSize": 85470351,
  "usedJSHeapSize": 66542795,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
