### ISSUE TITLE
Framework support for Quasar Framework

### ISSUE THREAD

**Issue by smolinari** [stackblitz/webcontainer-core#244]
**Describe the solution you'd like:**
Hello. I'm from the Quasar Framework team (https://quasar.dev/) and have some questions and excited to hear the hopefully positive answers.
- Would we be able to get a Quasar Framework template set up? Is there a process for this?
- Currently we have a Codesandbox template set up, but it is only an application preset similar to what you have with the Vue template available. However, we'd like to offer a working CLI and believe a webcontainer can allow for that, similar to the NestJS template. Is this correct thinking?
I could actually install the Quasar CLI locally with the Node template, however it fails when trying to download the application starter kit from Github. 

**Provide a link to a github repo containing an example of the framework:**
https://github.com/quasarframework

Would be great, if this could work and it would be a huge step up from codesandbox for us. 

Thanks!

Scott

**Comment by SamVerschueren** [comment]
Hi @smolinari! So I tried setting it up in StackBlitz, you can see it here https://stackblitz.com/edit/node-ivwlw1. It fails when trying to run `quasar dev` because of some IP address issue, so we have to investigate what causes this. It's probably on our side. It looks like `quasar build` does seem to work though.

**Comment by smolinari** [comment]
@SamVerschueren - Awesome you are working on it. Not sure how far we can take Quasar with Stackblitz, but it sure would be fun to find out. 😁 

Scott

**Comment by SamVerschueren** [comment]
@smolinari I fixed something internally and now `quasar dev` seems to work 🎉  https://stackblitz.com/edit/node-ivwlw1?file=README.md.

**Comment by smolinari** [comment]
@SamVerschueren - appreciate the effort. Thanks so much. Seems to work. The only thing is, when adding a mode, then I get a good number of warning toasts and a popup asking to move to the pro version. I guess that is normal? 

Try: `quasar m add pwa`. 

Lastly, would it be possible to get Quasar up as a selection on the templates/ new project page too? That was the intention of this issue actually. 😀 

Scott

**Comment by SamVerschueren** [comment]
>  The only thing is, when adding a mode, then I get a good number of warning toasts and a popup asking to move to the pro version. I guess that is normal?

I believe this is due to the fact it's writing binary files to the file system like images and what not. Currently they are only for pro users but we are aware that WebContainer actually needs this for basic users as well. So this means that we're looking into how we can mitigate this to allow users to upload a limited amount of binary files (for instance 10MB).

> Lastly, would it be possible to get Quasar up as a selection on the templates/ new project page too? That was the intention of this issue actually.

I know that we're currently looking into improving this and even allowing contributors to add projects to the templates. For now they are pretty limited and we have to do it manually.

Chiming in @fvsch @sulco. Does any of you have more information on this topic?

**Comment by fvsch** [comment]
> Lastly, would it be possible to get Quasar up as a selection on the templates/ new project page too?

The selection of templates shown in the "Create a new project" section will probably change, but we can't guarantee that we'll include any specific framework right now.

We’ll probably prioritize the default templates depending on user demand and how well the framework is supported by WebContainer. But we also want to improve discoverability for all frameworks. So what we do want to make possible soon is along those lines:

- Searching "quasar" (or any other framework, library or term) on StackBlitz should show a list of matching templates.
- We might create a dedicated pages for popular frameworks or libraries that showcase examples on StackBlitz, so it could make sense to have one for Quasar.

**Comment by smolinari** [comment]
@fvsch - Sounds good. I'm now sort of confused though about what a "template" is. Can you or someone explain what that is? I was thinking the selections on the "Create a new project" page are templates. Are they not?

Scott

**Comment by fvsch** [comment]
@smolinari They are. In StackBlitz, any public project from any user can be forked, so technically any public project is a "template". :)

When we say "templates" or sometimes "starters", we usually refer those projects which we have manually selected and added to the stackblitz.com homepage (both the public home page or the logged-in Dashboard). We won't be able to add entries for all compatible frameworks and libraries directly on the home page, so we're exploring other ways to surface good "templates" or "starter projects" to users.

**Comment by smolinari** [comment]
Ok. Gotcha. Thanks for the explanation. 

Scott

**Comment by SamVerschueren** [comment]
@smolinari Feel free to create a PR to add Quasar to the list of [supported frameworks](https://github.com/stackblitz/webcontainer-core/blob/main/Supported_frameworks.md).

**Comment by smolinari** [comment]
@SamVerschueren - Willdo. Any chance of also getting a "fork Quasar" URI like the other frameworks? aka. `https://stackblitz.com/fork/quasar` 😊 

Scott

**Comment by SamVerschueren** [comment]
@smolinari is my project ok for you?

@sulco could you rename that project slug to `quasar`?

**Comment by smolinari** [comment]
Actually, I can fork and rename the slug. Didn't think of that. :) We'll get a new user added and fork and rename. Then I'll make the PR. 

Thanks!

Scott

**Comment by HeyGarrison** [comment]
❤️ ❤️ ❤️  closing this for now for book keeping purposes :D

**Comment by angelhdzmultimedia** [comment]
Good to see this question posted!

Any update as of 2023?

Would be awesome to have a Quasar with Vite project.

Tried to get Quasar working on Nuxt but got many issues, and the creator of Quasar posted few hours ago, about not having the time to make Quasar working on Nuxt 3, as Quasar has its own implementation of SSR.

So I'm gonna start learning SSR in Quasar and it would be awesome to have a project on the best online IDE so far, Stackblitz!!! 😁🤩🔥
