### ISSUE TITLE
.scss and .css files don't appear when opening local project from files on your computer

### ISSUE THREAD

**Issue by ShoulM** [stackblitz/webcontainer-core#246]
**Describe the bug:**
When loading a local project all .scss .css files were discarded and didn't copy into the editor.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-jfx5dz

**Steps to reproduce:**
1. Go to local projects
2. Select a project that has .scss files in it 
3. notice that the .scss files don't appear in the editor and are not found when running a build

**Expected behavior:**
expected the .scss files to be copied into the editor

**Version of webcontainer:**
Hash: e6adaf772b18819f7b4ab8325b73d63276acda8f

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.67
performance.memory = {
  "totalJSHeapSize": 96810825,
  "usedJSHeapSize": 89296205,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by dariuszbasiak** [comment]
Hi, I just opened my local Angular project and all `.scss` files did not upload at all. Please can you take a look at it?

**Comment by HeyGarrison** [comment]
@ShoulM I can't seem to access your project anymore? Could you send another link? Thanks ❤️

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
