### ISSUE TITLE
Bug: Web Container fails to load with certain project structure

### ISSUE THREAD

**Issue by rajsite** [stackblitz/webcontainer-core#25]
**Describe the bug**
A WebContainer gets stuck on the `Booting WebContainer` step and devtools shows the error `Cannot set property 'NodeFS.gcomp' of undefined` where NodeFS.gcomp is the name of both a folder and a file within a folder for my project:
![image](https://user-images.githubusercontent.com/1588923/119081550-cd5a3580-b9c1-11eb-9552-ee2ef2023d02.png)

Error screenshot:
![image](https://user-images.githubusercontent.com/1588923/119081803-69843c80-b9c2-11eb-97f4-e36bf70c6bc0.png)

Full error text:
<details>
<summary>click to show full console log</summary>
<pre>
[Violation] Forced reflow while executing JavaScript took 42ms
client-c18b3511dd425ab7c939b.js:2 Uncaught (in promise) TypeError: Cannot set property 'NodeFS.gcomp' of undefined
    at client-c18b3511dd425ab7c939b.js:2
    at Array.reduce (<anonymous>)
    at client-c18b3511dd425ab7c939b.js:2
    at Array.forEach (<anonymous>)
    at C (client-c18b3511dd425ab7c939b.js:2)
    at client-c18b3511dd425ab7c939b.js:2
    at u (client-c18b3511dd425ab7c939b.js:2)
    at Generator._invoke (client-c18b3511dd425ab7c939b.js:2)
    at Generator.E.forEach.e.<computed> [as next] (client-c18b3511dd425ab7c939b.js:2)
    at client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
C @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
u @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
E.forEach.e.<computed> @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
nrWrapper @ node-webvi-express?file=Builds:8
r @ node-webvi-express?file=Builds:8
_ @ client-c18b3511dd425ab7c939b.js:2
x @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
Da @ client-c18b3511dd425ab7c939b.js:2
As @ client-c18b3511dd425ab7c939b.js:2
t.unstable_runWithPriority @ client-c18b3511dd425ab7c939b.js:2
vo @ client-c18b3511dd425ab7c939b.js:2
Ds @ client-c18b3511dd425ab7c939b.js:2
_s @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
t.unstable_runWithPriority @ client-c18b3511dd425ab7c939b.js:2
vo @ client-c18b3511dd425ab7c939b.js:2
Eo @ client-c18b3511dd425ab7c939b.js:2
wo @ client-c18b3511dd425ab7c939b.js:2
Es @ client-c18b3511dd425ab7c939b.js:2
notify @ client-c18b3511dd425ab7c939b.js:2
t.notifyNestedSubs @ client-c18b3511dd425ab7c939b.js:2
t.handleChangeWrapper @ client-c18b3511dd425ab7c939b.js:2
y @ client-c18b3511dd425ab7c939b.js:2
dispatch @ VM655:3856
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
dispatch @ VM655:14608
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
nrWrapper @ node-webvi-express?file=Builds:8
Promise.then (async)
(anonymous) @ node-webvi-express?file=Builds:8
i @ client-c18b3511dd425ab7c939b.js:2
Jo @ client-c18b3511dd425ab7c939b.js:2
da @ client-c18b3511dd425ab7c939b.js:2
Ns @ client-c18b3511dd425ab7c939b.js:2
js @ client-c18b3511dd425ab7c939b.js:2
Os @ client-c18b3511dd425ab7c939b.js:2
ys @ client-c18b3511dd425ab7c939b.js:2
Zs @ client-c18b3511dd425ab7c939b.js:2
Js @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
xs @ client-c18b3511dd425ab7c939b.js:2
ac @ client-c18b3511dd425ab7c939b.js:2
render @ client-c18b3511dd425ab7c939b.js:2
m @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
f @ client-c18b3511dd425ab7c939b.js:2
g @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
nrWrapper @ node-webvi-express?file=Builds:8
Show 8 more frames
registry.worker.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6 [@blitz/registry] [INFO] Successfully initialized
blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:8 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
_0x4c8301 @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:8
initFileSystem @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
init @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
_0x293e01 @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
_0x293e01 @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
node-webvi-express?file=Builds:8 [Violation] 'setTimeout' handler took 149ms
[Violation] Forced reflow while executing JavaScript took 31ms
blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
_0x293e01 @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
client-c18b3511dd425ab7c939b.js:2 Uncaught (in promise) TypeError: Cannot read property 'updateOptions' of undefined
    at client-c18b3511dd425ab7c939b.js:2
    at u (client-c18b3511dd425ab7c939b.js:2)
    at Generator._invoke (client-c18b3511dd425ab7c939b.js:2)
    at Generator.E.forEach.e.<computed> [as next] (client-c18b3511dd425ab7c939b.js:2)
    at a (client-c18b3511dd425ab7c939b.js:2)
    at nrWrapper (node-webvi-express?file=Builds:8)
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
u @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
E.forEach.e.<computed> @ client-c18b3511dd425ab7c939b.js:2
a @ client-c18b3511dd425ab7c939b.js:2
nrWrapper @ node-webvi-express?file=Builds:8
Promise.then (async)
(anonymous) @ node-webvi-express?file=Builds:8
c @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
nrWrapper @ node-webvi-express?file=Builds:8
r @ node-webvi-express?file=Builds:8
_t @ client-c18b3511dd425ab7c939b.js:2
value @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
nrWrapper @ node-webvi-express?file=Builds:8
setTimeout (async)
nrWrapper @ node-webvi-express?file=Builds:8
value @ client-c18b3511dd425ab7c939b.js:2
As @ client-c18b3511dd425ab7c939b.js:2
t.unstable_runWithPriority @ client-c18b3511dd425ab7c939b.js:2
vo @ client-c18b3511dd425ab7c939b.js:2
Ds @ client-c18b3511dd425ab7c939b.js:2
_s @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
t.unstable_runWithPriority @ client-c18b3511dd425ab7c939b.js:2
vo @ client-c18b3511dd425ab7c939b.js:2
Eo @ client-c18b3511dd425ab7c939b.js:2
wo @ client-c18b3511dd425ab7c939b.js:2
Es @ client-c18b3511dd425ab7c939b.js:2
notify @ client-c18b3511dd425ab7c939b.js:2
t.notifyNestedSubs @ client-c18b3511dd425ab7c939b.js:2
t.handleChangeWrapper @ client-c18b3511dd425ab7c939b.js:2
y @ client-c18b3511dd425ab7c939b.js:2
dispatch @ VM655:3856
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
dispatch @ VM655:14608
z @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
u @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
E.forEach.e.<computed> @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
nrWrapper @ node-webvi-express?file=Builds:8
r @ node-webvi-express?file=Builds:8
fa @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ client-c18b3511dd425ab7c939b.js:2
r._invokeFactory @ loader.js:7
r.complete @ loader.js:7
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._resolve @ loader.js:8
r.defineModule @ loader.js:7
o @ loader.js:7
r @ editor.main.js:6
r._invokeFactory @ loader.js:7
r.complete @ loader.js:7
r._onModuleComplete @ loader.js:8
r._onModuleComplete @ loader.js:8
r._resolve @ loader.js:8
r.defineModule @ loader.js:7
_ @ loader.js:8
window.define @ client-c18b3511dd425ab7c939b.js:2
(anonymous) @ editor.main.nls.js:6
Show 44 more frames
iframe.7286dbe8d47d3…048fb59b05f2.html:1 Uncaught (in promise) {message: "ENOENT: no such file or directory", code: "ENOENT", errno: -2, path: undefined, syscall: undefined, …}
Promise.then (async)
apply @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
run @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
async function (async)
run @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
registerListenersAndRunOnInstance @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
run @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
_0x293e01 @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11
blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
</pre>
</details>

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-webvi-express

**To Reproduce**
1. Open the blitz
2. Note: the blitz gets stuck on Booting WebContainer
   
    ![image](https://user-images.githubusercontent.com/1588923/119081997-c97ae300-b9c2-11eb-8e20-a66fdd234f4b.png)

**Expected behavior**
Blitz continues to load and I eventually can run the `npm start` command

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Win 10 20H2 (OS Build 19042.985)
 - Browser Chrome 
 - Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**
My guess is that something is getting tripped up by the file output of our tool which places files inside folders of the same name, ie a folder named NodeFS.gcomp (yes the folder name has a period) containing a file named NodeFS.gcomp.

If I manually remove folders with that naming convention the WebContainer is able to fully load: https://stackblitz.com/edit/node-webvi-express-names-clean

**Comment by KwintenP** [comment]
Aha, yeah that's definitely a bug. 

Thanks for reporting 🙏
