### ISSUE TITLE
ReferenceError: node is not defined

### ISSUE THREAD

**Issue by anujkhaire** [stackblitz/webcontainer-core#251]
**Describe the bug:**

ReferenceError: node is not defined

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-njdvbz?file=index.js

**Steps to reproduce:**

1. run in terminal: $ node index.js

**Expected behavior:**

1. should fetch json from pokeAPI
**Version of webcontainer:**
Hash: 822a3541dddeeb70796ee74aa67c96011d201179

**Screenshots:**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90186207,
  "usedJSHeapSize": 72819679,
  "jsHeapSizeLimit": 2172649472
}
```

**Additional context:**

**Comment by SamVerschueren** [comment]
It appears to be an issue with your `require` statement`.

![image](https://user-images.githubusercontent.com/1913805/126128261-7cc7efc0-5484-4fe0-8428-41e13641381d.png)

I changed it and now it seems to work https://stackblitz.com/edit/node-jrxoec 🙏 .

**Comment by anujkhaire** [comment]
😂️ totally missed it...should've checked before raising the issue

**Comment by anujkhaire** [comment]
> It appears to be an issue with your `require` statement`.
> 
> ![image](https://user-images.githubusercontent.com/1913805/126128261-7cc7efc0-5484-4fe0-8428-41e13641381d.png)
> 
> I changed it and now it seems to work https://stackblitz.com/edit/node-jrxoec  .

😂️ totally missed it...should've checked before raising the issue
