### ISSUE TITLE
the port does not open.

### ISSUE THREAD

**Issue by Lucifer25x** [stackblitz/webcontainer-core#253]
### Describe the bug

the port sometimes works and sometimes does not.

Example code (express.js):
```javascript
app.listen(port, () => {
  console.log('Server running.');
});
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-6oh3cs?file=server.js

### Steps to reproduce

1. Create Node.js app.
2. Install express.js
3. Create port
4. This sometimes work and sometimes does not.

### Expected behavior

the port sometimes works and sometimes does not.

Example code (express.js):
```javascript
app.listen(port, () => {
  console.log('Server running.');
});
```

### Platform

```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.203
performance.memory = {
  "totalJSHeapSize": 71592387,
  "usedJSHeapSize": 68698567,
  "jsHeapSizeLimit": 2172649472
}
Hash = 84452ea99b8c6a79e19cae2129beaf85d5da007c
```

**Comment by SamVerschueren** [comment]
Hi @Lucifer25x!

Sorry it took a while to get back to you. I noticed the URL you shared doesn't exist anymore.

A reason that this could happen is if you already run a project with the same port in your browser. So the port is basically occupied, just as on local. We have an issue tracked to improve the error on this one as quite some users run into this once in a while.

Let's close this issue for now but don't hesitate to let us know if you run into it again.
