### ISSUE TITLE
File System may be truncating the index.tsx in my NextJS project

### ISSUE THREAD

**Issue by sgoguen** [stackblitz/webcontainer-core#255]
### Describe the bug

When trying to compile a NextJS project (TypeScript), the compiler is failing because the most recently changed file is being truncated.  

NOTE:  The file is visible in *whole* in the editor, but if you run "cat pages/index.tsx" from the command-line, it displays a truncated file.  This truncated file reflects the TypeScript error.

In the editor, the file looks like this:

```typescript
import Link from 'next/link';
import { useState } from 'react';
import Layout from '../components/Layout';

const IndexPage = () => (
  <Layout title="Home | Next.js + TypeScript Example">
    <h1>Hello Next.js!!! 👋</h1>
    <p>This is a lot of fun</p>
    <p>
      <Link href="/about">
        <a>About</a>
      </Link>
    </p>
    <ToggleButton />
  </Layout>
);

function ToggleButton() {

  const [isOn, setOn] = useState(false);
  return (
    <button onClick={() => {
      setOn(!isOn);
    }}>
      {isOn ? 'Turn off' : 'Turn on'}
    </button>
  );
}

export default IndexPage;
```

When `cat pages/index.ts` is run, the output is truncated like so:

```typescript
import Link from 'next/link';
import { useState } from 'react';
import Layout from '../components/Layout';

const IndexPage = () => (
  <Layout title="Home | Next.js + TypeScript Example">
    <h1>Hello Next.js!!! 👋</h1>
    <p>This is a lot of fun</p>
    <p>
      <Link href="/about">
        <a>About</a>
      </Link>
    </p>
    <ToggleButton />
  </Layout>
);

export default IndexPage;

function ToggleButton() {
  const [isOn, setOn] = useState(false);
  return (
    <button
      onClick={() => {
        setOn(!isOn);
      }}
    >
      {isOn ? 'Turn off' : 'Turn on'}
    </b
```

How I produced the bug:

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-sf5ns9-puble1?file=pages%2Findex.tsx

### Steps to reproduce

1. I forked a simple NextJS example (https://github.com/vercel/next.js/tree/canary/examples/with-typescript)
2. Saved it to my Github repo
3. Clone to my local machine and made a simple change.
4. Pushed it change to Github
5. Reloaded Stackblitz project (https://stackblitz.com/edit/github-sf5ns9-puble1?file=pages%2Findex.tsx)
6. Compiler error happened

### Expected behavior

File System shouldn't truncate file

### Platform

```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80060760,
  "usedJSHeapSize": 74447776,
  "jsHeapSizeLimit": 4294705152
}
Hash = 84452ea99b8c6a79e19cae2129beaf85d5da007c
```

**Comment by jrvidal** [comment]
@sgoguen Hey, sorry about taking forever :sweat: Are you still affected by this issue? I can't reproduce it on my end.

**Comment by sgoguen** [comment]
@jrvidal - This issue appears to have been resolved.  Thank you!
