### ISSUE TITLE
Creating a server issue

### ISSUE THREAD

**Issue by 18jad** [stackblitz/webcontainer-core#256]
### Describe the bug

i am creating a server on a local server with port 3000 with createServer function and listening but i can't access to it, when i click on port 3000 in the port in use tab it's taking me to this webpage "https://node-ggjdv3--3000.local.webcontainer.io/" but it's not loading, it's infinitely loading  

-code : 

`
const http = require('http');

const server = http.createServer((req, res) => {
  if(req.url === "/") {
    res.write('Hello World')
    res.end();
  }
});

server.listen(3000);

console.log('Listening on port 3000...')`

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-ggjdv3

### Steps to reproduce

Creating local server with port 3000 
Run it in terminal with node .
Clicking on port in use tab and clicking 3000 port 
Takes me to a webpage with infinite loading

### Expected behavior

Run the local host webpage on stackblitz server and excute the code on screen 

### Screenshots

![Capture](https://user-images.githubusercontent.com/74220144/126492315-93f9b810-9718-409f-a439-c03fe784ac00.PNG)

### Platform

```
Browser name  = Chrome 
Full version  = 91.0.4472.164
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109853684,
  "usedJSHeapSize": 100126164,
  "jsHeapSizeLimit": 1634467840
}
Hash = 84452ea99b8c6a79e19cae2129beaf85d5da007c
```

**Comment by sulco** [comment]
Hey @DizerX , are you still experiencing this issue?

When I initially checked it right after you've posted it here, it looks like you didn't have a server response logic defined, i.e. it was only `const server = http.createServer()`.

In that case the page will not load. So at minimum you need to make sure you're _ending_ the response, e.g.:
```javascript
const server = http.createServer((req, res) => res.end());
```

I've noticed that your project already has a similar code at the moment of my responding – and it actually does run correctly on my machine right now – so I'm assuming you might've found a solution in the meantime (?)

If you're still experiencing this bug, try reloading the page. Make sure you have no other tab with this same project running at the same time, as it used to sometimes cause problems in the past.

Let me know if it's works now, otherwise we'll keep investigating!

**Comment by DizerX** [comment]
> Hey @DizerX , are you still experiencing this issue?
> 
> When I initially checked it right after you've posted it here, it looks like you didn't have a server response logic defined, i.e. it was only `const server = http.createServer()`.
> 
> In that case the page will not load. So at minimum you need to make sure you're _ending_ the response, e.g.:
> 
> ```js
> const server = http.createServer((req, res) => res.end());
> ```
> 
> I've noticed that your project already has a similar code at the moment of my responding – and it actually does run correctly on my machine right now – so I'm assuming you might've found a solution in the meantime (?)
> 
> If you're still experiencing this bug, try reloading the page. Make sure you have no other tab with this same project running at the same time, as it used to sometimes cause problems in the past.
> 
> Let me know if it's works now, otherwise we'll keep investigating!

i do have an ending and my code is same as yours check the 3rd line... i don't know why i can't access the port when i click on port 3000 console is logging new connection in console section but the web isn't loading the page

**Comment by SamVerschueren** [comment]
@DizerX I noticed that the StackBlitz app is not running in one of your tabs. Is it running in another browser?

The server only runs within the same browser, so you can't use another browser to connect to your server for instance. Not sure if this is the case here though, but when testing, make sure you run StackBlitz in one tab, start the server, and open the webpage in another tab in the same browser (or to be sure, in the same browser instance).

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
