### ISSUE TITLE
Failure to open the browser

### ISSUE THREAD

**Issue by hippee-lee** [stackblitz/webcontainer-core#258]
### Describe the bug

When I set up a new project it works as expected the first few times. Then, it stops opening the browser and there is a message in yhte console

```[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)```

### Link to the blitz that caused the error

https://stackblitz.com/edit/cds-workshop

### Steps to reproduce

1. Open th estackblitz in Chrome (latest)
2. wait for install and start
3. Wait for browser to open

### Expected behavior

Browser always opens after the web container start, packages are installed and the app is served. 

### Platform

```
Browser name  = Chrome 
Full version  = 91.0.4472.164
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 70525407,
  "usedJSHeapSize": 66967471,
  "jsHeapSizeLimit": 4294705152
}
Hash = 84452ea99b8c6a79e19cae2129beaf85d5da007c
```

**Comment by SamVerschueren** [comment]
@hippee-lee Thanks for reporting 🙏 ! What happens if you refresh? Does it still show the error message for you? I noticed some inconsistenties as well so it's definitely a bug. For me it shows the error message, but it looks like it still works. Do you experience the same or is it entirely broken for you?

**Comment by SamVerschueren** [comment]
@hippee-lee We noticed you removed the project that was linked in the issue. Would you be able to re-upload or re-create it?

**Comment by hippee-lee** [comment]
Sorry I was trying to re-use the url for a workshop forgot that I had submitted the project with the issue. 

I tried to recreate it today but the ones I was getting the issue on seem to load ok now. 

I did have an issue happen where the web container never got past installing dependencies even though the cli shows that it did. But that might be a separate issue.

**Comment by hippee-lee** [comment]
I'll close and re-open if I can get a reproduction.
