### ISSUE TITLE
Terminal Problem

### ISSUE THREAD

**Issue by dakshverma8899** [stackblitz/webcontainer-core#259]
### Describe the bug

Sometime Terminal stops working . It dosent follow your command . So please fix it . 

Thank You .

For Team Stackblitz

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-lnfn59?file=chatter%2Fsrc%2FApp.js

### Steps to reproduce

Fix the terminal issue 

### Expected behavior

It works Like the real terminal . It will be good for all 

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.107
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 120156639,
  "usedJSHeapSize": 97395607,
  "jsHeapSizeLimit": 2114191360
}
Hash = 84452ea99b8c6a79e19cae2129beaf85d5da007c
```

**Comment by SamVerschueren** [comment]
@dakshverma8899 Thanks for reporting 🙏 . When does it happen for you? Does it happen often and in multiple projects? Do you have a screen capture if the issue happening? I personally never ran into this issue yet, so hard to reproduce. The more info we have, the better we can investigate. If it happens, is an error being logged to the Chrome DevTools?

**Comment by dakshverma8899** [comment]
Its problem from My Side But sometimes in compiling of react app doesnt work so i reported but try to fix it please
