### ISSUE TITLE
Bug: npm run script is not able to run files correctly

### ISSUE THREAD

**Issue by rajsite** [stackblitz/webcontainer-core#26]
**Describe the bug**
Running npm scripts that use paths with certain characters seems to fail.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-npm-run-script

**To Reproduce**
1. Open the blitz and run `npm start`
2. Note: The command results in an error
3. Run the command printed by `npm start` manually in the console by copy and pasting
4. Note: The command when run from the terminal directly succeeds

**Expected behavior**
Using `npm start` is able to run the script correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1588923/119085042-8885cd00-b9c8-11eb-8953-258eec243640.png)

**Desktop (please complete the following information):**
 - OS: Win 10 20H2 (OS Build 19042.985)
 - Browser Chrome 
 - Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by SamVerschueren** [comment]
Thanks for reporting 🙏 ! This seems like a bug.

**Comment by HeyGarrison** [comment]
Thanks again for reporting! We shipped a fix for this. 💪
