### ISSUE TITLE
npm cache verify does not work

### ISSUE THREAD

**Issue by jeanmachuca** [stackblitz/webcontainer-core#260]
### Describe the bug

The command npm cache verify is returning a non-zero exit code with this message:

Unknown Syntax Error: Command not found; did you mean one of:
 0. turbo cache clean [--cwd,--prefix #0] [-s,--silent] [--quiet] [-V,--verbose] [--loglevel #0]
  1. turbo cache invalidate [--cwd,--prefix #0] [-s,--silent] [--quiet] [-V,--verbose] [--loglevel #0]

There should be compatibility using the standard command npm cache verify to clean the cache of npm. Suggesting to use the turbo command is not a solution for compatibility as it is another completely different command. An alternative could be to mask the turbo command when npm cache is being called but  this should be done by the platform behind the curtain. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-lv1cgf?file=package.json

### Steps to reproduce

Executes the command 

```
npm cache verify
```

### Expected behavior

npm should check the cache in a location and return the common result done by this command on any other platform

Cache verified and compressed (... cache location ):
Content verified: ... (... bytes)
Index entries: ...
Finished in ...s

### Screenshots

<img width="2275" alt="Screenshot 2021-07-23 at 20 55 54" src="https://user-images.githubusercontent.com/7239462/126852937-a2479c2e-7a8e-48dc-84e0-81bfc49f4290.png">

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.107
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55742875,
  "usedJSHeapSize": 53436283,
  "jsHeapSizeLimit": 4294705152
}
Hash = d86858d537c0a310ebafd72a06454769861ab23a
```

### Additional context

Several tools like QCObjects CLI need to execute the command npm cache verify to clean up the npm cache and and keep it safe. Using another alternative like turbo cache is not an option as the use of npm vs an non-standard alternative cannot be changed by settings.

To enable these tools, you should include the npm cache verify command in the allowed command list of Stackblitz and integrate the turbo solution behind the curtain for compatibility purposes.

Official docs about npm cache verify 
https://docs.npmjs.com/cli/v7/commands/npm-cache

**Comment by jrvidal** [comment]
> Several tools like QCObjects CLI need to execute the command npm cache verify to clean up the npm cache and and keep it safe

Can you elaborate exactly on what the use case for this is? Depending on your answer we could have a no-op `cache` command or maybe consider interacting with the turbo cache.

**Comment by jrvidal** [comment]
FWIW, we're working on native `npm`, which would automatically support this. You can track its progress in https://github.com/stackblitz/webcontainer-core/issues/1070.

I'll close this for now, thanks!
