### ISSUE TITLE
Live reload broken

### ISSUE THREAD

**Issue by mfbx9da4** [stackblitz/webcontainer-core#264]
### Describe the bug

Live reload broken. Requires full page refresh to update.

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-7zdn9z?file=pages%2Findex.js

### Steps to reproduce

Try changing some markup.

### Expected behavior

Expected to change some markup

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.107
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86048733,
  "usedJSHeapSize": 81553993,
  "jsHeapSizeLimit": 4294705152
}
Hash = 548843700a830a9170c7b4f676310f668ec52ffc
```

**Comment by jrvidal** [comment]
@mfbx9da4 I'm having trouble reproducing. Do you get any errors in the console?


https://user-images.githubusercontent.com/1636604/127221697-ac5481a4-cc21-4869-94fd-bd336a5d2b88.mp4

**Comment by mfbx9da4** [comment]
Thanks for the prompt response will check when I get home

**Comment by mfbx9da4** [comment]
![image](https://user-images.githubusercontent.com/1690659/127229787-ea74d7a2-842c-4863-9309-17c2645cea7a.png)

**Comment by mfbx9da4** [comment]
Nuking all site data fixed it for me

**Comment by mfbx9da4** [comment]
After cancelling the active server with ctrl+c and restarting the server with `npm run dev`. The issue is back 

```
Uncaught (in promise) Error: EEXIST: file already exists
    at Function.fromJSON (blitz.548843700a830a9170c7b4f676310f668ec52ffc.js:11)
    at Function.create (blitz.548843700a830a9170c7b4f676310f668ec52ffc.js:11)
    at _0x2e94ab (blitz.548843700a830a9170c7b4f676310f668ec52ffc.js:11)
    at _0x122fa6 (blitz.548843700a830a9170c7b4f676310f668ec52ffc.js:11)
    at _0xc5d5f3._maybeCacheAdditiveChange (blitz.548843700a830a9170c7b4f676310f668ec52ffc.js:11)
    at _0xc5d5f3.createFolder (blitz.548843700a830a9170c7b4f676310f668ec52ffc.js:11)
    at MessagePort._0x46e158 (blitz.548843700a830a9170c7b4f676310f668ec52ffc.js:8)
    ```

**Comment by jrvidal** [comment]
@mfbx9da4 Can you still observe this issue?

**Comment by kc0tlh** [comment]
I'm going to close this for now for inactivity and inability to reproduce. Feel free to re-open if this is still a recurring issue!
