### ISSUE TITLE
BUG: `npx @vue/cli test:unit` does not run unit tests

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#267]
### Describe the bug

Using `npx @vue/cli test:unit` results in `json5` help-output and does not actually run the intended binary. The output is:

```
~/projects/yqnipzqya.github
❯ npx @vue/cli test:unit
Usage: json5 -c path/to/file.json5 ...
Compiles JSON5 files into sibling JSON files with the same basenames.

~/projects/yqnipzqya.github
❯
```

### Link to the blitz that caused the error

https://stackblitz.com/github/moaxcp/vue-astro?file=tests%2Funit%2FApp.spec.js

### Steps to reproduce

1. Go to https://stackblitz.com/github/moaxcp/vue-astro?file=tests%2Funit%2FApp.spec.js
2. Run `npx @vue/clil test:unit`
3. Observe the output

### Expected behavior

The command should run `@vue/cli`

### Platform

```
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 115112428,
  "usedJSHeapSize": 112017828,
  "jsHeapSizeLimit": 4294705152
}
Hash = 548843700a830a9170c7b4f676310f668ec52ffc
```

**Comment by jrvidal** [comment]
@tony19 It's been quite a while :sweat_smile: I can't reproduce on my end, I get `Unknown command test:unit` instead. Seems like `@vue/cli` has changed in the meantime?

Anyway, are you still affected by this issue?

**Comment by tony19** [comment]
I also cannot reproduce it. Although running `npm run test:unit` results in `Error: spawn find ENOENT`, which is a duplicate of #266.
