### ISSUE TITLE
Automatically start Docusuaurus devserver

### ISSUE THREAD

**Issue by EricSimons** [stackblitz/webcontainer-core#268]
### Describe the bug

When opening a docusaurus site webcontainer doesn't automatically run `npm run start`

### Link to the blitz that caused the error

https://stackblitz.com/github/vercel/next.js/tree/canary/examples/api-routes

### Steps to reproduce

Open https://stackblitz.com/github/facebook/docusaurus/tree/master/examples/classic

### Expected behavior

Start command should run

### Platform

```
Browser name  = Chrome 
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66105397,
  "usedJSHeapSize": 56907061,
  "jsHeapSizeLimit": 4294705152
}
Hash = 548843700a830a9170c7b4f676310f668ec52ffc
```

**Comment by sulco** [comment]
Should be fixed now 🙌
