### ISSUE TITLE
Feature: Autorun the start script if included in package.json

### ISSUE THREAD

**Issue by rajsite** [stackblitz/webcontainer-core#27]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I open a WebContainer and I have to manually start it to see the behavior.

**Describe the solution you'd like**
As a WebContainer author I'd like the container to start running automatically by including a script named [`"start"` in my package.json](https://docs.npmjs.com/cli/v7/commands/npm-start).

**Describe alternatives you've considered**
Can't think of any workaround to have a script auto start.

**Additional context**
N/a

**Comment by SamVerschueren** [comment]
You can totally do that! But it's not yet documented... 

Create a `.stackblitzrc` in the root of your project. Then you have two options you can set. First one is `installDependencies` (which is `true` by default if `package.json` exists). The other one is `startCommand` which you can set to `npm start`.

**Comment by rajsite** [comment]
That's awesome, I'll try it out! Thanks!
