### ISSUE TITLE
Calling 'exit' in terminal makes it stuck

### ISSUE THREAD

**Issue by freehuntx** [stackblitz/webcontainer-core#272]
### Describe the bug

When i run the 'exit' command in the terminal, it will stop any further input.

### Link to the blitz that caused the error

https://stackblitz.com/edit/bit-data-view

### Steps to reproduce

1. Open the terminal
2. Type 'exit' and hit enter
3. Any further input is not working

### Expected behavior

The terminal will close itself

### Screenshots

![](https://i.imgur.com/rhOEBw2.png)

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.107
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 221115850,
  "usedJSHeapSize": 188712278,
  "jsHeapSizeLimit": 4294705152
}
Hash = 548843700a830a9170c7b4f676310f668ec52ffc
```

**Comment by jrvidal** [comment]
@freehuntx This should be fixed by now, thanks for the report!
