### ISSUE TITLE
URL parsing error

### ISSUE THREAD

**Issue by modderme123** [stackblitz/webcontainer-core#273]
### Describe the bug

When running a vite project (https://stackblitz.com/edit/node-bpzuhi) I ran into an `Invalid URL` error. Digging a little deeper, it looks like stackblitz doesn't support urls with relative:/// as the base even though node does.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-bpzuhi

### Steps to reproduce

1. open any webcontainer
2. run `node`
3. `new URL("/hi/ho.js", "relative:///")`

alternatively

1. open https://stackblitz.com/edit/node-bpzuhi
2. `npx vite`

### Expected behavior

I would expect this to return a URL object like it does in the latest version of node
```js
URL {
  href: 'relative:///hi/ho.js',
  origin: 'null',
  protocol: 'relative:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/hi/ho.js',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

### Platform

- OS: macOS
- Browser: Chrome
- Version: 92.0

**Comment by d3lm** [comment]
Hey there! Yes this is a bug. I am actually on it 👍 I'll keep you posted when this gets fixed.

**Comment by d3lm** [comment]
This is now fixed.
