### ISSUE TITLE
No way if running the terminal on mobile

### ISSUE THREAD

**Issue by khru** [stackblitz/webcontainer-core#274]
### Describe the bug

When I've created a node project, I could not use the terminal, because I could not accesos it

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-q3k4tg?file=index.js

### Steps to reproduce

1. Create node project on mobile
2. There os no way to access the terminal

### Expected behavior

Find the terminal

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.115
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; Redmi Note 9S) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53500000,
  "usedJSHeapSize": 44700000,
  "jsHeapSizeLimit": 1136000000
}
Hash = 6a754de1dca8799163c05b54a4efbad0569024b8
```

**Comment by SamVerschueren** [comment]
Hi @khru! That is correct, currently WebContainers do not run on mobile. They will work on Android though, so stay tuned. I can't give you an exact time frame, but we're working on it.
