### ISSUE TITLE
Check and update dependencies

### ISSUE THREAD

**Issue by rajsite** [stackblitz/webcontainer-core#278]
**Is your feature request related to a problem? Please describe:**

Not related to a specific problem.

**Describe the solution you'd like:**

I'd like to be able to see what dependencies are outdated in a WebContainer and update them to the latest. ie have the `npm outdated` command to check and `npm update` to perform the update when I'm ready.

**Describe alternatives you've considered:**

The WebContainer could be aware of the packages and make it easier to update in the UI. I do prefer being able to use the normal CLI commands though.

**Additional context:**

N/A

**Comment by SamVerschueren** [comment]
Hi @rajsite ! thanks for expressing your intrest in those commands. You are correct that we don't have them right now but would be great additions.

**Comment by d3lm** [comment]
Hey 👋 Just wanted to give an update, and we are working on native npm support which means that those commands will be available once that effort is finished. We'll keep you posted.

**Comment by jrvidal** [comment]
You can track native `npm` in https://github.com/stackblitz/webcontainer-core/issues/1070, thanks!
