### ISSUE TITLE
BugReporting

### ISSUE THREAD

**Issue by Mizan-Al-Sabbih** [stackblitz/webcontainer-core#279]
### Describe the bug

I don't know what is the bug on StackBlitz. But you can find a bug in your code editor. :)

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-qeved9

### Steps to reproduce

1. Go and make a project the type will be node.js
2. A few moments later a button will appear its saying File a bug

### Expected behavior

A button it saying File a bug was appeared when i tapped that it was move me here the bug reporting on github.com

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.115
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 131000000,
  "usedJSHeapSize": 123000000,
  "jsHeapSizeLimit": 747000000
}

```

**Comment by jrvidal** [comment]
Good one! :joy:
