### ISSUE TITLE
BUG: Gatsby

### ISSUE THREAD

**Issue by tujoworker** [stackblitz/webcontainer-core#28]
v2 of StackBlitz looks amazing!

The only thing, I can't get Gatsby to work.

**Describe the bug**

1. I run: npm run start -or- yarn start
2. and get this (after a view seconds): 

```
Error: listen EADDRINUSE: address already in use ::
...
UNHANDLED REJECTION Cannot read property 'updateTimeout' of undefined
```

**Link to the blitz that caused the error**
[gatsby-starter](https://stackblitz.com/edit/gatsby-starter)

**To Reproduce**
1. Go to [gatsby-starter](https://stackblitz.com/edit/gatsby-starter)
2. Scroll down to the CLI
3. Enter: npm run start
4. See error (after a view seconds)

**Expected behavior**
See the index page of the app -or- get it up and running, basically.

**Screenshot**
<img width="582" alt="Screenshot 2021-05-21 at 08 47 36" src="https://user-images.githubusercontent.com/1501870/119094357-3917bf00-ba11-11eb-823d-1a8962f56aed.png">

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 71299714,
  usedJSHeapSize: 66683866,
  jsHeapSizeLimit: 4294705152
}

**Additional context**
I really hope we can sort this out and even better, get a default Gatsby starter provided by your amazing Team! (You can use mine if you wish)

Happy day! 

Tobias Høegh

**Comment by SamVerschueren** [comment]
Hi @tujoworker! Thanks for trying out Gatsby! @KyleAMathews already reached out in #4 but I'll leave this one open because it contains more information and a link to a StackBlitz project 🙏 .
