### ISSUE TITLE
Npm install broken

### ISSUE THREAD

**Issue by Camashima1112** [stackblitz/webcontainer-core#280]
### Describe the bug

Using NPM INSTALL with any dependency breaks the WebContainer, constantly and repeatedly sending "Loading ideal dependency tree" in the terminal.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-hpbcxf?file=README.md

### Steps to reproduce

Go to terminal
Use npm install (any dependency)
Booom

### Expected behavior

I EXPECTED to be able to install my dependency.

### Screenshots

![Screenshot 2021-08-02 10 56 32](https://user-images.githubusercontent.com/56922360/127881661-810d882f-545a-42cf-9c11-e5ed93a3dc00.png)

### Platform

```
Browser name  = Chrome 
Full version  = 91.0.4472.167
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 13904.97.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.167 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 162010869,
  "usedJSHeapSize": 151242001,
  "jsHeapSizeLimit": 2020605952
}
Hash = 6a754de1dca8799163c05b54a4efbad0569024b8
```

**Comment by jrvidal** [comment]
Hi @rithcam I think the link you provided might not be correct? It just contains an empty project.

**Comment by mokuzuu** [comment]
I had same issue. I ran `yarn` and `Loading ideal dependency tree` is displayed.

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
