### ISSUE TITLE
Next.js + TS template

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/webcontainer-core#282]
I need a Next.js + TypeScript template instead of just JS.

I think most people start projects nowadays with Next.js instead of CRA as it's just so faster & simpler.

**Comment by purplem1lk** [comment]
@deadcoder0904 This feature request is part of our V2 launch and has been transferred to the webcontainer core repo where it can be readily addressed. Thank you! :)

**Comment by SamVerschueren** [comment]
Our Next.js starter nowadays uses TypeScript. So I believe we can close this issue now.
