### ISSUE TITLE
Browser issue

### ISSUE THREAD

**Issue by rguptaaccountcontrol** [stackblitz/webcontainer-core#289]
### Describe the bug

Does not work on my iPad with chrome browser. Says incompatible web browser even though I am using chrome.

### Link to the blitz that caused the error

https://stackblitz.com/edit/http-server-zy6dzw

### Steps to reproduce

Go to http server link on chrome browser on iPad.

### Expected behavior

Did not expect incompatible browser screen on the right pane.

### Platform

chrome on iPad

**Comment by SamVerschueren** [comment]
Hi @rguptaaccountcontrol. Thanks for reaching out!

Although the name implies that it's running Chrome, it isn't. Apple does not allow 3rd parties to use a custom browser engine. So what Chrome does is basically using WebKit (Safari browser engine) and putting a Chrome-like look and feel on top of it. But they don't let Google to use their own Blink engine unfortunately.

So as long as Apple isn't willing to add the necessary features that the market is begging for, we can't do anything unfortunately.
