### ISSUE TITLE
BUG: Doesn't work on Brave (chromium based)

### ISSUE THREAD

**Issue by aptfx** [stackblitz/webcontainer-core#29]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
It seems it cannot open a port (so the final step hangs)

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-rbr6hp

**To Reproduce**

**Expected behavior**

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.93
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
performance.memory = {
  totalJSHeapSize: 63342813,
  usedJSHeapSize: 55091709,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by SamVerschueren** [comment]
Hi @aptfx, thanks for reaching out! @jonathansampson reported that you have to do something extra for Brave in #14. I'm looping his feedback back to the team so we can improve this experience 🙏 .

Closing in favour of #14. Feel free to write extra findings down in that issue.
