### ISSUE TITLE
Failed to apply a correct font file

### ISSUE THREAD

**Issue by web2033** [stackblitz/webcontainer-core#290]
### Describe the bug

```
⚠ vite-vue3-tailwind-starter--3000.local.webcontainer.io/:1 - Failed to decode downloaded font: https://vite-vue3-tailwind-starter--3000.local.webcontainer.io/font/Inter-roman.var.woff2

⚠ vite-vue3-tailwind-starter--3000.local.webcontainer.io/:1 - OTS parsing error: invalid sfntVersion: 1752462448

client:180 [vite] connecting...
client:202 [vite] connected.
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/vite-vue3-tailwind-starter

### Steps to reproduce

1. Error in console

### Expected behavior

Apply correct font.
Example - https://vvt.netlify.app/

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.131
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 103186871,
  "usedJSHeapSize": 91919027,
  "jsHeapSizeLimit": 2172649472
}
Hash = 47414162f2189b1617faff93cc091995742946b8
```

**Comment by jrvidal** [comment]
I can reproduce the error running the project locally in regular Node.js, so I suspect this is not WebContainer-related.

**Comment by web2033** [comment]
I tried to pull the changes from the original repo, but it tries from `master` branch instead of `main` and leaves me with a broken reproduction link.

**Comment by jrvidal** [comment]
Yes, this is a known issue with our Git implementation, see https://github.com/stackblitz/webcontainer-core/issues/11

Meanwhile, if you want to test the latest changes in that repo, maybe you could fork it and rename the default branch to `master`?
