### ISSUE TITLE
URL Parsing Error

### ISSUE THREAD

**Issue by modderme123** [stackblitz/webcontainer-core#292]
### Describe the bug

When working on a solid vite starter, I successfully managed to get everything a javascript version working on mac, thanks for everything that went into that! However, I shared with others and found a new unexpected behavior: on Windows `new URL('file:' + '/path/to/something.cjs').href` reports only double slashes which is inconsistent with the native behavior. 

All thanks to @rturnq for tracking this one down

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-url-bug

### Steps to reproduce

1. open https://stackblitz.com/edit/node-url-bug
2. see that `file://path/to/something.cjs` is logged

### Expected behavior

I would expect `file:///path/to/something.cjs` to be logged (note the triple slash instead of a double slash)

### Screenshots

https://cdn.discordapp.com/attachments/730114401427783713/874526003450503168/unknown.png

### Platform

On a mac with chrome this works, but on windows it fails

- Chrome 92.0.4515.107
- Windows 10.0.19042 Build 19042

### Additional context

This seems to be a difference in behavior between the browser native `new URL` feature, Firefox on windows reports the other way

**Comment by jrvidal** [comment]
> see that file://path/to/something.cjs is logged

@modderme123  I see three slashes, maybe you are running a cached, old version?

**Comment by modderme123** [comment]
This specifically only happens on Windows computers (on mac it works), and clearing cache doesn't help

**Comment by jrvidal** [comment]
@modderme123 Oh, sorry, I understand what you're saying now. It seems we're being bitten by a web compat bug. Thanks for reporting!

**Comment by d3lm** [comment]
This is fixed now.
