### ISSUE TITLE
An exception is thrown when executing jest.

### ISSUE THREAD

**Issue by MSakamaki** [stackblitz/webcontainer-core#293]
### Describe the bug

When I run jest on a stackblitz nodejs, I get the following error
this does not happen with local nodejs.

```sh
TypeError: 'getOwnPropertyDescriptor' on proxy: trap returned undefined for property 'jest-symbol-do-not-touch' which is non-configurable in the proxy target
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-ked4s2

### Steps to reproduce

I looked into it as much as I could, but it seems that if you add properties to a global object defined in `node-vm` by `Object.defineProperties`, it crashes when you access it.

Here is a small piece of code to reproduce it.

```ts
const { runInContext, createContext } = require('vm');

const context = createContext();
const global = (this.global = runInContext('this', context));

Object.defineProperties(global, {
  'jest-symbol-do-not-touch': {
    enumerable: false,
    value: global.Symbol,
    writable: false
  }
});

console.log(global['x']); // success
console.log(global['jest-symbol-do-not-touch']); // error
Object.keys(global); // error
```

### Expected behavior

the reproduced code above works fine locally, so it should also work fine on stackblitz.

### Screenshots

<img width="813" alt="error" src="https://user-images.githubusercontent.com/2183053/129016774-ca3a7169-98e1-497a-b784-efd550daed65.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 92.0.4515.131

**Comment by freehuntx** [comment]
I think this is related to how "Proxy" is implemented inside of WebContainers node.  
jest relies on Proxy as you can see here: https://github.com/facebook/jest/blob/bc50e7f360ab1845abbaa0b3ad788caead0d3174/packages/jest-util/src/createProcessObject.ts  
So if the implementation of Proxy is broken inside of WebContainers node, that might be the reason.

**Comment by freehuntx** [comment]
Maybe related with:
https://github.com/nodejs/node/issues/30985
https://github.com/nodejs/node/issues/17465

**Comment by freehuntx** [comment]
A workaround is, to set configurable to true when its not defined.
*test/test-environment.js*
```
const defineProperties = Object.defineProperties;
Object.defineProperties = function(obj, props) {
  Object.values(props).forEach(prop => {
    if (typeof prop.configurable === 'undefined') prop.configurable = true;
  });
  return defineProperties(obj, props);
};

module.exports = require('jest-environment-node');
```
*package.json*
```
...
  "jest": {
    "testEnvironment": "./test/test-environment.js"
  }
...
```

**Comment by MSakamaki** [comment]
Thanks for the kind reply!
I have confirmed that jest 27 will run with the solution you suggested.
https://stackblitz.com/edit/node-qsuzv8

since my issue has been solved, I will close this issue.

**Comment by freehuntx** [comment]
This still looks like a bug that shouldnt happen imo. I would not close it as such a bug can cause alot of different bugs.
It should definitely be investigated.

**Comment by freehuntx** [comment]
Note: This has been fixed. So no workaround anymore needed!
