### ISSUE TITLE
WebContainer not sending POST body

### ISSUE THREAD

**Issue by afarago** [stackblitz/webcontainer-core#295]
### Describe the bug

Trying to setup a MEAN like environment - having a node/express server, serving an Angular frontend within one container.
Architecture wise the express server would be serving the static Angular frontend through dist static.
(currently the ng build is not yet working on the stackblitz environment, so there is a manual copy from local build)

Expected behaviour
Angular frontend fires a POST request with a body (e.g. JSON) and express server receives the content and reacts accordingly.

Current behaviour
Angular frontend fires the POST with a properly filled body content. e.g. at login POST - visible in chrome dev tools.
Node/express backend receives an empty body (though JSON body parser is configed and works fine in the local environment).

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-with-node?file=server.js

### Steps to reproduce

1. Open up the stackblotz webcontainer
2. Start the app (currently there is an autostart), yet can be started with node server.js
3. Click on login
4. open debugger tool, network and console
4. fill "a" and "a" for username and password
5. inspect what content express reports

### Expected behavior

Angular frontend fires a POST request with a body (e.g. JSON) and express server receives the content and reacts accordingly.

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.131
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 182426785,
  "usedJSHeapSize": 171185413,
  "jsHeapSizeLimit": 4294705152
}
Hash = 45fbdfd85f8aacdd47a9d95801c7283dc42b054f
```

**Comment by jrvidal** [comment]
@afarago I can't reproduce the bug. We recently fixed an issue which might have taken care of your problem. Please feel free to re-file if you find anything else. Thanks for the report!

**Comment by afarago** [comment]
Thank you, I have checked it in a forked environment and it works like a charm.
https://stackblitz.com/edit/angular-with-node-e71rda
