### ISSUE TITLE
Saving doesn't work for connected repositories

### ISSUE THREAD

**Issue by jafri** [stackblitz/webcontainer-core#296]
### Describe the bug

If you open a node.js project, make modifications and then run `node index.js`, it does not use the version you just saved and instead uses some old version.

Only way for it to update seems to be to commit, and then refresh

### Link to the blitz that caused the error

private

### Steps to reproduce

1. Open nodejs
2. Make modifications
3. Try running node index.js

### Expected behavior

node index.js to run the updated file that you just saved

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Pyrolistical** [comment]
I'm seeing this as well. It seems to be stuck on the previous version of the file until I commit and reload the page

**Comment by Pyrolistical** [comment]
This bug still remains. This is a very serious bug as it makes any project unusable once connected to a github repo

**Comment by jrvidal** [comment]
@Pyrolistical @jafri Could you elaborate a bit on the steps to reproduce? What I've tried so far is:
* Create a new project based on the "Node.js - Blank Project" template.
* Edit `index.js`
* Save
* Run `node index.js` in the terminal.

And it does run the updated version.

**Comment by Pyrolistical** [comment]
@jrvidal Sorry the steps were incomplete. Here's the full repo steps.

1. Create a new project based on the "Node.js - Blank Project" template.
2. Connect it to a github repository
2. Edit index.js
3. Save
4. Run `node index.js` in the terminal.
5. See the change didn't work
6. Commit change
7. Run `node index.js` in the terminal.
8. See the change didn't work
9. Reload site
10. Run `node index.js` in the terminal.
11. See the change finally

**Comment by SamVerschueren** [comment]
Thanks @Pyrolistical for the steps. I did try this again and it seems to be fixed. I know that we worked on improving the git integration a while back, so I assume this was fixed back then.

If you still run into this issue, let us know so we can investigate and improve because this is not something that should happen.
