### ISSUE TITLE
Full stack projects

### ISSUE THREAD

**Issue by mwisnicki** [stackblitz/webcontainer-core#299]
Is it possible to create full stack project e.g. node + react?

All starters seem to be purely server side.

**Comment by SamVerschueren** [comment]
Hi @mwisnicki ! Sure, it's definitely possible. If you would open a server side application on port 8000, and start a react app on port 4000, they will be able to communicate. We aim to support everything you can do on local. 

Just give it a try and let us know if you run into issues 🙏 !

Hope this answers your question.
