### ISSUE TITLE
BUG: npx does not look for local .bin 

### ISSUE THREAD

**Issue by nartc** [stackblitz/webcontainer-core#3]
**Describe the bug**
Usually when executing `npx <cli_name>`, `npx` will look for local `node_modules/.bin` before trying to install the CLI from a registry. Although, this does not work as you can see in the screenshot, `nestjs/cli` is installed as a `devDependencies`
![image](https://user-images.githubusercontent.com/25516557/119020227-99e8be00-b963-11eb-802b-e803bbde5522.png)

**Link to the blitz that caused the error**
https://stackblitz.com/edit/github-yid42f?file=package.json

**To Reproduce**
1. Open Terminal
2. Try `npx nest`

**Expected behavior**
`npx nest` should execute the already-installed `nestjs/cli` 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Chrome

**Comment by SamVerschueren** [comment]
Yes, this looks like a bug as it should work as you describe. Thanks for reporting 🙏 !

**Comment by deadcoder0904** [comment]
`npx` doesn't work but without `npx` it works.

I was doing `npx tailwindcss init -p` but only `tailwindcss init -p` worked.

**Comment by HeyGarrison** [comment]
Hi @nartc it looks like this has been fixed! Thanks for reporting this!
