### ISSUE TITLE
Bug: Running start command doesn't works on Brave browser 

### ISSUE THREAD

**Issue by adarshaacharya** [stackblitz/webcontainer-core#30]
**Describe the bug**
Running `npm dev` (start command) on next.js project does't work on brave browser by default. Booting the web container, Installing dependencies works successfully but running start command doesn't work.

If you open the console you may get following error : 

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
x.clearbitjs.com/v1/pk_cf7f6c8b720be71dfc730b02eb55b0bd/clearbit.min.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
js-agent.newrelic.com/nr-spa-1208.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
registry.worker.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-nee224

**To Reproduce**
1. Open the blitz and run npm dev

**Expected behavior**
using `npm dev` should allow to 

**Screenshots**
![image](https://user-images.githubusercontent.com/50266088/119093020-e3520f80-ba2e-11eb-92f7-3afa775872b3.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04.2 LTS x86_64
 - Browser Brave
 - Version Version 1.24.85 Chromium: 90.0.4430.212 (Official Build) (64-bit)

**Fix**
This error might occur beacuse brave browser might block the cookies for stackblitz. For fix I've followed the given steps: 
1. Go to brave://settings/cookies
2. Click add on sites that can always use cookies.
3. Add https://[*.]stackblitz.com and click allow third-party cookies.

![image](https://user-images.githubusercontent.com/50266088/119095214-b81cef80-ba31-11eb-8dab-3b3b0e4f2305.png)

**Comment by KwintenP** [comment]
In order to get it working on Brave, this is indeed what you'll have to do. We're gonna add some instrumenting to detect whether the editor is running in Brave and point to documentation on how to enable it.

Thanks for reporting!

**Comment by d3lm** [comment]
We have a section in our docs for Brave now https://developer.stackblitz.com/platform/webcontainers/browser-config-brave#running-in-brave, so I am going to close this one. If you're running into more issues, please open a new issue.
