### ISSUE TITLE
API routes with GraphQL server Error

### ISSUE THREAD

**Issue by jonassunandar** [stackblitz/webcontainer-core#304]
### Describe the bug

I just try to preview the content of API routes with GraphQL in [nextjs example](https://github.com/vercel/next.js/tree/canary/examples/api-routes-graphql) and then it says "failed to load"

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-knyu4b?file=pages%2Findex.js

### Steps to reproduce

1. Go to https://github.com/vercel/next.js/tree/canary/examples/api-routes-graphql
2. Wait until all dependencies are installed
3. There is failed to load on the right side

### Expected behavior

We should be able to see all the users from the graphql

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.131
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 110808893,
  "usedJSHeapSize": 105134489,
  "jsHeapSizeLimit": 2172649472
}
Hash = 8ffc536d8181e8b30c228dec423d18afae547c40
```

**Comment by jrvidal** [comment]
@jonassunandar I can't reproduce on my end. Are you still affected by this issue?
