### ISSUE TITLE
Fail to fetch URL package

### ISSUE THREAD

**Issue by runningair** [stackblitz/webcontainer-core#305]
### Describe the bug

Web container cannot fetch URL package, while the package URL is valid.

![image](https://user-images.githubusercontent.com/3164151/130007809-f05602cb-7145-4030-928c-f9d9519600b4.png)

### Link to the blitz that caused the error

Any link can reproduce the bug.

### Steps to reproduce

1. Go to https://stackblitz.com/edit/node-ihqp2y?file=package.json
2. run: `yarn add https://qhstaticssl.kujiale.com/temp/testpkg-1.0.0.tgz`

### Expected behavior

![image](https://user-images.githubusercontent.com/3164151/130007883-1f0c775f-b9fb-4cdb-a863-61246b7472e9.png)

### Platform

- OS: Windows
- Browser: Edge
- Version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.73

**Comment by d3lm** [comment]
Hey there! Thanks for reporting this issue. It's currently not supported to install dependencies via URLs. This is on our todo list tho.

**Comment by kc0tlh** [comment]
@runningair although we are still working on a final resolution to loading packages from a URL, there is a new workaround that may be useful for people needing to use packages that are not listed in npm: host the package locally inside the StackBlitz project. Below is a demo from @HeyGarrison on how it works:
https://stackblitz.com/edit/vitejs-vite-qdipen?file=package.json&terminal=dev

**Comment by d3lm** [comment]
Installing file dependencies (a tarball url) with yarn works now, so I am going to close this one.
