### ISSUE TITLE
Slowdown in starting Vue CLI scaffolded project

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#314]
### Describe the bug

This web container is taking unusually long to boot. Several seconds (10+ seconds) pass in starting up the Webpack dev server (`outputting HtmlWebpackPlugin...`). And then the container just sits at "Running start command" for several more seconds (30+ seconds). This is new behavior (not sure since when), but this was not an issue before when I created the StackBlitz.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vue2-vue-cli?file=.vscode%2Fsettings.json

### Steps to reproduce

Go to the blitz, and let the start command run automatically (`npm run serve`).

### Expected behavior

The project starts without excessive delays (delay < 10s).

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.131
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60968009,
  "usedJSHeapSize": 57150401,
  "jsHeapSizeLimit": 4294705152
}
Hash = 7d2bc3c823b658a8c8b5c71d5f1f8e12a183cbbb
```

**Comment by d3lm** [comment]
Hey! Thanks for reporting this issue. I briefly looked into this and I already found the culprit. It's indeed an issue that has sneaked in recently. I'll fix this ASAP.

**Comment by d3lm** [comment]
Good news, this is fixed. You can check it our in your original project.
