### ISSUE TITLE
Platform not recognizing install of an npm

### ISSUE THREAD

**Issue by Darkmift** [stackblitz/webcontainer-core#316]
### Describe the bug

Hi folks,

I made a playground from a repo I imported.
Please see image for details....I verfied and manually installed "node-sass"....however seems the platform is not registering this properly.

Please let me know if I need to do something on my end to fix this or if its an actual issue.

Any and all help is very much appreciated!

### Link to the blitz that caused the error

https://stackblitz.com/github/Darkmift/vue-interview-exercise?file=.vscode%2Fsettings.json

### Steps to reproduce

1. create env with url containing repo name
2. wait for the build to finish
3. run npm run serve (its vue)

also,
1.manually run `npm i node-sass`
2.run `npm run serve`

### Expected behavior

Expected env to run properly.

### Screenshots

![cry](https://user-images.githubusercontent.com/12433441/132092482-6bdb3d18-9267-47f6-a54f-5bb613a5c9de.png)

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.159
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79837271,
  "usedJSHeapSize": 73984775,
  "jsHeapSizeLimit": 4294705152
}
Hash = dd88a1655a6ea3f646b7279b57a2839a424ce920
```

### Additional context

Any help is greatly appreciated!

**Comment by jrvidal** [comment]
Hi @Darkmift this behavior is expected, see https://developer.stackblitz.com/docs/platform/turbo/#node-sass. You should have gotten a warning when `npm install` exited.

**Comment by Darkmift** [comment]
Thank you for your help! After making the change the project is indeed loading properly.
