### ISSUE TITLE
Nothing happens on clicking "Open In new Window"

### ISSUE THREAD

**Issue by andreas-kater** [stackblitz/webcontainer-core#320]
### Describe the bug

Nothing happens on clicking "Open In new Window"

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-t5ooxw

### Steps to reproduce

click on button in top right

### Expected behavior

opening in new window

### Platform

```
Browser name  = Chrome 
Full version  = 93.0.4577.63
Major version = 93
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86347889,
  "usedJSHeapSize": 75476061,
  "jsHeapSizeLimit": 4294705152
}
Hash = dd88a1655a6ea3f646b7279b57a2839a424ce920
```

**Comment by jrvidal** [comment]
@andreas-kater The "Open in New Window" is meant to open the _preview pane_ and the blitz you provided does not actually run any server. Could that be the issue you were experiencing?
