### ISSUE TITLE
Filewatch in a Nestjs project not working

### ISSUE THREAD

**Issue by SnirShechter** [stackblitz/webcontainer-core#321]
### Describe the bug

nest's dev mode (nest start --watch) doesn't work properly. On file change the process throws an error and seems to exit in the console but the server keeps running and serves the server (without the file changes).

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-ngv34r?file=src%2Fapp.service.ts

### Steps to reproduce

1. Go to https://stackblitz.com/edit/node-ngv34r?file=src%2Fapp.service.ts
2. `npm run start:dev`
3. Change the file app.service.ts * hit Ctrl + S (save)
4. The error should appear on the console

```
[12:31:55 AM] Found 0 errors. Watching for file changes.

jsh: command not found: ps
[Error: spawn ps ENOENT] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 70 ]
}

~/projects/node-ngv34r 6s
```

### Expected behavior

watching the files, updating the server on change.

If the process does exit - it should kill the server (possibly unrelated to WebContainers)

### Screenshots

![image](https://user-images.githubusercontent.com/26040325/132589406-4d02d666-f9ab-4d9f-98b5-19b39b886d67.png)

### Platform

```
Browser name  = Chrome 
Full version  = 93.0.4577.63
Major version = 93
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108063279,
  "usedJSHeapSize": 91757555,
  "jsHeapSizeLimit": 4294705152
}
Hash = dd88a1655a6ea3f646b7279b57a2839a424ce920
```

**Comment by jrvidal** [comment]
@SnirShechter Just as an FYI, this is a known limitation for the time being, since we don't ship a `ps` command.

**Comment by jrvidal** [comment]
I'm closing this in favor of https://github.com/stackblitz/webcontainer-core/issues/391 :pray:
