### ISSUE TITLE
Error when trying to load a MDX file with mdx-bundler and next.js

### ISSUE THREAD

**Issue by brunomoutinho** [stackblitz/webcontainer-core#325]
### **Description of Bug**
I have a create-next-app for which I installed mdx-bundler and was trying to load MDX files. Outside of Stackblitz, the MDX files are being loaded fine, but I am unable to do it in Stackblitz due to the following error:

```
TypeError: Failed to resolve module specifier 'xdm/esbuild.js'
```

According to a user in the Stackblitz Discord server, the issue is probably related to the following:

```
// xdm is a native ESM, and we're running in a CJS context. This is the
  // only way to import ESM within CJS
  const [
    {default: xdmESBuild},
    {default: remarkFrontmatter},
  ] = await Promise.all([
    import('xdm/esbuild.js'),
    import('remark-frontmatter'),
  ])
```

My Stackblitz project link:
https://stackblitz.com/edit/nextjs-bwcbzv

### **Steps to Reproduce**

1. Open the Stackblitz project (https://stackblitz.com/edit/nextjs-bwcbzv)
2. Navigate to `/post/test` by directly modifying the URL

### **Expected Behavior**
The page loads without any errors.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/8903024/133334269-f2176845-9fec-4821-8a37-8d6d4f62db9f.png)

**Comment by d3lm** [comment]
I have moved this issue because it's related to WebContainer.

**Comment by brunomoutinho** [comment]
I have recriated the Stackblitz project and just thought later that the URL might be needed still. So this is it: https://stackblitz.com/edit/nextjs-zsxy8n

I have created the `.stackblitzrc` file and will test it now.

**Comment by brunomoutinho** [comment]
@d3lm I can confirm that the `.stackblitz` file with the content you provided makes it work like a charm! Thanks for the solution!

**Comment by d3lm** [comment]
You are welcome. Glad it worked out for you. Sorry that it's an opt-in for CJS but it's a performance reason and we need to do some more work to make it fast by default without manually enabling it.
