### ISSUE TITLE
Failing when run Mocha Chai testing

### ISSUE THREAD

**Issue by rubenvidales** [stackblitz/webcontainer-core#327]
### Describe the bug

Trying to use pass a simple test asserts with Mocha & Chai throws an error
`TypeError: Failed to fetch dynamically imported module: file:///home/projects/node-um3w4m/test/appTest.js`

The same code exactly in a local machine works fine.

Maybe is a problem when the dependecies was installed.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-um3w4m?file=package.json

### Steps to reproduce

1. Run `npm run test`

### Expected behavior

Just execute the test and run correctly.

### Platform

```
Browser name  = Chrome 
Full version  = 93.0.4577.82
Major version = 93
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77403542,
  "usedJSHeapSize": 71116946,
  "jsHeapSizeLimit": 4294705152
}
Hash = fa2fa735bbb029186c23972eb56445ed5c5fdef5
```

**Comment by jrvidal** [comment]
It works with:

```
ENABLE_CJS_IMPORTS=true npm test
```

This is due to a "legacy" CommonJS file trying to use dynamic `import()`. This works but you need to opt in through an environment variable. Please check https://github.com/stackblitz/webcontainer-core/issues/281 for more info.
