### ISSUE TITLE
Work like github codespaces

### ISSUE THREAD

**Issue by Milo123459** [stackblitz/webcontainer-core#33]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Allow you to code in vscode, via the stackblitz platform. Like github codespaces. This'd be the ultimate dev experience! 🚀
**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by KwintenP** [comment]
This is definitely our end goal. What we released yesterday is the beta version. In upcoming version, we will provide better git integration, more node API support, better stability, ....

Closing since no actual action item.

**Comment by Milo123459** [comment]
Can't wait! Must say, this is the future! Well done! And can't wait to try it out! I have a few frameworks I'll add :)
