### ISSUE TITLE
Server is not opening.

### ISSUE THREAD

**Issue by Lucifer25x** [stackblitz/webcontainer-core#332]
### Describe the bug

Server is not opening.

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-cuaf2i?file=src%2Fpages%2Fdeneme.md

### Steps to reproduce

1. Create node.js project.
2. Create Web server.

### Expected behavior

Web server is not working sometimes.

### Platform

```
Browser name  = Chrome 
Full version  = 93.0.4577.82
Major version = 93
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 104969528,
  "usedJSHeapSize": 101676148,
  "jsHeapSizeLimit": 2172649472
}
Hash = fa2fa735bbb029186c23972eb56445ed5c5fdef5
```

**Comment by jrvidal** [comment]
@Lucifer25x Sorry I was not able to reproduce. Can you elaborate on what happens exactly? Does the preview window open at all? Do you get open port notifications? Also, do you get any suspicious errors in the dev tools console?

**Comment by Lucifer25x** [comment]
> @Lucifer25x Sorry I was not able to reproduce. Can you elaborate on what happens exactly? Does the preview window open at all? Do you get open port notifications? Also, do you get any suspicious errors in the dev tools console?

I did not get any error.  The console says the port is open, but this is not visible in the preview on window right. It works when I try it first. However, when you end and restart the port, the port does not open and does not give any errors. This is not the first time this has happened to me. I use Opera.

**Comment by d3lm** [comment]
Also make sure the same project is not open in another tab. That can also result in funky behavior.

**Comment by Lucifer25x** [comment]
> Also make sure the same project is not open in another tab. That can also result in funky behavior.

Sometimes it work well, but sometimes server not opening. Thanks.
