### ISSUE TITLE
Problem after conect project with repository

### ISSUE THREAD

**Issue by DavidOtero91** [stackblitz/webcontainer-core#337]
### Describe the bug

After connecting the project with the github account it stops working properly.

If I change any of the scripts in the package.json and try to run it, node tries to run what was there before.

I have also noticed that when I start for example the sass script it does not work correctly either.

All this after creating the github repository

I have tried downloading and copying all files into a new node project and it seems to work fine

### Link to the blitz that caused the error

https://stackblitz.com/edit/ahaowebestatica?file=package.json

### Steps to reproduce

1º Pull
2º Change somo script in package.json for example:
    "start": "node server.js" to "nodemon server.js"
3º Try npm start

### Expected behavior

Command is successful

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.61
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68006444,
  "usedJSHeapSize": 59406392,
  "jsHeapSizeLimit": 4294705152
}
Hash = d5494ef8952bfa639324ffc4677d49b0e07d691b
```

**Comment by geromegrignon** [comment]
Hey @DavidOtero91,

About the node/nodemon part, you need to save changes on the project before using them with (CTRL + S).
Meanwhile, the affected files are tagged as they would be on VSCode: 
![image](https://user-images.githubusercontent.com/32737308/135264759-d2913fd0-8e69-44df-88f5-f128c6653de3.png)


About `build-css`, WebContainers don't seem to allow multiple scripts running at the same time. The script works as expected if you stop `npm start`.

**Comment by d3lm** [comment]
You can start multiple scripts with multiple different terminal windows. Or you can use something like `concurrently`.

**Comment by geromegrignon** [comment]
You are right Dominic, for some reasons `npm run build-css` was stuck when I first tested it. It works as expected now.

**Comment by DavidOtero91** [comment]
mmm

Yes, the problem is that after changing the start script in the package.json it does not run the new previous version but the one that was there before.

![Captura](https://user-images.githubusercontent.com/29038513/135455099-80b942a0-5e00-448f-b003-85481f2b9450.PNG)
Initially the start script was node server.js

And Sass although it starts it does not work correctly.

The idea is that when saving a scss file, sass will compile the css and with nodemon it will be implemented again. Everything was working properly until I connected with github.

**Comment by SamVerschueren** [comment]
A while back we fixed some issues with the github integration. File changes should be picked up correctly now and I verified that and it seems to work on my end. Feel free to create a new issue if you still run into bugs with the integration.
