### ISSUE TITLE
Terminal uses other keyboard configuration

### ISSUE THREAD

**Issue by brjupo** [stackblitz/webcontainer-core#338]
### Describe the bug

Terminal uses a different configuration of keyboard [different to the file editor] [different to the computer keyboard configuration]

1.- Create a file
2.- In the created file, write the next text using keyboard [DO NOT COPY IT]
"Hello! My name = Jürguen Díaz"
3.- Open a terminal
4.- In the terminal, write the next text using keyboard [DO NOT COPY IT]
"Hello! My name = Jürguen Díaz"
In my case LATIN-AMERICA KEYBOARD, the text in the terminal show LIKE:
 @Hello! My name ) Jurguen Diaz@

You can try with any special character.
![image](https://user-images.githubusercontent.com/8333728/135377821-ad951211-b77f-4b76-8bc5-664de58fa609.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-azt16e?file=process-cli.js

### Steps to reproduce

1.- Create a file
2.- In the created file, write the next text using keyboard [DO NOT COPY IT]
"Hello! My name = Jürguen Díaz"
3.- Open a terminal
4.- In the terminal, write the next text using keyboard [DO NOT COPY IT]
"Hello! My name = Jürguen Díaz"
In my case LATIN-AMERICA KEYBOARD, the text in the terminal show LIKE:
 @Hello! My name ) Jurguen Diaz@

You can try with any special character.

### Expected behavior

1.- Create a file
2.- In the created file, write the next text using keyboard [DO NOT COPY IT]
"Hello! My name = Jürguen Díaz"
3.- Open a terminal
4.- In the terminal, write the next text using keyboard [DO NOT COPY IT]
"Hello! My name = Jürguen Díaz"
In my case LATIN-AMERICA KEYBOARD, the text in the terminal should show:
"Hello! My name = Jürguen Díaz"

You should try with any special character.

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.61
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82510105,
  "usedJSHeapSize": 71944909,
  "jsHeapSizeLimit": 2172649472
}
Hash = 0daf18d66bd0477c044a0c3738a8c32b0eb4fbe2
```

### Additional context

Operative System: Ubuntu 20.04 LTS
Settings > Region & Language > Input Source: Spanish Latin America
Google Chrome downloaded from https://www.google.com/chrome/?

**Comment by SamVerschueren** [comment]
Hi @brjupo! Thanks for reporting this issue. Can you reproduce this in VSCode terminal as well? Or does it work correctly in VSCode terminal? We use XTerm.js which is used by VSCode, so I'm wondering if they do something differently.

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
