### ISSUE TITLE
N.BrotliEncoder is not a constructor

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#339]
### Describe the bug

Trying to use Brotli compression (via `compression-webpack-plugin`) in StackBlitz Node container results in an error:

```
N.BrotliEncoder is not a constructor
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-bug-no-brotli?file=vue.config.js

### Steps to reproduce

1. Use Vue CLI 5 to scaffold project, and configure `compression-webpack-plugin` to Brotli-compress `.js` files:

```js
// vue.config.js
const CompressionPlugin = require('compression-webpack-plugin')

module.exports = {
  transpileDependencies: true,
  configureWebpack: {
    plugins: [
      new CompressionPlugin({
        filename: '[path][base].br',
        algorithm: 'brotliCompress',
        test: /\.js$/,
      }),
    ],
  },
}
```

2. Serve project with `npm run serve`
3. Observe error in terminal and preview panes

### Expected behavior

Webpack dev server uses Brotli compression for `.js` files (as observed in DevTools Network panel).

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.61
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82930761,
  "usedJSHeapSize": 81318793,
  "jsHeapSizeLimit": 4294705152
}
Hash = 2c9073eccdf0736e23acc49c5a06b18dd822d7ed
```

**Comment by jrvidal** [comment]
This is a known limitation and it's in our internal tracker.

**Comment by tony19** [comment]
This seems to work now.

**Comment by tony19** [comment]
While the Brotli error is no longer reproducible, a different error occurs in StackBlitz:

```none
r.init is not a function
```

There is no stacktrace in the browser console.

**Comment by d3lm** [comment]
Yes, we still haven't had a chance to work on this but we are aware of it and it's already tracked internally.

**Comment by benminer** [comment]
Still getting this in September '22, any updates?

**Comment by d3lm** [comment]
No, unfortunately not. We'll post an update here if we land this but I can't speak to an ETA.

**Comment by Agapurnis** [comment]
If it's of any use, the `r.init` issue can be reproduced quite easily with `ts-node --esm` seemingly regardless of environment as long as `ts-node` is installed.

Here's the error and trace I get when doing so:
```
TypeError: r.init is not a function
    at BrotliCompress.Brotli (https://node-p4wgwo.w.staticblitz.com/blitz.421e70ed35311a61ea4321fec3fad6b3e279633a.js:6:1726958)
    at new BrotliCompress (https://node-p4wgwo.w.staticblitz.com/blitz.421e70ed35311a61ea4321fec3fad6b3e279633a.js:6:1727133)
    at https://node-p4wgwo.w.staticblitz.com/blitz.421e70ed35311a61ea4321fec3fad6b3e279633a.js:6:1725551
    at compress (/home/projects/node-p4wgwo/node_modules/ts-node/dist/child/argv-payload.js:9:42)
    at callInChild (/home/projects/node-p4wgwo/node_modules/ts-node/dist/child/spawn-child.js:25:67)
    at bootstrap (/home/projects/node-p4wgwo/node_modules/ts-node/dist/bin.js:42:50)
    at main (/home/projects/node-p4wgwo/node_modules/ts-node/dist/bin.js:32:12)
    at Object.eval (/home/projects/node-p4wgwo/node_modules/ts-node/dist/bin.js:578:5)
    at Object.function (https://node-p4wgwo.w.staticblitz.com/blitz.421e70ed35311a61ea4321fec3fad6b3e279633a.js:15:141194)
    at Module._compile (https://node-p4wgwo.w.staticblitz.com/blitz.421e70ed35311a61ea4321fec3fad6b3e279633a.js:6:219079)
```

**Comment by FossPrime** [comment]
What's the best workaround for this?

Using TSX? it's kind of heavy.

**Comment by jrvidal** [comment]
Brotli support was recently added and this now works! :tada: 

(Note that in Node 18, you need to run your example with `NODE_OPTIONS=--openssl-legacy-provider` for it to work).
