### ISSUE TITLE
Astro examples just say "Upgrade Required"

### ISSUE THREAD

**Issue by SteveALee** [stackblitz/webcontainer-core#341]
### Describe the bug

Clicking on the "Launch In Stackblitz" button on the astro examples Is just see the message "Upgrade Required" in the ouput window on the right.

https://github.com/snowpackjs/astro/tree/main/examples/starter
https://stackblitz.com/github/snowpackjs/astro/tree/latest/examples/portfolio

Upgrade what? How?

Windows + latest Chrome

### Link to the blitz that caused the error

https://stackblitz.com/github/snowpackjs/astro/tree/latest/examples/portfolio

### Steps to reproduce

Clicking on the "Launch In Stackblitz" button on the astro examples

### Expected behavior

somehting else :)

### Screenshots

![image](https://user-images.githubusercontent.com/618922/135840885-ebc261fd-80ae-4e69-9474-fdecfb5a64ef.png)

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.61
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68390948,
  "usedJSHeapSize": 64432124,
  "jsHeapSizeLimit": 4294705152
}
Hash = 2c9073eccdf0736e23acc49c5a06b18dd822d7ed
```

**Comment by SamVerschueren** [comment]
Hi @SteveALee! This seems to be a regression on our side. Thanks for reporting! We'll see what we can do.

**Comment by jrvidal** [comment]
@SteveALee FWIW, the "Upgrade Required" message you're getting is the response of the server running on port 12321 (as you can see in the URL in the preview bar). We're looking into why the main server is not responsive.

**Comment by SteveALee** [comment]
@jrvidal Thanks for the info!

**Comment by jrvidal** [comment]
@SteveALee The linked blitz works now :tada: Thanks for the report!

**Comment by SteveALee** [comment]
@jrvidal Thanks, I'm glad you added that note :)

**Comment by Dypnotic** [comment]
As far as I can see this issue has not been solved. I have been waiting for an hour now and it still shows me "Upgrade Required". Am I missing something here?

**Comment by jrvidal** [comment]
@SteveALee Is this for the same blitz or for a different one?

**Comment by Dypnotic** [comment]
> @SteveALee Is this for the same blitz or for a different one?
> 
> EDIT: responding to a deleted comment 👻

No it wasn't, but just for completion sake: the issue was that the repo was private and not public. Making it public resolved the issue.
