### ISSUE TITLE
PNPM like caching

### ISSUE THREAD

**Issue by Milo123459** [stackblitz/webcontainer-core#345]
**Is your feature request related to a problem? Please describe:**

Installing dependencies can take a while
**Describe the solution you'd like:**

Dependencies, cached with PNPM in browser storage. It doesn't have to use PNPM, but just something like PNPM
**Describe alternatives you've considered:**

N/A
**Additional context:**

N/A

**Comment by geromegrignon** [comment]
Hey @Milo123459, could you change the title of this issue, so it matches the cache part of the request?
It'll help the core team to triage your issue.

**Comment by SamVerschueren** [comment]
@Milo123459 Going to close this issue. Feel free to create a new issue if you have use cases where the caching doesn't seem to work correctly. Caching is an important part of our setup so we're definitely interested to hear when it doesn't work.

**Comment by okikio** [comment]
pnpm doesn't work in StackBlitz.
