### ISSUE TITLE
Framework support for electron

### ISSUE THREAD

**Issue by hmmhmmhm** [stackblitz/webcontainer-core#347]
Is it possible to run the electron program through webcontainer?
I wonder if I can expose the browser window shown within the electron to the user browser.

**Comment by jrvidal** [comment]
Electron is a native app, a custom Chromium installation in essence. WebContainer runs entirely within the browser, so we can't make Electron work per se.

**Comment by d3lm** [comment]
As per the comment from @jrvidal, running Electron in WebContainer is not something that will work any time soon because it's a native app. I am going to close this one for now because it's not actionable.
