### ISSUE TITLE
Refused to load script because it violates the following Content Security Policy directive: "default-src 'none'"

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#355]
### Describe the bug

Attempting to start [Vite + Vue 2 blitz](https://stackblitz.com/edit/vue-vmodel-demo-y3bh2n) results in the following errors seen in the browser console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Refused to load the script 'https://vue-vmodel-demo-y3bh2n--5000.local.webcontainer.io/.localservice@runtime.b18a3e4ceae8ff2e644e5522c88ded4dea7c71bb.js' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.
```

The terminal window shows no errors. The preview pane shows `Cannot GET /`.

Interestingly, no errors are shown at all in Incognito mode, but the blitz never opens the preview. It gets stuck in "Running start command".

### Link to the blitz that caused the error

https://stackblitz.com/edit/vue-vmodel-demo-y3bh2n

### Steps to reproduce

1. Go to blitz.
2. Observe error in DevTools console.

### Expected behavior

The bltiz starts without error.

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 60307305,
  "usedJSHeapSize": 55517789,
  "jsHeapSizeLimit": 4294705152
}
Hash = b18a3e4ceae8ff2e644e5522c88ded4dea7c71bb
```

**Comment by tony19** [comment]
The strange thing is the problem doesn't occur in a [this blitz that recreates the original project](https://stackblitz.com/edit/vue2-v-model-demo-2?file=src/App.vue).

**Comment by jrvidal** [comment]
@tony19 The 404 ("Cannot GET /") is also shown when running this project locally, so this doesn't look like a WebContainer problem. The CSP issue is interesting though, we'll take not of that.

Thanks for the report!
