### ISSUE TITLE
Afafa

### ISSUE THREAD

**Issue by Ssaacc** [stackblitz/webcontainer-core#357]
### Describe the bug

AgaggHGqbaNa
akhzjiau
BggcGb
.auyjan  gzzb Hz.a

### Link to the blitz that caused the error

https://stackblitz.com/edit/http-server-3pqgmf

### Steps to reproduce

HsnVz. @&&*&🤪#&&*;℅

### Expected behavior

AhhzjZv,n bahshjsg bahxqx.jkx

### Screenshots

HsajshbWj. Bjshznsjhd

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.71
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; M2006C3LII) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53500000,
  "usedJSHeapSize": 50400000,
  "jsHeapSizeLimit": 1070000000
}
Hash = b18a3e4ceae8ff2e644e5522c88ded4dea7c71bb
```malvshhsjs vhahjdjdh as hsjahhs

### Additional context

Shhshahvbzn. Jagshau7

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
