### ISSUE TITLE
BUG: Always wants to install 'next' even on bare Node project

### ISSUE THREAD

**Issue by aptfx** [stackblitz/webcontainer-core#36]
---
name: Bug report
about: Create a report to help us improve
title: 'Always wants to install 'next' even on bare Node project'
labels: ''
assignees: ''

---

**Describe the bug**
I tried it in Brave - configured Shields to make it work in the browser. Then I installed it as desktop app. It now tries to always install 'next' (and fails) - even for plain Node.js projects

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-gantcb

**To Reproduce**

**Expected behavior**

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.93
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
performance.memory = {
  totalJSHeapSize: 85706543,
  usedJSHeapSize: 79518563,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by Milo123459** [comment]
This doesn't seem to happen for me. I opened a blank project and it hasn't installed Next?

**Comment by louy** [comment]
happened to me. steps:
- create a next project
- create a node project
The node project errors with something about react missing as a dep for next. startup command was `npm install && npx next dev`

**Comment by SamVerschueren** [comment]
Thanks for reporting this 🙏 ! Yes, this is a bug. Thanks for finding the steps to reproduce this @louy !

**Comment by SamVerschueren** [comment]
This should be fixed now 🎉 .
