### ISSUE TITLE
Calling `worker.once` implicitly calls `worker.ref`

### ISSUE THREAD

**Issue by arcanis** [stackblitz/webcontainer-core#365]
### Describe the bug

Calling `unref` from a `message` event handler doesn't have any effect in StackBlitz. This causes the following code to hang, unlike in stock Node:

```ts
const { Worker } = require(`worker_threads`);

const worker = new Worker(
  `
    const {parentPort} = require('worker_threads');
    parentPort.on('message', async message => {
      console.log(message);
      parentPort.postMessage('child');
    });
  `,
  {
    eval: true,
    execArgv: [...process.execArgv, `--unhandled-rejections=strict`],
  }
);

worker.once(`message`, (message) => {
  console.log(message);
  worker.unref();
});

worker.ref();
worker.postMessage('parent');
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-fmhgw9

### Steps to reproduce

1. Run `index.js`

### Expected behavior

It shouldn't hang.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by d3lm** [comment]
This has been fixed and deployed.

Example: https://stackblitz.com/edit/node-9pp1kp.
