### ISSUE TITLE
App not compiling.

### ISSUE THREAD

**Issue by MatthewGHub2** [stackblitz/webcontainer-core#368]
### Describe the bug

Will not compile app.

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-poeerw?file=package-lock.json

### Steps to reproduce

npm run dev

### Expected behavior

error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
[TypeError: Failed to fetch dynamically imported module: file:///home/projects/github-poeerw/next.config.js]

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.54
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82370438,
  "usedJSHeapSize": 76909330,
  "jsHeapSizeLimit": 2172649472
}
Hash = eb19bc088249a645473767848622a1d98c51b8f3
```

**Comment by jrvidal** [comment]
This issue should be fixed by now. Thanks for the report @MatthewGHub2
