### ISSUE TITLE
Support for "node:" protocol for importing builtin nodejs modules

### ISSUE THREAD

**Issue by Mortynex** [stackblitz/webcontainer-core#369]
**Is your feature request related to a problem? Please describe:**
Many libraries make use of this feature, so not supporting would result in not being able to use these libraries.

**Describe the solution you'd like:**
Add the support for the protocol 😄 

**Describe alternatives you've considered:**

**Additional context:**

`node:` is a protocol/prefix for importing a module to make clear that its _node.js builtin module_

example:
```js
import fs from "node:fs/promises"
// or
const fs = require("node:fs/promises")
```
this feature was first introduced in node.js release v14.17.6, PR [#37246](https://github.com/nodejs/node/pull/37246)

**Comment by jrvidal** [comment]
@Mortynex AFAICS we do support this feature: https://stackblitz.com/edit/node-ccqtbh?file=index.mjs&terminal=start

**Comment by d3lm** [comment]
@Mortynex FWIW, this is only supported in ESM in Node 14 and not in CommonJS. As @jrvidal pointed out above, you can use `type: module` or, change `index.js` to `index.mjs` to run an ES module.
