### ISSUE TITLE
jhkg

### ISSUE THREAD

**Issue by abbbbbr** [stackblitz/webcontainer-core#371]
### Describe the bug

hn

### Link to the blitz that caused the error

https://stackblitz.com/github/webpack/webpack.js.org/tree/master/examples/getting-started?file=package-lock.json&terminal=

### Steps to reproduce

s

### Expected behavior

s

### Platform

```
Browser name  = Safari 
Full version  = 13.0.5
Major version = 13
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1
performance.memory = undefined
Hash = eb19bc088249a645473767848622a1d98c51b8f3
```

**Comment by geromegrignon** [comment]
Hey @abbbbbr, please motivate this issue: what's your problem?

**Comment by codergautam** [comment]
abbbbr.problem = undefined

**Comment by d3lm** [comment]
Closing this issue because it's missing relevant information. If you still encounter an issue, please open a new issue and fill in the required information.
