### ISSUE TITLE
Error creating a createCipheriv instance.

### ISSUE THREAD

**Issue by WorkAttackDev** [stackblitz/webcontainer-core#373]
### Describe the bug

I'm trying to create a ´createCipheriv ´ instance from node crypto module but always throw an exception 'ERR_CRYPTO_UNKNOWN_CIPHER'.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-md2g1u?file=index.js

### Steps to reproduce

const {
  createHash,
  scryptSync,
  randomBytes,
  timingSafeEqual,
  createHmac,
  createCipheriv,
  createDecipheriv,
  getCiphers,
} = require('crypto');

const { log } = require('console');

const message = 'Never forget that';

const cipherKey = randomBytes(32);
const cipherIv = randomBytes(16);

const cipher = createCipheriv('aes256', cipherKey, cipherIv);

const encryptedMessage =
  cipher.update(message, 'utf8', 'hex') + cipher.final('hex');

//* Decipher

const decipher = createDecipheriv('aes256', cipherKey, cipherIv);

const decryptedMessage =
  decipher.update(encryptedMessage, 'hex', 'utf8') + decipher.final('utf8');

log('encrypted message:', encryptedMessage);
log('decrypted message:', decryptedMessage);

### Expected behavior

Create a Cipher Instance

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.54
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93842787,
  "usedJSHeapSize": 86356375,
  "jsHeapSizeLimit": 2172649472
}
Hash = eb19bc088249a645473767848622a1d98c51b8f3
```

**Comment by jrvidal** [comment]
@WorkAttackDev Our support for crypto primitives is partial. For instance, `createCipheriv('aes-256-cbc')` should work.

If you could elaborate on your usecase, that would help us get a better idea of what crypto primitives are more interesting to support.

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
