### ISSUE TITLE
Fork stuck in "Running start command"

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#381]
### Describe the bug

This [blitz](https://stackblitz.com/edit/vue2-dynamicaly-importing-vue-composition-api-vue-cli) works fine, but forks of it get stuck in *Running start command*. There are no console error messages.

<details>
<summary>Console log</summary>
<pre>[@blitz/fetchers] [INFO] GitFetcher successfully initialized
fetch.worker.eb19bc088249a645473767848622a1d98c51b8f3.js:6 [@blitz/fetchers] [INFO] RegistryFetcher successfully initialized
8[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See <URL> for more details.
8XHR finished loading: POST "<URL>".
vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun:7 [Violation] 'setTimeout' handler took 280ms
[Violation] Forced reflow while executing JavaScript took 31ms
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11 [Contextify] [WARNING] running source code in new context
(anonymous) @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
_0x370d43 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
runInContext @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
runInContext @ vm.js:143
runInNewContext @ vm.js:148
runInNewContext @ vm.js:303
(anonymous) @ repl.js:148
a0_0x2d77 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:6
_0x4a9ab5 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:8
_0x250f29 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
(anonymous) @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
compileForInternalLoader @ loaders.js:283
compileForPublicLoader @ loaders.js:225
loadNativeModule @ helpers.js:35
Module._load @ loader.js:740
Module.require @ loader.js:952
i @ helpers.js:88
_0x30ed18 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
eval @ /bin/jsh:6
r @ /bin/jsh:6
eval @ /bin/jsh:6
r @ /bin/jsh:6
eval @ /bin/jsh:6
r @ /bin/jsh:6
eval @ /bin/jsh:6
Promise.then (async)
eval @ /bin/jsh:6
eval @ /bin/jsh:6
r @ /bin/jsh:6
eval @ /bin/jsh:6
eval @ /bin/jsh:6
eval @ /bin/jsh:6
eval @ /bin/jsh:6
function @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
Module._compile @ loader.js:1063
Module._extensions..js @ loader.js:1092
Module.load @ loader.js:928
Module._load @ loader.js:769
executeUserEntryPoint @ run_main.js:72
a0_0x2d77 @ run_main_module.js:17
_0x4a9ab5 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:8
_0x250f29 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
_0x55f40a @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
run @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
async function (async)
run @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
_0x4bc59c @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:8
vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun:7 [Violation] 'requestAnimationFrame' handler took 68ms
vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun:7 [Violation] 'setTimeout' handler took 115ms
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11  INFO  Starting development server...
VM108:7290 crbug/1173575, non-JS module files deprecated.
(anonymous) @ VM108:7290
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11 [Contextify] [WARNING] running source code in new context
(anonymous) @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
_0x370d43 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
runInContext @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
runInContext @ vm.js:143
evaluateCompilationResult @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/html-webpack-plugin/index.js:247
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/html-webpack-plugin/index.js:161
Promise.then (async)
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/html-webpack-plugin/index.js:154
eval @ VM3368:24
lazyCompileHook @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/tapable/lib/Hook.js:154
emitAssets @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compiler.js:491
onCompiled @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Watching.js:51
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compiler.js:681
eval @ VM3366:15
lazyCompileHook @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/tapable/lib/Hook.js:154
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compiler.js:678
eval @ VM3365:9
lazyCompileHook @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/tapable/lib/Hook.js:154
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1423
eval @ VM3362:9
lazyCompileHook @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/tapable/lib/Hook.js:154
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1414
eval @ VM3360:9
lazyCompileHook @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/tapable/lib/Hook.js:154
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1409
eval @ VM3359:9
lazyCompileHook @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/tapable/lib/Hook.js:154
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1405
eval @ VM3293:9
lazyCompileHook @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/tapable/lib/Hook.js:154
seal @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1342
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compiler.js:675
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1261
eval @ VM3274:20
lazyCompileHook @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/tapable/lib/Hook.js:154
finish @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1253
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compiler.js:672
_done @ VM2853:9
eval @ VM2853:32
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1185
eval @ /home/projects/vue2-dynamicaly-importing-vue-composition-api-vue-cli-appcun/node_modules/webpack/lib/Compilation.js:1097
(anonymous) @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
(anonymous) @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
_0x1863b3 @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
_0x3dd56b.<computed>.onmessage @ blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11
Show 14 more frames
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11 

blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11  DONE  Compiled successfully in 2427ms                                                              10:35:08 PM
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11   App running at:
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11   - Local:   http://localhost:8080/ 
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11   - Network: unavailable
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11   Note that the development build is not optimized.
blitz.eb19bc088249a645473767848622a1d98c51b8f3.js:11   To create a production build, run npm run build.
</pre>
</details>

### Link to the blitz that caused the error

https://stackblitz.com/edit/vue2-dynamicaly-importing-vue-composition-api-vue-cli-nwr33h

### Steps to reproduce

1. Fork this blitz: https://stackblitz.com/edit/vue2-dynamicaly-importing-vue-composition-api-vue-cli
2. Observe the fork gets stuck at *Running start command*.

### Expected behavior

The fork starts normally.

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65000592,
  "usedJSHeapSize": 61562600,
  "jsHeapSizeLimit": 4294705152
}
Hash = eb19bc088249a645473767848622a1d98c51b8f3
```

**Comment by d3lm** [comment]
Hey! Thanks for reporting this issue. I can confirm that when you fork the original project that it won't open the preview and gets stuck at "Running start command".

**Comment by SamVerschueren** [comment]
Hi @tony19. We looked into it and found the culprit. The problem here is that the project slug (`vue2-dynamicaly-importing-vue-composition-api-vue-cli-nwr33h`) is too long. It's currently 60 characters, and for technical reasons, it should be limited to 56. 

I made an internal PR to make sure that project slugs don't exceed 56 characters, but for now the only thing you can do is manually rename the slug in your project settings.

**Comment by d3lm** [comment]
I think we can close this one then?

**Comment by SamVerschueren** [comment]
Yes, wanted to wait until the fix landed in production, which is the case now. 🎉

**Comment by d3lm** [comment]
Closing this for now. If there's still any issues feel free to open a new issue.
