### ISSUE TITLE
Stackblitz stuck on installing dependencies for auto-generated Angular 13 app

### ISSUE THREAD

**Issue by crissxross** [stackblitz/webcontainer-core#382]
### Describe the bug

When opening a Stackblitz example from Angular Material Components docs (e.g. [Sidenav component](https://material.angular.io/components/sidenav/overview)) it gets stuck in the installing dependancies phase and the example app does not load in the window.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fsidenav-overview-example.html

### Steps to reproduce

1. Go to https://material.angular.io/components/sidenav/overview
2. Click on 'Edit Basic sidenav example in Stackblitz' (external link) button
3. Go to the browser tab that launches Stackblitz for "Basic sidenav - Auto-generated from: https://material.angular.io"
4. The app fails to load in window

### Expected behavior

The app should load in window.

### Screenshots

![image](https://user-images.githubusercontent.com/5307070/140510082-4620344d-fa6f-447e-ac9e-cd1cafc5e524.png)

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87509333,
  "usedJSHeapSize": 85123973,
  "jsHeapSizeLimit": 4294705152
}
Hash = a2650b30e72da165a9b10039536c7b8fea1cf462
```

### Additional context

Here's the terminal output:

`~/projects/mwpdie--run
❯ npm install && turbo start
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 2.924s
┌ [2/3] 🚚  Fetching dependencies
│ info pruneDeps Excluding 13 dependencies. For more information use `--verbose`.
└ Completed in 6.987s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 5.297s
info security We found `install` scripts which turbo skips for security reasons. For more information see
https://turbo.sh/install-scripts.
├─ @angular/cli@13.0.0-rc.2
├─ core-js@3.19.0
└─ esbuild@0.13.9
info Some packages were automatically replaced with polyfills. For more information see
https://turbo.sh/polyfills.
└─ esbuild@0.13.9 => esbuild-wasm@0.13.8

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 16.127s
$ ng serve
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   5.40 MB
polyfills.js          | polyfills     | 336.76 kB
styles.css, styles.js | styles        | 296.74 kB
main.js               | main          |  24.94 kB
runtime.js            | runtime       |   6.86 kB

                      | Initial Total |   6.05 MB

Build at: 2021-11-05T11:52:33.769Z - Hash: 5babc6d4f41cf307 - Time: 24688ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Compiled successfully.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2021-11-05T11:52:34.399Z - Hash: 5babc6d4f41cf307 - Time: 325ms

✔ Compiled successfully.
 `

**Comment by d3lm** [comment]
Hey there! This seems to work for me just fine. But we have also reverted a regression which affected terminal output. Can you try again and see if it works now for you?

**Comment by crissxross** [comment]
Hi - No, still not working but the result is different. Angular seems to be stuck in the compiling phase and the window loads a blank white view: 

![image](https://user-images.githubusercontent.com/5307070/140643768-ecd48ff3-456e-4b02-a750-5db89d033c7b.png)

Here's the terminal output:

`~/projects/eejgco--run
❯ npm install && turbo start
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 156.812s
┌ [2/3] 🚚  Fetching dependencies
│ info pruneDeps Excluding 14 dependencies. For more information use `--verbose`.
└ Completed in 8.315s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 3.933s
info security We found `install` scripts which turbo skips for security reasons. For more information see
https://turbo.sh/install-scripts.
├─ @angular/cli@12.2.13
├─ core-js@3.16.0
└─ esbuild@0.13.8
info Some packages were automatically replaced with polyfills. For more information see
https://turbo.sh/polyfills.
└─ esbuild@0.13.8 => esbuild-wasm@0.13.8

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 169.604s
$ ng serve
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
⠋ Generating browser application bundles (phase: setup)...    Project is attempting to disable the Ivy compiler. Angular versions 12 and higher do not support the deprecated View Engine compiler for applications. The Ivy compiler will be used to build this project. 
    For additional information or if the build fails, please see https://angular.io/guide/ivy
⠙ Generating browser application bundles (phase: setup)...Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
⠏ Generating browser application bundles (phase: sealing)...
`

**Comment by d3lm** [comment]
Can you provide a link? Cause when I click on the example from the docs it all works fine for me.

**Comment by d3lm** [comment]
Can you reproduce @SamVerschueren @jrvidal?

**Comment by jrvidal** [comment]
I cannot. @crissxross Do you get any error messages in the browser devtools console?

**Comment by SamVerschueren** [comment]
Can't reproduce either.

@crissxross Did you waited long enough? When looking at the terminal output, it looks like Angular wasn't done compiling everything and was still sealing the browser bundles. This is what you should see after it is done compiling and sealing.

![image](https://user-images.githubusercontent.com/1913805/140730802-4cb9e72d-7b0f-4d2a-a9d6-dde16e3f3d1b.png)

**Comment by crissxross** [comment]
@d3lm Here's a link - https://stackblitz.com/edit/kbhtka--run?file=src/app/sidenav-overview-example.ts

@SamVerschueren Yes, I waited a long time for the previous examples. It's actually been 20 minutes since I launched the link above and it's still stuck in same state as I reported [above](https://github.com/stackblitz/webcontainer-core/issues/382#issuecomment-962597226)

@jrvidal error message in browser console: `Fetch API cannot load stackblitz:/node_modules/%40angular/cli/lib/config/schema.json. URL scheme "stackblitz" is not supported.`

Here's all the console output:

`[@blitz/fetchers] [INFO] GitFetcher successfully initialized
fetch.worker.d83b9b15484f32317787d8c7cc41da5651102bdc.js:6 [@blitz/fetchers] [INFO] RegistryFetcher successfully initialized
12[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See <URL> for more details.
blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:11 [Contextify] [WARNING] running source code in new context
(anonymous) @ blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:11
7SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See <URL> for more details.
injected.min.js:7 Fetch API cannot load stackblitz:/node_modules/%40angular/cli/lib/config/schema.json. URL scheme "stackblitz" is not supported.
o @ injected.min.js:7
​ Compiling @angular/core : es2015 as esm2015
​ Compiling @angular/animations : es2015 as esm2015
​ Compiling @angular/cdk/keycodes : es2015 as esm2015
​ Compiling @angular/cdk/observers : es2015 as esm2015
​ Compiling @angular/animations/browser : es2015 as esm2015
​ Compiling @angular/common : es2015 as esm2015
​ Compiling @angular/platform-browser : es2015 as esm2015
​ Compiling @angular/cdk/platform : es2015 as esm2015
​ Compiling @angular/cdk/bidi : es2015 as esm2015
​ Compiling @angular/platform-browser/animations : es2015 as esm2015
​ Compiling @angular/cdk/a11y : es2015 as esm2015
​ Compiling @angular/forms : es2015 as esm2015
​ Compiling @angular/common/http : es2015 as esm2015
​ Compiling @angular/platform-browser-dynamic : es2015 as esm2015
​ Compiling @angular/material/core : es2015 as esm2015
DevTools failed to load source map: Could not load content for chrome-extension://hponfflfgcjikmehlcdcnpapicnljkkc/static/js/get-video-id.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://apjeljpachdcjkgnamgppgfkmddadcki/scripts/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**Comment by geromegrignon** [comment]
Hey @crissxross, did you delete the previous sample, I can't access it with the provided link?

**Comment by crissxross** [comment]
No I haven't deleted it. Here's the link again with display console:

https://stackblitz.com/edit/kbhtka--run?devtoolsheight=33&file=src/app/sidenav-overview-example.ts

**Comment by wallace41290** [comment]
FWIW, I am seeing the same issue on my machine. Just now I was looking at the Material tooltip: https://material.angular.io/components/tooltip/overview and clicked the stackblitz link for the basic tooltip.

Seems to get stuck on `Generating browser application bundles (phase: sealing)...`, and I waited at least 30 minutes.

**Comment by wallace41290** [comment]
ok, so (on Chrome) I did an "Empty Cache and Hard Reload", went back to the doc site, and clicked the stackblitz link and it is working now. I tried it on tooltip and list, both working.

**Comment by crissxross** [comment]
Yes, that worked for me too on Chrome. Thanks!

**Comment by rogerfar** [comment]
I have the same issue here:
https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-hr6m5c?file=src%2Fapp%2Fapp.component.html

Tried in both Edge and Chrome incognito windows, it hangs on `Installing dependencies` while the terminal window seems to work properly.

I attached the console log output (not terminal but the Chrome window).

[stackblitz.com-1637256450328.log](https://github.com/stackblitz/webcontainer-core/files/7564777/stackblitz.com-1637256450328.log)

[stackblitz.com-1637256688512.log](https://github.com/stackblitz/webcontainer-core/files/7564786/stackblitz.com-1637256688512.log)

Maybe the most interesting is:
```
_relay_:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://clarity-light-theme-clr12-cds5-hr6m5c.stackblitz.io/') with script ('https://clarity-light-theme-clr12-cds5-hr6m5c.stackblitz.io/_sw_.js'): The user denied permission to use Service Worker.
```

**Comment by jrvidal** [comment]
@rogerfar Might your issue be related to #405 ?

**Comment by rogerfar** [comment]
It must be yes, I tried on Chrome beta without privacy options enabled and it started worked.
