### ISSUE TITLE
right click for angular components not working

### ISSUE THREAD

**Issue by matruim** [stackblitz/webcontainer-core#384]
### Describe the bug

Right clicking in an angular app and the angular helper is not showing up.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-l4tuvq?file=angular.json

### Steps to reproduce

open an angular project
right click on the app folder
should see option to create angular components

### Expected behavior

right click on file should allow for angular components to be created

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111209829,
  "usedJSHeapSize": 101014437,
  "jsHeapSizeLimit": 2172649472
}
Hash = d83b9b15484f32317787d8c7cc41da5651102bdc
```

**Comment by jrvidal** [comment]
See https://github.com/stackblitz/webcontainer-core/issues/377
