### ISSUE TITLE
HMR broken in Astro Blog starter

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#386]
### Describe the bug

The Astro Blog Starter HMR seems to be broken, as file changes are not automatically updated in the preview window. The only way to see the changes is to hit the refresh button on the preview window.

The console log shows:

```
[14:28:31] [snowpack] File changed: projects/snowpackjs-astro-ckfow4/src/pages/index.astro
No parser for file type: astro
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/snowpackjs-astro-ckfow4?file=src%2Fpages%2Findex.astro

### Steps to reproduce

1. Go to [blitz](https://stackblitz.com/edit/snowpackjs-astro-ckfow4?file=src%2Fpages%2Findex.astro)
2. Edit `pages/index.astro` (e.g., insert some text into `<body>`), and save.
3. Observe the change does not affect the preview window.

### Expected behavior

HMR updates the preview window

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 124353493,
  "usedJSHeapSize": 121086405,
  "jsHeapSizeLimit": 4294705152
}
Hash = d83b9b15484f32317787d8c7cc41da5651102bdc
```

**Comment by d3lm** [comment]
I can't reproduce this. If I change something it gets properly reflected on the page.

![image](https://user-images.githubusercontent.com/12571019/140622905-f5576d98-694f-4cb4-ae03-bbda626bf0a5.png)

**Comment by tony19** [comment]
Interesting. It seems HMR doesn't update when the DevTools are open. With the DevTools closed, HMR does update, but slowly (3s after saving the change), and the result often doesn't match the actual change, as seen here:

<img width="836" alt="Screen Shot 2021-11-06 at 4 33 33 PM" src="https://user-images.githubusercontent.com/26580/140624506-beee6452-3e84-4b16-a3b5-e906015c289f.png">

**Comment by tony19** [comment]
Actually, I can also make it happen with DevTools closed:

![Kapture 2021-11-06 at 16 41 01](https://user-images.githubusercontent.com/26580/140624682-b11f8e26-69b0-4d1c-a712-393df8f9e6ec.gif)

**Comment by d3lm** [comment]
That's very strange indeed 🤔 I noticed the HMR is a bit slower, and I am wondering why. Though I can't reproduce that it won't update at all. I ll bring this to the attention of the team and we can see if we find something.

**Comment by tony19** [comment]
The latest version of the Astro Blog starter in StackBlitz does not exhibit this problem (however still reproducible in original blitz). No need to investigate. Thanks!
