### ISSUE TITLE
Right clicking but No Angular Generator appearing

### ISSUE THREAD

**Issue by dan1saipros** [stackblitz/webcontainer-core#388]
### Describe the bug

Right click on the app folder and use the Angular Generator to generate a new component

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-frehq4?file=src%2Fapp%2Fproducts.ts

### Steps to reproduce

right click on app
no angular generator appearing on the options

### Expected behavior

Angular Generator should appear as an option after right clicking on app

### Screenshots

![Screenshot from 2021-11-08 13-54-35](https://user-images.githubusercontent.com/87789561/140691233-a55fdb4f-86a7-4443-bb34-cc34957827af.png)

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82581751,
  "usedJSHeapSize": 79330967,
  "jsHeapSizeLimit": 4294705152
}
Hash = d83b9b15484f32317787d8c7cc41da5651102bdc
```

**Comment by jrvidal** [comment]
See https://github.com/stackblitz/webcontainer-core/issues/377
