### ISSUE TITLE
Framework support for RedwoodJS

### ISSUE THREAD

**Issue by ajcwebdev** [stackblitz/webcontainer-core#390]
**Describe the solution you'd like:**

RedwoodJS is a fullstack JavaScript framework built with React, Prisma, and Node. You can currently use it with [GitPod](https://community.redwoodjs.com/t/run-redwoodjs-on-gitpod/2303/14) which requires quite a bit of [GitPod YAML magic](https://github.com/redwoodjs/redwood/blob/main/.gitpod.yml). We're huge proponents of making Redwood as accessible to as many developers as possible and think that Stackblitz is a fantastic platform for enabling quick iteration and easy onboarding. Tom's also a [fan of Stackblitz](https://blog.stackblitz.com/posts/introducing-webcontainers/) as well 😉.

**Provide a link to a github repo containing an example of the framework:**

Here's a basic boilerplate Redwood app that just includes a home page and GraphQL API. The database is not being utilized at all which should help narrow the scope a bit:

https://github.com/ajcwebdev/redwood-stackblitz

For a full blown Redwood app check out:

https://github.com/thedavidprice/redwood-tutorial-test
https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#redwood-project-create-a-functional-test-project

**Additional context:**

When trying out the above repo I ran into a few issues with Yarn. Here's the Stackblitz link:

https://stackblitz.com/edit/node-kftktj

I'm seeing two different errors. First, it seems like it's installing the dependencies but failing on the linking step:

```
└ Completed in 85.854s
┌ [2/3] 🚚  Fetching dependencies
│ info pruneDeps Excluding 13 dependencies. For more information use `--verbose`.
└ Completed in 70.819s
┌ [3/3] 🔗  Linking dependencies
└ 𐄂 Failed
Error: EIO: failed to link packages

error Command failed with exit code 1
```

Also when trying to run Redwood commands I get an error telling me to use `turbo` instead of Yarn.

```
┌─ WARNING ───────────────────────────────────────────────────────────────────────────────┐
│ It seems you are trying to use `yarn`. This is a compatibility layer which uses `turbo` │
│ instead, a blazingly fast package manager designed for the web. If you wish to hide     │
│ this warning, you can do so by setting `warnings.yarn = false` inside                   │
│ "/home/.turbo/.turborc.json" or use `turbo` directly.                                   │
└─────────────────────────────────────────────────────────────────────────────────────────┘
ERR!: Unknown command `rw`

Try this: turbo --help

error Command failed with exit code 1
```

Let us know if there's anything we can do to help!

**Comment by jrvidal** [comment]
Hi @ajcwebdev , thanks for the report. Something is off with the turbo installation, we'll look into it.

However, Prisma cannot run on WebContainer given its reliance on: 
* Post-install scripts (which we [don't support](https://developer.stackblitz.com/docs/platform/turbo/#install-scripts)), and
* Native libraries (https://github.com/prisma/prisma-engines).

**Comment by ajcwebdev** [comment]
Gotcha, that makes sense and I'm not surprised to hear that. For now we can just work on getting the basic `web` and `api` sides setup without a database and then maybe in the future as WebContainers continue to progress we can collaborate with the Prisma team on compatibility.

**Comment by jrvidal** [comment]
@ajcwebdev Sorry we didn't get back to you promptly, but the turbo installation issue should be fixed now. Thanks for the report!
