### ISSUE TITLE
nothing is showing up in the browser view pane.

### ISSUE THREAD

**Issue by miridk** [stackblitz/webcontainer-core#401]
### Describe the bug

I never get anything showing in the browser view pane. I save and I update the view, but nothing happens.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-6rqxlk?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

follow the tutorial to the 2nd task and try to update the view.

### Expected behavior

I should see a list in the view box.

### Screenshots

![image](https://user-images.githubusercontent.com/93247832/141612416-4485a312-d981-4ea7-9076-186aa7c74eb1.png)

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111827792,
  "usedJSHeapSize": 101433884,
  "jsHeapSizeLimit": 2172649472
}
Hash = 320dd3b483ec8295ca1e4a3ccd95cf9e5165f9d0
```

**Comment by geromegrignon** [comment]
Hey @miridk, I can't reproduce it by opening the link:

![image](https://user-images.githubusercontent.com/32737308/141613013-c9014f91-815a-4ffc-a4cb-00b0f87d1a03.png)
