### ISSUE TITLE
Dont show the web container 

### ISSUE THREAD

**Issue by victorers** [stackblitz/webcontainer-core#404]
### Describe the bug

When I Fork the tutorial Angular from  ready-made sample project in StackBlitz. (https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html) only show the project but the preview is not charged

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-25y8wu?file=src%2Fassets%2Fshipping.json

### Steps to reproduce

1.-https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html
2.-log into stack blitz
3.- Fork the project you generated. 

### Expected behavior

![image](https://user-images.githubusercontent.com/68405401/141704460-4cacb77b-a867-4509-8037-6bf18d22d4bc.png)

### Screenshots

![image](https://user-images.githubusercontent.com/68405401/141704498-e17ad108-ccb2-4fa3-98b5-1c923b8016e3.png)

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 94680331,
  "usedJSHeapSize": 85902127,
  "jsHeapSizeLimit": 4294705152
}
Hash = 320dd3b483ec8295ca1e4a3ccd95cf9e5165f9d0
```

**Comment by firekoala** [comment]
same for me but on nodejs all the other platforms seem to work ;/

**Comment by jrvidal** [comment]
@firekoala Sorry I don't understand what you meant with "all the other platforms". Do you see any errors in the devtools console? Have you looked at #405?

**Comment by firekoala** [comment]
I meant frameworks. It works with every framework but the blank nodejs.
All the others load the container properly.

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
