### ISSUE TITLE
Running start command indefinitely

### ISSUE THREAD

**Issue by oaustegard** [stackblitz/webcontainer-core#405]
### Describe the bug

Attempting to run the Angular tutorial from https://angular.io/start in Chrome Version 95.0.4638.69
The code compiles successfully but the preview is stuck indefinitely at the "Running start command" level.

The browser console shows the following errors: 
> Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://angular-pyhjsn.stackblitz.io/') with script ('https://angular-pyhjsn.stackblitz.io/_sw_.js'): The user denied permission to use Service Worker.

and

> ​Fetch API cannot load stackblitz:/node_modules/%40angular/cli/lib/config/schema.json. URL scheme "stackblitz" is not supported.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-pyhjsn?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

In Chrome
1. Go to https://angular.io/start
2. Follow steps to start/fork StackBlitz tutorial
3. Observe above errors

### Expected behavior

Expect to see a preview of the Angular app

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101811547,
  "usedJSHeapSize": 91565639,
  "jsHeapSizeLimit": 4294705152
}
Hash = 320dd3b483ec8295ca1e4a3ccd95cf9e5165f9d0
```

**Comment by oaustegard** [comment]
This was caused by 3rd Party cookies being blocked. Allowing Stackblitz to set 3rd party cookies allowed the Serviceworker to be run and the preview to show.  It may be useful to check for that specific condition and provide a meaningful error message in the console? Better yet, find a way to NOT require 3rd party cookies.

**Comment by jrvidal** [comment]
@oaustegard We're aware of this error being confusing, we're working on it

**Comment by oaustegard** [comment]
Excellent - appreciate it.

**Comment by jrvidal** [comment]
@oaustegard We now have a friendlier error and some [documentation](https://developer.stackblitz.com/docs/platform/third-party-blocker/) about it :tada:
