### ISSUE TITLE
Angular tutorial project never loads

### ISSUE THREAD

**Issue by brian-cato-lab49** [stackblitz/webcontainer-core#407]
### Describe the bug

Angular tutorial project never loads but instead hangs at installing dependencies step. I waited 10 minutes once, 30 minutes a second time. Guess I'll go do a different tutorial.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=package.json

### Steps to reproduce

1. Go to https://stackblitz.com/run?file=src/app/app.component.ts

### Expected behavior

I can use StackBlitz

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62557170,
  "usedJSHeapSize": 59430142,
  "jsHeapSizeLimit": 4294705152
}
Hash = 16495809c277ab8697fd8fae8005569533001817
```

**Comment by jrvidal** [comment]
@brian-cato-lab49 hey, sorry for the troubles. Do you see any errors in the browser console? Could it perhaps be related to https://github.com/stackblitz/webcontainer-core/issues/405?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
