### ISSUE TITLE
./src/App.js Module not found: Can't resolve './App.css' in '/home/projects/node-r5tzyr/src'

### ISSUE THREAD

**Issue by ronykhanking** [stackblitz/webcontainer-core#409]
### Describe the bug

import './App.css';
import { BrowserRouter as Routes, Route } from 'router-dom';
import Login from './Com/Login/Login';

function App() {
  return (
    <div className="App">
      <Routes>
        <Route path="/login" element={<Login />} />
      </Routes>
    </div>
  );
}

export default App;

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-r5tzyr?file=package.json

### Steps to reproduce

Failed to compile
./src/App.js
Module not found: Can't resolve 'router-dom' in 'G:\friendshare\src'
This error occurred during the build time and cannot be dismissed.

### Expected behavior

  "dependencies": {
    "@testing-library/jest-dom": "^5.15.0",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.1.2"
  },

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 158978488,
  "usedJSHeapSize": 136585468,
  "jsHeapSizeLimit": 1098907648
}
Hash = 16495809c277ab8697fd8fae8005569533001817
```

**Comment by jrvidal** [comment]
@ronykhanking Thanks for the report! Looks like the blitz you linked no longer exists. Could you provide a new one?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
