### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Bobzilla07** [stackblitz/webcontainer-core#411]
### Describe the bug

When you click on favicon it will go to a grey screen to wich i have to right click then reload

### Link to the blitz that caused the error

https://stackblitz.com/edit/requests?file=static%2Ffavicon.ico

### Steps to reproduce

go to nuxt.js
click on favicon

### Expected behavior

it would show the favicon

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.114
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14150.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112530942,
  "usedJSHeapSize": 91501854,
  "jsHeapSizeLimit": 2020605952
}
Hash = 40159b6b13ba8403bf0ee8bb28e8b76409f29342
```

**Comment by jrvidal** [comment]
@Bobzilla07 Thanks for the report, this is definitely a bug.

**Comment by jrvidal** [comment]
This should be fixed now :tada: Please feel free to file more issues if you find anything else!
