### ISSUE TITLE
webcontainer does not refresh properly

### ISSUE THREAD

**Issue by BonjourYY** [stackblitz/webcontainer-core#412]
### Describe the bug

I've created a new node project and when I'm not connected to github, I can see the latest changes after I've changed the code and restarted the node server. But after I commit the code to github. No matter how much I refresh the code, I can't see the latest changes. It's as if I keep seeing the previous cache as it was. Also, before I commit to github, when I refresh the page, my modified code is lost. He will automatically become the code on github. This is annoying and I hope this bug can be fixed.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-vkb883?file=index.html

### Steps to reproduce

1. Run "node index 8888" to start the project
2. Modify the contents of the index.html file at will
3. save
4. Refresh the page, but you cannot see the result of the latest changes
5. Run the project again, still can't see the changed result

### Expected behavior

1. I want to be able to see the result of the changes after I have changed the code.
2. When we have already committed the code to github. At some point we need to change the project code, but I don't want to commit to github right away, I want the page to refresh when I click the save button and still look like I changed it, not like the code on github when we refresh the page.

### Screenshots

![1B6F05F0-1A03-4958-B411-A243704651A6](https://user-images.githubusercontent.com/42639257/142365436-2306adbc-f5a0-4fb8-80de-97bcd584aad9.png)

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44
performance.memory = {
  "totalJSHeapSize": 101007670,
  "usedJSHeapSize": 92429190,
  "jsHeapSizeLimit": 2172649472
}
Hash = f1851d58a79e8e7306fb558d46f360885ca58f96
```

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
