### ISSUE TITLE
webcontainer not working with nodejs

### ISSUE THREAD

**Issue by firekoala** [stackblitz/webcontainer-core#414]
### Describe the bug

WebContainer doesnt load on nodejs. it works on everything else but node ;((

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-thzdrc

### Steps to reproduce

open a new nodejs blank project

### Expected behavior
showing white loaded page of webcontainer

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 74493512,
  "usedJSHeapSize": 68362236,
  "jsHeapSizeLimit": 2172649472
}
Hash = 5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b
```

### Additional context

I tried it with chromium firefox and brave and its the same

**Comment by firekoala** [comment]
when i go https://developer.stackblitz.com/docs/platform/supported-frameworks and click on the nodejs <a href= "https://stackblitz.com/edit/nodejs-fz6ant"> demo</a> it works as intended to but whenever i try to create a project from the main site it doesnt load.
My new project : https://stackblitz.com/edit/node-aydvvv?file=index.html
Demo project : https://stackblitz.com/edit/nodejs-fz6ant

The only difference i see is that demo has "nodejs" in url while normal ones have "node".

**Comment by firekoala** [comment]
```
blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:8 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
_0xfeaf73 @ blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:8
DevTools failed to load source map: Could not load content for https://node-yzutm1.w.staticblitz.com/deps.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js.map: Connection error: net::ERR_SSL_PROTOCOL_ERROR
blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:8 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
_0x39699e @ blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:8
blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:8 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
_0x39699e @ blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:8
blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:8 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
_0x39699e @ blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:8
blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:11 [Contextify] [WARNING] running source code in new context
```

This is what i get in console after disabling all chrome extensions

**Comment by jrvidal** [comment]
@firekoala Thanks for the report. I see that you have linked a few projects. Could you be a bit more specific? Which one of those links does not work as expected?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
