### ISSUE TITLE
WebContainer does not start

### ISSUE THREAD

**Issue by shaozi** [stackblitz/webcontainer-core#418]
### Describe the bug

when loading the NodeJS stack in chrome, the panel on the right shows Booting WebContainer and is stuck.
and in the developer console, it shows 3 errors:

1.	Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute
1.	Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being set in a cross-site context. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
	Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
	Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests.
2.	AFFECTED RESOURCES
1.	2 cookies
1.	
Name	Domain & Path
ahoy_visitor	node-3sbord.stackblitz.io/
ahoy_visit	node-3sbord.stackblitz.io/
2.	1 request
1.	
_relay_

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-3sbord

### Steps to reproduce

1. goto stackblitz.com
2. click NodeJS blank project [BETA] 
3. See right panel booting webcontainer stuck

### Expected behavior

It should work

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 57728330,
  "usedJSHeapSize": 53810586,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b
```

**Comment by jrvidal** [comment]
@shaozi Thanks for the report!

It seems the blitz you linked no longer exists, could you link a new one? Also, could you share a screenshot of the developer console errors?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
