### ISSUE TITLE
BUG: `*` not working in jsh

### ISSUE THREAD

**Issue by ClassicOldSong** [stackblitz/webcontainer-core#42]
**Describe the bug**
`*` not working in jsh

**Link to the blitz that caused the error**

**To Reproduce**
``` shell
rm -r *
# rm: cannot remove '*': No such file or directory

mv aaa/* bbb
# mv: cannot stat 'aaa/*': No such file or directory
```

**Expected behavior**
Do what it should do

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KwintenP** [comment]
Hi!

🙏 for reporting. It's something that we haven't implemented yet. I'll add it to our internal tracker.

**Comment by d3lm** [comment]
Hey there 👋 This has been implemented now. Thanks for your patience 🙏
