### ISSUE TITLE
npm install does not accept -g (global)

### ISSUE THREAD

**Issue by ramonck** [stackblitz/webcontainer-core#423]
### Describe the bug

command: npm install -g @ionic/cli cordova-res

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-yvj7wm

### Steps to reproduce

go to terminal.
copy and paste the npm install command: npm install -g @ionic/cli cordova-res

### Expected behavior

accept install with global

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50
performance.memory = {
  "totalJSHeapSize": 58565405,
  "usedJSHeapSize": 51022537,
  "jsHeapSizeLimit": 2172649472
}
Hash = 5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b
```

**Comment by d3lm** [comment]
Hey! Yes, that's right, currently our npm client (turbo) doesn't support installing dependencies globally. However, you can use yarn to do that. Also, we are working on native npm support and post an update once that's done.

**Comment by jrvidal** [comment]
You can track native `npm` in https://github.com/stackblitz/webcontainer-core/issues/1070, thanks!
