### ISSUE TITLE
Its is not working after save

### ISSUE THREAD

**Issue by ManikandanR27** [stackblitz/webcontainer-core#424]
### Describe the bug

I go to material.angular.io and button toggle  ==> click om stackblitz from multiple selection is not working

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fbutton-toggle-mode-example.ts

### Steps to reproduce

I go to material.angular.io and button toggle  ==> click om stackblitz from multiple selection is not working

### Expected behavior

All issues

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.29
performance.memory = {
  "totalJSHeapSize": 96512652,
  "usedJSHeapSize": 90807256,
  "jsHeapSizeLimit": 4294705152
}
Hash = 19c34b6682252415afe6a0280c63a7c091453a84
```

**Comment by geromegrignon** [comment]
Hey @ManikandanR27, by `is not working`, can you please describe the behavior observed?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
