### ISSUE TITLE
Connect to github repository assumes master branch and fails

### ISSUE THREAD

**Issue by PuruVJ** [stackblitz/webcontainer-core#427]
### Describe the bug

When I click on the Connect to git repository, import a repo, it assumes master branch, tries to get it, and fails. My default branch is main.

I think the default branch should be considered in the github integration

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-4iheam

### Steps to reproduce

Go to the URL
Wait for it to try and load

### Expected behavior

Stackblitz should not assume default branch as master, and should get the default branch

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 83505490,
  "usedJSHeapSize": 72264658,
  "jsHeapSizeLimit": 2172649472
}
Hash = 4a765956abf077f03ded84a27eb9cf5e3bfff5ad
```

**Comment by tony19** [comment]
Duplicate of #195

**Comment by PuruVJ** [comment]
Thanks! I will stay on top of that issue
