### ISSUE TITLE
Remix with github just keeps loading.

### ISSUE THREAD

**Issue by ramonck** [stackblitz/webcontainer-core#429]
### Describe the bug

The hot realoding stopped working and the github just keeps on spinning, I guess the github is causing bugs with the hot reloading feature from remix.

### Link to the blitz that caused the error

https://stackblitz.com/edit/mechain

### Steps to reproduce

Open the  stackblitz and start making modifications with the remix and github loaded.

### Expected behavior

hot reloading still working. (which is not working)

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50
performance.memory = {
  "totalJSHeapSize": 321347988,
  "usedJSHeapSize": 299688172,
  "jsHeapSizeLimit": 2172649472
}
Hash = 4a765956abf077f03ded84a27eb9cf5e3bfff5ad
```

**Comment by d3lm** [comment]
Hey there! Yes, we are actively working on a git cli and it will be entirely reworked for webcontainer. We keep you posted.

**Comment by d3lm** [comment]
The project linked doesn't really work and there's quite some issues with the project. I have tested the latest version of remix which seems to work. I don't really know what "Remix with GitHub" means. This needs more info, and maybe you can update your project to the latest version to rule out some issues from 1 year ago.
