### ISSUE TITLE
jsh: command not found: astro

### ISSUE THREAD

**Issue by TMorgan99** [stackblitz/webcontainer-core#432]
### Describe the bug

I just opened the starter example from astro,

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/snowpackjs/astro/tree/latest/examples/starter)

But I don't think it installed correctly.

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-v6jvwi?file=package.json

### Steps to reproduce

- Click on the Open in StackBiltz button.
- I patched the ./src/pages/index to refer to the 'css' and not the 'scss' files that don't exist.
- npm run dev
- 

### Expected behavior

Well the starter example should at least start.

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.98
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS armv7l 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.98 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77224290,
  "usedJSHeapSize": 72435678,
  "jsHeapSizeLimit": 1031536640
}
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

### Additional context

Thanks for looking at this,
Im hoping that  StackBlitz could be a great option for the team!

**Comment by jrvidal** [comment]
@TMorgan99 Thanks for the report. Do you still see the issue when you enter your newly created blitz? I can't seem to reproduce.

https://user-images.githubusercontent.com/1636604/143554359-83d07e72-8590-4710-a673-637d04104ede.mp4

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
