### ISSUE TITLE
angular: can not create new component with ng generate component componentName

### ISSUE THREAD

**Issue by Marko2509** [stackblitz/webcontainer-core#434]
### Describe the bug

when i run this command or ng g c componentName it says that everything is created but this changes are not visible in file tree on the left side

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

1. open terminal and run this command

### Expected behavior

to see something change 😄 

### Screenshots

.

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89296982,
  "usedJSHeapSize": 68231202,
  "jsHeapSizeLimit": 4294705152
}
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

**Comment by jrvidal** [comment]
@Marko2509 Thanks for the report.

The URL you provided (`/run?...`) is used by a POST API, so it's useless by itself (as clicking it does not take you anywhere). Could you share the original link (I presume, from an Angular tutorial) that you clicked to arrive to StackBlitz? Even better, you could fork the project and provide a reproduction based on that.

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
