### ISSUE TITLE
Remix new application displays upgrade required message after launch

### ISSUE THREAD

**Issue by Lance1997** [stackblitz/webcontainer-core#435]
### Describe the bug

Started a new Remix application and after packages were installed, on the first run. The preview of the application showed an upgrade required message. I tried stopping the server and restarting the dev server and still the same message showed

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-nyjcyz?file=package.json

### Steps to reproduce

1. Go to stackblitz.com
2. Sign In
3. On new projects tab, select Fullstack
4. Select Remix Nodejs
5. Wait for application packages to install and visit the preview link by opening in new window
6. Make a couple of file changes to see if the change is reflected.

### Expected behavior

See the remix default homepage template and also new content change in the files.

### Screenshots

![screenshot-nimbus-capture-2021 11 26-19_44_11](https://user-images.githubusercontent.com/52635726/143624904-5d2e38f9-8d33-4e8b-8a69-c29760bf5b81.png)
![screenshot-nimbus-capture-2021 11 26-19_42_41](https://user-images.githubusercontent.com/52635726/143624907-5012b021-7914-4432-aebf-639d48f54079.png)

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 175608495,
  "usedJSHeapSize": 170245907,
  "jsHeapSizeLimit": 2079850496
}
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

**Comment by tony19** [comment]
This issue is similar to #341. See https://github.com/stackblitz/webcontainer-core/issues/341#issuecomment-936290408 for explanation.

The "Upgrde required" message is only temporary, and the real site eventually renders.

**Comment by jrvidal** [comment]
@Lance1997 Does the comment in https://github.com/stackblitz/webcontainer-core/issues/341#issuecomment-936290408 clarify things? Do you observe the site being rendered correctly after waiting enough?

**Comment by Lance1997** [comment]
> @Lance1997 Does the comment in [#341 (comment)](https://github.com/stackblitz/webcontainer-core/issues/341#issuecomment-936290408) clarify things? Do you observe the site being rendered correctly after waiting enough?

Yes it does clarify it, I just tried it now and after a couple of minutes, it did render the site. I guess maybe we need a note somewhere on the site or IDE that makes this message quite clear else might lead to more unnecessary issues like this.

Thanks for the fast response.
