### ISSUE TITLE
Kindly give support for mozilla browser

### ISSUE THREAD

**Issue by santhoshkumar-27** [stackblitz/webcontainer-core#437]
### Describe the bug

Hey, I am a beginner in angular, so I'm trying to do the sample work on stackblitz it shows the browser "Incompatible Web Browser

WebContainers currently work in Chrome and Chromium-based browsers. We’re hoping to add support for more browsers as they implement the necessary Web Platform features."

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

Go to https://angular.io/start
Select the Getting Started --> Try it --> Getting started --> create a sample project
click the ready-made sample project in StackBlitz

### Expected behavior

It should display  browser content

### Screenshots

![Screenshot (93)](https://user-images.githubusercontent.com/90305985/143743029-4531ae81-0b77-49e0-bb75-ba7f8ea1ada9.png)

### Platform

```
Browser name  = Firefox 
Full version  = 94.0
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
performance.memory = undefined
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

**Comment by jrvidal** [comment]
@santhoshkumar-27 Thanks for the report. We have a detailed explainer of our browser support [here](https://developer.stackblitz.com/docs/platform/browser-support). We'll try to keep that up to date with our progress.

**Comment by Nemikolh** [comment]
Hi @santhoshkumar-27 ! :wave: 

Support for Firefox has been in beta for quite some time now :tada: We'll keep improving the support but I think we can close this ticket for now. Feel free to reopen if there's something in particular that you think is missing!
