### ISSUE TITLE
Broken link on blog

### ISSUE THREAD

**Issue by JeremyJaydan** [stackblitz/webcontainer-core#44]
**Describe the bug**
A broken link in the interweb between the latest blog post and this repository.

**To Reproduce**
1. open browser
2. navigate to [this blog post](https://blog.stackblitz.com/posts/introducing-webcontainers/)
3. smile
4. scroll down to the bottom
5. click on 'core WebContainer WG repo' link

**Expected behavior**
I expected to be transported from the blog page to the repo page

**Screenshots**
![image](https://user-images.githubusercontent.com/15324232/119151019-90557800-ba81-11eb-9fe0-721f4fccc8a0.png)

**Additional context**
the exact broken link is `https://github.com/stackblitz/webcontainer-core/blob/main/Add_support_for_a_framework.md`

**Comment by SamVerschueren** [comment]
Oh snap! Good catch! We renamed some files and that's probably why they broke. Thanks for reporting 🙏 !  We will fix ASAP.

**Comment by SamVerschueren** [comment]
Oh, it's already fixed :)!
