### ISSUE TITLE
Stackblitz Error in Firefox

### ISSUE THREAD

**Issue by Trend20** [stackblitz/webcontainer-core#445]
### Describe the bug

I am trying to open this Angular application: [link](https://angular.io/generated/live-examples/router-tutorial/stackblitz.html ) but it fails to run and says that the browser is incompatible. What might be the problem?

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.html

### Steps to reproduce

Click the link.
Navigate to the new tab where the application is opened.
Test the application.

### Expected behavior

When I click the application link, it should open the live application on Stackblitz editor. But instead, it does not.

### Screenshots

![stackblitz](https://user-images.githubusercontent.com/47891932/143833365-57a7ea19-548a-4364-bcbe-2bee5ea835a0.png)

### Platform

```
Browser name  = Firefox 
Full version  = 94.0
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
performance.memory = undefined
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

**Comment by jrvidal** [comment]
@Trend20 Thanks for the report. Closing in favor of https://github.com/stackblitz/webcontainer-core/issues/437
