### ISSUE TITLE
[Feature proposal] Enhanced moderation experience

### ISSUE THREAD

**Issue by geromegrignon** [stackblitz/webcontainer-core#446]
On a regular basis, there are issues ending closed for not providing any content. Among them, there are 2 common ones:

- issues created without body content
- issues opened with the framework support template without filling it

Such issues just waste the maintainer's time and energy.

## Proposal

I would like to help you by adding GitHub features to help with moderation through a pull request

### Move framework template to Issue Forms

GitHub released a Issue Forms feature earlier this year.
It leverages the Issue Templates by enforcing the way to fill an issue with proper input fields.

It allows requiring some information for the issue to be opened.
By moving the current Framework Issue Template to a Issue Form one with the required restriction on the framework name, it would mitigate some empty issues.

Here is an example: https://github.com/angular/angular/issues/new?assignees=&labels=&template=1-bug-report.yaml

### Add a GitHub Action to automate closing empty issues

By creating a GitHub Action on the project, we could trigger a dedicated workflow when an issue is opened to check the body content. If empty, the related GitHub Action can close the issue.

Tagging you @jrvidal as you are one of the most active members triaging issues.

**Comment by jrvidal** [comment]
This is an interesting idea @geromegrignon. Do you want to take a stab at creating that template?

**Comment by geromegrignon** [comment]
Sure, I'm used to creating such templates. I'll create a pull request to showcase it.

**Comment by geromegrignon** [comment]
closing as merged

**Comment by d3lm** [comment]
Thanks @geromegrignon ❤️ 🙏
