### ISSUE TITLE
Incompatible Web Browser on Android 11 Tablet

### ISSUE THREAD

**Issue by six-edge** [stackblitz/webcontainer-core#447]
### Describe the bug

Using the Vanilla Vite template on a Samsung Galaxy S7 and latest chrome browser.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-3scisj

### Steps to reproduce

1. Open stackblitz vite vanilla template on a Galaxy S7 tablet running Android 11

### Expected behavior

Should be compatible on Android Chrome.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
See: https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 11; SM-T733) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76714720,
  "usedJSHeapSize": 74691680,
  "jsHeapSizeLimit": 907804672
}
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

### Additional context

Would be super awesome if this would work on this tablet as I want to start a new Nuxt project after buying a course in Mastering Nuxt, but unfortunately when I open a new Stackblitz app template for Nuxt it says this browser is not supported, although it seems the required technologies are available in Android Chrome.

**Comment by rayfoss** [comment]
Same issue on Android 12, Pixel 6, Chrome

`User agent: Mozilla/5.0 (Linux; Android 12; Pixel 6 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4756.0 Mobile Safari/537.36 EdgA/98.0.1107.0`

https://tests.caniuse.com/?feat=cors Pass
https://tests.caniuse.com/?feat=sharedarraybuffer Pass

**Comment by jrvidal** [comment]
Thanks for the report. Could you folks paste the result of:

```javascript
console.log(navigator.userAgent);
console.log(window.SharedArrayBuffer);
console.log(navigator.serviceWorker);
```

**Comment by six-edge** [comment]
I setup the chrome remote debugger and confirmed that window.SharedArrayBuffer is not available. After checking the compatibility table again here there is a Asterix in the Chrome Android column stating that `SharedArrayBuffer` is gated behind COOP/COEP. For more detail, read Making your website "cross-origin isolated" using COOP and COEP...

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#browser_compatibility  

![image](https://user-images.githubusercontent.com/42222405/150651271-23a831b6-7483-4976-bde9-bf79fc20f974.png)

Quoted from this page: https://developer.chrome.com/blog/enabling-shared-array-buffer/#in-brief

> SharedArrayBuffer is currently supported in Firefox 79+, and will arrive in Android Chrome 88. However, it's only available to pages that are cross-origin isolated.

Seems there may be some headers that need to be set to enable the `SharedArrayBuffer` feature:

```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

Console output from the remote debugging session from a Galaxy S7 tablet running Android 11:

![image](https://user-images.githubusercontent.com/42222405/150651432-83d24bd7-c5c8-453a-9d8f-e4e548ab8a37.png)

### References
- https://developer.chrome.com/blog/enabling-shared-array-buffer/#in-brief
- https://developer.chrome.com/blog/enabling-shared-array-buffer/#cross-origin-isolation
- https://web.dev/coop-coep/

**Comment by six-edge** [comment]
If you solve this problem for Chrome Android I **promise to pay for a membership** as this would be amazing if it works on my tablet. I use it in the evening while my computer is sleeping in the bedroom with my daughter. Hmm so I'm stuck with this tablet. I managed to hack the tablet a bit to install VS Code and Node.JS on it using Termux and it works ok, but it's not ideal and a bit clunky. I would love to use stackblitz and when it works I will definitely upgrade to test your GitHub private repos (beta) feature too. Having said that if it's still in beta, I will happily test it for you if you give me a test account ⚡👉😃

**Comment by jrvidal** [comment]
@six-edge Thanks, we do have a limitation in our browser support that prevents SB from running in Chrome mobile. This issue is in our roadmap so I'll keep this updated with our progress, though I can't offer a concrete timeline.

Thanks!

**Comment by six-edge** [comment]
Thanks @jrvidal really looking forward to this working 🚀

**Comment by rayfoss** [comment]
@six-edge FIrefox for Android is real firefox... however it also has the same COEP header requirement as Chrome for Android. It should be relatively easy to run an nginx reverse proxy on the tablet in Termux and search and replace all references to stackblitz.io, then inject the COEP headers. I won't have time to try it this week, but I recon it can be done by a skilled hobbyist in an hour-ish.

**Comment by amalbenny** [comment]
👍🏼 +1

**Comment by six-edge** [comment]
This is working now on a Samsung Galaxy S7 Android Tablet!

Amazing! I've been waiting a while for this. Stackblitz team rocks!!!

**Comment by SamVerschueren** [comment]
I guess we can close this issue now? Android (Chrome and Firefox) should be supported. Please feel free to create a new issue if something doesn't work correctly.
