### ISSUE TITLE
After dependency installation - terminal UI hangs

### ISSUE THREAD

**Issue by cliffordfajardo** [stackblitz/webcontainer-core#448]
### Describe the bug

After the dependencies for my code sandbox finishes and I try to type in the terminal, the terminal input doesn't work, which prevents me from typing in the command to start my web app.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-3xxt8m?file=src%2Fapps%2Fexample5%2FExample5.tsx

### Steps to reproduce

1. Visit stackblitz sandbox
2. Wait for dependencies to be installed
3. Attempt to type into terminal prompt to start dev server

### Expected behavior

The terminal prompt should allow me to type text into it if the cursor is present and blinking

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.55
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 164811752,
  "usedJSHeapSize": 122818184,
  "jsHeapSizeLimit": 4294705152
}
Hash = f0f0e35d34e6f38828752db79b041c48b98806b5
```

**Comment by jrvidal** [comment]
@cliffordfajardo Thanks for the report, we're looking into this.

**Comment by jrvidal** [comment]
@cliffordfajardo Sorry we did not get back to you on time, but this should be fixed now! :tada:  Thanks for the report.
