### ISSUE TITLE
BUG(?): imported TypeScript libs don't seem inferred

### ISSUE THREAD

**Issue by KATT** [stackblitz/webcontainer-core#45]
**Describe the bug**
imported TypeScript libs don't seem inferred

**Link to the blitz that caused the error**
https://stackblitz.com/github/trpc/trpc/tree/main/examples/next-prisma-starter?file=pages%2Fapi%2Ftrpc%2Fposts.ts

**To Reproduce**
1. Go to https://stackblitz.com/github/trpc/trpc/tree/main/examples/next-prisma-starter?file=pages%2Fapi%2Ftrpc%2Fposts.ts
2. Hover over `postsRouter`
3. See type def

**Expected behavior**

Should have typescript definition

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

### StackBlitz screenshot

infers type `any`

![Screenshot 2021-05-21 at 17 01 34](https://user-images.githubusercontent.com/459267/119158348-689cea80-ba56-11eb-99cc-215ad24d80a5.png)

### CodeSandbox Screenshot

infers correct type

https://codesandbox.io/s/github/trpc/trpc/tree/main/examples/next-prisma-starter?file=/pages/api/trpc/posts.ts
![Screenshot 2021-05-21 at 17 01 42](https://user-images.githubusercontent.com/459267/119158305-5e7aec00-ba56-11eb-88af-377b79e38ed5.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 138985846,
  usedJSHeapSize: 132344770,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by SamVerschueren** [comment]
Thanks for trying things out @KATT 🙏 ! We are aware of this and it's in the pipeline to fix soon.

**Comment by jrvidal** [comment]
This should be fixed now :tada: Thanks for the report.
