### ISSUE TITLE
Auto-enable Dynamic Imports for CJS files in Next.js projects

### ISSUE THREAD

**Issue by EricSimons** [stackblitz/webcontainer-core#450]
### Describe the bug

Next.js has started using dynamic imports in CJS files, which is causing certain Next.js projects to fail.

### Link to the blitz that caused the error

https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-i18n-next-intl

### Steps to reproduce

For example, here is one of their official examples that is now breaking: https://github.com/vercel/next.js/tree/canary/examples/with-i18n-next-intl

And here's the working version w/ `ENABLE_CJS_IMPORTS` flag turned on: https://stackblitz.com/edit/github-8ezthy?file=.stackblitzrc

### Expected behavior

IMO we should auto enable CJS imports if we detect a certain project is using Next.js (or even better, somehow generically check files for dynamic import statements before evaluation).

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.55
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 59243069,
  "usedJSHeapSize": 55549529,
  "jsHeapSizeLimit": 4294705152
}
Hash = 381d8e23c5bf5b1d29278d4e63be21122d702b6e
```

**Comment by SamVerschueren** [comment]
I believe we can close this now? As CJS is enabled by default.
