### ISSUE TITLE
Live Preview after Connecting to GitHub broken & files added by npm do not allow commit

### ISSUE THREAD

**Issue by TomSmedley** [stackblitz/webcontainer-core#453]
### Describe the bug

Live Preview will no longer work after connecting to Github.

https://user-images.githubusercontent.com/95056193/144142171-25b5c60c-00ac-4ac8-900d-85601324290b.mp4

### Link to the blitz that caused the error

https://stackblitz.com/edit/james-lowe?file=src%2Fcomponents%2FDownArrow.svelte

### Steps to reproduce

1. Create a project in my case Astro.
2. Commit to Github.
3. Live Preview no longer functions.
4. Reloading the editor after a commit shows new content, but Live Preview continues not to function, 
5. Use something like npm build, the new files do not register and commit isn't an option.

### Expected behavior

Live Preview should show a Live Preview.

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 162489478,
  "usedJSHeapSize": 155393854,
  "jsHeapSizeLimit": 4294705152
}
Hash = 381d8e23c5bf5b1d29278d4e63be21122d702b6e
```

**Comment by jpmayorga** [comment]
i got the same error, any solution?

**Comment by TomSmedley** [comment]
Nope, I asked for a refund because it was stopping me using StackBlitz in the way it's intended. If it was a video game, it would be considered a game breaking bug. I just got ignored about that request, but the community manager said they will be looking at this issue early next year.

In my personal opinion, StackBlitz is an absolutely brilliant idea but it shouldn't offer membership until the actual membership functionality works.

**Comment by fvsch** [comment]
Hi @TomSmedley @jpmayorga, we just shipped a fix for this issue. Sorry for the delay!
