### ISSUE TITLE
Angular CLI uses Node worker API which doesn't exist yet in WebContainer

### ISSUE THREAD

**Issue by zdrawku** [stackblitz/webcontainer-core#456]
### Describe the bug

Error is returned on build of WebContainer app.

[This post](https://github.com/stackblitz/core/issues/1657#issuecomment-984403159) provide additional explanation and context that can help you to identify the problem:

https://github.com/stackblitz/core/issues/1657#issuecomment-984403159

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-i1jikx-bv1ygj?file=src%2Fstyles.scss

### Steps to reproduce

1. Open the referenced sample
2. Wait for the project to build
3. Observe the returned error:

```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.

2 │ @use 'igniteui-angular/theming' as *;
```

### Expected behavior

The project to load without problems

### Platform

- OS: all
- Browser: all
- Version: latest

**Comment by markwhitfeld** [comment]
There is a PR in progress to fall back when using WebContainers 🎉 
https://github.com/angular/angular-cli/pull/22294

PS. We are looking into solutions to provide this API in the long term.

**Comment by markwhitfeld** [comment]
The WebContainer version should be working since the 3.1.0 release of Angular (which is more compatible with currently supported WC apis):
https://stackblitz.com/edit/angular-i1jikx-jy8ix9?file=package.json
