### ISSUE TITLE
Open-sourcing for the webplatform ?

### ISSUE THREAD

**Issue by abflow** [stackblitz/webcontainer-core#458]
**Is your feature request related to a problem? Please describe:**

 It would be great if any website could have its own "WebOS" and be able to launch their own "Web Containers" in order to have offline-first backend applications directly working into the browser.

**Describe the solution you'd like:**

Is there any plan on open-sourcing the technology or to begin a standardization process which would allow more actors in the industry to participate to a collective project ?

**Describe alternatives you've considered:**

Would [deno](https://deno.land/) be a better choice than node.js as a wasm component (as deno is built in Rust which is directly compilable to wasm and has a nodejs compatibility layer) ?

**Additional context:**

The idea of `Trusted Desktop Activity` has been suggested since november 2018 in the chromium repo.

Some similar ideas from [the issue in chromium repo](https://bugs.chromium.org/p/chromium/issues/detail?id=907525):
>One could even compile nodejs to webassembly and run node into the browser with special authorizations for example running node in sandboxed VM mode or allowing access to hard drive only for some user-defined paths for example.

>A permissions-based security model similar to the one in Deno could be configured by the user into the browser UI when installing the web application

**Comment by milahu** [comment]
> alternatives

- [browsix](https://github.com/plasma-umass/browsix) - Unix-like operating system for the browser. outdated

**Comment by jrvidal** [comment]
We don't have any immediate plans to open source WebContainers, beyond the API client library in [@webcontainer/api](https://www.npmjs.com/package/@webcontainer/api).

This might or might not change in the future, but I'm closing this issue for now, as it's not really actionalbe/trackable. If/when that happened, I'm pretty sure that we would make a lot of noise in https://blog.stackblitz.com/ and other venues.

Thanks for the suggestion!

**Comment by sanandnarayan** [comment]
just for educational purposes
https://github.com/RealSput/Wenode/blob/main/dist/wenode.js
