### ISSUE TITLE
problem with github

### ISSUE THREAD

**Issue by brayden10** [stackblitz/webcontainer-core#460]
### Describe the bug

when i save the project to gethub  i get 
Error: src/app/product-alerts/product-alerts.component.html:1:11 - error TS2339: Property 'product' does not exist on type 'ProductAlertsComponent'.

1 <p *ngIf="product && product.price > 700">
            ~~~~~~~

  src/app/product-alerts/product-alerts.component.ts:5:16
    5   templateUrl: './product-alerts.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ProductAlertsComponent.

Error: src/app/product-alerts/product-alerts.component.html:1:22 - error TS2339: Property 'product' does not exist on type 'ProductAlertsComponent'.

1 <p *ngIf="product && product.price > 700">
                       ~~~~~~~

  src/app/product-alerts/product-alerts.component.ts:5:16
    5   templateUrl: './product-alerts.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ProductAlertsComponent.

Error: src/app/product-list/product-list.component.html:12:23 - error NG8002: Can't bind to 'product' since it isn't a known property of 'app-product-alerts'.
1. If 'app-product-alerts' is an Angular component and it has 'product' input, then verify that it is part of this module.
2. If 'app-product-alerts' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

12   <app-product-alerts [product]="product"> </app-product-alerts>
                         ~~~~~~~~~~~~~~~~~~~

  src/app/product-list/product-list.component.ts:7:16
    7   templateUrl: './product-list.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ProductListComponent.

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✖ Failed to compile.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2021-12-03T21:56:42.224Z - Hash: 8d392117166e3213 - Time: 585ms

Error: src/app/product-alerts/product-alerts.component.html:1:11 - error TS2339: Property 'product' does not exist on type 'ProductAlertsComponent'.

1 <p *ngIf="product && product.price > 700">
            ~~~~~~~

  src/app/product-alerts/product-alerts.component.ts:5:16
    5   templateUrl: './product-alerts.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ProductAlertsComponent.

Error: src/app/product-alerts/product-alerts.component.html:1:22 - error TS2339: Property 'product' does not exist on type 'ProductAlertsComponent'.

1 <p *ngIf="product && product.price > 700">
                       ~~~~~~~

  src/app/product-alerts/product-alerts.component.ts:5:16
    5   templateUrl: './product-alerts.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ProductAlertsComponent.

Error: src/app/product-list/product-list.component.html:12:23 - error NG8002: Can't bind to 'product' since it isn't a known property of 'app-product-alerts'.
1. If 'app-product-alerts' is an Angular component and it has 'product' input, then verify that it is part of this module.
2. If 'app-product-alerts' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

12   <app-product-alerts [product]="product"> </app-product-alerts>
                         ~~~~~~~~~~~~~~~~~~~

  src/app/product-list/product-list.component.ts:7:16
    7   templateUrl: './product-list.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ProductListComponent.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-skn8yk?file=src%2Fapp%2Fproduct-alerts%2Fproduct-alerts.component.ts

### Steps to reproduce

save to github
refresh 

### Expected behavior

should work when saved 

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.55
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 107504685,
  "usedJSHeapSize": 93715661,
  "jsHeapSizeLimit": 2172649472
}
Hash = 6c82f838340a5d37c50f004ca724bcc8f75bc71c
```

**Comment by SamVerschueren** [comment]
Hi @brayden10. I just tested the project you shared and I'm not able to reproduce this issue. We did some fixes to the GitHub integration in the mean time so it might be that it got resolved a while ago. Feel free to create a new issue if you run into something like this again.
