### ISSUE TITLE
App never loads

### ISSUE THREAD

**Issue by bryan-sullivan-ascendlearning-com** [stackblitz/webcontainer-core#463]
### Describe the bug

The commands in the terminal appear to run correctly, but the app never loads in the side sheet. The "Running Start Command" icon doesn't stop spinning.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/table-wrapped-example.ts

### Steps to reproduce

- Go to https://material.angular.io/components/table/examples (version 13.0.2 is the current version).
- Click on example labelled "Table example that shows how to wrap a table component for definition and behavior reuse." which takes you to https://stackblitz.com/run?file=src/app/table-wrapped-example.ts.
- The application never loads in the right frame.

### Expected behavior

The application should load.

### Screenshots

![stackblitz-bug](https://user-images.githubusercontent.com/47981595/144895120-8c806136-ee72-4e3d-acc9-c885605bf0b1.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 106239349,
  "usedJSHeapSize": 101245401,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6c82f838340a5d37c50f004ca724bcc8f75bc71c
```

### Additional context

- This same issue happens for all StackBlitz examples I try to load from https://material.angular.io/ (version 13.0.2).
- mVersion 12.2.13 and below don't use WebContainer and load correctly.

### Text from terminal:

~/projects/bwdwsp--run
❯ npm install && turbo start
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 1.497s
┌ [2/3] 🚚  Fetching dependencies
│ info pruneDeps Excluding 13 dependencies. For more information use `--verbose`.
└ Completed in 7.298s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 6.188s
info security We found `install` scripts which turbo skips for security reasons. For more information see https://turbo.sh/install-scripts.
├─ @angular/cli@13.0.0-rc.2
├─ core-js@3.19.0
└─ esbuild@0.13.9
info Some packages were automatically replaced with polyfills. For more information see https://turbo.sh/polyfills.
└─ esbuild@0.13.9 => esbuild-wasm@0.13.8

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 15.536s
$ ng serve
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   5.38 MB
polyfills.js          | polyfills     | 336.76 kB
styles.css, styles.js | styles        | 296.74 kB
main.js               | main          |  37.28 kB
runtime.js            | runtime       |   6.86 kB

                      | Initial Total |   6.04 MB

Build at: 2021-12-06T17:38:31.880Z - Hash: 945c61afad166da4 - Time: 37589ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Compiled successfully.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2021-12-06T17:38:32.708Z - Hash: 945c61afad166da4 - Time: 468ms

✔ Compiled successfully.

**Comment by jrvidal** [comment]
@bryan-sullivan-ascendlearning-com Thanks for the report. I cannot reproduce, I'm able to see the iframe loading. Do you see any suspicious errors in the devtools console? Could it be related to [3rd party cookie blockers](https://developer.stackblitz.com/docs/platform/third-party-blocker)?

**Comment by bryan-sullivan-ascendlearning-com** [comment]
Thanks for the suggestions. It looks like the WebContainer resources are being blocked by my company. I'm closing this bug with this comment.
