### ISSUE TITLE
133333333333333333

### ISSUE THREAD

**Issue by onePersonInDemo** [stackblitz/webcontainer-core#466]
### Describe the bug

22222

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-nwmyn5?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev

### Steps to reproduce

333333333333333

### Expected behavior

333

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109108074,
  "usedJSHeapSize": 86800762,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6c82f838340a5d37c50f004ca724bcc8f75bc71c
```

### Additional context

2222222222222222

**Comment by geromegrignon** [comment]
Please fill the template with proper information to explain your issue.
So far, without any additional context, the Stackblitz project linked works as expected.

Without any effort from your side, this issue will more likely be closed.
