### ISSUE TITLE
Share button issue

### ISSUE THREAD

**Issue by guillemsarda** [stackblitz/webcontainer-core#468]
### Describe the bug

When I click on the share button, the browser (on the right) that you provide stops working. If I try to do some changes, it does not respond.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-hnvjmg?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

1. Arrive at step 7 of the Angular Tutorial.
2. Do step 7.
3. Go to any of the "Share" buttons.
4. Click on the button.
5. Click "OK" on the alert.
6. Change button's name.
7. Does not update the information.

### Expected behavior

I expect that after I click on the "OK" button, I will be able to change its name (or whatever feature I want to add).

### Screenshots

<img width="1917" alt="Captura de Pantalla 2021-12-08 a les 15 18 42" src="https://user-images.githubusercontent.com/88349941/145223892-bf1c0f42-7c14-4fa5-967d-e5549732665f.png">

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93952248,
  "usedJSHeapSize": 88933688,
  "jsHeapSizeLimit": 2172649472
}
Hash = 6c82f838340a5d37c50f004ca724bcc8f75bc71c
```

### Additional context

I am in this [tutorial](https://angular.io/start).

**Comment by Nemikolh** [comment]
Hi @guillemsarda! :wave: 

I don't seem to be able to reproduce this issue anymore. Is it something you are still able to produce in the last version of the editor?

**Comment by guillemsarda** [comment]
It seems to be working fine. Thanks!✌🏼
