### ISSUE TITLE
Forking a project does not update the URL in the preview panel

### ISSUE THREAD

**Issue by socsieng** [stackblitz/webcontainer-core#47]
**Describe the bug**

When forking a project, the URL in the preview panel isn't updated to reflect the URL of the new fork. Therefore, modifications to the project are not reflected in the preview panel.

The workaround is to refresh the entire screen.

**Link to the blitz that caused the error**

https://stackblitz.com/edit/nextjs-bw83rd?file=pages%2Findex.js

**To Reproduce**
1. Go to https://stackblitz.com/edit/nextjs-bw83rd?file=pages%2Findex.js
2. Click on the fork button
3. Notice that the project name changes, but the URL in the preview panel doesn't
4. Make changes to the content in `index.js`
5. Notice that the changes made to `index.js` aren't reflected in the preview

**Expected behavior**

The preview panel URL should be updated to reflect the new forked project and any subsequent changes to `index.js` should be applied to the preview.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 90.0.4430.212

**Additional context**

N/A

**Comment by bruno-oliveira** [comment]
I'll have a look at this!

**Comment by KwintenP** [comment]
Hi, 

🙏 for reporting this. We do need to update the url when this happens. 
I can't repro the changes to `index.js` not being reflected after forking though.

Can you provide reliable steps to reproduce?

**Comment by socsieng** [comment]
I was testing this out by adding more exclamation marks to the `h1`, however, I'm no longer able to reproduce.

The only thing outstanding now is the URL in the preview window.

**Comment by jrvidal** [comment]
@socsieng  This is most likely related to https://github.com/stackblitz/webcontainer-core/issues/209, which we fixed by reloading the page on forking (for Node projects).

Thanks for the report! Please feel free to open more issues if you find something else.
