### ISSUE TITLE
Agular "ng serve" not working

### ISSUE THREAD

**Issue by marcoalesan** [stackblitz/webcontainer-core#475]
### Describe the bug

Page doesn´t load

### Link to the blitz that caused the error

https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html

### Steps to reproduce

At the very bigining of the sample proyect

### Expected behavior

Load the page 

### Screenshots

![image](https://user-images.githubusercontent.com/39069314/145682470-437ec977-62ef-4b42-a7a6-298604a259da.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86323059,
  "usedJSHeapSize": 68518543,
  "jsHeapSizeLimit": 2172649472
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

### Additional context

I'm trying to use the AGULAR expample from official site
https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html

**Comment by jrvidal** [comment]
@marcoalesan Thanks for the report. This issue is probably an upstream problem, see https://github.com/stackblitz/webcontainer-core/issues/473
