### ISSUE TITLE
Web Crypto API not detected correctly?

### ISSUE THREAD

**Issue by developit** [stackblitz/webcontainer-core#48]
**Describe the bug**
Attempting to use zlib's brotli or gzip compression seems to generate an error like:
`Cannot read property `constants` of undefined.`

Looking into the stack, this seems to happen because initialization of the zlib module fails due to `crypto.randomBytes()` being unavailable. Looking into why that would be the case, it seems like the detection for the Web Crypto API is attempting to access `self.crypto`:
```
<snip> "object"==typeof self)self.crypto&&self.crypto.getRandomValues ? <snip>
```

... unfortunately, `self` has been set to `undefined` (not sure why). Paused at that callsite however, `global.crypto` does exist.

https://stackblitz.com/edit/node-zewtyo?file=package.json

**To Reproduce**
1. Go to https://stackblitz.com/edit/node-zewtyo?file=package.json
2. Run `npm start` (or directly, `node ./node_modules/.bin/wmr`)
3. See error:

    <img width="1093" alt="Screen Shot 2021-05-21 at 12 51 16 PM" src="https://user-images.githubusercontent.com/105127/119171965-4fcf0d80-ba33-11eb-825b-bde5306aeaf2.png">

**Expected behavior**
`global.crypto` is used, there is no error, and importing zlib returns zlib.

**Screenshots**
<img width="857" alt="Screen Shot 2021-05-21 at 12 49 42 PM" src="https://user-images.githubusercontent.com/105127/119171800-0f6f8f80-ba33-11eb-867d-85395b4055d5.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser:  Chrome 91.0.4472.57

**Comment by SamVerschueren** [comment]
Hi @developit , cool to see you trying out WebContainer 🙏! Currently the crypto APIs are lacking a lot of features. It's most likely the first thing we are going to tackle to bring this on par and offer all capabilities.

So I'm sorry you run into this, but we'll do our best to tackle this soon!

**Comment by d3lm** [comment]
Hey 👋 The original issue seems to be resolved but this is down to the lack of `brotli` support. We are tracking this internally but can't speak to an exact timeline for this to land.

**Comment by d3lm** [comment]
Related issue for missing brotli support #339.

**Comment by jrvidal** [comment]
We recently added Brotli support and this now works! :tada:
