### ISSUE TITLE
Angular "Getting Started Tutorial" need to update typescript

### ISSUE THREAD

**Issue by UmbertoBagnati** [stackblitz/webcontainer-core#480]
### Describe the bug

I was trying to follow the tutorial at [https://angular.io/start](url) but i get an error on "ng serve" command.

To solve open a new terminal and paste: `npm install typescript@4.4.2`

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

1. Go to: [https://angular.io/start](url)
2. Click on:  "ready-made sample project in StackBlitz"
3. Get the error:  "(node:6) UnhandledPromiseRejectionWarning: Error: The Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.3 was found instead"

### Expected behavior

Expected to load the application as on the tutorial

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 100388809,
  "usedJSHeapSize": 95088993,
  "jsHeapSizeLimit": 4294705152
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

**Comment by jrvidal** [comment]
@UmbertoBagnati Thanks for the report. This seems to be an upstream issue, see https://github.com/stackblitz/webcontainer-core/issues/477 and https://github.com/stackblitz/webcontainer-core/issues/473
