### ISSUE TITLE
None of the Angular sample apps work

### ISSUE THREAD

**Issue by danrald** [stackblitz/webcontainer-core#482]
### Describe the bug

The sample apps for Angular found on this page do not work in Stackblitz.

sample list:
https://angular.io/guide/example-apps-list

Trying to run these, we get the following error:
 The Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.4 was found instead.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

1. Go the page that caused the error
2. Wait for the error

### Expected behavior

The sample application runs

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96137981,
  "usedJSHeapSize": 90822061,
  "jsHeapSizeLimit": 4294705152
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

**Comment by jrvidal** [comment]
@danrald Thanks for the report. This seems to be an upstream issue, see #477 and #473
