### ISSUE TITLE
Angular project not working

### ISSUE THREAD

**Issue by riccardorinaldi7** [stackblitz/webcontainer-core#487]
### Describe the bug

Hi, I'm sorry for the generic title but I couldn't guess what happened.
I opened an autogenerated Angular project linked in Angular documentation. At the beginning the compiler detected code changes and worked fine but at one point, apparently without reasons (certainly without errors in the terminal or in the code), the application stopped working. The compiler stopped to compile after my changes and the right pane, where you see the rendered web page, was no longer refreshed. I tried to refresh the page manually but it didn't work and also click on the "Open in New Window" button wasn't helpful.

The project stopped working after 5 or 6 changes in the code.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/tree-checklist-example.ts

### Steps to reproduce

1. Go to [angular documentation page](https://material.angular.io/components/tree/examples)
2. In the first example (Tree with checkboxes) click on "Edit example on Stackblitz" button (a square with an arrow pointing up right)
3. Change the code
4. The compiler should update the page and the right pane should be refreshed
5. Change the code again
6. After some changes the compiler stopped working

### Expected behavior

The compiler should detect changes in the code and should recompile it, refreshing the right page showing the rendered page

### Screenshots

![image](https://user-images.githubusercontent.com/35295021/146027344-4f6f921a-bf33-48c0-9c6b-94781edb6fd4.png)

![image](https://user-images.githubusercontent.com/35295021/146027397-ac463b2d-34b6-45c4-993c-14d865aaa729.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 126141041,
  "usedJSHeapSize": 122201233,
  "jsHeapSizeLimit": 4294705152
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

**Comment by devendran1** [comment]
Same issue for me too.

**Comment by SamVerschueren** [comment]
I know this is a pretty old issue. I just tried this out and I can't seem to get it to break. We released quite some updates and improvements to WebContainers over the previous months/years. So maybe this got fixed in the mean time?

Let's close this issue. Don't hesitate to create a new issue if you still run into this issue 🙏 .
