### ISSUE TITLE
Add support for payment in the preview iframe

### ISSUE THREAD

**Issue by socsieng** [stackblitz/webcontainer-core#49]
**Is your feature request related to a problem? Please describe.**

It would be great if the preview iframe included support for the payment request handler so that projects that make use of it can function correctly.

For instance, clicking the Google Pay button in the [example](https://stackblitz.com/edit/nextjs-nakdbt?file=pages%2Findex.js) while in the preview launches a new tab/window which is a workaround for when the payment request isn't supported. Ideally, the behavior should match the experience if you open the content in its own window (e.g. by clicking the _Open in new window_ link) which shows a modal dialog (on Chrome)

**Describe the solution you'd like**

My proposed solution is to include [`payment`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#:~:text=payment) to the iframe's `allow` attribute. This will allow the payment handler to be triggered by the content of the iframe.

**Describe alternatives you've considered**

My current workaround is to do some detection in the code and include instructions for the user to open the window in a new tab.

Example: https://stackblitz.com/edit/nextjs-nakdbt?file=pages%2Findex.js

**Additional context**

Clicking on the Google Pay button in the preview tab launches the payment sheet in a new window (not desirable behavior).

Clicking on the Google Pay button in its own window launches the payment sheet in a modal window (expected behavior on Chrome)

Previous feature request: https://twitter.com/aussoc/status/1359219567600390145

**Comment by SamVerschueren** [comment]
Oh, this is very interesting! Thanks for opening the bug report 🙏 ! You are right, we will have to allow it. If you directly update the iframe with an `allow="payment"` attribute in the dev console, it seems to work fine. This shouldn't be hard to add :).

**Comment by EricSimons** [comment]
Also @socsieng if you click the "open in new window" at the top of the page this should also fix the problem, as it's no longer running in an iframe :)

**Comment by socsieng** [comment]
> Also @socsieng if you click the "open in new window" at the top of the page this should also fix the problem, as it's no longer running in an iframe :)

Yes, I'm aware. However, I included the instruction in the demo because I don't think many developers will know that the button behaves differently in a new window/preview. If the button behaves correctly, then I can remove the prompt altogether.

**Comment by SamVerschueren** [comment]
I created an internal PR to fix this. Not sure when it will land though. Probably Monday, latest.

**Comment by SamVerschueren** [comment]
@socsieng alright, should be live 😀 !

**Comment by socsieng** [comment]
Thanks for the quick turnaround @SamVerschueren.

Do you know if this will also be applied to non webcontainer instances in StackBlitz?

See https://stackblitz.com/edit/google-pay-react for example.

**Comment by SamVerschueren** [comment]
It's a different part of the project so should be fixed separately. I'll see if I can take a look at it today or maybe tomorrow. Feel free to ping me back if you haven't heard anything from me at the end of the week.

**Comment by SamVerschueren** [comment]
@socsieng It should be live for non-webcontainer projects now as well 🙏 .

**Comment by socsieng** [comment]
Thanks for the update @SamVerschueren.

I did some initial testing and found that it isn't working in Chrome 90.0.4430.212.

From what I can tell, the `allow` attribute is set to `geolocation; microphone; camera; payment;` which looks correct, however, when compared to the web-container version `geolocation; microphone; camera; payment`, the only difference is the trailing `;`. When I remove the trailing semicolon from the `allow` attribute, and reload the iframe, it works as expected.

The ask is to remove the trailing semicolon.

I'm happy to file a separate issue. Is there a repo or a separate process to do this?

**Comment by SamVerschueren** [comment]
Mmm, this is super weird. I tested this before I deployed it to production but when trying it again now, it doesn't seem to work. I'll fix it 👍 .

**Comment by SamVerschueren** [comment]
@socsieng I tried fixing it, and although it seemed to work on our staging environment, it doesn't work on production. I have no clue what's going on (yet). Could you maybe create a new issue for it in https://github.com/stackblitz/core? That's where we track issues for non-WebContainer projects.

**Comment by socsieng** [comment]
Will do. Thanks.
