### ISSUE TITLE
Generating browser application bundles (phase setup) for more than 3 hours

### ISSUE THREAD

**Issue by DayakarMalgari** [stackblitz/webcontainer-core#490]
### Describe the bug

I was trying to fork the  ready-made sample project in StackBlitz under the "getting started with Angular", and for the past 3 hours its been sitting in the setup phase of the "Generating browser application bundles".

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-1v3vql?file=package.json

### Steps to reproduce

[Angular_StackBlitz_bug.txt](https://github.com/stackblitz/webcontainer-core/files/7717647/Angular_StackBlitz_bug.txt)

### Expected behavior

I want to execute ng serve --o command. Its not letting me do anything.

### Screenshots

![image](https://user-images.githubusercontent.com/88380811/146151371-7b6d4623-beeb-4c03-bbb8-98d033a5624a.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 99457772,
  "usedJSHeapSize": 93521780,
  "jsHeapSizeLimit": 2172649472
}
Hash = 731360fb19d99dfc563f19370095b1e3465a14ed
```

**Comment by jrvidal** [comment]
@DayakarMalgari Thanks for the report, I suspect this is an upstream issue, see https://github.com/angular/angular/issues/44480 and https://github.com/stackblitz/webcontainer-core/issues/473. Please, do comment if that does not apply to your problem.
