### ISSUE TITLE
error Command failed with exit code 1

### ISSUE THREAD

**Issue by notsozen** [stackblitz/webcontainer-core#492]
### Describe the bug

can't resolve dependencies

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fapp.module.ts

### Steps to reproduce

open the the URL

### Expected behavior

find all depencencies

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 71581865,
  "usedJSHeapSize": 68202761,
  "jsHeapSizeLimit": 2172649472
}
Hash = a3339ebb87d0fe73c7995fe67420660e0dc95de2
```

**Comment by jrvidal** [comment]
@notsozen Thanks for the report. The URL you provided is actually for a POST request, so we can't recover the blitz where you encountered the problem. Could you share the original link you clicked, that redirected to that URL?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
