### ISSUE TITLE
saving changes (leading to forked stackblitz) breaks static asset image serving

### ISSUE THREAD

**Issue by thescientist13** [stackblitz/webcontainer-core#493]
### Describe the bug

Noticed that if I made changes to a blitz, thus causing a fork, and then re-ran the same `npm start` command, that the image in the header was not loading anymore.

### Link to the blitz that caused the error

https://stackblitz.com/github/ProjectEvergreen/greenwood-getting-started

### Steps to reproduce

1. Load the blitz
1. Run `npm start`.  Observe the dev server starts and you can see the Greenwood logo in the header
    ![Screen Shot 2021-12-15 at 9 15 09 PM](https://user-images.githubusercontent.com/895923/146295660-321b2058-927f-4692-bc65-ae52eafe389b.png)
1. Make and save any change to a file (like editing the `name` field in _package.json_)
   ![Screen Shot 2021-12-15 at 9 15 39 PM](https://user-images.githubusercontent.com/895923/146295727-ca4a1a9e-343f-4e64-b367-0e00e70bb999.png)
1. This will cause a fork
1. Run the `npm start` command again, now the image in the header is not loading
    ![Screen Shot 2021-12-15 at 9 16 11 PM](https://user-images.githubusercontent.com/895923/146295754-02a2d438-1e9d-4cb6-b30d-d161b2ddd720.png)

### Expected behavior

It would be great if the image continued to load.  😃 

### Screenshots

Provided in the _Steps to reproduce_ section 👆 

### Platform

- OS: macOS
- Browser: Chrome
- Version: 96

### Additional context

The image is referenced in a folder called _/assets_ and is served by a simple Koa server from _src/components/header/header.js_.

Not sure if this is related to #208 ?

I can make as many changes as I want and keep running `npm start` and everything is fine, but as soon as I save and get into a fork, the image loading breaks.

----

Thanks in advance for any help / guidance!

**Comment by kc0tlh** [comment]
@thescientist13 thanks for submitting this report! As you determined, this is the same underlying issue as #677 so I will close this report, and we can follow #677 for updates. Cheers!
