### ISSUE TITLE
Connect Repository button is mislabled

### ISSUE THREAD

**Issue by rayfoss** [stackblitz/webcontainer-core#495]
### Describe the bug

Connect repository means connect Github... I was hopping to connect a Gitlab, Gitter, Bitbucket, Gitorious, or Azure cloud git repository.

Also, the button is far far too prominent for an optional third-party integration feature. The ability to integrate with Github is not the most important part of my Sandbox.
![Screenshot from 2021-12-16 15-40-35](https://user-images.githubusercontent.com/876076/146453140-45321e71-f81b-410f-b64e-abca0c110367.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/feathersjs-xanga1

### Steps to reproduce

Load any repository not connected to Github

### Expected behavior

- Irrelevant distractions should be minimized.

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.55
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43
performance.memory = {
  "totalJSHeapSize": 131971230,
  "usedJSHeapSize": 84479778,
  "jsHeapSizeLimit": 4294705152
}
Hash = a3339ebb87d0fe73c7995fe67420660e0dc95de2
```

### Additional context

Workaround

- Ublock origin:  
```
! 2021-12-17 https://stackblitz.com
##button:has([class*=firebase_svg_])
stackblitz.com##.git-info
```

**Comment by HeyGarrison** [comment]
Thanks for the feedback @rayfoss ❤️ 

Closing this as we have some other issues planned you'll be pretty excited about that'll help address this.
