### ISSUE TITLE
Angular project not updating when linked to github repo

### ISSUE THREAD

**Issue by Collin2245** [stackblitz/webcontainer-core#496]
### Describe the bug

angular project is not building or dynamically updating when project is linked to github repo.
### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-bffu9e?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.ts

### Steps to reproduce

follow this tutorial
https://angular.io/guide/setup-local
angular project does update when forked, but does not when connected to github repo.
### Expected behavior

expected to dynamically update with code changes, update html for example when connected to repo

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 133597939,
  "usedJSHeapSize": 124725283,
  "jsHeapSizeLimit": 4294705152
}
Hash = a3339ebb87d0fe73c7995fe67420660e0dc95de2
```

**Comment by stepanic** [comment]
I can confirm the same issue, it is not Angular specific, it seems that every project after connection to the GIT repo stops updating.

The current workaround to see changes is to save edited files and manually refresh the browser (which is annoying :D)
