### ISSUE TITLE
[FR] Share line number

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#497]
**Is your feature request related to a problem? Please describe:**
It's hard to find the line people are talking about without external information

**Describe the solution you'd like:**
Right click on the line number to share a reference to it. `&line=70`

**Describe alternatives you've considered:**
Praying. It didn't work.

**Additional context:**
I'm trying to reference line 70 of this 100 line behemoth, I really don't want anyone to read 60 lines of boilerplate.
https://stackblitz.com/edit/feathersjs-7kqlyt?file=server.js

**Comment by SamVerschueren** [comment]
This actually works now in our classic editor.

https://stackblitz.com/edit/feathersjs-7kqlyt?file=server.js%3AL13-L16
