### ISSUE TITLE
Node-RED support

### ISSUE THREAD

**Issue by zuhito** [stackblitz/webcontainer-core#499]
### Describe the bug

WebContainer is a great environment to use [Node-RED](https://nodered.org/), Low code programming tool because Katacoda or GitPod environments are limited in terms of the time and lost flow that users developed. But there is some problem to show the development UI.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-lwdex7

### Steps to reproduce

1. Type the following commands on the terminal.
```
npm install node-red
node node_modules/node-red/red.js
```
2. Click the "Open in New Window" button to show Node-RED flow editor.
3. Positions of some UI components are incorrect. Especially, deploy button.

### Expected behavior

Users can see in-corrupted UI in the Node-RED flow editor.

### Screenshots

<img width="1024" alt="スクリーンショット 2021-12-19 3 53 00" src="https://user-images.githubusercontent.com/6851138/146653131-2ebfa9ee-9df5-4f0c-b023-b12d3cc9db6e.png">

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54248970,
  "usedJSHeapSize": 52273526,
  "jsHeapSizeLimit": 2172649472
}
Hash = a3339ebb87d0fe73c7995fe67420660e0dc95de2
```

### Additional context

There is another problem with the http request node. When the node accesses external REST API on the Internet, the Node-RED process is crashed. I think that WebContainer doesn't support `got` module.

**Comment by joelml** [comment]
Hi!
I got Node-RED working by using another start command than you did. I could also click Deploy and test a simple timestamp and I got a successful message in the debug component.

My start command was:
`./node_modules/.bin/node-red`

Does that help for you @zuhito ?

**Comment by HeyGarrison** [comment]
@joelml could you link to you a project that @zuhito could fork by chance?

@zuhito the project you linked to doesn't seem to have any files besides the basic node files. If the problem persists could you link to a new starter?
