### ISSUE TITLE
BUG: Installing node modules as global via npm fails 

### ISSUE THREAD

**Issue by neo773** [stackblitz/webcontainer-core#50]
---
name: Bug report
about: jsh syntax error when installing npm package as global
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
I'm unable to install any node modules as global via npm. I keep getting syntax error
`Unknown Syntax Error: Command not found; did you mean one of:`

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-vutu3g?file=README.md

**To Reproduce**

**Expected behavior**

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 136726149,
  usedJSHeapSize: 130206821,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by KwintenP** [comment]
Hi, 

We currently don't support installing npm packages as global. The reason for this is a little nuanced. What does global even mean in the context of stackblitz. Would you want it to be available in all of your blitz's? What about collisions in that case where you install a global version which collides with a local dependency.

It's considered a bad practice to install global packages so we might never support it. To get your use case to work, please install the dep as a `devDependency` and use `npx ${commandName}` to run the command. This will look up the binary in the `node_modules/.bin` folder.

**Comment by SamVerschueren** [comment]
There's an update on this one though https://github.com/stackblitz/webcontainer-core/issues/96#issuecomment-848962891.

We now hoist binary files from `node_modules/.bin` directly to your terminal so in a Next.js project you can now run `next dev` and it will work 🎉 .
