### ISSUE TITLE
aman allam

### ISSUE THREAD

**Issue by CanMehmetK** [stackblitz/webcontainer-core#504]
### Describe the bug

not running

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-dh948x?file=src%2Fapp%2Fapp.component.html

### Steps to reproduce

https://angular.io/guide/i18n-example

live example

### Expected behavior

run

### Screenshots

![image](https://user-images.githubusercontent.com/1278985/147359178-164c926f-06af-4f36-b964-433a15ce26ff.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
performance.memory = {
  "totalJSHeapSize": 104551291,
  "usedJSHeapSize": 96703471,
  "jsHeapSizeLimit": 4294705152
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

### Additional context

no comment

**Comment by SamVerschueren** [comment]
Closing in favour of #509
