### ISSUE TITLE
Angular V13 i18n example project broken - Locale data for 'baseHref' cannot be found.  No locale data will be included for this locale.

### ISSUE THREAD

**Issue by ultrasonicsoft** [stackblitz/webcontainer-core#506]
### Describe the bug

The URL for [Angular i18n example](https://angular.io/guide/i18n-example) is broken with below error.
```
Locale data for 'baseHref' cannot be found.  No locale data will be included for this locale.
An unhandled exception occurred: Unsupported translation file format in /home/projects/scebts--run. The following parsers were tried:
*** ArbTranslationParser ***
*** SimpleJsonTranslationParser ***
WARNINGS:
 - File does not have .json extension.
*** Xliff1TranslationParser ***
*** Xliff2TranslationParser ***
*** XtbTranslationParser ***
WARNINGS:
 - Must have xtb or xmb extension.
See "/tmp/ng-Ow1Q7F/angular-errors.log" for further details.
```

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

1. Go to https://angular.io/guide/i18n-example
2. Click on "live example" link
3. Let the StackBlitz load the project and start "ng serve" command

### Expected behavior

The application should start with any errors.

### Screenshots

<img width="911" alt="Screenshot 2021-12-26 at 09 34 01" src="https://user-images.githubusercontent.com/4145169/147398562-091f0128-6aaa-404a-9d00-459b004f019a.png">

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 75516240,
  "usedJSHeapSize": 72693848,
  "jsHeapSizeLimit": 4294705152
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

**Comment by SamVerschueren** [comment]
Could we continue this conversation in #509? I can't get this to work locally either. Can you give it a try perhaps?
