### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by orsoxii** [stackblitz/webcontainer-core#507]
### Describe the bug

where is it ? (firefox)

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-vfzw4m?devtoolsheight=33

### Steps to reproduce

just try to see the terminal on stackblits
`error`

### Expected behavior

you cant see it

### Platform

```
Browser name  = Firefox 
Full version  = 95.0
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; lubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
performance.memory = undefined
computer.ver = 20.04
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

### Additional context

no additional context

**Comment by geromegrignon** [comment]
Hey @orsoxii,

As showcased in the preview part, `WebContainers currently work in Chrome and Chromium-based browsers.``

![image](https://user-images.githubusercontent.com/32737308/147469881-3ee39380-350d-460b-990f-d660488fa793.png)

**Comment by orsoxii** [comment]
yeah but how you enable it?

**Comment by SamVerschueren** [comment]
If you click the `Read more about browser support` link and scroll down you can find [a section on how to enable it in Firefox](https://developer.stackblitz.com/docs/platform/browser-support/#testing-on-firefox). You can also read why it currently doesn't work in Firefox/Safari if you're interested.

It's experimental and not everything might/will work out-of-the-box. If you want it to work out-of-the-box, you will need a chromium based browser.
