### ISSUE TITLE
Locale data for 'baseHref' cannot be found.  No locale data will be included for this locale.

### ISSUE THREAD

**Issue by jamalsahri** [stackblitz/webcontainer-core#509]
### Describe the bug

Locale data for 'baseHref' cannot be found.  No locale data will be included for this locale.
An unhandled exception occurred: Unsupported translation file format in /home/projects/angular-agnmjy. The following parsers were tried:
*** ArbTranslationParser ***
*** SimpleJsonTranslationParser ***
WARNINGS:
 - File does not have .json extension.
*** Xliff1TranslationParser ***
*** Xliff2TranslationParser ***
*** XtbTranslationParser ***
WARNINGS:
 - Must have xtb or xmb extension.
See "/tmp/ng-6ULYl3/angular-errors.log" for further details.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-agnmjy?file=angular.json

### Steps to reproduce

Click on https://angular.io/guide/i18n-example ->"live example"
start "ng serve" command

### Expected behavior

The app should start without any problem

### Screenshots

![i18n-bug](https://user-images.githubusercontent.com/41706336/147478915-4307ec90-09da-4ba7-91c5-be6dbbae4f2b.PNG)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79102320,
  "usedJSHeapSize": 75648532,
  "jsHeapSizeLimit": 4294705152
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

**Comment by SamVerschueren** [comment]
Are you able to run this locally? the `Locale data for 'baseHref' cannot be found` message is also shown on local. But the red error on local is even worse.

![image](https://user-images.githubusercontent.com/1913805/147598286-e36a6f6a-5b17-4b93-ac77-2705ca8ad9da.png)

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
