### ISSUE TITLE
BUG: cannot importing private repo

### ISSUE THREAD

**Issue by gauravpan** [stackblitz/webcontainer-core#51]
---
name: cannot importing private repo
about: Create a report to help us improve
title: ''cannot import github repo
---

while importing error box says : 
       Error: Could not resolve reference "refs/heads/master".

clicking to top of files tab redirects to [repo link]/tree/null

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-afxmy2

**To Reproduce**

**Expected behavior**
Just to import github repo

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 63660623,
  usedJSHeapSize: 56307547,
  jsHeapSizeLimit: 2172649472
}

**Additional context**

**Comment by KwintenP** [comment]
Hi!

This is currently only supported on our paid plan: https://stackblitz.com/membership.
