### ISSUE TITLE
Remix starter kit fork is unable to save, progress lost on refresh

### ISSUE THREAD

**Issue by blankey1337** [stackblitz/webcontainer-core#511]
### Describe the bug

Using the remix-app-template, I am unable to persist my file changes past page refresh.

If I click Save, the loading icon spins for a while, and eventually I can hit Save again. Despite that, changes never save so I am unable to use this awesome template.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-qpuswh?file=app%2Froot.tsx

### Steps to reproduce

1. go to stackblitz.com and click Fullstack then Remix
2. make any changes
3. save your changes and refresh the page. 
4. OBSERVE: A warning prompt appears asking you to confirm you want to leave, if you leave, your changes will be lost. Indeed, if you click OK then changes are not persisted.

### Expected behavior

Changes should auto-save and should never be lost on page refresh ideally.

### Platform

```
Browser name  = Chrome (Brave - shields disabled)
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 166227163,
  "usedJSHeapSize": 148300723,
  "jsHeapSizeLimit": 4294705152
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

### Additional context

love stackblitz!!

**Comment by HeyGarrison** [comment]
Thanks for reporting @blankey1337! We shipped a fix for this. Feel free to re-open if for some reason you still have an issue. ❤️
