### ISSUE TITLE
.stackblitzrc start command has no effect in official Vite starter

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#512]
### Describe the bug

Setting the start command via `.stackblitzrc` in a Vite starter has no effect. The container starts with `npm install && npm run dev` regardless of the config.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-ztdh63?file=.stackblitzrc&terminal=dev

### Steps to reproduce

1. Go to blitz (created from `https://vite.new/vue`)
2. Allow to start up.
3. Observe the start command in the terminal is `npm install && npm run dev` instead of `npm run build` (configured in `.stackblitzrc`).

### Expected behavior

The configured start command is run instead of the default.

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 138505472,
  "usedJSHeapSize": 88110992,
  "jsHeapSizeLimit": 4294705152
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

**Comment by SamVerschueren** [comment]
Hi @tony19 👋 !

It is taken into account, the thing her eis that the queryparam `terminal` overwrites the `startCommand` in the `.stackblitzrc` file.

Is the URL https://vite.dev/vue incorrect? It doesn't seem to work on my end 🤔 ? I'm trying to see if we made a mistake somewhere in setting up the URLs?

**Comment by tony19** [comment]
That was a typo in the URL. It should've been https://vite.new/vue.

Ah, you're right about the `terminal` query param, which I didn't even notice. I usually just copy the address bar without looking. I'm assuming it's added to the URL based on something I select. How exactly was that added? Thanks

**Comment by SamVerschueren** [comment]
I believe it's added when redirected from https://vite.new/vue so we can run the start command by default when opened. This way we don't have to infer the start command based on some heuristics that detect the framework as that would be quite error prone. So I think we decided to just add the `terminal` query param. If you then add a `.stackblitzrc` and refresh, it wil not work. Not sure if there's anything we can improve here? It makes sense that the query param gets presedence over the `startCommand` in the config file to make it overwriteable.

**Comment by tony19** [comment]
Ok, I see. A `.stackblitzrc` baked into the starter would also avoid having to heuristically detect the framework, and probably would've prevented my confusion here (not complaining). However, I'm not necessarily looking for a change here. I just thought it was a bug. Thanks anyway!

**Comment by SamVerschueren** [comment]
@sulco do you know if these projects come from GitHub directly or do we own them ourselves? If we own them, we might want to add a `.stackblitzrc` instead of working with query params. If they are coming from a GitHub repository, they might not want to add a platform agnostic config file?

**Comment by EricSimons** [comment]
Projects created via vite.new come directly from Vite’s main GitHub repo, which don’t include stackblitzrc configs. Maybe we could add them in at import time though? Or do heuristic based defaults for frameworks? I’d personally be in favor of the latter
