### ISSUE TITLE
BUG: "UnknownError The user denied permission to access the database." when opening using incognito

### ISSUE THREAD

**Issue by kdfriedman** [stackblitz/webcontainer-core#52]
---![image](https://user-images.githubusercontent.com/37988868/119187816-d5f54f00-ba47-11eb-9daf-e4d0c30c21a8.png)name: Bug report
about: Create a report to help us improve
title: 'Received UnknownError The user denied permission to access the database.' when opening project in incognito tab via Google Chrome.
labels: ''
assignees: ''

---

**Describe the bug**
I received an error when attempting to open a nodejs StackBlitz project in an incognito tab via Google Chrome. When I open the url via incognito, I see the StackBlitz message, 'Unable to connect to local.webcontainer.io', which I'd expect. However, when selecting the open button or project title link, a new window opens with an error, `'UnknownError The user denied permission to access the database'`.

**Link to the blitz that caused the error**
https://express-in-browser--5000.local.webcontainer.io/

**To Reproduce**
1. Go to https://express-in-browser--5000.local.webcontainer.io/
2. Click on either 'Open Project' or option 1 with your project title link.
3. Open up console in new window

**Expected behavior**
User project should open with no non-logged in state.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

<img width="1275" alt="Screen Shot 2021-05-21 at 3 16 32 PM" src="https://user-images.githubusercontent.com/37988868/119187857-e0afe400-ba47-11eb-83f8-b0180f85e24e.png">
**Desktop (please complete the following information):**![image](https://user-images.githubusercontent.com/37988868/119187816-d5f54f00-ba47-11eb-9daf-e4d0c30c21a8.png)Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 53737633,
  usedJSHeapSize: 51401537,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by KwintenP** [comment]
Hi!

🙏 for reporting. This does seem like a bug on our end!

**Comment by mdwyer6** [comment]
I'm getting the same error while trying to use the JS SDK@1.5.2

**Comment by HeyGarrison** [comment]
Hi @umairhm! 

It looks like we successfully shipped a fix for this. Here is my example: https://express-in-browser-hvwpdp--5000.local.webcontainer.io/

Feel free to let us know if you have any more issues!

**Comment by umairhm** [comment]
@HeyGarrison @KwintenP Thank you both for the updates. I tried a few days back and got the same issue. I suspect it may be due to an Organization repository that I am trying to use. Please confirm if that is the case and how can I utilize an organizational repository, if possible.

**Comment by HeyGarrison** [comment]
@umairhm can you open a new issue with your specific repro steps? The original repro steps here don't include anything git related. Thanks for your help!!

**Comment by yangxing5200** [comment]
Hello @HeyGarrison ,
I encountered the same issue in Chrome version 115.0.5790.110's incognito mode. In my environment, I am using an iframe to load a URL from a different domain. The problem occurs only in incognito mode, and it works fine outside of incognito mode. Can you please advise on how to resolve this?

**Comment by kernelguardian** [comment]
Sorry to bring this up again but the jsfiddle link in the homepage doesn't seem to work and brings up the same error on Brave but works on Safari?
https://jsfiddle.net/3tf5r0cu/
