### ISSUE TITLE
Not givin code completion and having radom syntax errors

### ISSUE THREAD

**Issue by Raufr1** [stackblitz/webcontainer-core#522]
### Describe the bug

it what the title says, I'm not getting any code completion when editing the html files. Also when editing adding a line of code to the typescript file, and accidently misspelling a function call (the function is declared in a different file). The right error shows up but it doesn't disappear even if i correct the changes. I have to save the file instead to make it work.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-cjrp25-9zzj1j?file=src%2Fapp%2Fshipping%2Fshipping.component.html

### Steps to reproduce

For the html bug. Jut go to a HTML file and type a tag to see if code completion works.

For typescript bug, slightly misspell the getShippingPrices function (line 23) under app/cart.service.ts. Then under app/shipping/shipping.component.ts line 10, you'll see the an error isn't given, To get it retype the function call. Then the error comes, then if you fix the name in the cart.service.ts file, the error doesnt go away

### Expected behavior

Code completion for HTML worked before.
Don't think one should need to save to get error updates

### Screenshots

![image](https://user-images.githubusercontent.com/90327786/148270833-27e139e1-95e7-40fa-8358-cdfc365c99a1.png)

![image](https://user-images.githubusercontent.com/90327786/148270927-0f37b8e3-8669-4ada-841d-bb82826aade9.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
performance.memory = {
  "totalJSHeapSize": 130300466,
  "usedJSHeapSize": 121180430,
  "jsHeapSizeLimit": 2172649472
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

**Comment by HeyGarrison** [comment]
@Raufr1 is this still any issue?

**Comment by Raufr1** [comment]
Nope. 


Get Outlook for Android
