### ISSUE TITLE
Angular Beginner's Web App broken

### ISSUE THREAD

**Issue by Raufr1** [stackblitz/webcontainer-core#523]
### Describe the bug

I made a web app following the angular guide, it worked a day ago when building it but today it's broken. Routing is broken. Every link leads to a blank screen

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-cjrp25-9zzj1j?file=src%2Fapp%2Fapp.module.ts

### Steps to reproduce

Click on the Checkout button, or any one of the phone names. 

### Expected behavior

Routing should work

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
performance.memory = {
  "totalJSHeapSize": 103960103,
  "usedJSHeapSize": 96560103,
  "jsHeapSizeLimit": 2172649472
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

**Comment by jrvidal** [comment]
@Raufr1 Thanks for the report. I see some errors in the dev console:
```
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[CartService -> HttpClient -> HttpClient -> HttpClient]: 
  NullInjectorError: No provider for HttpClient!
NullInjectorError: R3InjectorError(AppModule)[CartService -> HttpClient -> HttpClient -> HttpClient]: 
  NullInjectorError: No provider for HttpClient!
```
These errors also appear when I try to run the project locally, so I don't think this is a WebContainer issue.

**Comment by geromegrignon** [comment]
@Raufr1 
Your AppModule is missing the `HttpClientModule` in the imports array.
Without it, you can't use HttpClient.

By adding it, it'll work as expected.

**Comment by Raufr1** [comment]
Ohh. I'm dumb. Thanks man


Get Outlook for Android
