### ISSUE TITLE
Error: Unsupported option name ("--no-audit")  when using cra in web container

### ISSUE THREAD

**Issue by aliasgar55** [stackblitz/webcontainer-core#524]
### Describe the bug

Whenever we try to create a cra app with the following command ```npx create-react-app tutorial --template typescript```
it results in a error

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-snfmot?file=refine.dev%2Fpackage.json

### Steps to reproduce

Create a node project
run this command
```npx create-react-app tutorial --template typescript```
Results in the following error
```Unknown Syntax Error: Unsupported option name ("--no-audit").```

### Expected behavior

A cra app must be created when we run npx creat=react-app in the terminal

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91967478,
  "usedJSHeapSize": 88006386,
  "jsHeapSizeLimit": 2130968576
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

**Comment by jrvidal** [comment]
@aliasgar55 This is a bug indeed, thanks for reporting.

**Comment by HeyGarrison** [comment]
@aliasgar55 in the interim this StackBlitz might be useful to you: https://stackblitz.com/edit/cra-typescript-qqojjs

I generated a CRA app locally and then uploaded the files. :)

**Comment by aliasgar55** [comment]
> @aliasgar55 in the interim this StackBlitz might be useful to you: https://stackblitz.com/edit/cra-typescript-qqojjs
> 
> I generated a CRA app locally and then uploaded the files. :)

Thank you so much 🙂👍

**Comment by SamVerschueren** [comment]
Support for `--no-audit` was added a while ago. Running CRA in [Codeflow](https://stackblitz.com/~) works now. The reason it doesn't work in the StackBlitz Classic editor is because there's no `git` binary available there.
