### ISSUE TITLE
Firefox not supported for webcontainer

### ISSUE THREAD

**Issue by hacker-eleos** [stackblitz/webcontainer-core#527]
### Describe the bug

When I open the link in Firefox browser, I get the following error.

`WebContainers currently work in Chrome and Chromium-based browsers. We’re hoping to add support for more browsers as they implement the necessary Web Platform features.`

### Link to the blitz that caused the error

https://stackblitz.com/github/webpack/webpack.js.org/tree/master/examples/module-federation?terminal=start&terminal=

### Steps to reproduce

1. Go to the [link](https://stackblitz.com/github/webpack/webpack.js.org/tree/master/examples/module-federation?terminal=start&terminal=).
2.  See the right hand side of screen.

### Expected behavior

I should see a terminal.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox 
Full version  = 95.0
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
performance.memory = undefined
Hash = 4bc445b0bf2f24de41719bcf76515e3a7b66a071
```

**Comment by jrvidal** [comment]
Closed in favor of #437
