### ISSUE TITLE
Phone-start.html

### ISSUE THREAD

**Issue by Chutani09** [stackblitz/webcontainer-core#528]
<html>
<head>
    <meta name="viewport" content="width=device-width">
    
    <script src=file:///android_asset/app.js></script>
    <script src="file:///android_asset/Libs/JQuery.js"></script>
    <script src="file:///android_asset/Libs/Flot.js"></script>
</head>
	
<script>
    //Initialise variables.        
    sampleCount = 100;                
    updateInterval = 10;   
    sensorData = null;

    //Called when document is loaded.
    function OnStart()
    {
        //Lock screen orientation to Landscape.
        //(Callback draws the page after the orientation change completes)
        app.SetOrientation( "Landscape", DrawPage );
        
        //Create and start accelerometer sensor.
    	sns = app.CreateSensor( "Accelerometer", "Fast" );
    	sns.Start();
    }
    
    //Draw the HTML page.
    function DrawPage()
    {
        //Set graph options
        var options =
        {
            grid: { color: "#656565", borderWidth: 1 },
            series: { shadowSize: 0  },
            yaxis: { min: -20, max: 20 },
            xaxis: { max: 0, min: -sampleCount, show: false }
        }
       
        //Get data and plot the graph.
        var vals = sns.GetValues();
        var series = GetSeries( sampleCount, [vals[1],vals[2],vals[3]] );
        plot = $.plot("#placeholder", series, options );
       
        //Start updating the graph.
        Update();
    }
   
    //Update the graph.
    function Update()
    {
        //Get more data.
        var vals = sns.GetValues();
        var series = GetSeries( sampleCount, [vals[1],vals[2],vals[3]] );
       
        //Re-plot the graph.
        plot.setData( series );                   
        plot.draw();
       
        //Call this function again.
        setTimeout( Update, updateInterval );
    }
   
    //Get accumulated data series.
    function GetSeries( points, funcs )
    {                                 
        if( typeof flt_dataStore == "undefined" )
            flt_dataStore = new Array( funcs.length );
       
        var series = [];
        for( var i=0; i< funcs.length; i++ )
        {
            if( !flt_dataStore[i] ) flt_dataStore[i] = [];

            if( flt_dataStore[i].length > sampleCount )
                flt_dataStore[i] = flt_dataStore[i].slice(1);
                                                           
            var val = funcs[i];
            flt_dataStore[i].push( val );                                        
           
            var res = [];
            var len = flt_dataStore[i].length;
            for( var j = 0; j < len; j++ )
                res.push( [j-len, flt_dataStore[i][j]] )
                           
            series[i] = res;
        }                             
        return series;
    }             
</script>

<style>
    body 
	{  
        font: 1.5em Helvetica, Arial, sans-serif;
        vertical-align: middle;
        background: #383838; 
    }
     
    .plot-container 
    {
        box-sizing: border-box;
        width: 90%;
        height: 90%;
        padding: 1% 1% 1% 1%;
        margin: 2% auto 2% auto;
        border: 1px solid #444444;
        border-radius: 6px;
        background: #101010;   
    }
     
    .plot-placeholder 
    {
        width: 100%;
        height: 100%;
        font-size: 14;
        line-height: 1.2em;
    }
    
    .flot-tick-label
    {
        color: #777777;
    }
</style>
    
<body onload="app.Start()">

    <div id="content">
        <div class="plot-container">
            <div id="placeholder" class="plot-placeholder"></div>
        </div>                  
    </div>  
	
</body>
</html>

**Comment by jrvidal** [comment]
@Chutani09 If you have an issue with WebContainer, could you try and open an issue following the templates? Thanks!
