### ISSUE TITLE
HTML do not get updated, fork doesnt work. sharing URL doesnt work

### ISSUE THREAD

**Issue by msms007** [stackblitz/webcontainer-core#533]
### Describe the bug

changes do not get updated

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fexpansion-overview-example.html

### Steps to reproduce

changes do not get updated

### Expected behavior

HTML changes  get updated

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.71
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108225472,
  "usedJSHeapSize": 103622444,
  "jsHeapSizeLimit": 4294705152
}
Hash = 528f704493b63b14b6f9ee36935eead8382e8395
```

**Comment by jrvidal** [comment]
@msms007 Thanks for the report. The link you provided does not work by itself (it is a POST link). Could you provide the original link you clicked to reach the project?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
