### ISSUE TITLE
What does "Developer API" entail?

### ISSUE THREAD

**Issue by RhinoCodes** [stackblitz/webcontainer-core#535]
Will this be a way to start custom web containers? Want to run Node.js in a browser on my site and homebrew solutions look rather complicated

**Comment by Nemikolh** [comment]
Hi @RhinoCodes !

I think you might be looking into the WebContainers API that we released very recently :partying_face: 
You can get started there: https://webcontainers.io/tutorial/1-build-your-first-webcontainer-app

Let us know if you have any questions!
