### ISSUE TITLE
WebContainer Is Invoking '@angular/core' Error 

### ISSUE THREAD

**Issue by jiten4tune** [stackblitz/webcontainer-core#547]
### Describe the bug

WebContainer Invoking "Cannot find module '@angular/core' or its corresponding type declarations.(2307)"

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-whm3lo-uk4vzn?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

1. Go To https://angular.io/start
2. Navigate to "ready-made sample project in StackBlitz" link given in the Create the sample project.
3. Angular component giving below error:
![image](https://user-images.githubusercontent.com/97447384/149773693-bf22028f-0658-4d39-8a95-1db49228de5c.png)

### Expected behavior

Angular component should render in the sample project.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.71
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91279973,
  "usedJSHeapSize": 83290393,
  "jsHeapSizeLimit": 2172649472
}
Hash = d4ed89204e54de5c40d109298317e6dc4d60aef7
```

**Comment by SamVerschueren** [comment]
Hi @jiten4tune 👋 ! 

It's actually expected behaviour. Wait until the packages got installed (like `@angular/core`) so the editor can pick up the type definitions.

![image](https://user-images.githubusercontent.com/1913805/150375828-6155feb2-628c-45b4-bbc2-7691661bb6d1.png)

Unless I miss something here?

**Comment by jiten4tune** [comment]
Hi Mr. Sam,

Thanks for your reply. You are right and Its working fine now. Actually, it
was taking time to installing the package. Thanks for your time.

Regards,
Jitender

**Comment by SamVerschueren** [comment]
Awesome. Thanks for letting us know and don't hesitate to create a new issue if you run into something else.
