### ISSUE TITLE
BUG: Folders that you drag into the environment do not sync with the project

### ISSUE THREAD

**Issue by Davien21** [stackblitz/webcontainer-core#55]
---
name: Bug report
about: Create a report to help us improve the Nextjs environment
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
I copied a bunch of folders into the **/pages** directory and I could not open these newly added pages.
When I created the same folders manually, they worked well.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-mh5kn3?file=pages%2Finvestments%2Findex.js

**To Reproduce**
1. Drag and drop some files / valid folders (a folder with an index.js) into the **/pages** directory of the **nextjs** project
2. Try to route to these pages on the live server
3. They re-route to a 404 page because for some reason, they are not recognised

**Expected behavior**
Once I drop any file / folder into the pages directory, they should automatically be saved and cause a hot reload of the live server.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.93
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
performance.memory = {
  totalJSHeapSize: 85509863,
  usedJSHeapSize: 80044759,
  jsHeapSizeLimit: 4294705152
}

**Additional context**
Nothing else I guess

**Comment by KwintenP** [comment]
Hi!

🙏 for reporting. This does seem like a bug on our end!

As a workaround for the time being, if you upload the folders, save and refresh the page, the files are picked up!

**Comment by SamVerschueren** [comment]
@Davien21 Can you try this again? I think @KwintenP did some fixes for drag-and-drop and files and it seems to work now without save and refresh.

**Comment by jrvidal** [comment]
@Davien21 I'm closing this since it's been a while. Please feel free to comment/re-file if you find any further issues.
