### ISSUE TITLE
Cannot fork Angular Material mat-select demo but it's ok to fork other projects 

### ISSUE THREAD

**Issue by XSun771** [stackblitz/webcontainer-core#552]
### Describe the bug

Cannot fork Angular Material mat-select demo but it's ok to fork other projects 

Angular Material mat-select demo:  https://stackblitz.com/run?file=src%2Findex.html

the request to Fork in F12 - Network

Request URL: https://stackblitz.com/api/projects
Request Method: POST
Status Code: 500 
Remote Address: 127.0.0.1:7890
Referrer Policy: strict-origin-when-cross-origin

Request Header:

:authority: stackblitz.com
:method: POST
:path: /api/projects
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
content-length: 1000980
content-type: application/json
cookie: ahoy_visitor=ddf644f9-846e-45b4-b0a9-708f389b77bb; _ga=GA1.2.1741171796.1642228246; cb_user_id=null; cb_group_id=null; cb_anonymous_id=%22ab52c33e-a7c6-408c-932c-aa178278d048%22; ajs_user_id=485480; ajs_anonymous_id=b5d5085e-ec39-49ff-b24d-8f987f161460; ahoy_visit=9076b3a6-5305-4b93-a20d-5ad4a0e0fdb7; _gid=GA1.2.603714125.1642508577; remember_user_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IlcxczBPRFUwT0RCZExDSWtNbUVrTVRFa1NHRndaMWN3YmpCclkySkxiM0Z2WkdsVGJqSm9aU0lzSWpFMk5ESTFNRGcxT0RFdU5qRTBPVE0xSWwwPSIsImV4cCI6IjIwMjItMDItMDFUMTI6MjM6MDEuNjE0WiIsInB1ciI6bnVsbH19--2edded8f4f89760e9771e003280ce58db5408186; CSRF-TOKEN=6%2FWniUCqiAIcBt9xiNfJgu7gByHpqA0OhEhaQzrqKDA5CF6qY32raLs0Xiolba8I%2BUQo6w6RJ1KqtClAGHhudw%3D%3D; mp_6a7f2ae4a8f5ca0202a8ae580f8af152_mixpanel=%7B%22distinct_id%22%3A%20%22485480%22%2C%22%24device_id%22%3A%20%2217e5c6e67f6d6-003239c445ca07-3e604809-1fa400-17e5c6e67f7cb4%22%2C%22mp_lib%22%3A%20%22Segment%3A%20web%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fmaterial.angular.io%2Fcomponents%2Fselect%2Foverview%22%2C%22%24initial_referring_domain%22%3A%20%22material.angular.io%22%2C%22%24user_id%22%3A%20%22485480%22%2C%22mp_name_tag%22%3A%20%22485480%22%2C%22id%22%3A%20%22485480%22%2C%22%24search_engine%22%3A%20%22google%22%7D; _gat=1; _session_id=L1NyTXg3cS91NnJJV29MbFFqL1AvU2l4NnZiMHpsRFZ5Z0I2MWVkRXFIZERaRVVSd2VoTWxhcnBlK2IwblV4bkcyWkRnVzI4eDFPSUdCclV0Sm5oNmNSQ0NsamRmWHg0U1FSQitBMGRLanA3OGk2T1dBL05LTXo3SkZJamJVUm1LSmh6UTVwSGN5UjVMT1lBNTJZNFo3S2dtUXJ6UEdQWS92UytLV0JJQndYZmJlbGZWQktuRTcrd1M4Q0hwU0ZiMStacEY1YjNWUU5qdjlzLzk5QXc4T1BBOGRudU1aSnFrRVVwVGovUWl5a2F3YjRidjVNSlROcm1MZkNEMUkyMi0tSUJlVk52aDVNZEhaeXI5NjNZRWwrdz09--a04a88939564d34a1fc7f664cc644f376a311513
origin: https://stackblitz.com
referer: https://stackblitz.com/run?file=src/app/select-overview-example.ts
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
x-csrf-token: 6/WniUCqiAIcBt9xiNfJgu7gByHpqA0OhEhaQzrqKDA5CF6qY32raLs0Xiolba8I+UQo6w6RJ1KqtClAGHhudw==
x-newrelic-id: VwcPUldXCRAFVFNSBQYBU10=

Response Header:

content-type: text/html; charset=utf-8
date: Tue, 18 Jan 2022 12:29:04 GMT
referrer-policy: strict-origin-when-cross-origin
server: StackBlitz
status: 500
strict-transport-security: max-age=63072000
via: 1.1 632eb0a30868eceed91db73a67cea410.cloudfront.net (CloudFront)
x-amz-cf-id: LNagIDhD04hio_QMeKtcHI4oS2gSxUQ5K13vjH0zQtk3aTroqF_OQw==
x-amz-cf-pop: NRT57-C4
x-cache: Error from cloudfront
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-newrelic-app-data: PxQEUF5QCQcBR1RSBQEFUVIEDxFORCANXhZKDVRUUUAcAEECVBFHCwtYaAkHDVxfVRZOB09SUhYQWFldEUkQCl8VGk4IFgQeA0sJWQZZA1FSBgVTV1sOAQddUk4aABtEAglSAFEEAloGVAoECloBVBFJXwBdElY/
x-permitted-cross-domain-policies: none
x-request-id: 7b11c762-a6b1-4e76-a41b-bb41b5250ceb
x-runtime: 0.087129
x-xss-protection: 1; mode=block

The request body is too long to copy here.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/select-overview-example.ts

### Steps to reproduce

Click Fork Button

### Expected behavior

Fork successfully

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 86.0.4240.198
Major version = 86
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 167292992,
  "usedJSHeapSize": 159313004,
  "jsHeapSizeLimit": 1098907648
}
Hash = d4ed89204e54de5c40d109298317e6dc4d60aef7
```

**Comment by jrvidal** [comment]
Possibly a duplicate of https://github.com/stackblitz/webcontainer-core/issues/552
