### ISSUE TITLE
Previewing Markdown Files does not allow overflow content || Scrolling disabled

### ISSUE THREAD

**Issue by Cyburstud** [stackblitz/webcontainer-core#553]
### Describe the bug

The code editor element does not allow scrolling of markdown files when it is displayed in preview mode. 

![screenshotDemo](https://user-images.githubusercontent.com/77064515/150036544-07e2f754-8ce5-4150-b819-2147dd2c9870.gif)
 
Upon further inspection of the rendered code, I suspect a possible cause might be failure to render a container labeled class="overflow-guard" that appears to provide a navigation interface for the code editor in the browser.

![image](https://user-images.githubusercontent.com/77064515/150036701-a4e1a1db-6238-45c1-8845-4db6b9510e7a.png)

### Link to the blitz that caused the error

https://stackblitz.com/fork/github/snowpackjs/astro/tree/latest/examples/blog

### Steps to reproduce

1. Open any project
2. Open the README.md or any markdown file.
3. If the content exceeds the viewport on the page, you will not be able to scroll at all with neither keyboard or mouse commands.

### Expected behavior

The ability to scroll without borders, to not be confined to windows implemented and enforced by some other developer.

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

![screenshotDemo](https://user-images.githubusercontent.com/77064515/150037040-06eb67f7-a518-4a8c-9a96-254183e0e59e.gif)

### Platform

- OS: [Windows 10 Home 64-bit]
- Browser: Chrome
- Version: Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by jrvidal** [comment]
:wave: Thanks for the report. The link you provided does not work. Could you provide a link to look at the issue?

**Comment by Cyburstud** [comment]
It appears that the bug is no longer present. Thank you! And sorry, I can't seem to find the original template repo that I linked back then. 


https://user-images.githubusercontent.com/77064515/222966218-00695302-8f26-437c-94bc-5226bdb6ad15.mp4
