### ISSUE TITLE
'SyntaxError: Unexpected end of JSON input' when running peeky ui

### ISSUE THREAD

**Issue by Akryum** [stackblitz/webcontainer-core#563]
### Describe the bug

The Peeky UI fails to connect via WebSockets to the GraphQL server with `SyntaxError: Unexpected end of JSON input`

### Link to the blitz that caused the error

https://stackblitz.com/edit/peeky-demo?file=package.json

### Steps to reproduce

1. Run `test:dev` script
2. The web app fails to connect

### Expected behavior

The web app connects and show the passed test

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

Actual:

![image](https://user-images.githubusercontent.com/2798204/150645377-5162b115-a558-4bbf-82ae-eecfe4f865c9.png)

![image](https://user-images.githubusercontent.com/2798204/150645406-db69fb84-1448-40fb-b48c-9bbebf1304f8.png)

Expected:

![image](https://user-images.githubusercontent.com/2798204/150645371-a0db715b-0f53-4139-8c49-9a9b4727d45d.png)

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.99
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 74957733,
  "usedJSHeapSize": 65741421,
  "jsHeapSizeLimit": 4294705152
}
Hash = 01faa899fac41642342f4b7113feacabea334fa1
```

**Comment by jrvidal** [comment]
@Akryum Thanks for the report. We've just deployed a fix for some of the errors that can be seen in your console screenshot. Could you try and see if the issue is still present?

**Comment by Akryum** [comment]
So I don't see the errors anymore but the data received by the frontend is very strange. Is there a way to debug the web sockets?

**Comment by Akryum** [comment]
For example, I've put two test files: 
![image](https://user-images.githubusercontent.com/2798204/150799237-33044671-1b84-4458-aeb6-6330df1e6851.png)

The data received with websockets is weird:
![image](https://user-images.githubusercontent.com/2798204/150799308-afc51505-9012-41ca-87af-f099e7133309.png)

**Comment by Akryum** [comment]
Expected result (in local):
![image](https://user-images.githubusercontent.com/2798204/150799662-36298001-e27a-4f29-b477-f44b415a4db0.png)

**Comment by jrvidal** [comment]
> Is there a way to debug the web sockets?

Devtools should work as usual if you open the preview window in a separate tab.

**Comment by Akryum** [comment]
@jrvidal I don't see the websockets:

![image](https://user-images.githubusercontent.com/2798204/151666371-adba9cad-415d-445f-aaff-f457a1f5fa44.png)

**Comment by SamVerschueren** [comment]
@Akryum It looks like I'm seeing the correct result now in StackBlitz? 

![image](https://github.com/stackblitz/webcontainer-core/assets/1913805/8628c53e-1dda-45d3-b03d-325210b0c60d)

The problem with WebSockets is that you can't see them in DevTools because we have to intercept them. This means that the WebSocket connection never leaves the browser, and thus you can't see them in the network panel unfortunately.l

**Comment by SamVerschueren** [comment]
Closing this issue as it seems to become stale. Feel free to create a new issue if there's anything else you run into.
