### ISSUE TITLE
The webpage never loads and shows running start command spinner indefinitely

### ISSUE THREAD

**Issue by manit815** [stackblitz/webcontainer-core#568]
### Describe the bug

Was trying to look through the mat date picker example.

1. Opened the stackblitz link from the page.
2. I could see the code loading properly.
3. Booting webcontainer step was completed.
4. Dependencies were installed.
5. I could see on the terminal that the bundle has been generated and the compilation is successfully completed.
6. The web page on the right hand side never loads and shows indefinite spinner against Running start command.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/date-range-picker-forms-example.ts

### Steps to reproduce

1. Opened the stackblitz link from the page.
2. I could see the code loading properly.
3. Booting webcontainer step was completed.
4. Dependencies were installed.
5. I could see on the terminal that the bundle has been generated and the compilation is successfully completed.
6. The web page on the right hand side never loads and shows indefinite spinner against Running start command.

### Expected behavior

Should show the webpage with the mentioned example.

![image](https://user-images.githubusercontent.com/18312520/150839088-75c23033-577b-43d1-9e1d-759868686c46.png)

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/18312520/150839114-9e98f03d-0dce-4088-b944-41e725e31995.png)

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.71
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93818136,
  "usedJSHeapSize": 85093168,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5df97b5e61f923919ea927c406a4806b792de8c6
```

**Comment by jrvidal** [comment]
@manit815 Thanks for the report.

> https://stackblitz.com/run?file=src/app/date-range-picker-forms-example.ts

This URL is meant for POST request, it does not take you to any blitz. Could you share the original link you clicked to reach that project?

> * [ ] I have run the project in my local machine and I could not reproduce the issue.

Did you try to run the project locally?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
