### ISSUE TITLE
Making a commit produces 2 commits

### ISSUE THREAD

**Issue by LWooler** [stackblitz/webcontainer-core#571]
### Describe the bug

When I make changes to my app and commit to my linked repo it creates 2 commits. First is the one that has my message and all my changes. Second is a commit that says "3 files modified" and no changes.

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-bmttpz?file=main.js

### Steps to reproduce

1. Make changes to app
2. Save
3. Click commit button
4. Type my commit message
5. Submit my commit

Result: 2 commits are made to my branch

### Expected behavior

There should only be 1 commit

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

![bug](https://user-images.githubusercontent.com/48956441/151191074-73ef7db4-11a1-423b-9640-8a765d5ac15d.JPG)

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.99
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 156364090,
  "usedJSHeapSize": 147694178,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5df97b5e61f923919ea927c406a4806b792de8c6
```

**Comment by tony19** [comment]
Possible duplicate of #318.

Per comment from @HeyGarrison, the issue was fixed (back in Sep 2021), but *still* not in production.

**Comment by LWooler** [comment]
Good call, yeah looks like the one you opened is the same issue. I was surprised when I didn't find any one else had reported it, guess I didn't look hard enough.

I'll close this one as duplicate, hopefully the fix gets pushed to production soon!
