### ISSUE TITLE
 ﻿ client-a8606f262e6f.js:2   TypeError: Cannot read properties of undefined (reading 'Memory')

### ISSUE THREAD

**Issue by aum-app** [stackblitz/webcontainer-core#576]
### Describe the bug

![image](https://user-images.githubusercontent.com/29253358/151658498-7efc10e8-dab0-453e-942e-3a6320578fa5.png)

### Link to the blitz that caused the error

https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth?file=src/App.tsx

### Steps to reproduce

[[![Uploading image.png…]()
[](https://reactrouter.com/docs/en/v6/examples/auth)](https://reactrouter.com/docs/en/v6/examples/auth)](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth?file=src/App.tsx)

### Expected behavior

[![image](https://user-images.githubusercontent.com/29253358/151658513-d9d37e67-d502-4e9d-8f6b-6a027479b183.png)
](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth?file=src/App.tsx)

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.99
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.76
performance.memory = {
  "totalJSHeapSize": 35804134,
  "usedJSHeapSize": 33730862,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5df97b5e61f923919ea927c406a4806b792de8c6
```

**Comment by jrvidal** [comment]
@aum-app Thanks for the report.

My guess is that some extension is blocking the usage of WebAssembly. Can you try in a profile without extensions? (incognito mode might or might not work, since additional restrictions might apply to 3rd party scripts and storage).

Alternatively, you could check the value of `globalThis.WebAssembly.Memory` in the different workers that are spawned.

**Comment by SageKwun** [comment]
> @aum-app Thanks for the report.
> 
> My guess is that some extension is blocking the usage of WebAssembly. Can you try in a profile without extensions? (incognito mode might or might not work, since additional restrictions might apply to 3rd party scripts and storage).
> 
> Alternatively, you could check the value of `globalThis.WebAssembly.Memory` in the different workers that are spawned.

It may cause this problem in Edge browser( I use MacOS so I do not know if it's same in Windows ) that open the feature "Enable security mitigations for a more secure browser experience" even I make "https://stackblitz.com" in the white list.
