### ISSUE TITLE
slidev entry point error

### ISSUE THREAD

**Issue by dirheimerb** [stackblitz/webcontainer-core#584]
### Describe the bug

Loading the template from stackblitz, the dev script fails because it can't determine the entry point from rollupOptions or the html files. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/slidev-mmvyvj

### Steps to reproduce

1. Load the template from stackblitz main page

### Expected behavior

Error in the console, stating could not determine entry point.... skipping pre-bundling.  

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 97.0.4692.99
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65287406,
  "usedJSHeapSize": 61123930,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5df97b5e61f923919ea927c406a4806b792de8c6
```

**Comment by HeyGarrison** [comment]
@dirheimerb thanks for reporting this! Does the project eventually load if you wait long enough? It should still load, but skips the prebundling.

**Comment by d3lm** [comment]
@dirheimerb Did you try running this project on local? Does it give the same error?

**Comment by SamVerschueren** [comment]
Closing this issue as the "warning" is exactly identical on local

![image](https://user-images.githubusercontent.com/1913805/235091951-3ff281e0-5a37-45d2-ba23-9a51886e8359.png)
