### ISSUE TITLE
Puppeteer support

### ISSUE THREAD

**Issue by pierfrancesco** [stackblitz/webcontainer-core#59]
**Is your feature request related to a problem? Please describe.**
I'd like to run puppeteer script inside a node project but despite the fact I'm able to install `npm i puppeteer` I can't find a way to install a Chrome instance (if possible)

**Describe the solution you'd like**
 I can run a puppeteer commands inside web containers in the same way I can do it on my machine.

**Describe alternatives you've considered**
No one at the moment.

**Additional context**

`index.js`
```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```
`package.json`

```javascript
{
  "name": "node-starter",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "axios": "^0.21.1",
    "chrome": "^0.1.0",
    "chrome-launcher": "^0.14.0",
    "chromedriver": "^90.0.1",
    "chromium": "^3.0.2",
    "install": "^0.13.0",
    "npm": "^7.14.0",
    "puppeteer": "^9.1.1"
  },
  "scripts": {}
}
```
Error:
```
(node:28) UnhandledPromiseRejectionWarning: Error: Could not find expected browser (chrome) locally.
```

**Comment by SamVerschueren** [comment]
Hi @pierfrancesco, thanks for trying out WebContainer. Because we don't run anything on a server and everything in the browser this is currently not possible unless maybe if puppeteer would have a WASM compiled binary, which I guess they don't.

We have some ideas to make it possible to communicate with your chrome instance on your machine, but currently it's only in the idea phase and no research is done yet on this front.

**Comment by pierfrancesco** [comment]
Hi Sam, thanks for you reply.
>this is currently not possible unless maybe if puppeteer would have a WASM compiled binary
Makes sense.

I'll be waiting if anything from this side will come up. Thanks again

**Comment by SamVerschueren** [comment]
No worries :). Everyone is still exploring the possibilities of WebContainer which is cool to see.

**Comment by florentpergoud** [comment]
Hi ! 
@SamVerschueren is there anything new take could allow to run Puppeteer in WebContainers now ?
thanks :)

**Comment by SamVerschueren** [comment]
Hi @florentpergoud. No, nothing has changed since then in regards to Puppeteer as far as I'm aware.

**Comment by florentpergoud** [comment]
Thanks for the anwser

**Comment by irux** [comment]
Hello, may I ask what was the idea ? was it something like running a chrome instance inside a web container ? like a browser in a browser ?

**Comment by florentpergoud** [comment]
@irux 
I am a front-end React developer working daily with [Remotion](https://github.com/remotion-dev/remotion), a lib to create videos using React.

Under the hood, the frames of the video are created by screenshotting the React web page using Puppeteer and Chromium, then using FFmpeg to stitch all the images together.

One main attention point is that you cannot render the video client-side as you need to use Puppeteer and Chromium for the screenshotting. 

So actually, the implemented render methods are: using some AWS lambda or deploying a server.

I thought that if we can run Chromium/Puppeteer in a web-container, we would be able to move the render to the client-side!

**Comment by ocodista** [comment]
Hi, can we reopen this?

I would also like to run puppeteer on a WebContainer.

**Comment by danvoyce** [comment]
+1

**Comment by reactone** [comment]
> @irux I am a front-end React developer working daily with [Remotion](https://github.com/remotion-dev/remotion), a lib to create videos using React.
> 
> Under the hood, the frames of the video are created by screenshotting the React web page using Puppeteer and Chromium, then using FFmpeg to stitch all the images together.
> 
> One main attention point is that you cannot render the video client-side as you need to use Puppeteer and Chromium for the screenshotting.
> 
> So actually, the implemented render methods are: using some AWS lambda or deploying a server.
> 
> I thought that if we can run Chromium/Puppeteer in a web-container, we would be able to move the render to the client-side!

I’m in the exactly the same position, being able to render remotion client side would be a game changer. All I can think of for now it to create an electron app and rendering locally using node.

**Comment by tewarig** [comment]
> @irux I am a front-end React developer working daily with [Remotion](https://github.com/remotion-dev/remotion), a lib to create videos using React.
> 
> Under the hood, the frames of the video are created by screenshotting the React web page using Puppeteer and Chromium, then using FFmpeg to stitch all the images together.
> 
> One main attention point is that you cannot render the video client-side as you need to use Puppeteer and Chromium for the screenshotting.
> 
> So actually, the implemented render methods are: using some AWS lambda or deploying a server.
> 
> I thought that if we can run Chromium/Puppeteer in a web-container, we would be able to move the render to the client-side!

i was also thinking same.

**Comment by SamVerschueren** [comment]
Hi everyone! Thanks for all the interest regarding this topic. However, this is currently technically not possible.

**Comment by jlia0** [comment]
> Hi everyone! Thanks for all the interest regarding this topic. However, this is currently technically not possible.

I see there is a recent update to support native language in web container, i.e., python, can I run Selenium instead?

**Comment by Osub** [comment]
+1

**Comment by Biogasbottle** [comment]
+1

**Comment by twicer-is-coder** [comment]
+1
