### ISSUE TITLE
The panel to add a dependency is missing

### ISSUE THREAD

**Issue by kvjrhall** [stackblitz/webcontainer-core#591]
### Describe the bug

The turbo package manager is missing from the user interface of an angular-material project after forking from the project's documentation. It is not possible to add additional packages to the derived project.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-xzfzqt

### Steps to reproduce

1. Open project
2. Look at left panel
3. Click through side tabs

### Expected behavior

One would expect to see the turbo package manager available.
Note that parity with local is based on launching the desktop interface for stackblitz from the browser.

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

Actual outcome:

![image](https://user-images.githubusercontent.com/63366453/153652141-accdc821-4b26-4504-9839-cc6c9b91dfc6.png)

Expected outcome from another project:

![image](https://user-images.githubusercontent.com/63366453/153652329-5d715812-589e-4f5c-90d9-a72a3866589e.png)

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.80
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88237791,
  "usedJSHeapSize": 77948007,
  "jsHeapSizeLimit": 4294705152
}
Hash = d7261b7448b4a0bf35c1ba6d98461d9487544022
```

### Additional context

The blitz itself is forked from an example in the angular material documentation.

**Comment by jrvidal** [comment]
@kvjrhall Thanks for the report. The project you have linked is not one of the classic Angular-based projects, but a WebContainer one, which means it's actually a [full Node application running in your browser](https://blog.stackblitz.com/posts/introducing-webcontainers/).

Instead of the dependency panel, you have access to a terminal where you can add dependencies as you would in a local setup:

```
npm install lodash

# These work as well
# yarn add lodash
# turbo install lodash
```

**Comment by kvjrhall** [comment]
Thank you for the clarification! I suspected it was going to be something
like that. I'm new to the platform and it's not quite foolproof enough for
me yet.
