### ISSUE TITLE
Fixed Sidenav Bug Report

### ISSUE THREAD

**Issue by SaikrishnaSam** [stackblitz/webcontainer-core#593]
### Describe the bug

When i'm opening fixed side nav in angular material it takes too much time. I thought that there is a network issue but below i noted a bug which is web container is in Beta. That is what now i'm reporting to you Thank You.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/sidenav-fixed-example.ts

### Steps to reproduce

1) Go to ' https://material.angular.io/components/sidenav/examples '.
2) Scroll Down up to Fixed Sidenav.
3) Click on edit fixed sidenav example in stackblitz.
4) you will find the error like Web Container is in bBeta below.

### Expected behavior

Fixed navbar should be opened based on the written code

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 97.0.4692.71
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 70623523,
  "usedJSHeapSize": 68956939,
  "jsHeapSizeLimit": 2172649472
}
Hash = e1937cc6e2ee7e7a1da198d43493f4063378a564
```

**Comment by d3lm** [comment]
Hey there 👋 This works just fine for me https://stackblitz.com/run?file=src/app/sidenav-fixed-example.ts.
