### ISSUE TITLE
BUG: esmodule syntax doesn't work when setting type: "module" on package.json

### ISSUE THREAD

**Issue by reaktivo** [stackblitz/webcontainer-core#6]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
esmodule syntax doesn't work when setting type: "module" on package.json nor when renaming index.js to index.mjs

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-e2tzh5?file=index.mjs

**To Reproduce**
1. Try running `node index.mjs` from the terminal

**Expected behavior**
Running the mjs file

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 65041199,
  usedJSHeapSize: 59647271,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by KwintenP** [comment]
We currently don't have support yet for ESM modules. 

It is on our radar though.

**Comment by reaktivo** [comment]
Nice to hear. Truly amazing work by the way. Game-changer

**Comment by SamVerschueren** [comment]
More context https://twitter.com/jdalton/status/1395510624830988290

**Comment by SamVerschueren** [comment]
We now officially support ESM 🎉!
