### ISSUE TITLE
When creating a new project on disk, files in sub directories are missing

### ISSUE THREAD

**Issue by nickdotht** [stackblitz/webcontainer-core#60]
**Describe the bug**
Originally reported by someone else on Discord. I went ahead and tested it myself and they are indeed missing.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-xfumvg

It's a freshly generated Nodejs server using express-generator.

**To Reproduce**
1. Go to https://stackblitz.com/local
2. Click on the "Start a new Node project with your local files" button
3. Pick your directory/files. Make sure you have a file within two parent directories
4. Once the upload is done, you'll notice the two folders but no file within the sub folder. Interestingly enough, sub sub folders (folders within sub folders) get uploaded. And files within sub sub folders are also nonexistent.

**Expected behavior**
I expected all my files and directories to be uploaded.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by KwintenP** [comment]
This is an issue indeed! 

The local fs integration is very alpha atm. Will be fixed asap!
🙏 for reporting.

**Comment by KwintenP** [comment]
@R4meau what was the extension of the files in those subfolders? 

There was a bug where .ts files were not uploaded properly. I'm thinking it's gonna be related to that since I can't repro this issue with .js files.

**Comment by R4meau** [comment]
@KwintenP It was all kinds of files.

**Comment by jrvidal** [comment]
This should be fixed now :tada: Thanks for the report.
