### ISSUE TITLE
Error when attempting to create component in Angular

### ISSUE THREAD

**Issue by montysexton** [stackblitz/webcontainer-core#604]
### Describe the bug

Error when attempting to create a component in angular.  

"ng generate component shipping"

Received error message:  "An unhandled exception occurred:  Cannot set property global of a #<Object> which has only a getter".  See "/tmp/ng-HvFjGL/angular-errors.log" for further details.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-6js12p

### Steps to reproduce

1. Open up stackblitz project described in report.
2. attempt to add component using new terminal by running "ng generate component shipping".
3. Error message generated:  "An unhandled exception occurred:  Cannot set property global of a #<Object> which has only a getter".  See "/tmp/ng-HvFjGL/angular-errors.log" for further details.

### Expected behavior

component added successfully without error.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89281501,
  "usedJSHeapSize": 82652361,
  "jsHeapSizeLimit": 4294705152
}
Hash = d64d45524a435df425e7813603b52872ecfbe08e
```

### Additional context

All other exercise component creation worked up to this point.  First component error in which has been received when following exercises and sample code.

**Comment by d3lm** [comment]
Hey! Thanks for reporting this issue. I can confirm that this is a regression that was introduced with one of our latest releases.

**Comment by montysexton** [comment]
Thanks for the quick response!  Glad I could help.  Stackblitz is a great
tool especially for when running exercises on angular io.

Respectfully

**Comment by d3lm** [comment]
This issue has been fixed and deployed.
