### ISSUE TITLE
Vite wont start on chromebook.

### ISSUE THREAD

**Issue by Quinn135** [stackblitz/webcontainer-core#607]
### Describe the bug

I'm not completely sure if my chromebook is just not powerful enough, but when I run vite, it runs the vite command, and it doesn't do anything. On my larger desktop, it runs fine.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-zqkwn9

### Steps to reproduce

1. Setup a Vite project
2. Run Vite

### Expected behavior

I expected for vite to start a server, and for it to show up on the right as a webpage.

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/59322843/155148407-db0c93e1-7b3e-4dd5-ac28-cc9cf7f17b62.png)

### Platform

```
Browser name  = **Chrome**
Full version  = 97.0.4692.102
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS aarch64 14324.80.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 126253424,
  "usedJSHeapSize": 117907572,
  "jsHeapSizeLimit": 1047003136
}
Hash = d64d45524a435df425e7813603b52872ecfbe08e
```

### Additional context

I am using a chromebook, so this may be a problem only on chromebooks.

**Comment by Quinn135** [comment]
This also happens with build and preview shown here:
![image](https://user-images.githubusercontent.com/59322843/155150897-eedfa2bb-a15e-4a3a-a3e5-9fdc84e468fc.png)
![image](https://user-images.githubusercontent.com/59322843/155151044-6915b5fe-9485-4b2e-a6a2-b72ed30c0a64.png)

**Comment by jrvidal** [comment]
@Quinn135 Thanks for the report. Are there any suspicious messages on the devtools console?

**Comment by Quinn135** [comment]
Sadly, I can't replicate it on any other device, and my chromebook has dev tools disabled...

**Comment by Quinn135** [comment]
It is pretty easy to replicate with a new react ts vite project (On my chromebook). Chance it could be just because of react ts...

**Comment by rayfoss** [comment]
I suspect you're having issues with a domain policy restricting your use of the browser. Stackblitz is demanding less than two gigs of ram to run your sandbox. I can fire `npm run dev` without issues.

**Comment by SamVerschueren** [comment]
Closing this issue as it didn't see any updates in almost a year. Thanks @FossPrime for asking these questions and chiming in 🙏 !

@Quinn135 If you stil run into issues these days, feel free to create a new issue and we can take it from there.
