### ISSUE TITLE
How to use postman for network requests for node webcontainers

### ISSUE THREAD

**Issue by supercoder123** [stackblitz/webcontainer-core#612]
### Describe the bug

I just tried a simple express js project and made one test API, it works fine in the browser but when I use some API client like postman it returns some weird values. Is there any way to get the proper response.

### Link to the blitz that caused the error

https://stackblitz.com/edit/express-simple-n4yjqi?file=backend%2Fserver.js

### Steps to reproduce

1. Just try to hit this endpoint from post man `https://express-simple-n4yjqi--5000.local.webcontainer.io/api/test`

### Expected behavior

Should return the response
```{"message":"Get goals"}```

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 97.0.4692.99
Major version = 97
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 OPR/83.0.4254.62
performance.memory = {
  "totalJSHeapSize": 106579263,
  "usedJSHeapSize": 99468939,
  "jsHeapSizeLimit": 4294705152
}
Hash = 60eafec8d3c353b6b62cb733670ec59f842c88b1
```

**Comment by jrvidal** [comment]
Unfortunately that cannot work at the moment. Our networking layer cannot really open ports on your machine, the browser does not allow that. The URL you are trying to hit will only work from within the browser you are running WebContainer on.

We do take note of the fact that something like Postman can be useful when developing APIs though.
