### ISSUE TITLE
Broken routing?

### ISSUE THREAD

**Issue by arielrobaldo** [stackblitz/webcontainer-core#615]
### Describe the bug

Injecting a second dependency in ProductDetailsComponent constructor makes ruotes not working

Maybe a step is missing in the tutorial when injecting this second dependency?

Thank you and best regards
Ariel

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-cqrdxj?file=src%2Fapp%2Fproduct-details%2Fproduct-details.component.ts

### Steps to reproduce

1 - Follow the tutorial in https://angular.io/start until reaching the step described in:
https://angular.io/start/start-data 
2 - under "Use Cart Service" section , when injecting the CartService by passing it to the ProductDetailsComponent constructor the routing stops working.
3 - Links that previously worked do not anymore.
           Examples :
              https://angular-cqrdxj--4200.local.webcontainer.io/products/1
              https://angular-cqrdxj--4200.local.webcontainer.io/cart

4 - I tried to remove this part (second dependency injection in constructor) and routing  seems to work again. Both previously referred URL start to behave as expected.

5 - As soon as I try to pass the "private cartService : CartService" to the constructor stops routing again.

### Expected behavior

Adding the second parameter in the constructor should not affect routing.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 117804066,
  "usedJSHeapSize": 111137954,
  "jsHeapSizeLimit": 4294705152
}
Hash = a8f9013f6760f2c4e84edef607d361d3a32b8049
```

**Comment by SamVerschueren** [comment]
Hi @arielrobaldo. It looked like the issue you where experiencing had more to do with Angular than with StackBlitz. I can't really check as the URL that you provided from the project doesn't exist anymore. If you feel like this is not correct in their tutorial, you can file an issue in [their repository](https://github.com/angular/angular).
