### ISSUE TITLE
Localservice runtime script prevents `<!DOCTYPE>` declaration

### ISSUE THREAD

**Issue by sulco** [stackblitz/webcontainer-core#617]
### Describe the bug

The WebContainers add the localservice runtime script invalidates the <!DOCTYPE> declaration – unless the <!DOCTYPE> is the first declaration in an HTML document, browsers go into Quirks Mode which can result in unexpected issues, e.g. with styling.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-wday1d

### Steps to reproduce

1. Open the rendered preview in a separate window
2. View source
3. See the `<script src="/.localservice@runtime.f79725df77a2d39e41f58b2534bc22660e1ae9b6.js></script>` before `<!DOCTYPE>`

### Expected behavior

The localservice runtime should be added somewhere after the <!DOCTYPE> declaration

### Additional context

This issue was first reported by @pomber on [Twitter](https://twitter.com/pomber/status/1498985716176633858) and in [this Code Hike issue](https://github.com/code-hike/codehike/issues/140)

**Comment by d3lm** [comment]
This has been fixed and the script gets correctly inserted into the `head` if there is one. Thanks for reporting the isssue 🙏 
 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/12571019/223444456-7c8e4b5c-5d48-4e2d-b89d-3196bc9d5371.png">
