### ISSUE TITLE
Why is it always booting the container?

### ISSUE THREAD

**Issue by dragN-TheGodLike** [stackblitz/webcontainer-core#619]
### Describe the bug

Why is it always booting the container? please help me

### Link to the blitz that caused the error

https://stackblitz.com/edit/nacrozbot

### Steps to reproduce

nothing new happens when i type a command in the terminal

### Expected behavior

it would be something like replit:

![image](https://user-images.githubusercontent.com/95991775/156881282-1bc7a5e8-6ac4-4dce-8bf4-ad68289175e7.png)

### Parity with Local

- [x] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

Why is it always booting the container?
![image](https://user-images.githubusercontent.com/95991775/156881332-57e280b2-377d-4842-b610-cbbacaa4399d.png)

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.51
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.30
performance.memory = {
  "totalJSHeapSize": 85684079,
  "usedJSHeapSize": 78068423,
  "jsHeapSizeLimit": 2172649472
}
Hash = 5bca79c80956550a0ee18f24bf5b874e18bb8626
```

**Comment by jrvidal** [comment]
@dragN-TheGodLike Thanks for the report.

> Why is it always booting the container?

It's not, the check icon indicates that booting did finish.

> nothing new happens when i type a command in the terminal

OK, so typing, say, `ls` doesn't print anything? Can you show us some screenshots of the terminal? What about the devtools console, is there anything fishy showing up?
