### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by francescogiunta** [stackblitz/webcontainer-core#623]
### Describe the bug

after fiew seconds inactivity, the project do not refresh automatically

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-8lxum1-twoenr?devtoolsheight=33&file=src%2Fapp%2Fform-field-prefix-suffix-example.css

### Steps to reproduce

just whaiting some time....

### Expected behavior

updating broowser view even if the project is not touched for some period

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.51
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 107046437,
  "usedJSHeapSize": 101759709,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5bca79c80956550a0ee18f24bf5b874e18bb8626
```

**Comment by kc0tlh** [comment]
Closing this due to lack of ability replicate based on the details provided above. If this is still an issue please feel free to reach out and we can investigate further!
