### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by miscany** [stackblitz/webcontainer-core#627]
### Describe the bug

Do images work yet in stackblitz? Because mine refuse to load. I really like this onlien code editor, but I'm probably going to have to start using another one. 
Let me know.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-12yj1g?file=pages%2Findex.js

### Steps to reproduce

d

### Expected behavior

d

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

d

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108653872,
  "usedJSHeapSize": 100330568,
  "jsHeapSizeLimit": 2172649472
}
Hash = 5bca79c80956550a0ee18f24bf5b874e18bb8626
```

### Additional context

d

**Comment by jrvidal** [comment]
@miscany Thanks for the report. Which images are not loading, specifically? Can you elaborate a bit more on the steps to reproduce?

**Comment by mikesimons** [comment]
I'm seeing this too. In my case I'm trying to set up a PIXI.js sandbox.
Project url is https://stackblitz.com/edit/mikesimons-pixi-play

PIXI is trying to load https://mikesimons-pixi-play.stackblitz.io/assets/character.png but if you open that url in a tab you get the HTML from the project, not the image.

**Comment by d3lm** [comment]
This is not an issue with WebContainer, and images also don't load on local.

Please make sure that the project works locally before submitting an issue. There's a checkbox in the issue description which is also unchecked.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/12571019/161150597-2210d150-c84d-4b13-91c7-f78052fbd0c4.png">

Closing this issue.
