### ISSUE TITLE
NGCC issue

### ISSUE THREAD

**Issue by BenRacicot** [stackblitz/webcontainer-core#628]
### Describe the bug

This setup is an exact replication of my actual Angular app's drag and drop setup but breaks when including the CDK's CdkVirtualScrollViewport.

```
Error: node_modules/@angular/cdk/scrolling/virtual-scroll-viewport.d.ts:20:22 - error NG6003: Appears in the NgModule.exports of MaterialExampleModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (@angular/cdk/scrolling) which declares CdkVirtualScrollViewport has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

20 export declare class CdkVirtualScrollViewport extends CdkScrollable implements OnInit, OnDestroy {
                        ~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/material.module.ts:102:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors

102 export class MaterialExampleModule {}
                 ~~~~~~~~~~~~~~~~~~~~~
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-6mmern-qdcrei?file=src%2Fapp%2Fcdk-drag-drop-connected-sorting-example.ts

### Steps to reproduce

Build the blitz

### Expected behavior

The app builds without error

### Parity with Local

- [x] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.51
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109716093,
  "usedJSHeapSize": 105276817,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5bca79c80956550a0ee18f24bf5b874e18bb8626
```

**Comment by jrvidal** [comment]
@BenRacicot Thanks for the report.

> [x] I have run the project in my local machine and I could not reproduce the issue.

I can actually reproduce the error locally, so this is probably an issue with the tutorial itself that should be reported in https://github.com/angular/angular/issues
