### ISSUE TITLE
Refresh button in PWA title bar

### ISSUE THREAD

**Issue by MarkHalls** [stackblitz/webcontainer-core#63]
**Is your feature request related to a problem? Please describe.**
When I install as a PWA there is no refresh button on the entire window. You described in the blog post that if I have an issue with my environment I can ["hit the refresh button"](https://blog.stackblitz.com/posts/introducing-webcontainers/#a-fresh-environment-on-every-page-load.). For now, if I want to get a clean environment I have to refresh using the keyboard or close and reopen the window.

**Describe the solution you'd like**
I'd like a refresh button on the window like you get with the youtube pwa. 
This could be fixed by changing the `manifest.json` to use  [`standalone-ui`](https://web.dev/add-manifest/#display)

**Describe alternatives you've considered**
I realize f5 or ctrl+r will accomplish the same thing but for heavy mouse users like myself it's more intuitive to click refresh.

**Comment by KwintenP** [comment]
Good remark. I think, like you said, there is a workaround for it.

For mouse usage, you can also go to `View -> Reload this page`.

**Comment by MarkHalls** [comment]
Is something your team might take action on in the future? I just noticed that the link in the app to open an issue took me to webcontainer-core instead of core. Should I open an issue over there instead?
