### ISSUE TITLE
WebContainer is significantly slower than non-WebContainer

### ISSUE THREAD

**Issue by yalunqin** [stackblitz/webcontainer-core#631]
### Describe the bug

I don't know when Stackblitz started using WebContainer. In the past when I made some code changes it would almost instantly be reflected in the browser (1s at most). Now it always re-downloads and re-installs the dependencies every time I make code changes which always takes >5s. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-n2xjyr?file=src/app/paginator-configurable-example.ts

### Steps to reproduce

1. Make a tiny code change.
2. You'll see how slow it is for the change to be reflected. 

### Expected behavior

<= 1s.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 102958095,
  "usedJSHeapSize": 98992883,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5bca79c80956550a0ee18f24bf5b874e18bb8626
```

**Comment by SamVerschueren** [comment]
Hi @yalunqin. Not sure why making a change would reinstall the dependencies. I tested the project that you provided and it seems to instantly reflect the changes (definitely below 1s). Maybe at the time you where trying it was a bug on our side with the Angular projects, but that's hard to tell. Closing as I think this is not an issue anymore.
