### ISSUE TITLE
Cannot initialize prisma via Terminal

### ISSUE THREAD

**Issue by JNussenzveig** [stackblitz/webcontainer-core#633]
### Describe the bug

Hi!

I'm currently using the NextJS fork, but when I tried to initialize prisma (npx prisma init), it errors out the following:
`~/projects/nextjs-pzff2x
❯ npx prisma init
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [] 0%Error: request to https://binaries.prisma.sh/all_commits/73e60b76d394f8d37d8ebd1f8918c79029f0db86/debian-openssl-1.1.x/prisma-fmt.gz.sha256 failed, reason: socket hang up`

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-pzff2x?view=preview

### Steps to reproduce

1. `npm install prisma @prisma/client`
2. `npx prisma init`

### Expected behavior

It should initialize prisma and generate prisma schema and files.

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jrvidal** [comment]
@JNussenzveig Thanks for the report. The download fails due to CORS restrictions, which we cannot do much about at the moment.

However, even if it worked, it's worth noting that prisma won't work anyway, since it relies on native binaries that WebContainer cannot run.

**Comment by JNussenzveig** [comment]
@Roberto, got it! Thanks for the explanation. Is there any other
alternatives or something like that?

**Comment by d3lm** [comment]
@JNussenzveig The only work around for this would be that prisma has a fallback for environments that don't support native binaries, either compile their native code to WASM or provide some sort of JS fallback.

I am going to close this issue for now because there is not much to do on our side at this point.
