### ISSUE TITLE
Vite not provided named exports from history.js

### ISSUE THREAD

**Issue by ThomasBurleson** [stackblitz/webcontainer-core#635]
### Describe the bug

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/210413/159003088-0ad7a559-735c-487d-a875-94a7585051db.png">

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-2xmcr8?file=package.json

### Steps to reproduce

I have include the npm package history@5.3.0.
The editor shows the History interfaces for:

#### `src/hooks/useLanguage.tx`
```ts
import { createBrowserHistory, Action, Listener, Update } from 'history';

```

Yet the runtime throws the reported error.

### Expected behavior

Compiler and runtime should be sync'ed.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.51
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 181488916,
  "usedJSHeapSize": 172076952,
  "jsHeapSizeLimit": 4294705152
}
Hash = b13a26b27ada247a0652614f4de766b5b4e9d421
```

**Comment by jrvidal** [comment]
@ThomasBurleson Thanks for the report.

> [ ] I have run the project in my local machine and I could not reproduce the issue.

This does not seem to be a WebContainer problem, as I could reproduce it locally.
