### ISSUE TITLE
Where is the index content shown?

### ISSUE THREAD

**Issue by pflegende** [stackblitz/webcontainer-core#636]
### Describe the bug

why does the server-snippet doesnt know the index.html?

is only THIS folder available.
Why does it not tuch the file for spreading the word?

### Link to the blitz that caused the error

https://stackblitz.com/edit/http-server-egur84?file=README.md

### Steps to reproduce

1. copy the server.js `cp server.js server2.js`
2. changing the message inside the serverscript to "tach ...."
6. stop server by C-c, ok stopped
3.  RUN: npm install && npx nodemon server2.js
4. works fine, new updated message
5. added a index.html  (very light) only consisting 2 tags and text
6. stop server by C-c, ok stopped
7.  RUN: npm install && npx nodemon server2.js
8. waiting for new output (from index-inside-text) -> Nothing
9. the "tach ..." message continued

Does you have some hint for how realising the conection between index.html and server2.js?

### Expected behavior

Want see the content of index.html

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

![Opera Momentaufnahme_2022-03-18_234253_stackblitz com](https://user-images.githubusercontent.com/52720420/159094894-4772e5ed-afd5-431f-a7e4-12df9eb913a9.png)

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 OPR/84.0.4316.21 (Edition 360-1)
performance.memory = {
  "totalJSHeapSize": 72549020,
  "usedJSHeapSize": 68219424,
  "jsHeapSizeLimit": 540016640
}
Hash = 6495216afc69f31e3592b868d6f1407d8619435d
```

### Additional context

---

we are looking forward also with a [monitoring Wiki](https://github.com/pflegende/http-server-egur84/wiki/caput-1----read-the-docs) for your interesting project.

---

**Comment by jrvidal** [comment]
@pflegende Thanks for the report. This is not an actual WebContainer issue, though, as it behaves exactly as Node.js would.

**Comment by pflegende** [comment]
thx, 
so we will climb in a weekend course for the node.ja learning curve
;)

So, if you have some hint for 1st steps to see our lovely index.html on screen, dont hesistate to write a secret note ...

;)
