### ISSUE TITLE
Unspecified web container support for mobile Chrome or not

### ISSUE THREAD

**Issue by Seanmclem** [stackblitz/webcontainer-core#637]
### Describe the bug

It seems pretty clear that by default Chromium is mainly the supported browser for web containers. However the official doc for browser support makes no mention though if mobile Chrome is supported or not. The link was provided on an error message about my unsupported browser for web containers on mobile Chrome, but the link doesn't mention if mobile chrome is specifically supported or not yet. It should make some mention of any kind, even if just to say "not yet" . Understandably it would not be supported on iOS but the question would be outstanding on Android.. This link specifically 

https://developer.stackblitz.com/docs/platform/browser-support/

### Link to the blitz that caused the error

https://stackblitz.com/edit/withastro-astro-ga3cgp

### Steps to reproduce

Open any web container template in mobile Chrome 

### Expected behavior

Since Chrome is a supported browser, the error message or linked article should make some mention of the mobile version specifically being not supported. If there's somehow already is some mentioned, it should be more explicit easier to find 

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

![Screenshot_20220318-223147~2](https://user-images.githubusercontent.com/6831540/159103478-b5ec0769-400b-486b-b767-36e723dfca57.png)

### Platform

User agent

Mozilla/5.0 (Linux; Android 11; Surface Duo) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.73 Mobile Safari/537.36

**Comment by FossPrime** [comment]
At some point Chrome for Android started requiring a COOP header for SAB support. Stackblitz is working on it. We'll probably see it Oct 12th. I detailed how to enable it on #810, but it's a lot of work and requires an ADB connection. Another possible solution is to change the user agent to Firefox using the Kiwi browser and the User-Agent Switcher for Chrome extension to permanently spoof stackblitz.com with a Firefox user-agent.

**Comment by SamVerschueren** [comment]
Hi @Seanmclem. Android Chrome should be supported and was supported for a while. Then due to a bug it didn't work anymore and we now just released a fix.

Could you try it again? If you still run into an issue, let us know!

**Comment by Seanmclem** [comment]
> Hi @Seanmclem. Android Chrome should be supported and was supported for a while. Then due to a bug it didn't work anymore and we now just released a fix.
> 
> Could you try it again? If you still run into an issue, let us know!

Hi, I tried it today and it says "Failed to boot WebContainer" 

I can't find any other output or errors. 

User agent: Mozilla/5.0 (Linux; Android 11; Surface Duo) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Mobile Safari/537.36

**Comment by SamVerschueren** [comment]
@Seanmclem There was a misconfiguration in our setup which caused CORS issues under the hood. Can you test again?

**Comment by SamVerschueren** [comment]
We believe this is now entirely fixed (also for Chrome mobile with desktop mode turned on).

**Comment by Seanmclem** [comment]
> We believe this is now entirely fixed (also for Chrome mobile with desktop mode turned on).

@SamVerschueren ok I tried it again. Fails to install dependencies. See screenshot. ![Screenshot_20221029-233357.png](https://user-images.githubusercontent.com/6831540/198861389-25fd2390-a331-4dad-93fb-21ce21b72531.png)

**Comment by FossPrime** [comment]
> > We believe this is now entirely fixed (also for Chrome mobile with desktop mode turned on).
> 
> @SamVerschueren ok I tried it again. Fails to install dependencies. See screenshot.
> 
> ![Screenshot_20221029-233357.png](https://user-images.githubusercontent.com/6831540/198861389-25fd2390-a331-4dad-93fb-21ce21b72531.png)

That's an IO error... Probably a sandbox issue. 
Try Vite.new/vue-ts

My phone works but my 4GB arm32 tablet quits
