### ISSUE TITLE
npx create-remix returns errror

### ISSUE THREAD

**Issue by HeyGarrison** [stackblitz/webcontainer-core#640]
### Describe the bug

If you create a new node project (node.new) and run the command "npx create-remix@latest" it'll return an error.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-up6dmy?file=.stackblitzrc

### Steps to reproduce

1. https://node.new
2. Navigate to terminal
3. run `npx create-remix@latest`
4. observer error

### Expected behavior

To successfully create a remix app.

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Screenshots

<img width="650" alt="Screen Shot 2022-03-20 at 8 51 35 PM" src="https://user-images.githubusercontent.com/5100597/159196199-6d10fe4d-f627-477f-947c-2ad60054f7b0.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by d3lm** [comment]
I think this is fixed now that we support native `npx`. I am going to close this for now but we can open a new ticket if there's still an issue.
