### ISSUE TITLE
a command can only contain words and redirects for `#! /usr/bin/env node` scripts

### ISSUE THREAD

**Issue by JonnyBurger** [stackblitz/webcontainer-core#643]
### Describe the bug

When running the template repository linked below, and running `npm start`, the following error occurs:

```
/home/projects/zzmilgmyz.github/node_modules/.bin/remotion: line 2: a command can only contain words and redirects
```

The "start" script inside `package.json` defines the following script:
```
  "start": "remotion preview src/index.tsx"
```

When running:

```
npx remotion preview src/index.tsx
```

everything works fine (amazing!)

This is the `.bin/remotion` script:

```ts
#! /usr/bin/env node
const {cli} = require('./dist/index');

cli()
	.then(() => process.exit(0))
	.catch((err) => {
		// eslint-disable-next-line no-console
		console.error(err);
		process.exit(1);
	});
```

We might be able to change the script to fix it.
I think the bug is on Stackblitz's side though because it works with `npx`, just not in an npm script.

### Link to the blitz that caused the error

https://stackblitz.com/github/remotion-dev/template-helloworld

### Steps to reproduce

Run `npm start` after the initialization is done

### Expected behavior

Webpack server is starting.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SamVerschueren** [comment]
Oh this is interesting.

Apparently it's the space between `#!` and `/usr/bin/env`. Removing that space seems to do the trick. I'll have a look to fix this internally.

**Comment by JonnyBurger** [comment]
@SamVerschueren That's brilliant, thanks a lot for investigating this! We'll remove the space from our side as well and announce StackBlitz compatibility soonish 😊

**Comment by SamVerschueren** [comment]
I'm looping in @sulco here as he was talking to me about adding Remotion as one of our starter projects.

The fix is already merged on our end, we just have to release it on stackblitz.com. Not sure when that will happen though.

**Comment by SamVerschueren** [comment]
@JonnyBurger Pushed a bit through and we got the fix already deployed on production. I just confirmed that the template you provided now works 🎉 . This is super excited stuff 👏 !
