### ISSUE TITLE
Failed to boot web container

### ISSUE THREAD

**Issue by kevlarpar** [stackblitz/webcontainer-core#646]
### Describe the bug

failed to boot web container after fork.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-9jhtrs?file=src%2Fapp%2Fapp.module.ts

### Steps to reproduce

fork project

### Expected behavior

project loads

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.82
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78718553,
  "usedJSHeapSize": 73517809,
  "jsHeapSizeLimit": 1098907648
}
Hash = 498a09d3a17f259cef953b5298448503c90e055d
```

**Comment by kevlarpar** [comment]
No longer an issue

Sent from my iPhone

On Mar 7, 2023, at 9:06 AM, Dominic Elm ***@***.***> wrote:

﻿

Hey 👋 Is this still an issue? Cause I can fork it and the container boots successfully so I can't reproduce the issue on my end.

**Comment by d3lm** [comment]
Thank you for double checking 🙏
