### ISSUE TITLE
Should ports in use icon show a notification?

### ISSUE THREAD

**Issue by SteveALee** [stackblitz/webcontainer-core#649]
### Describe the bug

The "ports in use" icon alway has a notification. There appears to be no way to clear it. 

Arguably the default port allocation is not  very interesting an not worth our attention.  Especially as we don;t need ot use it directly given the nice button to open the preivew in a new window.

It feels like an attention grabbing and irratating nag. :)

![image](https://user-images.githubusercontent.com/618922/160102574-f59aec84-a991-44e2-9315-f61e7cde8d0e.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/opendir-metronome?file=index.html

### Steps to reproduce

Just open the URI

### Expected behavior

No notification?

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.82
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64091094,
  "usedJSHeapSize": 58775890,
  "jsHeapSizeLimit": 4294705152
}
Hash = 498a09d3a17f259cef953b5298448503c90e055d
```

**Comment by fvsch** [comment]
Thanks for the feedback @SteveALee. We're considering keeping the port count indicator, but making it less distracting visually.

**Comment by donmckenna** [comment]
Closing this issue, as we've now updated the port count indicator to be less intrusive / not as attention grabbing.
Thanks for the feedback!

<img width="93" alt="Screen Shot 2022-05-09 at 7 11 14 PM" src="https://user-images.githubusercontent.com/22125230/167744045-ce7f0be7-26f8-4eb0-a37d-c66d83120703.png">
