### ISSUE TITLE
Injected scripts break AlpineJS example and force Quirks mode

### ISSUE THREAD

**Issue by SteveALee** [stackblitz/webcontainer-core#651]
### Describe the bug

I'm having problems getting the simplest possible AplineJS example to work (as my more complex example is also failing).  The counter value does not appear next to the button.

When I open the preview in another Window and view page source I see:

```html
<script src="[/.localservice@runtime.0e61f5616522419418be8a0cc53f5e2e645f635f.js](view-source:https://opendir-metronome-eyxgtc--3000.local-corp.webcontainer.io/.localservice@runtime.0e61f5616522419418be8a0cc53f5e2e645f635f.js)"></script>
<!DOCTYPE html>
<html lang="[en]()">
  <head>
    <script type="[module]()" src="[/@vite/client](view-source:https://opendir-metronome-eyxgtc--3000.local-corp.webcontainer.io/@vite/client)"></script>

    <meta charset="[UTF-8]()" />
    <meta name="[viewport]()" content="[width=device-width, initial-scale=1.0]()" />
    <title>Checkbox test</title>
    <script
      defer
      src="[https://unpkg.com/alpinejs@3.9.5/dist/cdn.min.js](view-source:https://unpkg.com/alpinejs@3.9.5/dist/cdn.min.js)"
    ></script>
  </head>
  <body>
    <div x-data="[{ count: 0 }]()">
      <button x-on:click="[count++]()">Increment</button>
      <span x-text="[count]()"></span>
    </div>
  </body>
</html>
```

Critically, the 1st injected script is BEFORE the doctype so kicks the browser into QuirksMode - a horror I had hoped not to see again since the bad old days of IE!!

The other question is could they be interfering with Alpine? I can't tell as they are obfuscated.

So I downloaded the code tarball (which removes both scripts as is understandable) and run using Zeit's trusty old `npx serve` and yep it works fine!

For completeness, it also runs locally wth Vite via ` npm install && npm run dev`

Steve

### Link to the blitz that caused the error

https://stackblitz.com/edit/opendir-metronome-eyxgtc?file=index.html

### Steps to reproduce

See above

### Expected behavior

Clicking button increments counter

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 98.0
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
performance.memory = undefined
Hash = 0e61f5616522419418be8a0cc53f5e2e645f635f
```

**Comment by SteveALee** [comment]
Aha! I have good news and bad news. 

It works fine in Chrome.  I was using Firefox as I understood it now works adn it's my default browser so always launches

So, either there's Firefox issue, or perhaps more likely, Chrome does not care about the misplaced 1st Script.

**Comment by SteveALee** [comment]
FYI I only spotted this as I once spent days with non working code only to eventually find it was as I had added a helpful comment BEFORE the doctype!! D'oh!

**Comment by SteveALee** [comment]
Actually, Chrome DOES warn about Quirks mode. It's behind the issues icon, not in the console.

**Comment by d3lm** [comment]
Hey there! Thanks for reporting this issue and sorry about the silence on our end. We have a fix in our end which will most likely address this issue.

**Comment by Nemikolh** [comment]
Hi @SteveALee! Sorry for the late response, I think every issues you have reported have been fixed and your blitz works in Firefox if you add the `crossorigin` attribute to your `<script>` element importing alpine:

```html
<script crossorigin
  defer
  src="https://unpkg.com/alpinejs@3.9.5/dist/cdn.min.js"
></script>
```

I'm going to close this issue but feel to reopen if we missed something! :smiley:
