### ISSUE TITLE
__vite_ssr_import_1__.default is not a function

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [stackblitz/webcontainer-core#652]
### Describe the bug

This happens every once in a while, I will have a working project, and then the next time I try to open it, this is the error I get:
![image](https://user-images.githubusercontent.com/53215039/160607694-baf11f10-3993-402a-8812-c4809c9f0132.png)

Nothing has changed since the last time I opened my project, I didn't upgrade any dependencies either.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-pegwk5

### Steps to reproduce

1. Go to the project page
2. Run `turbo dev` in the terminal if it doesn't auto start.

### Expected behavior

I expect my project to load.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: ChromeOS
- Browser: Chrome
- Version: 96.0.4664.111

### Additional context

It's a sveltekit project.
This has happened before, to fix it I usually push it to Github and then create a new project, connect the repo, and then it works.

**Comment by jrvidal** [comment]
@TheBlueOompaLoompa Thanks for your report.

> I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

I ran this code locally and observed the same error. Is the code yours or did you get it from one of our templates?

**Comment by TheBlueOompaLoompa** [comment]
This code is mine

**Comment by jrvidal** [comment]
I see. This repo is mostly for WebContainer compatibility issues, and there doesn't seem to be any in this case.

Now, you say that your code got into a bad state somehow. Could you try to reproduce the exact steps needed for that to happen?

**Comment by TheBlueOompaLoompa** [comment]
Never mind, I have had issues in the past with stackblitz randomly updating sveltekit and switching to a native binary that is incompatible, I just assumed this was one of those times, but it turns out that was wrong. Sorry for wasting your time.
