### ISSUE TITLE
No "Dependencies" section

### ISSUE THREAD

**Issue by Deewens** [stackblitz/webcontainer-core#653]
### Describe the bug

Hi,

I wanted to try the Getting Started Tutorial of Angular https://angular.io/start
They are using StackBlitz, however, I have an error about my dependencies: "Cannot find module '@angular/core' or its corresponding type declarations.(2307)".

Also, I cannot install those missing dependencies because the Dependencies section does not exist.

![image](https://user-images.githubusercontent.com/26287270/160618396-3423e09f-20a6-4e6e-a05d-288e6e4acf39.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-ratwrk

### Steps to reproduce

1. Go to my Blitz
2. Check if there is the "Dependencies" section.

### Expected behavior

The "Dependencies" section should be displayed I think.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/26287270/160618760-3ef8af00-c1ed-4924-b46a-c923a49dbd60.png)

### Platform

```
Browser name  = Chrome
Full version  = 91.0.4472.114
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93878738,
  "usedJSHeapSize": 83405458,
  "jsHeapSizeLimit": 1098907648
}
Hash = 0e61f5616522419418be8a0cc53f5e2e645f635f
```

**Comment by jrvidal** [comment]
@Deewens Thanks for the report.

The UI is different b/c you're in a WebContainer project, which works differently from our classic "EngineBlock" projects, which is what you might be used to. We now have [some docs](https://developer.stackblitz.com/docs/platform/available-environments) clarifying the difference.

See for instance my comment in https://github.com/stackblitz/webcontainer-core/issues/591#issuecomment-1036597703.

**Comment by d3lm** [comment]
I have closed this issue for now. If there are actions to take here we can open a new issue.
