### ISSUE TITLE
"... run Node.js, entirely inside your browser"

### ISSUE THREAD

**Issue by guest271314** [stackblitz/webcontainer-core#658]
### Describe the bug

This article https://blog.stackblitz.com/posts/introducing-webcontainers/ claims

> run Node.js, entirely inside your browser

Is that claim true and correct?

Is there an example of the code required to do that locally?

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-uccx6z

### Steps to reproduce

Try to reproduce this claim locally, offline:

> run Node.js, entirely inside your browser

### Expected behavior

> run Node.js, entirely inside your browser

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

No clear, step by step exaple of running WebContainers ("run Node.js, entirely inside your browser") locally.

**Comment by jrvidal** [comment]
@guest271314 Thanks for the report.

I'm not exactly sure what is the scope of your question. The blog post you linked and the docs in this repo go into some detail of what WebContainer is, and what it can do. The project you linked above does show those capabilities. If you have a more concrete question, we'd be happy to help.

**Comment by guest271314** [comment]
I couldn't detrmine if the linked stackblitz is working asc excpected. The goal is to run Node.js in the browser - outside of stacckblitz. How to do that?

**Comment by jrvidal** [comment]
It is working as expected. If you type `node index.js` in the embedded terminal, the code will be executed as in a Node environment.

> outside of stacckblitz

Not sure if you're asking how to use this outside of https://stackblitz.com, but the answer is that this is not possible, WebContainer is part of our online IDE.

**Comment by guest271314** [comment]
> Not sure if you're asking how to use this outside of https://stackblitz.com/, but the answer is that this is not possible, WebContainer is part of our online IDE.

Yes, that is the question. 

The advertised claim does not include that qualification.

**Comment by guest271314** [comment]
node-v17.8.0-linux-x64/bin/node into N discrete files here https://github.com/guest271314/node_executable. 

To reconstruct the executable, pertinent part

```
while (true) {
    readable = await fetch(`${path}node_${n++}.txt`)
      .then((r) => r.body)
      .catch((e) => false);
    if (readable === false) {
      break;
    }
    await readable.pipeTo(writable, { preventClose: true });
  }
  await writable.close();
```

Now I can dynamically fetch and run node in the browser utilizing Native Messaging, without WebAssembly. Then delete the file when done with the requirement. 

WebContainers needs to be at least as simple as that procedure. 

First we need to deal with the universal claims made without making sure it is known that claim applies only you your Website.

**Comment by guest271314** [comment]
Node.js, and 680 other languages can be run in the browser at https://tio.run/#javascript-node (https://github.com/TryItOnline).  

Node.js can be run in the browser using Native Messaging https://github.com/simov/native-messaging?

What is novel about WebContainers?

**Comment by EricSimons** [comment]
WebContainers run Node.js entirely _inside_ your browser, not on a remote server or local binary.

We currently do not expose a way to use WebContainer outside of StackBlitz.com, but this is something we're looking into. We'll post updates to this repo over the next quarter or so with our progress.

Closing this issue for now but lmk if you have other questions!

**Comment by guest271314** [comment]
> WebContainers run Node.js entirely inside your browser, not on a remote server or local binary.

> We currently do not expose a way to use WebContainer outside of StackBlitz.com

I don't understand that. 

On the one hand you claim Node.js is running entirely inside my browser.

On the other hand you say that only works on your Website.

So folks don't have to scour through your source files and reverse engineer your gear, FWIW, why not just openly release the Node.js WASM files as FOSS?
