### ISSUE TITLE
Refreshing page triggers infinite refreshes

### ISSUE THREAD

**Issue by PH4NTOMiki** [stackblitz/webcontainer-core#660]
### Describe the bug

If I click `Open in New Window (Live)` the page loads without any problem in new window, but if I do `F5` it just keeps on refreshing.

### Link to the blitz that caused the error

https://stackblitz.com/edit/sveltejs-kit-template-default-n7ocxm?file=src%2Froutes%2F__layout.svelte&terminal=dev

### Steps to reproduce

1. Go to repro link
2. Start server
3. Click Open in new window
4. The page loads
5. Do F5
6. it keeps refreshing

### Expected behavior

It doesn't infinitely refresh itself.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
performance.memory = {
  "totalJSHeapSize": 96555984,
  "usedJSHeapSize": 91368116,
  "jsHeapSizeLimit": 2172649472
}
Hash = 31afbfcfe1b0985e8cbdb27d44e16766166a118e
```

**Comment by d3lm** [comment]
Hey there 👋 

I can't seem to reproduce your issue on my end. If I open the page in a new window and then reload the page it works fine. If you open the dev console for both the editor and the preview window, are there any errors?

**Comment by PH4NTOMiki** [comment]
![Screenshot_20220408_195318](https://user-images.githubusercontent.com/35368241/162495573-3cd87b50-2293-4bb6-adef-a92a38c67d4d.png)

**Comment by PH4NTOMiki** [comment]
![Screenshot_20220408_195406](https://user-images.githubusercontent.com/35368241/162495669-c8e19824-035f-4289-96b8-e40b8bbb9156.png)

**Comment by PH4NTOMiki** [comment]
It looks like it's trying to load the page from some Cloudfront server and not my own  machine.

**Comment by PH4NTOMiki** [comment]
It's working okay if I close DevTools, but not if it's on

**Comment by d3lm** [comment]
Can you try in Chrome? I see you're using Edge, not sure if it's related but I still can't reproduce this issue on my end.

**Comment by PH4NTOMiki** [comment]
@d3lm thank you so much, that last thing you said helped me figure out what was wrong, because when I opened it in Chrome, it was working, and when combined that with the fact that it's not working only if I open DevTools helped me figure out that the issue was me toggling checkbox Bypass for Network for Service workers a long time ago. Immediately when I disabled it, it was working with no issue.

**Comment by d3lm** [comment]
Ohhh yes that's right. Bypassing service worker breaks it pretty much. The network layer depends on it. Glad it's working now 👍
