### ISSUE TITLE
Support node --experimental-vm-modules

### ISSUE THREAD

**Issue by dpeek** [stackblitz/webcontainer-core#661]
## Problem
I'd like to be able to use frameworks that dynamically load ES modules into a running node program, like `jest` and `miniflare`. 

Issues #307 #614 are likely because running the WASM version of node with `--experimental-vm-modules` shows no error, but running the following in Stackblitz demonstrates it has no effect:

```javascript
// test.js
const vm = require('vm');
console.log('SourceTextModule' in vm);
```

```bash
$ node --experimental-vm-modules test.js
false
```

(note: it seems you can pass any flag to WASM node without error?)

## Solution
Support the `node --experimental-vm-modules` flag to allow this capability.

**Comment by d3lm** [comment]
Hey there 👋 

I have started working on this and I'll keep you posted when it's available on production.

**Comment by d3lm** [comment]
This is now available on production. I have created an [example](https://stackblitz.com/edit/node-kowhgs?file=index.js) for you.
