### ISSUE TITLE
Websocket connections fail

### ISSUE THREAD

**Issue by edusperoni** [stackblitz/webcontainer-core#662]
### Describe the bug

When trying to connect through websockets to a remote url I get a CORS error:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/4061767/162248639-d8544932-0a38-4355-bad6-da391582b95f.png">

>Access to fetch at 'https://socketsbay.com/wss/v2/2/demo/' from origin 'https://node-xgyunu.w.staticblitz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

StackTrace:
```
performHTTPCall @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15
_write @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15
writeLatin1String @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15
writeLatin1String @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15
(anonymous) @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
writeGeneric @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
Socket._writeGeneric @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
Socket._write @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
doWrite @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
clearBuffer @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
Writable.uncork @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
OutgoingMessage._flushOutput @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
OutgoingMessage._flush @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
onSocketNT @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6
(anonymous) @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15
(anonymous) @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15
_0x455038 @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15
_0x988000.<computed>.<computed> @ https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15
```

The app also crashes with the following error message, instead of gracefully treating the error:
```
TypeError: Failed to fetch
    at _0x1874c8.performHTTPCall (https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:15:383215)
```

This request works fine by using devtools to run a normal `new Websocket('...')` connection.

Additionally, trying to use a raw http socket to create a websocket also doesn't work. The websocket connects, but the server crashes with:

```
~/projects/node-xgyunu
❯  npm run server
$ node ./server.js
{ port: 9898, address: '::', family: 'IPv6' }
Client connected
TypeError: n.writeAsciiString is not a function
    at https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:790399
    at writeGeneric (https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:790583)
    at Socket._writeGeneric (https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:237560)
    at Socket._write (https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:237718)
    at https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:878804
    at _write (https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:878865)
    at Socket.Writable.write (https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:882522)
    at WebSocketRequest.accept (/home/projects/node-xgyunu/node_modules/websocket/lib/WebSocketRequest.js:458:21)
    at WebSocketServer.eval (/home/projects/node-xgyunu/server.js:12:30)
    at WebSocketServer.EventEmitter.emit (https://node-xgyunu.w.staticblitz.com/blitz.31afbfcfe1b0985e8cbdb27d44e16766166a118e.js:6:155505)
```

on the line:

```
const connection = request.accept(null, request.origin);
```

The client connection then hangs.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-xgyunu?file=index.js&terminal=server&terminal=client

### Steps to reproduce

1. open the project
2. if terminals didn't open, open 1 terminal with `npm run server`
3. open second terminal with `npm run client`
4. comment out the specific `setupWs` to test local/remote individually

### Expected behavior

Application should run normally and you should see a couple of messages being exchanged back and forth.

If any connection fails, you should see the message:

> if everything was working correctly, this message should show up regardless of socket errors

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 100.0.4896.75 (Official Build) (arm64)

**Comment by d3lm** [comment]
Hey there, thanks for reporting this issue. I can confirm that this is not behaving as it should and it's most likely a bug on our side. I have created a ticket in our internal ticket system, and we'll keep you posted on any progress or once it's resolved.

**Comment by rayfoss** [comment]
I can't reproduce this...
I managed to link this Stackblitz https://stackblitz.com/edit/nodemon-n6nrt7?file=vite.config.ts to this CodeSandbox
https://codesandbox.io/s/socket-io-vanilla-c2gh56

I just had to configure `cors { origin: '*' }` on the socket.io server.

This is not related to issue #668

**Comment by rayfoss** [comment]
I made an example of a WebSockets relay in StackBlitz... it's not pretty, but it works
https://stackblitz.com/edit/nodemon-xyvji4?file=vite.config.ts

**Comment by d3lm** [comment]
@edusperoni I tried to reproduce your issue but it looks like it works for me. Is this still an issue?

**Comment by edusperoni** [comment]
Nope! Thanks!
