### ISSUE TITLE
Chrome: Web Serial API is not Available

### ISSUE THREAD

**Issue by fdeitelhoff** [stackblitz/webcontainer-core#663]
### Describe the bug

I am trying to use the web serial API in chrome but get the error

```[Violation] Permissions policy violation: serial is not allowed in this document.```

and

```Uncaught (in promise) DOMException: Failed to execute 'requestPort' on 'Serial': Access to the feature "serial" is disallowed by permissions policy.```

in the chrome developer console. It is a Vite + Vue 3 + TypeScript project which works fine locally.

### Link to the blitz that caused the error

https://stackblitz.com/edit/web-serial-api-example

### Steps to reproduce

1. Open the project
2. Open the console
3. See the error

### Expected behavior

Access to the web serial API should be possible.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/1618135/162587458-715de3a6-0f07-49a8-8167-48e579892f1c.png)

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.75
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82300663,
  "usedJSHeapSize": 78038803,
  "jsHeapSizeLimit": 4294705152
}
Hash = 31afbfcfe1b0985e8cbdb27d44e16766166a118e
```

**Comment by d3lm** [comment]
Hey there 👋 

This is an issue with our preview window. If you open it in a separate tab it should work. However, there is a differenterror:

`Must be handling a user gesture to show a permission request`

and it looks like the API is not used correctly. The `requestPort` has to be used inside a function that responds to a user action, e.g. a click handler. So changing it to 

```js
const getSerialPorts = async () => {
  const ports = await navigator.serial.requestPort();
};
```

fixes it. And for the time being you need to open it in a separate tab.

**Comment by SamVerschueren** [comment]
I think we can add this to the permission list of the iframe, it's pretty straight forward. What do you think @d3lm ?

**Comment by d3lm** [comment]
@SamVerschueren Yep, I was thinking the same 👍

**Comment by SamVerschueren** [comment]
@fdeitelhoff Do you happen to have your project that didn't work? It seems the project linked in the OP does not exist anymore.

**Comment by SamVerschueren** [comment]
This issue is addressed and it should now be possible to use these Web Serial APIs in the preview iframe.

As an example, click the button in the middle of the screen and the serial pane popup should open https://stackblitz.com/edit/nextjs-cgjgwt?file=pages%2Findex.js
