### ISSUE TITLE
All WC to WebSocket server requests fail with `400 BadRequest` error, breaking Chat bots, unit tests, DB connections, multi-process optimizations, dependencies and integrations

### ISSUE THREAD

**Issue by rayfoss** [stackblitz/webcontainer-core#665]
### Describe the bug

Trying to connect to a WebSockets server from WebContainers causes a 400 Bad Request error. This happens even when connecting to a Socket.io server hosted in the same WebContainer, **and** when connecting to remote Socket.io servers from within a WebContainer.

Connecting to WebSockets servers from the browser works normally, as long as CORS is configured. **this issue is not about connections from the browser**. This issue is exclusively about connecting from WebContainers to WebSocket servers, be it hosted in WebContainers or on an external Node.js server. **No browser code at all is necessary to encounter this issue.**

This affects:
- Chatbots
- Socket.io and Feathers api tests
- Connections to DBs from SB via a external WebSockets servers
- Access to WebSockets based live data APIs
- Dependencies and utilities that spawn a new node process to connect to your WS server

### Link to the blitz that caused the error

Simplest socket.io example: https://stackblitz.com/edit/sb-ws-bug?file=vite.config.ts,ReadMe.md

Other sandboxes suffering from this (Feathers does not support polling mode):
Feathers4 / Socket.io 2.4: https://stackblitz.com/edit/feathersjs-i8qr6f?file=README.md
Feathers5 / Socket.io 4.4: https://stackblitz.com/edit/vitejs-vite-ktyczk?file=README.md

### Steps to reproduce

1. run `npm run dev`

### Expected behavior

All posted Guestbook messages will print to the console.

### Actual Behavior

- Status code 400 'Bad Request' errors.
- WebContainers unable to connect to WebSockets servers, even ones running in WCs

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

From reproduction sandbox:
![{912B029F-8E8E-47BA-A788-84F081622A99}](https://user-images.githubusercontent.com/876076/173211307-85cd84db-f8fc-461a-84c7-2687f16688ad.png)

Same code in bare-metal Node.js:
![{26BB7518-1A14-4A18-A331-B923EBDCEDD3}](https://user-images.githubusercontent.com/876076/173211639-bc2f4458-c180-46c7-bb7c-8cfa477c22ad.png)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 100

### Additional context

Suspicious line of code in file:///root/project/packages/browser-node/@node/_http_client.js
```
// If the user did not listen for the 'response' event, then they
// can't possibly read the data, so we ._dump() it into the void
// so that the socket doesn't hang there in a paused state.
if (req.aborted || !req.emit('response', res))
res._dump();
```

Upgrade requests seem to be getting handled as a normal response, and then disconnected.

Workarounds:

- It is possible to use the browser as a WebSockets relay
  - Abomination: https://stackblitz.com/edit/nodemon-xyvji4?file=vite.config.ts
  - This only works for basic socket.io apps. If you use a library on top of socket.io, you'll have to create custom glue code and won't have a way to make a general relay. As there is no public API for socke.io connect event spoofing, and to spoof it we need the original connect event that we can use to call dispatchEvent.
- connection upgrades might work if we set a dummy 'response' event listener on the upgrade request... This isn't possible to do with Socket.io, so it's not viable for most people, if it works.

**Comment by HeyGarrison** [comment]
Closing this issue as *I think* it's a duplicate fo #662

**Comment by rayfoss** [comment]
@HeyGarrison it's not a duplicate, please reopen.

**Comment by d3lm** [comment]
Yes, we have an issue with server-side websockets which we have tracked internally. We'll keep you posted with any updates.

**Comment by rayfoss** [comment]
> Is [stackblitz/core#1876](https://github.com/stackblitz/core/issues/1876) the same issue maybe?

It's not related... That's a configuration issue, it's trying to connect on port 3000 when it should connect on 443. Similar to this https://github.com/vitejs/vite/issues/5153

This bug is exclusively about connecting **to any websocket server from Node.js**. Connecting from the browser has no known issues.

**Comment by rayfoss** [comment]
I've confirmed the latest StackBlitz still exhibits this issue. I've updated the bug reproduction sandbox to clarify expected behavior, and reduce timeouts hiding the connection error from 20 seconds to 3. 

New Reproduction (OP also updated): https://stackblitz.com/edit/sb-ws-bug?file=vite.config.ts,ReadMe.md

**Comment by rayfoss** [comment]
@d3lm Thanks for the heads up.... THIS IS A HUGE improvement, and will go a long way into helping me use SB for Feathers.js projects, which exclusively rely on WS. To clarify when you say `localhost` you meant StackBlitz WebContainer localhost, not baremetal localhost, which would actually work fine if you use Chrome's `example.localhost` TLD's.

I still do have REPLs that can't run and **extremely** weird behavior when connecting from one SandBox to another, running on the same browser session and SB user account. I try to connect to Sandbox's WC WS server by changing the URL, and it connects to the localhost WC WS server.

That's a bit of a deal breaker for projects that have separate but cozy repos for server and clients. I'll just connect to a real staging server in the meantime. 

WC Node.js connecting to a containerd Node.js in CodeSandbox:
![{9343B83E-8BE7-475D-B720-C28D445E3534}](https://user-images.githubusercontent.com/876076/173697213-c4585ea1-731a-41da-b655-6992618d734e.png)

I'll rewrite this issue as it's effectively half fixed...

P.S. For anyone curious I'm using @seald/nedb for a database in development, it runs in SB, specially now with improved file io... but MongoDB should work very well with _get, _find, etc DB service adapter hooks... which effectively turn any database into an unfiltered WebSocket DB.

**Comment by d3lm** [comment]
Yes that's correct. You can't connect to a server from a process running in a separate project. You'd have to pull the client and server into the same project and create 2 terminal windows and start both client and server from the same project. Or maybe I misunderstood what you are trying to do.

Also, when I say `localhost` I mean WebContainer's `localhost`. You **can** connect to your machine's localhost if you configure your server to be reachable via a domain other than `localhost` using the hosts file.
