### ISSUE TITLE
Webpack compilation stops at "asset processing"

### ISSUE THREAD

**Issue by chenjiahan** [stackblitz/webcontainer-core#668]
### Describe the bug

I am a maintainer of [modern.js](https://github.com/modern-js-dev/modern.js), a frontend framework based on Webpack.

I'm trying to put our project template on stackblitz, but the Webpack compilation stops at `asset processing`, and it's hard to debug the issue on stackblitz. 

Is there a way to debug or fix the problem?

### Link to the blitz that caused the error

https://stackblitz.com/edit/modern-js-zf6lih-cpw3by?file=package.json

### Steps to reproduce

1. Open the blitz.
2. Wait the Webpack compilation.

### Expected behavior

Finish webpack compiling and start the dev server.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/7237365/163135179-65fb2bbb-1c5d-4494-a9a9-a0ff0aae63be.png)

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [100]

**Comment by xiangst0816** [comment]
Watching the progress of this issue

**Comment by chenjiahan** [comment]
@d3lm Can you help us to run this project on stackblitz?

**Comment by d3lm** [comment]
We'll have to look into the issue but I can't give an exact timeline on this. We'll keep you posted with any updates.

**Comment by d3lm** [comment]
@chenjiahan Thanks a lot! That would be very helpful and speed up a resolution.

**Comment by chenjiahan** [comment]
@d3lm Hi, I have reproduce this issue in the webpack starter: https://stackblitz.com/edit/webpack-webpack-js-org-qubp1x

This issue can be reproduced after adding the [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) plugin (a widely used webpack plugin which provides typescript type checking).

**Comment by d3lm** [comment]
Thanks for reproducing the issue in a smaller scope. That's very interesting that this plug-in breaks it because we have an internal integration test for this. Must be a newer version maybe. I ll have a look. Thanks again for your work on this, it's very helpful.

**Comment by d3lm** [comment]
I quickly verified and it breaks since version 7. If you install 6 it works fine, so I need to take a closer look.

**Comment by d3lm** [comment]
Alright, this is the PR that broke it https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/691. We'll investigate further.

**Comment by chenjiahan** [comment]
Thanks for the quick feedback, looking forward to further progress 😄

**Comment by d3lm** [comment]
@chenjiahan Good news Sir. I have identified the issue and have fixed it. It will most likely be deployed early next week.

**Comment by chenjiahan** [comment]
Good job 🎉🎉🎉
