### ISSUE TITLE
HTTP requests impossible using external tool.

### ISSUE THREAD

**Issue by reesericci** [stackblitz/webcontainer-core#671]
### Describe the bug

Using either hoppscotch.io (with and without the browser extension) or Postman, I am unable to send any HTTP request (GET,POST,PUT,PATCH etc). This unfortunately makes it impossible to test any API software that relies on anything other than GET and query params.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-tewjah?file=src%2Froutes%2Fthoughts%2Findex.ts

### Steps to reproduce

Make GET request using hoppscotch.io to /thoughts/__data.json to the WebContainer.

### Expected behavior

GET request succeeds, returns JSON from database.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.88
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 193105115,
  "usedJSHeapSize": 185428943,
  "jsHeapSizeLimit": 2172649472
}
Hash = 49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf
```

**Comment by jrvidal** [comment]
:wave: Thanks for the report. This is expected, as the preview URLs are not reachable from outside the browser where you're running WebContainer. We do have in our roadmap the possibility of adding a `curl` command you can run from the project terminal, which would be a possible workaround.

I'll add this to our internal tracker, but unfortunately, I can't offer you a timeline.

**Comment by kirjavascript** [comment]
Hi! `curl` is now available in the project terminal which you should be able to use for API testing

feel free to open another issue if there's anything else

**Comment by d3lm** [comment]
I also want to add that with our next generation editor you can install extensions, e.g., the Thunder client.
