### ISSUE TITLE
Not Executing in Stackblitz

### ISSUE THREAD

**Issue by AkellaPranav** [stackblitz/webcontainer-core#674]
### Describe the bug

Failed to resolve dependencies. ng is not a known command and not displaying output.
![image](https://user-images.githubusercontent.com/62413513/164212636-8c7ed0d5-e98d-4a35-8b1a-b3d27f4de908.png)

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fquestion-base.ts

### Steps to reproduce

go to https://stackblitz.com/edit/tgnmch--run?file=src/app/question-base.ts
and check while running where I got ng not a known command

### Expected behavior

Needed to execute and display output

### Parity with Local

- [x] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.127
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 131300802,
  "usedJSHeapSize": 127253042,
  "jsHeapSizeLimit": 2172649472
}
Hash = 49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf
```

**Comment by d3lm** [comment]
Hey there, can you please provide a project to reproduce the issue?

**Comment by d3lm** [comment]
Hey there, can you please provide a project to reproduce the issue? The link you provided does not work. Also, could you be more specific about the error you encounter?

**Comment by AkellaPranav** [comment]
Regarding this now it's working even I don't know how but it's ok now.
Generally sometimes while opening stackblitz output is not being displayed.

**Comment by SamVerschueren** [comment]
Let's close this issue for now. Let us know if there's something else we can help with.
