### ISSUE TITLE
AngularPrueba

### ISSUE THREAD

**Issue by Naraku7777** [stackblitz/webcontainer-core#676]
### Describe the bug

....

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

....

### Expected behavior

....

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

...

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.127
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63471156,
  "usedJSHeapSize": 60535264,
  "jsHeapSizeLimit": 2172649472
}
Hash = 49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf
```

### Additional context

...

**Comment by d3lm** [comment]
Closing this issue due to missing information. The link provided points to a non-existing project.
