### ISSUE TITLE
Images fail to copy when forking a blitz imported from github

### ISSUE THREAD

**Issue by jmcooper** [stackblitz/webcontainer-core#677]
### Describe the bug

Forking a blitz imported from Github fails to copy the images to the forked blitz. The image files do appear but seem have no content in them. It's odd because you can view the images in the embedded editor, but they won't load in the browser. When troubleshooting this on the StackBlitz discord, @TheTiGuR pointed out that the files in the newly forked repo have a length of zero. You can see that conversation here: https://discord.com/channels/364486390102097930/364486390102097932/966763058418552962

This behavior doesn't occur with Engine, only with WebContainers which you see by loading and forking these two blitz's. The only difference between the two is the .stackblitzrc file exists in the first, but not in the second:

WebContainers: https://stackblitz.com/github/jmcooper/stackblitz-webcontainers-example
Engine: https://stackblitz.com/github/jmcooper/stackblitz-webcontainers-example/tree/engine

This issue also seems to be tied to importing from GitHub (so GitHub combined with WebContainers). Notice that you can clone this WebContainers blitz and the images work fine:
https://stackblitz.com/edit/stackblitz-webcontainers-images

### Link to the blitz that caused the error

https://stackblitz.com/github/jmcooper/stackblitz-webcontainers-example

### Steps to reproduce

To see it NOT working with WebContainers and GitHub:
1. Load this blitz: https://stackblitz.com/github/jmcooper/stackblitz-webcontainers-example
2. Notice that the images DO load in the embedded browser preview window.
3. Fork the repo
4. Notice that the images DO NOT load in the embedded browser preview window.
5. Also notice that you can actually click on the images in the embedded editor and they do appear.

To see it working with Engine:
1. Load this blitz: https://stackblitz.com/github/jmcooper/stackblitz-webcontainers-example/tree/engine
2. Notice that the images DO load in the embedded browser preview window.
3. Fork the repo
4. Notice that the images STILL load in the embedded browser preview window.

To see it working with WebContainers (but not imported from Github):
1. Load this blitz: https://stackblitz.com/edit/stackblitz-webcontainers-images
2. Notice that the images DO load in the embedded browser preview window.
3. Fork the repo
4. Notice that the images STILL load in the embedded browser preview window.

### Expected behavior

Images should still load in the embedded browser after forking a WebContainer blitz that was imported from GitHub.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

See this conversation in the Stackblitz Discord:
https://discord.com/channels/364486390102097930/364486390102097932/966763058418552962

**Comment by jmcooper** [comment]
Edited to add that this bug seems to only occur when using WebContainers AND GitHub.

**Comment by thescientist13** [comment]
noticed something similar myself in #493, not sure if related.  In my case, the image file itself still seems to be intact, but is broken in the browser.

**Comment by kc0tlh** [comment]
I have also been able to recreate this issue in Chrome on my Macbook Air:

Working pre-fork:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1532264/164699421-f4170e0f-9f76-41a0-a1f7-2386bc09c62e.png">

Not working post-fork:
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/1532264/164700052-01fdb900-7753-470e-b9e3-0a8311d8ab00.png">

I will shoot this over to the dev team for additional investigation!

**Comment by kc0tlh** [comment]
@jmcooper I have an update from the dev team:

> This is a known issue with the current git integration + WebContainer. The current workaround (as you discovered) is creating your WebContainer project without linking to a git repo. We are working on a complete refactor of the git implementation and will post updates here as they become available.

**Comment by kc0tlh** [comment]
@jmcooper this issue appears to be resolved! Both of your example links are now working as expected.
