### ISSUE TITLE
don't connect to online database

### ISSUE THREAD

**Issue by LuisAngel98** [stackblitz/webcontainer-core#679]
### Describe the bug

I have an online database (planetscale.com) with a single table and a single record.
This proyect works perfectly on my desk but in the editor it doesn't [work
![error](https://user-images.githubusercontent.com/94913839/165005502-77598c34-385a-48d9-b070-662e4ad40393.PNG)
![result](https://user-images.githubusercontent.com/94913839/165005504-02817611-b882-4a0d-a699-b6809f763fbb.PNG)

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-ngvhlg

### Steps to reproduce

1.execute node index.js 

### Expected behavior

receive a response to a query

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![result_mi_own_desk](https://user-images.githubusercontent.com/94913839/165005618-b2ad24d4-73c6-4353-b274-a2af0c45bc6d.PNG)
![result_stackblitz](https://user-images.githubusercontent.com/94913839/165005620-dc6fd56d-ace2-4352-b665-e7b8164c8564.PNG)

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.127
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 103113953,
  "usedJSHeapSize": 79536657,
  "jsHeapSizeLimit": 2172649472
}
Hash = 49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf
```

**Comment by d3lm** [comment]
Thanks for reporting this issue. There's nothing that jumps out immediately so we'll have to take a closer look. I have created a ticket in our internal system and when we get to it we'll post updates here.

**Comment by d3lm** [comment]
Quick update: This is not a bug but rather a feature which is currently not supported, which is connecting to a remote socket. We'll add this to our roadmap and make sure to post updates here if we start working on this. I can't promise any exact time frame for now.

**Comment by archiewood** [comment]
Would also love this feature.

Gitpod supports this, but is a worse UX than stackblitz, so would rather use stackblitz if possible.

**Comment by d3lm** [comment]
Hey 👋 Just wanted to give an update that this is still on our roadmap but I can't speak to an exact timeline. We keep you posted if there's any updates.

**Comment by kc0tlh** [comment]
I'm consolidating all of the database feature support requests into issue #749 for ease of tracking and due to @d3lm's excellent [explanation of the current state](https://github.com/stackblitz/webcontainer-core/issues/749#issuecomment-1460205393).
