### ISSUE TITLE
npx does not run binary from a GitHub repository

### ISSUE THREAD

**Issue by helloitsjoe** [stackblitz/webcontainer-core#68]
**Describe the bug**
`npx github:chalk/chalk-cli green "Hello world"` should pull and run `chalk-cli` from GitHub repo.

I'm not sure if this falls under [this section of the FAQ](https://github.com/stackblitz/webcontainer-core#faqs), but it seems like this should work similar to running a binary from a github repo locally.

Locally, these all run the `chalk-cli` binary from GitHub:
```
npx chalk/chalk-cli green "Hello world"
npx github:chalk/chalk-cli green "Hello world"
npx https://github.com/chalk/chalk-cli green "Hello world"
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/http-server-f8vdap

**To Reproduce**
1. Go to https://stackblitz.com/edit/http-server-f8vdap
2. In the terminal, run `npx chalk-cli green "Hello world"`
3. See "Hello world" display in green
4. In the terminal, run `npx github:chalk/chalk-cli green "Hello world"`
5. See error

**Expected behavior**
`npx` should run binary from GitHub repo

**Screenshots**
![image](https://user-images.githubusercontent.com/8823810/119244193-0ae2ce00-bb3c-11eb-9c5f-4e61eed3c017.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.6
 - Browser: Chrome
 - Version 90.0.4430.93 (Official Build) (x86_64)

**Comment by helloitsjoe** [comment]
Great project by the way 😄

**Comment by EricSimons** [comment]
Ah good find! Our npm client currently doesn't support pulling from git or any sources outside of the npm registry. Will take this back to the team and get this on the roadmap, thanks for letting us know (and for the kind words 🤗 )!

**Comment by SamVerschueren** [comment]
This now works correctly in [Codeflow](https://stackblitz.com/~/). We're probably not releasing the `git` binary for the classic editor, so closing this as solved.

<img width="313" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/1913805/675f2aef-2360-45be-85b5-22b5a8ca694f">
