### ISSUE TITLE
test

### ISSUE THREAD

**Issue by deecology** [stackblitz/webcontainer-core#681]
### Describe the bug

aaa

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

aaaa

### Expected behavior

aaaa

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

aaa

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.127
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 41167609,
  "usedJSHeapSize": 37995877,
  "jsHeapSizeLimit": 4294705152
}
Hash = be57dda01bcfe1c4973d7980b1ec44aabd3a6863
```

### Additional context

aa

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
