### ISSUE TITLE
Can't run webcontainer project multiple times in same browser context

### ISSUE THREAD

**Issue by HeyGarrison** [stackblitz/webcontainer-core#682]
### Describe the bug

Currently, we have a limitation in webcontainer where we cannot run the same webcontainer project multiple times and in the same browser context.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-pzsyik

### Steps to reproduce

1. Go to https://stackblitz.com/edit/nextjs-pzsyik
2. Let the server run
3. After the server is running open the same project in a new tab
4. Observer continuous "Running start command" message.

### Expected behavior

To be able to run multiple web container projects.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 100

**Comment by rayfoss** [comment]
Fixing this seems like it would make the behavior of the WC less deterministic. CodeSanbox's Containers also don't support this, and in a way bare-metal doesn't support having 2 processes listening on the same port. Forking is cheap...

That's said, connecting between two different WebContainers should work. And connecting to another port in the same WC but from a different node process,  should also work. Which is what #719 addresses.

**Comment by Nemikolh** [comment]
This has been fixed! :tada: We have support for running the same project opened in multiple tabs :partying_face:
