### ISSUE TITLE
Getting SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by RafidMuhymin** [stackblitz/webcontainer-core#683]
### Describe the bug

I am getting `SyntaxError: Unexpected strict mode reserved word` when trying to import the `@astropub/codecs` package. I am able to import the same when a Vite server is running. So, Vite is able to load the package but Node.js is not. It's only specific to StackBlitz. Because I am not getting the issue locally or in other cloud environments like GitPod and CodeSandbox.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-bechwn?file=index.mjs

### Steps to reproduce

1. Run `node index.js`

### Expected behavior

StackBlitz should load the `@astropub/codecs` package without any issue.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![](https://cdn.discordapp.com/attachments/956954142562217995/970641857677766746/unknown.png)

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.82
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 63024822,
  "usedJSHeapSize": 61007138,
  "jsHeapSizeLimit": 2172649472
}
Hash = be57dda01bcfe1c4973d7980b1ec44aabd3a6863
```

**Comment by d3lm** [comment]
Hey there 👋 Thanks for reporting this issue. I have taken a look and can confirm that this is a bug in our runtime. I have created a ticket for this and we'll get back to you when there's progress.

**Comment by d3lm** [comment]
Good news, I have already worked out a fix. I ll keep you posted once it's deployed to production.

**Comment by RafidMuhymin** [comment]
Awesome @d3lm ! Thank you so much for your quick response!

**Comment by d3lm** [comment]
This is now fixed and I confirmed your linked project works without errors now.
