### ISSUE TITLE
`peerDependenciesMeta` is not being honored

### ISSUE THREAD

**Issue by thescientist13** [stackblitz/webcontainer-core#684]
### Describe the bug

NPM specification defines support for a field in _package.json_ called [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta).
```json
{
  "name": "tea-latte",
  "version": "1.3.5",
  "peerDependencies": {
    "tea": "2.x",
    "soy-milk": "1.2"
  },
  "peerDependenciesMeta": {
    "soy-milk": {
      "optional": true
    }
  }
}
```

I observed that in my Stackblitz project when it installs in a project that has this field in _package.json_, the optional dependencies were still trying to get installed anyway.

### Link to the blitz that caused the error

https://stackblitz.com/github/projectevergreen/greenwood-getting-started

### Steps to reproduce

1. Load the stackblitz
2. Wait for install to complete
3. Observe the message about postinstall scripts

In this case, it looks like it is still trying to install **puppeteer**, which is coming from the [**@greenwood/cli**](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/package.json#L29) dependency.
```sh
npm install && npm start
┌ [1/4] 🔍  Resolving dependencies
└ Completed in 0.183s
┌ [2/4] 🚚  Fetching dependencies
│ info pruneDeps Excluding 1 dependency. For more information use `--verbose`.
└ Completed in 1.816s
┌ [3/4] 🔗  Linking dependencies
└ Completed in 0.223s
info security We found `install` scripts which turbo skips for security reasons. For more
information see https://turbo.sh/install-scripts.
└─ puppeteer@13.5.2
```

### Expected behavior

Stackblitz should not try and install anything associated with the `peerDependenciesMeta` field when set to `optional`.  

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1414" alt="Screen Shot 2022-05-03 at 08 08 47" src="https://user-images.githubusercontent.com/895923/166450126-ab994b8c-9884-4bd2-b92e-02adc7a521fb.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 100

**Comment by d3lm** [comment]
Hey there 👋

Yes that's correct, `peerDependenciesMeta` is not taken into account. That said, our package manager (turbo) does not install peer dependencies and does not print any warnings about missing peer dependencies as often it's extremely verbose and you'll notice quickly at runtime if a dependency is missing. So it sounds strange that you're seeing peer dependencies being installed. For example check [this example](https://stackblitz.com/edit/node-v3ccew?file=package.json). If you run `npm install` you'll notice that `chalk` won't be installed. The same applies to any `peerDependencies` of your own dependencies and deep down the dependency tree.

**Comment by thescientist13** [comment]
Ok thanks for the info and yeah, according to the logs, Stackblitz is still warning about **puppeteer**, which per the logic in place, seems like it should not be logged, `peerDependenciesMeta` or otherwise.  🤔

**Comment by d3lm** [comment]
No worries at all. Glad we sorted it out 👍
