### ISSUE TITLE
Failed to boot WebContainer

### ISSUE THREAD

**Issue by FedericoBarberon** [stackblitz/webcontainer-core#685]
### Describe the bug

Every time I start a Node.js project I get the following message _**"Failed to boot WebContainer"**_. It also does not allow me to type anything in the terminal

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-r77mdz

### Steps to reproduce

Just open the blitz

### Expected behavior

I expect that it boots correctly and that it allows me to write in the terminal

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/66987826/166577122-bafd4fec-1c38-4d87-9646-81b84d81743b.png)

### Platform

```
Browser name  = Chrome
Full version  = 101.0.4951.54
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 51552608,
  "usedJSHeapSize": 49623224,
  "jsHeapSizeLimit": 503578624
}
Hash = be57dda01bcfe1c4973d7980b1ec44aabd3a6863
```

**Comment by d3lm** [comment]
Hey there 👋 Thanks for reporting this issue. Do you get any errors in the console? I see you're using Chrome. Without more information and steps to reproduce it's really difficult for us to act on this.

**Comment by FedericoBarberon** [comment]
![image](https://user-images.githubusercontent.com/66987826/167020523-7717209c-6a5e-4cbf-9702-7556bb197d7d.png)

**Comment by SamVerschueren** [comment]
Hi @FedericoBarberon 👋 . I believe we fixed this issue in the mean time. If you still run into issues trying to run WebContainer, feel free to create a new issue 🙏 .
