### ISSUE TITLE
Text doesn't copy

### ISSUE THREAD

**Issue by b264** [stackblitz/webcontainer-core#686]
### Describe the bug

1. Copy doesn't copy text onto the clipboard.  Neither the right-click context menu nor selecting "Copy" from the "Edit" menu.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fcdk-drag-drop-axis-lock-example.html

### Steps to reproduce

go to the blitz
Select some text
Right click the text (or) press Ctrl+c (or) select Copy from the Edit menu

### Expected behavior

The text should be copied to the clipboard.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 99.0
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0
performance.memory = undefined
Hash = be57dda01bcfe1c4973d7980b1ec44aabd3a6863
```

**Comment by SamVerschueren** [comment]
Could you close your browser, reopen it and try again? Or maybe even reboot your computer? I noticed that I sometimes have the same issue in other apps as well. To met it feels like a macOS bug, but I could be wrong. We don't do anything to prevent copy pasting at all.

**Comment by b264** [comment]
I'm not using Apple products.  I have since rebooted, but now following the link above no longer works.  So now, it's a new problem.

**Comment by d3lm** [comment]
The project no longer seems to be available and was deleted.

**Comment by SamVerschueren** [comment]
The problem with the link is that it's pointing to `stackblitz.com/run` which are dynamic projects and don't really exist. Can you remember where you clicked this link? Seems like something in the Angular Material docs maybe?

**Comment by b264** [comment]
That sounds about right, yes.  Unfortunately, the moment has passed.  I only even opened the issue since copy/paste not working is such a major problem, the platform is practically unusable without that functionality.

**Comment by SamVerschueren** [comment]
Hi @b264. Not being able to copy/paste is definitely an issue. However, this is not something we actively block and it should work. I currently have no clue why it doesn't work for you, because it works perfectly fine for me. Maybe it's something in the specific example that you opened. Do you have this on every project you open? Do you also experience this issue in Chrome?

**Comment by rayfoss** [comment]
@b264 try now... There was a copy shortcut bug that broke the shortcut outside MacOS.
