### ISSUE TITLE
Vitest: Unhandled Rejection on "onTaskUpdate"

### ISSUE THREAD

**Issue by shawntax** [stackblitz/webcontainer-core#687]
### Describe the bug

On Blitzs that use [Vitest](https://vitest.dev/), the node script `npm run test` or `npm run test:ui` errors out with an unhandled rejection after 30 - 60 seconds of editing:

```js
Error: [birpc] timeout on calling "onTaskUpdate"
 ❯ listOnTimeout https:/vitest-dev-vitest-vb9yin.w.staticblitz.com/blitz.331c80ffab288536319518a60349d00207075dad.js:6:306401
 ❯ processTimers https:/vitest-dev-vitest-vb9yin.w.staticblitz.com/blitz.331c80ffab288536319518a60349d00207075dad.js:6:307224
 ❯ https:/vitest-dev-vitest-vb9yin.w.staticblitz.com/blitz.331c80ffab288536319518a60349d00207075dad.js:15:207551
 ❯ https:/vitest-dev-vitest-vb9yin.w.staticblitz.com/blitz.331c80ffab288536319518a60349d00207075dad.js:15:207869
```
```(consoleCall @blitz.331c80ffab2885…9d00207075dad.js:15)```

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitest-dev-vitest-vb9yin?initialPath=__vitest__

### Steps to reproduce

1. Go to https://vitest.new/
2. Start editing code, open preview in new window, changing test cases and saving, etc.
3. After about 30 - 60 seconds of the script re-running automatically and HMR, the process will hit the unhandled timeout and exit

### Expected behavior

I expect to be able to edit project files continuously without the vitest node scripts exiting unexpectedly with an unhandled rejection

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1660" alt="Screen Shot 2022-05-04 at 4 20 14 PM" src="https://user-images.githubusercontent.com/8904630/166843909-7238b1de-b039-4cb1-8966-c1caa0644462.png">

### Platform

```
Browser name  = Chrome
Full version  = 101.0.4951.41
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62299310,
  "usedJSHeapSize": 57724026,
  "jsHeapSizeLimit": 4294705152
}
Hash = 331c80ffab288536319518a60349d00207075dad
```

### Additional context

I found this potentially relevant issue in Vitest: https://github.com/vitest-dev/vitest/issues/1154

**Comment by d3lm** [comment]
Hey there 👋 Just wanted to let you know that we started to investigate this issue. We keep you posted.

**Comment by d3lm** [comment]
Hey 👋 Is this still an issue? I tried to reproduce this again and I can't anymore. If I run the project you have linked it doesn't throw anymore.

**Comment by shawntax** [comment]
@d3lm Hey, I'm not sure? It's been a while so I wouldn't be surprised if it got fixed over time. I'll close this out and re-open if I run into it again.

**Comment by d3lm** [comment]
Ok cool, thanks!
