### ISSUE TITLE
ES modules don't work

### ISSUE THREAD

**Issue by johandalabacka** [stackblitz/webcontainer-core#69]
**Describe the bug**
ES 6 modules don't work. Neither as .mjs files or setting "type": "module" in package.json
The icon for mjs is also a generic text icon.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-dgisvu

**To Reproduce**
1. Create file test.mjs with just a console.log statement inside
2. Run it with node test.mjs
3. No output

**Expected behavior**
Should run console.log in mjs

**Desktop**
 - OS: mac os 11.3.1
 - Browser chrome
 - Version  90.0.4430.212

**Comment by EricSimons** [comment]
Ah yes, this is one of the limitations atm: https://github.com/stackblitz/webcontainer-core#limitations

WIP! Should have this enabled in the next few weeks.

**Comment by KwintenP** [comment]
Duplicate #6
