### ISSUE TITLE
Cannot run Vitest UI with Vue

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#699]
### Describe the bug

When trying to open Vitest UI in StackBlitz, a blank screen appears instead. The console log shows:

```none
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/vue.js?v=ac2f29cf' does not provide an export named 'createElementBlock' (at App.vue:2:35)
```

This does not happen locally.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vue-vitest-mock-module-function-nrzcsw?file=package.json,.stackblitzrc

### Steps to reproduce

1. Go to linked blitz.
2. Observe the blank screen appears in the preview window.
3. Observe the error message in the browser's console.

### Expected behavior

Vitest UI works normally like it does for non-Vue projects. https://vitest.new opens Vitest UI just fine, but that's a vanilla JS project.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.88
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68709055,
  "usedJSHeapSize": 64111911,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5428dc6786c976e0e08fde1105586a722833c4ef
```

**Comment by d3lm** [comment]
Hey 👋 Thanks for reporting this issue. I tried to reproduce this with the link you provided and was successful in doing so. I have also tested this locally and it works as well. I am not sure why that happens in WebContainer but not locally.

**Comment by d3lm** [comment]
Curious, can this be solved if the dependencies are updated? 🤔

**Comment by Nemikolh** [comment]
Hey! I just wanted to let you know that if you visit manually `__vitest__/` in your preview it works.

If you want to make sure that this path is always opened in the preview you can add the `initialPath` query parameter like so:

https://stackblitz.com/edit/vue-vitest-mock-module-function-nrzcsw?file=package.json,.stackblitzrc&initialPath=__vitest__/

I'm going to close this issue for now, let us know if you run into any other issues! :smiley:
