### ISSUE TITLE
BUG: node-fetch/https.get doesn't work (Socket hang up)

### ISSUE THREAD

**Issue by jonathansampson** [stackblitz/webcontainer-core#7]
---
name: Bug report
about: https://stackblitz.com/edit/node-zfkjjc?file=index.js
title: 'BUG: node-fetch/https.get doesn't work (Socket hang up)'
labels: 'http, socket, networking'
assignees: ''

---

**Describe the bug**
Unable to load remote data via node-fetch (or https module).

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-zfkjjc?file=index.js

**Expected behavior**

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Brave
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 56890553,
  usedJSHeapSize: 50431077,
  jsHeapSizeLimit: 4294705152
}

**Comment by KwintenP** [comment]
This is supposed to work. Bug confirmed.

Thanks for reporting 🙏

**Comment by janpio** [comment]
This is probably caused by the browser rejecting the request because of CORS reasons. From the linked Blitz above, I get this in my console before the hangup message comes:

```
Access to fetch at 'https://sampson.codes/' from origin 'https://node-zfkjjc.jw.staticblitz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Something very similar happens in our Node ORM Prisma, which needs to download a binary from a server to work: https://github.com/prisma/prisma/issues/7185

**Comment by janpio** [comment]
You can unblock yourself by installing for example this Chrome extension: https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en

**Comment by KwintenP** [comment]
Like @janpio said, this issue happens cause it's not possible to call the url from the browser's env, which is where WebContainer is running. 

See an example here: https://stackblitz.com/edit/typescript-ive2dd.

You need to make sure this call works, and then the v2 project should also work.
