### ISSUE TITLE
Error: Cannot find module './wasi'

### ISSUE THREAD

**Issue by ahaoboy** [stackblitz/webcontainer-core#705]
### Describe the bug

Run cmd gets error
```
node --experimental-wasi-unstable-preview1  ./index.js
```

```js
const wasi = require('wasi');
console.log(wasi);
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-9pdcrv?file=index.js,package.json

### Steps to reproduce

run cmd
```
node --experimental-wasi-unstable-preview1  ./index.js
```

### Expected behavior

Run correctly

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: win10
- Browser: Edge
- Version:  101.0.1210.53

**Comment by Nemikolh** [comment]
Hey @ahaoboy ! We've landed support for WASI :partying_face: :partying_face: 

You can read more about our support in [our blog post](https://blog.stackblitz.com/posts/announcing-wasi/).

Feel to open an issue if your run into any problem using WASI :smiley:
