### ISSUE TITLE
project node not work

### ISSUE THREAD

**Issue by bassemeloraby** [stackblitz/webcontainer-core#706]
### Describe the bug

it does not work

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-vfzjtl?file=app.js

### Steps to reproduce

111111111

### Expected behavior

11111111111

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

1

### Platform

```
Browser name  = Chrome
Full version  = 102.0.5005.61
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76870396,
  "usedJSHeapSize": 69475796,
  "jsHeapSizeLimit": 888143872
}
Hash = 670e941965b7233a68cb924e1ca43e6a0f35bf71
```

### Additional context

1

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
