### ISSUE TITLE
BUG: Official Snowpack, Preact Typescript starter doesn't work at all.

### ISSUE THREAD

**Issue by JuniorDEVed** [stackblitz/webcontainer-core#71]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
Fresh github repository using the official snowpack preact with typescript starter project fails to run when using npm start.

**Link to the blitz that caused the error**
https://stackblitz.com/github/juniordeved/snowpack-preact-typescript

**To Reproduce**
1. scaffold fresh snowpack preact typescript into a fresh stackblitz project using this url:"https://stackblitz.com/github/juniordeved/snowpack-preact-typescript"
2.  npm install is run automatically by the stackblitz web container
3.  run npm start to try to start the project in developer mode, error happens.

**Expected behavior**
Application runs in developer mode with the starter project running.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 92.0.4512.3
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4512.3 Safari/537.36
performance.memory = {
  totalJSHeapSize: 69501042,
  usedJSHeapSize: 65410166,
  jsHeapSizeLimit: 4294705152
}

**Additional context**
Bit of a letdown that we can't run official snowpack starter projects..... please support snowpack, preact, typescript

**Comment by KwintenP** [comment]
You are 100% right. We currently don't have support for this yet. 

Do remember that this software is in beta. We only have official support for NextJS. Everything else is still to be tested. We are def tracking adding support for this though! We are tracking this through issue #8!
