### ISSUE TITLE
test

### ISSUE THREAD

**Issue by yunkido** [stackblitz/webcontainer-core#712]
### Describe the bug

test

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-bvbnbr?file=index.js

### Steps to reproduce

ttt

### Expected behavior

ttt

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

ttt

### Platform

```
Browser name  = Chrome
Full version  = 102.0.5005.63
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 54783829,
  "usedJSHeapSize": 49235421,
  "jsHeapSizeLimit": 4294705152
}
Hash = ad37e903755d89e0f5d9999e69be73a0c6cb6bcc
```

### Additional context

ttt

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
