### ISSUE TITLE
new Slidev Project does not run

### ISSUE THREAD

**Issue by Gnadii** [stackblitz/webcontainer-core#718]
### Describe the bug

I have no idea what slidev is, but when I tried to start the project it failed

### Link to the blitz that caused the error

https://stackblitz.com/edit/slidev-plwf5t?file=slides.md

### Steps to reproduce

1. Go to https://stackblitz.com/?starters=docs
2. Click on Docs, Blogs and Slides 
3. Click on Slidev

### Expected behavior

it should install the dependencies and run the project

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 102.0.0.0
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 110202762,
  "usedJSHeapSize": 103053410,
  "jsHeapSizeLimit": 4294705152
}
Hash = bbb482e7415e406cfc62838751ca694c1dc24cf6
```

**Comment by rayfoss** [comment]
Odd... check your extensions. Clear your cache. Try on incognito mode? I have noticed SlideEV waits for a long timeout when you are missing local image assets.

![{DEA5B9B0-D360-4C5F-8CBC-F1A22AF8EA29}](https://user-images.githubusercontent.com/876076/173702055-7c04aa2d-d7a0-4d06-835a-6683385da413.png)
