### ISSUE TITLE
When launching project from GitHub, title customization has no effect

### ISSUE THREAD

**Issue by jfgreffier** [stackblitz/webcontainer-core#722]
### Describe the bug

When adding `title` argument to an URL, the title is not customized.

Reproduced on Chrome, Firefox

I'm following this documentation https://developer.stackblitz.com/docs/guide/open-from-github/#customizing-the-title

### Link to the blitz that caused the error

https://stackblitz.com/github/vercel/next.js/tree/canary/examples/hello-world?file=README.md&title=Hello%20World

### Steps to reproduce

1. Got to https://stackblitz.com/github/vercel/next.js/tree/canary/examples/hello-world?title=Hello World
2. Issue : The title remains Next.js Hello World Example, the defaults one

### Expected behavior

The title should be "Hello World"

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 102.0.0.0
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62971188,
  "usedJSHeapSize": 57818928,
  "jsHeapSizeLimit": 2172649472
}
Hash = bbb482e7415e406cfc62838751ca694c1dc24cf6
```

**Comment by sylwiavargas** [comment]
Hello @jfgreffier ✨ thank you for this bug report! 
The fix is already ready and we will merge it today.
Thank you for helping us make StackBlitz better!

**Comment by jfgreffier** [comment]
It is indeed fixed. Thanks !
