### ISSUE TITLE
Failed to run ng serve due to outdated angular versions

### ISSUE THREAD

**Issue by ansifi** [stackblitz/webcontainer-core#723]
### Describe the bug

I am not able to run the app due to outdated angular libraries and also i am not able to update the libraries. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-be5pvt?file=src%2Fapp%2Fapp.component.ts,package.json

### Steps to reproduce

run ng serve and you wil lsee the error

### Expected behavior

The app should run without any bugs

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 102.0.0.0
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 129602022,
  "usedJSHeapSize": 125079006,
  "jsHeapSizeLimit": 4294705152
}
Hash = bbb482e7415e406cfc62838751ca694c1dc24cf6
```

**Comment by d3lm** [comment]
I am going to close this one due to inactivity. If you think this is still an issue please file a new bug 🙏
