### ISSUE TITLE
Typescript does not work in files with $-Dollar prefix

### ISSUE THREAD

**Issue by Xiphe** [stackblitz/webcontainer-core#725]
### Describe the bug

Given a basic typescript file named `dollar-file.ts`

When I add a `$` prefix to the name
Then I do not get auto-completion or see type errors in the editor

Console shows the error:

```
errors.ts:19 Uncaught Error: Could not find source file: 'stackblitz:/%24dollar-file.ts'.

Error: Could not find source file: 'stackblitz:/%24dollar-file.ts'.
    at _ (mtsw-6b51915de75da.js:1:4332670)
    at Object.getQuickInfoAtPosition (mtsw-6b51915de75da.js:1:4342326)
    at e.getQuickInfoAtPosition (mtsw-6b51915de75da.js:1:4440418)
    at e.getQuickInfoAtPosition (mtsw-6b51915de75da.js:1:4441680)
    at r.fmr (workerMain.js:13:116573)
    at a._handleMessage (workerMain.js:13:65955)
    at Object.handleMessage (workerMain.js:13:65622)
    at f._handleMessage (workerMain.js:13:63696)
    at f.handleMessage (workerMain.js:13:63305)
    at a.onmessage (workerMain.js:13:65672)
    at errors.ts:19:12
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/typescript-knkbkg?file=%24dollar-file.ts,no-dollar-file.ts

### Bad Case:

1. open `$dollar-file.ts`
2. see no error and no type-hints, auto-complete etc in editor
3. see error in console

### Good Case:

1. open `dollar-file.ts` with identical content then `$dollar-file.ts`
2. see error and type-hints, auto-complete etc in editor
3. see no error in console

### Expected behavior

I would expect that `$-prefixed` files work.

This would be especially valuable because [Remix](https://remix.run) uses the prefix as a core feature of the framework

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Bad

<img width="645" alt="image" src="https://user-images.githubusercontent.com/911218/174673019-37fc8996-65d5-432c-ba09-2974fe47186d.png">

### Good

<img width="633" alt="image" src="https://user-images.githubusercontent.com/911218/174673124-0b59e4ea-ff63-4fff-9731-d69366150ada.png">

### Platform

```
Browser name  = Chrome
Full version  = 102.0.5005.115
Major version = 102
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 140336171,
  "usedJSHeapSize": 130688223,
  "jsHeapSizeLimit": 4294705152
}
Hash = bbb482e7415e406cfc62838751ca694c1dc24cf6
```

**Comment by SamVerschueren** [comment]
Thanks for reporting 🙏 ! This is indeed a bug. I'll let you know when it's fixed.

**Comment by SamVerschueren** [comment]
This is fixed now.

**Comment by Xiphe** [comment]
Wow, that was fast! Thank you 👍
