### ISSUE TITLE
envinfo does not work

### ISSUE THREAD

**Issue by sapphi-red** [stackblitz/webcontainer-core#727]
### Describe the bug

Running `npx envinfo` in shell does not end.
I traced the sourcecode of envinfo and found that the code below is not ending.

```js
require('envinfo')
  .run(
    {
      System: ['OS', 'Shell'], // it works if I remove 'Shell'
    },
    {}
  )
  .then((res) => {
    console.log(res);
  });
```

So something around this code is the culprit.
https://github.com/tabrindle/envinfo/blob/7fe97eab8054a2ea81d822eeba79aff0b4afd9c9/src/helpers/system.js#L62-L76

Running `SHELL=jsh npx envinfo` or `SHELL=echo npx envinfo` did not end too.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-jqepfp?file=index.js

### Steps to reproduce

1. Open [this project (same with above)](https://stackblitz.com/edit/node-jqepfp?file=index.js).
2. Run `node index.js` or `npx envinfo`.

### Expected behavior

- Error happens that something is not available if it won't work in webcontainer.

or

- `envinfo` outputs env info and finishes

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Windows 10
- Browser: Chrome
- Version: 104.0.5112.14（Official Build）dev

and

- OS: Windows 10
- Browser: Firefox
- Version: 101.0.1

### Additional context

Vite suggests users to create a reproduction with stackblitz and also says to run `npx envinfo`.
https://github.com/vitejs/vite/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml#:~:text=Please%20provide%20a,vitejs/*%7D%27%20%2D%2Dbinaries%20%2D%2Dbrowsers

**Comment by d3lm** [comment]
Hey! Thanks a lot for debugging the issue, this is super helpful for us 🙏 There seems to be a bug indeed in our runtime. We'll have a look and post an update once we get to it.

**Comment by sapphi-red** [comment]
@d3lm Today I checked this again and it seems to work now! 😃Thank you.

**Comment by d3lm** [comment]
Yes, that's right. A fix for this particular issue was deployed.
