### ISSUE TITLE
Creates `master` branch instead of `main`

### ISSUE THREAD

**Issue by IanVS** [stackblitz/webcontainer-core#729]
### Describe the bug

Hi, I created a repository from stackblitz, and was a little surprised to see that the default branch is called `master`, whereas most new repositories in GitHub use `main` instead.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-ccuzee?file=vite.config.js,package-lock.json,package.json,main.jsx,app.jsx&terminal=dev

### Steps to reproduce

Create a stackblitz, turn it into a repo, notice that it's using `master`.

### Expected behavior

The default branch should be named `main`.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

**Comment by sulco** [comment]
Hey @IanVS, thanks for reaching out! It's fixed now and all projects being connected to GitHub from now on will use `main`.

Thanks again for reporting this issue 🙏
