### ISSUE TITLE
BUG: Can't copy folders

### ISSUE THREAD

**Issue by alcuadrado** [stackblitz/webcontainer-core#73]
**Describe the bug**

Copying a folder, at least with `fs-extra`, results in an empty file being created instead.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-gtkmju

**To Reproduce**

1. Open the project
2. Run rm -rf target/ && node index.js 
3. An empty file called `target` gets created.

**Expected behavior**
An empty folder should be created instead.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 76887746,
  usedJSHeapSize: 67581566,
  jsHeapSizeLimit: 4294705152
}

**Comment by jrvidal** [comment]
@alcuadrado This looks fixed now!
