### ISSUE TITLE
SQLite db does not work after connecting to Github Repo

### ISSUE THREAD

**Issue by archiewood** [stackblitz/webcontainer-core#730]
### Describe the bug

SQLite binary included in Stackblitz is replaced with a link to a download when connected to a github repo.
This then fails to operate as a database.

### Link to the blitz that caused the error

https://stackblitz.com/fork/evidence?file=pages%2Findex.md

### Steps to reproduce

1. Go to above blitz
2. Click "Connect repository" and authenticate with Github
3. Inspect needful_things.db file - it has been changed from a binary to a link
4. Navigate to the page `tutorial:-basics.md` using the UI
5. You can see queries are failing both in terminal and UI with: `✗ orders_by_month SQLITE_NOTADB: file is not a database`

### Expected behavior

The stackblitz container would continue to work the same way before and after connecting to a git repository.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

Before connecting to repo:
<img width="1453" alt="CleanShot 2022-06-24 at 15 07 30@2x" src="https://user-images.githubusercontent.com/58074498/175649498-817ade8e-b118-4f1b-88d4-091ae17c65f1.png">

After connecting to repo:
<img width="1435" alt="CleanShot 2022-06-24 at 15 05 34@2x" src="https://user-images.githubusercontent.com/58074498/175649267-c7e1180b-5d23-43d0-a59a-bb47e7bcc1d1.png">

### Platform

- OS: macOS
- Browser: Tested on Chrome, Firefox
- Version: [e.g. 91.1]

**Comment by sylwiavargas** [comment]
Hello @archiewood! Thank you for reaching out. This is how our workflow currently works and we won’t be able to fix it for the current version of the editor. However, the good news is that we are a few months from a release that will allow to address this issue.
