### ISSUE TITLE
Intellisense is broken in the vue-ts vite environment

### ISSUE THREAD

**Issue by stam** [stackblitz/webcontainer-core#739]
### Describe the bug

Intellisense looks to be broken in vite single file components.
The editor does not seem to be able to parse the typescript.
If a create new string `const a = 'asdf';` and in the next line type `a.alsdslkfjfaasdfladskjf()` , I would expect the editor to understand `a` is a string and that this gibberish method does not exist and give eslint errors. Instead: nothing is happening

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-vdxrot?file=src%2Fcomponents%2FHelloWorld.vue,package.json&terminal=dev

### Steps to reproduce

Create a new vue-ts vite environment. 
Open helloworld.vue
Create a new string: `const a = 'asdf';`
On the new line, type `a` and wait for autocompleting: nothing happens.
Then write gibberish like `a.alsdslkfjfaasdfladskjf()` and expect eslint to complain.

### Expected behavior

I expect the editor to understand that `a` is a string and:
1. Autocomplete string methods
2. Give eslint errors for undefined function calls on a

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![stackblitz-vue](https://user-images.githubusercontent.com/12035356/177174600-8d449a07-71d4-4dba-aed5-908acb79ba05.png)

### Platform

```
Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 120786951,
  "usedJSHeapSize": 115439411,
  "jsHeapSizeLimit": 4294705152
}
Hash = b0de7779cd2868347677a5b8bbbf526e914eb012
```

**Comment by SamVerschueren** [comment]
Hey @stam, thanks for reporting! Let's close this in favour of #821 and continue the discussion there.
