### ISSUE TITLE
BUG: Can't load asm.js dependency

### ISSUE THREAD

**Issue by alcuadrado** [stackblitz/webcontainer-core#74]
**Describe the bug**

Trying to load an asm.js dependency, `rustbn.js`, fails.

This dependency is a rust project compiled to asm.js that's used in the ethereum ecosystem.

I don't know enough about asm.js, but as far as I can tell the error comes from one of the variables that represent the heap having a smaller size than in node.

**Link to the blitz that caused the error**

https://stackblitz.com/edit/node-iklvdk?file=index.js

**To Reproduce**

1. Run `node index.js`
2. An exception is thrown

**Expected behavior**

Node should run without printing anything.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 646292885,
  usedJSHeapSize: 582661801,
  jsHeapSizeLimit: 4294705152
}

**Comment by KwintenP** [comment]
Hi!

Thanks for reporting! This is a bug indeed.

**Comment by jrvidal** [comment]
@alcuadrado This looks fixed now!
