### ISSUE TITLE
issue while connecting remote repository

### ISSUE THREAD

**Issue by Rakeshrajput999** [stackblitz/webcontainer-core#741]
### Describe the bug

when I try to import an existing repository from my GitHub it will show a not found error.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-dq1lxr?file=README.md

### Steps to reproduce

1. click on connect repository
2. click on import an existing repo
3. copy-paste the GitHub repo HTTPS  URL 
4. click on the import repository button 
5. in my case it show not found error

### Expected behavior

after doing all steps I want my code in the editor 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 101.0.0.0
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78462430,
  "usedJSHeapSize": 74723778,
  "jsHeapSizeLimit": 4294705152
}
Hash = bff91798029e1af88e01551d056a592b2882b9ac
```

**Comment by sylwiavargas** [comment]
Hello @Rakeshrajput999! Thank you for your report - we've found the bug and successfully squashed it. Hope you'll have a lovely weekend 🌞

**Comment by Rakeshrajput999** [comment]
welcome @sylwiavargas
