### ISSUE TITLE
node_modules directory is not preserved on save & reload

### ISSUE THREAD

**Issue by privatenumber** [stackblitz/webcontainer-core#746]
### Describe the bug

When creating a directory called `node_modules`, it is not preserved.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-vkssor?file=index.ts

### Steps to reproduce

1. Start a project
2. Create a `node_modules` directory
3. Click save
4. Reload

### Expected behavior

For any work I save to be saved.

Or at least display a warning that `node_module` changes are not saved.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 95327612,
  "usedJSHeapSize": 58922676,
  "jsHeapSizeLimit": 4294705152
}
Hash = bff91798029e1af88e01551d056a592b2882b9ac
```

### Additional context

I wanted to use Stackblitz to create a minimal reproduction demonstrating how TypeScript resolves export maps in dependencies. I created a `node_modules` directory with a random test package but it kept getting deleted.

File structure:
```
node_modules
└── test-package
    ├── index.ts
    └── package.json
```

node_modules/test/package.json
```json
{
	"exports": "./index.js"
}
```

node_modules/test/index.ts
```ts
export default 1234;
```

**Comment by SamVerschueren** [comment]
Hi @privatenumber. Yes this is correct, the `node_modules` folder will not be preserved as we assume all of those packages come from npm anyways (which is normally the case). If we had to store all the `node_modules`, we would have to store a lot of duplicate data.

In this situation, you could just create a directory (outside `node_modules`) with a `package.json` and `index.ts` file and use a relative import.

```
project
├── index.ts
└── test-package
    ├── index.ts
    └── package.json
```

And then in `index.ts`, do an import of `./test-package`. I believe that should work 🤔 .

If that doesn't work, another alternative would be to symlink the `test-package` directory to `node_modules` on startup by using `.stackblitzrc`. Here's an example https://stackblitz.com/edit/node-3sdzvr.

Kind regards
Sam

**Comment by privatenumber** [comment]
This is mainly a DX issue for me because I unexpectedly lost work.

I recommend at least showing a warning that changes in `node_modules` will not be saved when manual changes are detected.
