### ISSUE TITLE
Projects imported from github should run `npm start` automatically after build just like next.js

### ISSUE THREAD

**Issue by ntucker** [stackblitz/webcontainer-core#75]
**Describe the bug**
`npm start` is a standard command, so non-next.js projects should be able to utilize this as well

**Link to the blitz that caused the error**

**To Reproduce**
1. https://stackblitz.com/github/Rest-Hooks/todo-example

**Expected behavior**
After npm install finishes, npm start should run

**Comment by KwintenP** [comment]
We use a framework detection to figure out the command we want to run. If it's a `nextjs` project, we will automatically run `next dev`. If we don't detect which framework it is (we currently only do this for next but extending this very soon), we don't do anything.

You can change the behaviour of how this works by adding a `.stackblitzrc` file to the blitz and setting `startCommand` to whatever you want. (https://stackblitz.com/edit/github-tvonzc?file=.stackblitzrc) 

It might make sense to run `npm start` by default for every project that has it. We'll take this under considiration.

**Comment by ntucker** [comment]
Are there docs on stackblitzrc anywhere?
