### ISSUE TITLE
Blitz fails to start with google-analytics is blocked?

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/webcontainer-core#750]
### Describe the bug

blitz does not start -- network errors in dev tools

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-6vy58p?file=package.json

### Steps to reproduce

1. open console
2. load blitz
3. see that first error has something about google-analytics
4. see failed to fetch in the terminal

### Expected behavior

blitz starts

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Windows
- Browser: Chrome, Firefox
- Version: latest as of 2022-07-15

**Comment by jrvidal** [comment]
:wave: Thanks for the report. I can't reproduce on my end. Is this still an issue for you? If so, could you attach the error messages you're seeing?

**Comment by NullVoxPopuli** [comment]
Likely not! Thanks!
