### ISSUE TITLE
WebContainers not working in chrome

### ISSUE THREAD

**Issue by eduardvercaemer** [stackblitz/webcontainer-core#754]
### Describe the bug

Stackblitz complains `Incompatible Web Browser` when using WebContainers in chrome. Projects work completely fine in Firefox.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-byctbg?file=src%2FApp.jsx

### Steps to reproduce

1. Create new project using WebContainers
2. Attempt to start project
3. Preview window shows incompatible error

### Expected behavior

I expect the project to boot up correctly and display the preview as the projects not using WebContainers.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/40474768/181142203-3e2bb746-7fd4-466c-bb89-acbba3f41d43.png)

### Platform

```
Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 142275950,
  "usedJSHeapSize": 117023946,
  "jsHeapSizeLimit": 2172649472
}
Hash = 872be04de15f32da2f6e3973878bcc22a4a17b5d
```

**Comment by Kenramiscal1106** [comment]
I also have that same issue in microsoft edge.

**Comment by CHANG-CHING-CHUNG** [comment]
I found that this issue only happended when creating a Node.js project.
When I created fron-end only projects, it worked fine.

**Comment by Marcisbee** [comment]
Same issue for me!
This showed up today for node projects, even tho worked fine before on the same chrome browser.

**Comment by SamVerschueren** [comment]
Thanks for reporting. This should now be resolved. Sorry for the inconvenience.
