### ISSUE TITLE
Incompatible Web Browser

### ISSUE THREAD

**Issue by Kenramiscal1106** [stackblitz/webcontainer-core#755]
### Describe the bug

I was opening stackblitz on microsoft edge (103.0.1264.71 (Official build) (64-bit))
But it shows this error
![image](https://user-images.githubusercontent.com/89060408/181148777-b07f5041-b491-429d-95f5-13982e4c423c.png)
but when I open [https://stackblitz.com/edit/web-platform-uenbn1?file=index.html](https://stackblitz.com/edit/web-platform-uenbn1?file=index.html) template, it works fine

### Link to the blitz that caused the error

https://stackblitz.com/github/withastro/astro/tree/latest/examples/with-tailwindcss?file=README.md&on=stackblitz

### Steps to reproduce

1. Go to: [astro tailwind example](https://stackblitz.com/github/withastro/astro/tree/latest/examples/with-tailwindcss?file=README.md&on=stackblitz)

### Expected behavior

I expect to open a web container, but it doesn't. Even the terminal didn't even work.

### Parity with Local

- [x] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/89060408/181149051-3cfed0ea-e660-4307-ad6c-8654fec24fb2.png)

### Platform

```
Browser name  = Edge
Full version  = 103.0.1264.71
Major version = 103
Hash = 1f7a1d165042010b399db54bd56390dd47e15013
```

**Comment by Samathingamajig** [comment]
same error appears on the latest version of Google Chrome (but with Chrome details of course)

**Comment by zdrawku** [comment]
Same error for latest versions of Chrome, Edge, Brave and etc.

**Comment by SamVerschueren** [comment]
Thanks for reporting. This should now be resolved. Sorry for the inconvenience.
