### ISSUE TITLE
"Incompatible web browser" when using chrome

### ISSUE THREAD

**Issue by adj97** [stackblitz/webcontainer-core#757]
### Describe the bug

Trying to run certain stackblitz projects fails with the following error message:

```
Incompatible Web Browser
WebContainers currently work in Chromium-based browsers and Firefox. We’re hoping to add support for more browsers as they implement the necessary Web Platform features.

[Read more about browser support](https://developer.stackblitz.com/docs/platform/browser-support)
```

Another related project fails with a different error:
Project: https://stackblitz.com/run?file=src%2Fapp%2Fstepper-overview-example.ts
Error: 
```
❯ npm install && turbo start
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/4] 🔍  Resolving dependencies
│ ⠋ Loading ideal dependency tree
~/projects/sqpfdn--run
```

Other repositories work: 
- https://stackblitz.com/edit/angular?file=src%2Fapp%2Fapp.component.ts

System Info: 
Google Chrome | 103.0.5060.134 (Official Build) (64-bit) (cohort: Stable)
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 11 Version 21H2 (Build 22000.795)
JavaScript | V8 10.3.174.20

Expected behaviour:

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-ikoe1q?file=src%2Fapp%2Fstepper-states-example.ts

### Steps to reproduce

I'm not sure if this issue is coupled to my local machine/browser setup. Otherwise the steps are pretty simple:

1. Open https://stackblitz.com/edit/angular-ikoe1q?file=src%2Fapp%2Fstepper-states-example.ts
2. Read error

### Expected behavior

I'm using google chrome, which is a chromium based browser, the webcontainers feature should work 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 71301415,
  "usedJSHeapSize": 67021795,
  "jsHeapSizeLimit": 4294705152
}
Hash = 872be04de15f32da2f6e3973878bcc22a4a17b5d
```

**Comment by SamVerschueren** [comment]
Hi @adj97! Thanks for reporting. We noticed this issue in the mean time and resolved it. Can you try again? Let me know if you're still running into an issue.

**Comment by Mr-xzq** [comment]
Thank you very much for the prompt fix,  it's working fine now. @SamVerschueren 

![image](https://user-images.githubusercontent.com/53166933/181397211-611e7b33-b39e-42b9-b1f2-1356f3a71106.png)
