### ISSUE TITLE
Blitz not running on Edge Version 105.0.1321.0 (Official build) dev (64-bit)

### ISSUE THREAD

**Issue by nwazuo** [stackblitz/webcontainer-core#758]
### Describe the bug

This blitz reports an 'Incompatible Web Browser' error for the preview panel. I'm not sure if it's because I'm using the dev version of MS Edge. 

MS Edge Version - 105.0.1321.0 (Official build) dev (64-bit)

### Link to the blitz that caused the error

https://stackblitz.com/github/remix-run/react-router/tree/main/examples/modal?file=src%2FApp.tsx

### Steps to reproduce

Try to run the blitz in Miscrosoft Edge Dev Version (maybe with this specific version/build - 105.0.1321.0 (Official build) dev (64-bit))

### Expected behavior

The blitz is expected to run as this browser should be fully compatible based on the browser support spec

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Microsoft Edge Dev
Full version  = 105.0.1321.0 (Official build) dev (64-bit)
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1321.0
performance.memory = {
  "totalJSHeapSize": 93375289,
  "usedJSHeapSize": 89378457,
  "jsHeapSizeLimit": 4294705152
}
Hash = 872be04de15f32da2f6e3973878bcc22a4a17b5d
```

**Comment by SamVerschueren** [comment]
Can you try again and let us know if this is still an issue? We fixed something yesterday which should've addressed this so I'm wondering if it's still not working 🤔 .

**Comment by nwazuo** [comment]
It works!
