### ISSUE TITLE
Doesn't work in Brave (again)

### ISSUE THREAD

**Issue by m93a** [stackblitz/webcontainer-core#764]
### Describe the bug

I'm using Brave and if I try to load https://stackblitz.com/, only the base HTML loads but all stylesheets and scripts are blocked – even if I disable all shields.

![image](https://user-images.githubusercontent.com/1671665/182191695-b637a535-db0e-4f58-bca2-04e940ec4755.png)
[stackblitz.com-1659369797613.log](https://github.com/stackblitz/webcontainer-core/files/9235388/stackblitz.com-1659369797613.log)

.

Loading a project page, like https://stackblitz.com/fork/typescript, gives me an empty page:

![image](https://user-images.githubusercontent.com/1671665/182191930-a87b82dc-4a7f-4953-b692-356d9a114c66.png)
[stackblitz.com-1659370033230.log](https://github.com/stackblitz/webcontainer-core/files/9235401/stackblitz.com-1659370033230.log)

.

The bug is probably unrelated to #14, but also only affects Brave. If I open the same pages in Chromium, everything works just fine.

### Link to the blitz that caused the error

https://stackblitz.com/fork/typescript

### Platform

- OS: elementary OS 6.1 based on Ubuntu 20.04.3 LTS
- Browser: Brave 1.41.96, based on Chromium 103.0.5060.114

**Comment by skra-pa-pa** [comment]
Do you have JavaScript disabled in your browser or something?

**Comment by m93a** [comment]
No, I do not have JavaScript disabled.

**Comment by d3lm** [comment]
Hey there 👋 Thanks for the bug report. We have tested this in Brave and it seems to work perfectly fine even with shields up. Can you double check and provide more info if it still fails?

**Comment by m93a** [comment]
I can confirm that it works just fine now! Not sure what was wrong back then, but now it's gone :grin:
