### ISSUE TITLE
BUG: readline-sync not working

### ISSUE THREAD

**Issue by jw56578** [stackblitz/webcontainer-core#77]
https://stackblitz.com/edit/node-zr7qsc

run the program. Output is:

[Error: EBADF: bad file descriptor, write] {
  syscall: 'write',
  errno: -9,
  code: 'EBADF'
}

**Comment by KwintenP** [comment]
Bug indeed! 🙏 for reporting!

**Comment by SuperOleg39** [comment]
Hi!

Have the same problem here https://stackblitz.com/edit/node-fk1xaf - try to create our SSR framework template.

@KwintenP do you have some workarounds how to get much full logs, maybe error trace?
I want to debug this issue, Web Containers is so impressive, and it will be awesome to run our framework at stackblitz)

**Comment by KwintenP** [comment]
Getting better logs for this atm won't be really possible, it seems to be an internal error on our side. I'll try and see if we can figure out what the issue is on this on.

**Comment by SuperOleg39** [comment]
Thanks you!

**Comment by ntucker** [comment]
Any ideas for what might be causing it? Is there a way to work around possibly?

**Comment by d3lm** [comment]
Hey there 👋 The issue here is that the package tries to write to fd 1 (stdout) and it throws on our end. We'll keep you posted if there's any updates or once this issue has been fixed.

**Comment by SamVerschueren** [comment]
As an update on our end, writing directly to fd 1 (stdout) was fixed a while ago. However, the `readline-sync` package still doesn't work so we're tracking that separately now.

**Comment by d3lm** [comment]
Hey! Just wanted to let you know that this has been fixed 🎉
