### ISSUE TITLE
Failed to run start command

### ISSUE THREAD

**Issue by MarcSebastian** [stackblitz/webcontainer-core#777]
### Describe the bug

Followed the link on Angulars "Getting started with Angular"(https://angular.io/start#create-the-sample-project), but resulted in "Failed to run start command".

![image](https://user-images.githubusercontent.com/2987751/185147189-7d94cdd9-37da-40d1-a947-10a7db6694e5.png)

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Steps to reproduce

1. Go to https://angular.io/start#create-the-sample-project and click the link "ready-made sample project in StackBlitz".
2. Wait until startup procedure finishes.
3. Note, that it failed to run start command.
![image](https://user-images.githubusercontent.com/2987751/185147886-ec8b6afe-2006-4de2-a5ba-04de77df83c3.png)

### Expected behavior

To not fail during startup

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 104.0.0.0
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 65214676,
  "usedJSHeapSize": 59073388,
  "jsHeapSizeLimit": 2172649472
}
Hash = 1f021b18268b32e6c6b2095e039ac8c9f88b0d52
```

**Comment by gmanojisaac** [comment]
Hi Marc.. Cli- 14.1.3 works fine in stackblitz nodeJs app [https://stackblitz.com/edit/node-hkppp8 - i did ng update], But a fresh Angular project is not working [ng new proj name].. And it gives HttpError: Failed to fetch dependencies:- @types/json-schema@7.0.11
