### ISSUE TITLE
angular routing missmatch

### ISSUE THREAD

**Issue by luckylooke** [stackblitz/webcontainer-core#778]
### Describe the bug

stackblitz uses some relative paths for root files causing malfunction app when routing to nested paths

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-vwnzjg

### Steps to reproduce

- open result running app on separate tab to have full url control
- navigate to /customers/profile (by click on button "profile" or editing url), when using button do refresh afterwards
- application did not load in correct state, in console there are errors from trying to reach files on /customers base url instead of root

### Expected behavior

To work correctly as it behaves when you download example project and run it locally.
When I navigate to http://localhost:4200/customers/profile everything works as expected.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="2558" alt="Screenshot 2022-08-21 at 09 37 38" src="https://user-images.githubusercontent.com/3660030/185782466-43218aaf-74c1-4191-9757-ac7ea7b1552d.png">
<img width="2555" alt="Screenshot 2022-08-21 at 09 35 52" src="https://user-images.githubusercontent.com/3660030/185782473-f348de32-6e19-4a3c-8a0f-cec6a294a5e6.png">

### Platform

```
Browser name  = Chrome
Full version  = 104.0.0.0
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84310811,
  "usedJSHeapSize": 67414531,
  "jsHeapSizeLimit": 4294705152
}
Hash = df64f655701fde45529fa8e152b3842072335b47
```

**Comment by kirjavascript** [comment]
hi there! thanks for reporting this issue!

this issue is related to the fix https://github.com/angular/angular-cli/pull/24367 which was added as part of angular 15

since this is an angular 14 project the fix is not applied, but upgrading the project to angular 15 fixes and and seems to make the project run

feel free to open another issue if this is still not fixed after upgrading

**Comment by SamVerschueren** [comment]
This now also works for older versions of Angular as we fixed some issue with the Node.js eventloop.
