### ISSUE TITLE
Starter project **2 years** out of date [feathers]

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#782]
### Describe the bug

The Feathers project points to a **2 year old** outdated version of `@feathersjs/feathers`

It is also configured to show a "Hello World" Node.js file that, **doesn't use Feathers** at all.

### Link to the blitz that caused the error

https://stackblitz.com/fork/feathersjs

### Steps to reproduce

1. Create a Feathers.js starter project

### Expected behavior

The starter project should be up to date and preferably maintained by the framework maintainers.

Please point the starter project link to https://stackblitz.com/fork/github/feathersjs/playground/tree/main/starter

### Additional Details

- [X] Tested in Firefox/CORP iFrame 
![Screenshot 2022-09-09 08 25 38](https://user-images.githubusercontent.com/876076/189370588-e1d910c8-58f1-452c-bc03-73c8d5270f2e.png)

**Comment by FossPrime** [comment]
@EricSimons Here's the logo for dark mode... might be very hard to see in GH's white background:
![feathersjs-dark](https://user-images.githubusercontent.com/876076/189235983-dc1995cb-5051-4387-b122-2059b0b27ba5.svg)

This is in response to @sulco and @sylwiavargas 's discord messages on June 17th, 2022 12:03 UTC ... We've had bad luck communicating on discord, so posting here.

**Comment by sulco** [comment]
@donmckenna can you update the Feathers starter to https://stackblitz.com/fork/github/feathersjs/playground/tree/main/starter, with the logo above? 🙏

**Comment by donmckenna** [comment]
Icon and link updated :) 

<img width="1284" alt="Screen Shot 2022-09-09 at 3 21 56 PM" src="https://user-images.githubusercontent.com/22125230/189447632-095e05b0-f026-42f7-84fe-e4632847c1ea.png">

**Comment by FossPrime** [comment]
Update confirmed 🤠
Huge success!

https://user-images.githubusercontent.com/876076/189455393-5b20a9b4-6aa1-4766-b0a9-1fecd6958af5.mp4
