### ISSUE TITLE
Images lost when creating a GitHub repo

### ISSUE THREAD

**Issue by SteveALee** [stackblitz/webcontainer-core#787]
### Describe the bug

I open and forked https://stackblitz.com/github/littlesticksdev/odyssey-theme/tree/main/theme?file=README.md
and then connected to github, creating a new repo

The images in /public/assets/images went missing

![image](https://user-images.githubusercontent.com/618922/187643969-2716f15e-e834-4a1d-af2d-4333ee83e5c9.png)

### Link to the blitz that caused the error

https://stackblitz.com/github/littlesticksdev/odyssey-theme/tree/main/theme?file=README.md

### Steps to reproduce

1. fork
2. connect to github - create new repo

### Expected behavior

images there and no errors when running

NB I did NOT run locally even though I said I did below :D

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 103.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
performance.memory = undefined
Hash = 4f16907aeb1fd170bcc93609cea1d8dc6ad28342
```

**Comment by SteveALee** [comment]
I looks like a stackblitz issue - https://github.com/stackblitz/webcontainer-core/issues/787

**Comment by kc0tlh** [comment]
@SteveALee thanks for this detailed bug report! This is a known issue and being tracked internally for resolution. Updates will be posted here when complete.

**Comment by AleksandrSl** [comment]
Hi @SteveALee, I checked the fix on your example. Should be working fine now, though creating a repository takes some time.
