### ISSUE TITLE
This repo isn't working

### ISSUE THREAD

**Issue by Lamin-Jr** [stackblitz/webcontainer-core#789]
### Describe the bug

it stops building/installing the dependencies at a run-time
<img width="377" alt="Screenshot 2022-09-01 at 01 02 19" src="https://user-images.githubusercontent.com/54267031/187799852-60a474d8-f7c1-4fcf-87ef-58d177022b24.png">

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Steps to reproduce

1. from angular documentation about animation, the live example link that navigates to the stackblitz web-ide, automatically starts building the project and stops at the run-time

### Expected behavior

1. It suppose to build the project like the rest

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 104.0.0.0
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 120686022,
  "usedJSHeapSize": 106742734,
  "jsHeapSizeLimit": 4294705152
}
Hash = 4f16907aeb1fd170bcc93609cea1d8dc6ad28342
```

**Comment by Nemikolh** [comment]
Hi @Lamin-Jr ! :wave: 

This error often occurs when the project failed to install dependencies which could be because there was a network issue, a server issue or an npm registry issue. I think if you now go to:

 https://angular.io/generated/live-examples/animations/stackblitz.html

it should work fine now :+1:
