### ISSUE TITLE
Add documentation for .stackblitzrc

### ISSUE THREAD

**Issue by EricSimons** [stackblitz/webcontainer-core#79]
**Is your feature request related to a problem? Please describe.**
Devs in our discord are wondering about how they can use the stackblitzrc file to config their env. We currently have no documentation for this!

**Describe the solution you'd like**
Documentation for the fields that .stackblitzrc accepts over at https://developer.stackblitz.com

**Comment by sulco** [comment]
Here's the link :) https://developer.stackblitz.com/docs/platform/project-config
