### ISSUE TITLE
The dependencies sidebar UI  is not present for Next JS React project

### ISSUE THREAD

**Issue by laurencefass** [stackblitz/webcontainer-core#793]
### Describe the bug

There is no way to add dependencies to this project:

https://stackblitz.com/edit/next-typescript-eyxuaz

### Link to the blitz that caused the error

https://stackblitz.com/edit/next-typescript-eyxuaz?file=pages%2Ftest.tsx

### Steps to reproduce

Visit page note there is no way to automatically add dependencies.

parity with local is not relevant in this instance. i ticked it only to submit the issue.

### Expected behavior

Its been a while since I used stackblitz but I think there used to be a dependencies UI. Looking in forums. other users are reporting the same issue.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 104.0.0.0
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 141721395,
  "usedJSHeapSize": 89653967,
  "jsHeapSizeLimit": 4294705152
}
Hash = b97d17a00b41a7a326ea3ef530e60b6aada4f7c7
```

**Comment by AleksandrSl** [comment]
Hi @laurencefass. In nodejs based projects you can install new packages via the terminal.

Here I'm installing the nanoid in the right terminal.
![Screenshot from 2022-09-06 10-58-12](https://user-images.githubusercontent.com/15820496/188579502-d44c0827-44c7-430b-8a04-d6bd7d7fea67.png)

Dependencies UI exists only for EngineBlock projects, where terminal is not available
