### ISSUE TITLE
[FR] Disable all Firebase related noise/spam messages config

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#797]
**Is your feature request related to a problem? Please describe:**
Recently, around 25K lines of unexplained Firebase code have been added to WC. They print fetch errors, and non stop WebSocket connections and frames. This impedes our ability to develop apps that do not rely on Google's close-source private API's and frameworks.

**Describe the solution you'd like:**
A toggle next to freeze to disable Firebase integration.

**Describe alternatives you've considered:**
Switching to Glitch/Github spaces/Codesandbox Projects.

**Additional context:**
While less annoying than Firefox's spam situation #792 Chrome still exhibits a high level of WebSocket spam traffic. One way to get an idea of how annoying this can be is to block `||firebaseio.com` all together and open the console. The integration has thus far provided zero benefit to developers.

**Comment by jrvidal** [comment]
:wave: Thanks for the report. Can you elaborate a bit more about what your issue is? Maybe point to a concrete project?
