### ISSUE TITLE
Set-cookie headers get filtered out

### ISSUE THREAD

**Issue by adamziel** [stackblitz/webcontainer-core#798]
### **Description of Bug**

I'm running a minimal express.js server and I want to set some cookies. Unfortunately, they are filtered out from the response body:

```
import express from 'express';
const app = express();
app.all('*', async (req, res) => {
    res.socket.end(`HTTP/1.1 200 OK
X-TEST: This works
Set-Cookie: this_does=not_work
Content-Length: 12
Connection: close
Content-Type: text/html

Hello world!`);
});

app.listen(port, async () => {
   console.log(`WordPress server is listening on port ${port}`);
});
```

<img width="243" alt="CleanShot 2022-09-07 at 14 37 46@2x" src="https://user-images.githubusercontent.com/205419/188880024-ef1f7945-3786-46be-b247-1ec25fb97109.png">

I suspect this has to do with how service workers handle cookies. An Angular app using its own service worker has no troubles setting cookies:

https://stackblitz.com/edit/set-and-get-cookies-in-angular-readerstacks?file=index.html

<img width="1118" alt="CleanShot 2022-09-07 at 14 38 43@2x" src="https://user-images.githubusercontent.com/205419/188880240-bcf634f0-6e0c-49a7-977a-e1e22c6c49a9.png">

**Comment by fvsch** [comment]
Transferring this issue to `webcontainer-core` because it looks like it's squarely related to how WebContainers handles cookies in HTTP responses.

> I was surprised to find this app is somehow able to set cookies

It's setting a cookie client-side with `document.cookie`. Not via HTTP headers.

**Comment by adamziel** [comment]
> It's setting a cookie client-side with document.cookie. Not via HTTP headers.

I saw that in the code too, and yet the Response Headers tab of the devtools shows `set-cookie: ahoy_visit...` as on the attached screenshot.

**Comment by fvsch** [comment]
Oh, that's a cookie from StackBlitz itself, not from this specific project.
It's used to count project views (with https://github.com/ankane/ahoy).

**Comment by samdenty** [comment]
We now support `Set-Cookie` headers in webcontainer projects 🚀
