### ISSUE TITLE
Can’t open editor only on mobile

### ISSUE THREAD

**Issue by SamVerschueren** [stackblitz/webcontainer-core#80]
**Describe the bug**
The editor filter at the top does not work for V2 projects on mobile. 

![image](https://user-images.githubusercontent.com/1913805/119302447-6b6d2a80-bc64-11eb-9bb3-c773018712ca.png)

**Link to the blitz that caused the error**
Effects all projects

**To Reproduce**
1. Go to https://stackblitz.com/edit/node-gtkmju?file=package.json on mobile
2. Try opening the editor only

**Expected behavior**
I would only see the editor, not the preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/1913805/119302625-b4bd7a00-bc64-11eb-8f49-87352ed4dba8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.5
 - Browser: Stock Browser (Safari)
 - Version: 14.5

**Additional context**
/

**Comment by tarushm2006** [comment]
Are you able to open the terminal on mobile?

**Comment by SamVerschueren** [comment]
WebContainer projects should work on Android theoretically. But for that we need to add some headers first which Chrome will enforce in Chrome 92. So when we fix that, Android should be working fine. IOS does not have all the features we need (yet).

**Comment by SamVerschueren** [comment]
Fixed 🎉
