### ISSUE TITLE
[vite] error while updating dependencies:

### ISSUE THREAD

**Issue by emosheeep** [stackblitz/webcontainer-core#800]
### Describe the bug

<img width="851" alt="截屏2022-09-08 21 15 53" src="https://user-images.githubusercontent.com/31957758/189131616-aec3a7af-cac3-407b-8f79-0caad7e28c75.png">

### Link to the blitz that caused the error

https://stackblitz.com/edit/storybook-bug-reproduction

I made a same example with [codesandbox](https://codesandbox.io/s/eager-germain-oy7509), which works as expect.

### Steps to reproduce

nothing to do, just waiting the project initial process. After the lanuching, the error will reproduce. it runs well at the first time, but it always failed when i reopen the project or refresh the page. i guess there has some unexpected cache. but i don't know how to clear it.

### Expected behavior

 i think every time i open the project, it should be in a new context, in which the error about cache is not supposed to occur

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

Everything is ok!
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/31957758/189134958-cae83bd6-29bc-425b-b3dc-c9c92df7835d.png">

### Platform

```
Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86968458,
  "usedJSHeapSize": 74325270,
  "jsHeapSizeLimit": 4294705152
}
Hash = a1e315a41ec6498e2c2758b32fbf437db67b244b
```

**Comment by emosheeep** [comment]
I made a same example with [codesandbox](https://codesandbox.io/s/eager-germain-oy7509), which works as expect.

**Comment by Nemikolh** [comment]
Hi @emosheeep! :wave: 

I am not seeing the error you mentioned, but there seems to be other errors in your project that might prevent me from seeing the one you reported:

```
ERR! Error: 
ERR!           @storybook/builder-vite requires vite-plugin-vue2 to be installed when using @storybook/vue.
ERR!           Please install it and start storybook again.
```

Do you think you could update your blitz? That would help me a ton :pray:

**Comment by emosheeep** [comment]
Oh, sorry，this is a problem vite has tagged at https://github.com/vitejs/vite/issues/9986. 

Maybe this issue should be closed.

**Comment by Nemikolh** [comment]
No worries! Thanks for sharing the issue in vite itself :+1:
