### ISSUE TITLE
CORs network errors are incorrectly triggering `uncaughtException` events

### ISSUE THREAD

**Issue by penalosa** [stackblitz/webcontainer-core#807]
### **Description of Bug**
CORs network errors are incorrectly triggering `uncaughtException` events

### **Steps to Reproduce**

Add the following to a JS file:
```js
// test.mjs
import { fetch } from 'undici';
process.on('uncaughtException', (e) => {
  console.log('Uncaught');
});
async function main() {
  try {
    await fetch('https://example.com');
  } catch (e) {
    console.log('Caught');
  }
}

main();
```
And run with `node test.mjs`

### **Expected Behavior**
I expect the network request not to succeed, as `example.com` doesn't have the `Access-Control-Allow-Origin` header. I expect that error (a `TypeError`) to be caught by my exception handler, and for `"Caught"` to be printed (this is how browsers behave). However, it's caught by the `uncaughtException` event listener, and doesn't trigger my `catch` handler.

**Comment by d3lm** [comment]
Hey 👋 Thanks for reporting this issue. We will have a look at this and keep you posted about any updates.

**Comment by d3lm** [comment]
This issue has been fixed and it's live https://stackblitz.com/edit/node-agxtw8?file=index.js.
