### ISSUE TITLE
create file or directory inside dir stuck

### ISSUE THREAD

**Issue by jk2K** [stackblitz/webcontainer-core#808]
### Describe the bug

<img width="322" alt="image" src="https://user-images.githubusercontent.com/4025839/191048112-d1681876-e2ce-44d0-9c2e-e216c51b37e6.png">

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-domqfm?file=package.json&terminal=dev

### Steps to reproduce

create file in `.vitepress`

### Expected behavior

create file successfully

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 150626102,
  "usedJSHeapSize": 146386110,
  "jsHeapSizeLimit": 4294705152
}
Hash = 829380144b30b4dc31bd04f9b94de7766022f986
```

**Comment by jk2K** [comment]
thanks, I am willing to use CodeFlow

**Comment by Nemikolh** [comment]
Hey! This issue has been fixed. You should now be able to create a file without any issues. Let us know if you run into similar issues :smiley:
