### ISSUE TITLE
Report bug button does not work on mobile

### ISSUE THREAD

**Issue by SamVerschueren** [stackblitz/webcontainer-core#81]
**Describe the bug**
When opening a WebContainer project on mobile to view source code or what not, it's not possible to click the report button if you notice something fishy. The button is shown, but it doesn't do anything.

**Link to the blitz that caused the error**
Effects all projects

**To Reproduce**
1. Go to https://stackblitz.com/edit/node-gtkmju?file=package.json on mobile
2. Open the sidebar
3. Try clicking the report bug button

**Expected behavior**
I should be redirected to GitHub with the issue already filled in.

**Screenshots**
![image](https://user-images.githubusercontent.com/1913805/119303397-f0a50f00-bc65-11eb-80b0-de69ae5b265a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.5
 - Browser: Stock Browser (Safari)
 - Version: 14.5

**Additional context**
/

**Comment by fvsch** [comment]
Fixed with the redesign of the feedback button shipped today.
