### ISSUE TITLE
WebContainers not running on Chrome for Android

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#810]
### Describe the bug

I find it very strange that Chrome for Android, which has the same support for SAB's as Firefox, doesn't run WebContainers. Firefox for Android does work, but it's performance on Android 13 is way worse than Chrome.

I used to get lots of work done on my phone when I used another sandbox with good phone support, and lots of people use Galaxy Fold phones as primary work computers.

# Related

[SB Docs](https://developer.stackblitz.com/docs/platform/browser-support/)
[Chrome docs](https://developer.chrome.com/blog/enabling-shared-array-buffer/)

### Link to the blitz that caused the error

vite.new/vue-ts

### Steps to reproduce

Open any WebContainer sandbox on Android

### Expected behavior

Should run normally.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

WebContainer Screen on Chrome for Android version 106
![Screenshot 2022-09-23 08 36 28](https://user-images.githubusercontent.com/876076/191973887-fe213fe4-1ae9-456b-bd91-db372b42ba17.png)

After turning on Android Debugging, running `sudo apt install android-sdk` opeinging chrome://inspect to see devtools for the Android browser, this revealed error messages about the credentialless WebContainers domain.
![Screenshot 2022-09-23 09 33 32](https://user-images.githubusercontent.com/876076/191985808-eb808b07-888d-4a54-8cd4-cc22f4f38fd6.png)

### Platform

- OS: Android
- Browser: Chrome
- Version: 104+

### Additional context

Related to #637

# Workarround

Change the user agent to Firefox using the Kiwi browser and the User-Agent Switcher for Chrome extension to permanently spoof stackblitz.com with a Firefox user-agent.

# Solution

Looks like Android is served COEP mode, but the _relay_ is hosted at `stackblitz.io` and a number of resources in `//stackblitz.com` are missing COEP headers. I've attached a set of header and source overrides that would fix the problem. To use them you'll need ChromeDevTools's experimental Local Header Overrides feature turned on. This will work on Chrome 105, for 106 beta the schema was changed and headers uses an array, instead of an object.
[feathers-chat.zip](https://github.com/stackblitz/webcontainer-core/files/9636365/feathers-chat.zip)

Pixel 6 pro after ADB debugging Chrome 105 with the attached overrides
![Screenshot_20220924-035019](https://user-images.githubusercontent.com/876076/192037282-4fc1d436-af4a-45df-b9f6-f7d2117c795f.png)

**Comment by sombriks** [comment]
yes i can confirm this issue, running chrome on samsung s7 tablet on dex mode but unable to run the web containers

**Comment by SamVerschueren** [comment]
Thanks for letting us know! This is a regression indeed as it should just work. We will investigate and fix this issue. Keep you posted on this.

**Comment by SamVerschueren** [comment]
We've identified the issue and fixed it. It will be live in a bit!

**Comment by FossPrime** [comment]
> We've identified the issue and fixed it. It will be live in a bit!

It still doesn't seem to work. Tried on stable and dev, with classic and CodeFlow... I see a similar CORS error with fs_bg.wasm

![Screenshot_20221022-050645](https://user-images.githubusercontent.com/876076/197280403-3aef01ec-4125-4719-b5f0-a31afb9e49ce.png)


Browserstack has decent tools for debugging. The issue can also be debugged with Android SDK, Chromebooks or the Kiwi browser Android app on Windows 11.

**Comment by SamVerschueren** [comment]
I actually tested this on a real (older) Android tablet. Other colleagues with Android phones also tested it on theirs and it also worked for them. It also works on the Android emulator.

![image](https://user-images.githubusercontent.com/1913805/197492663-ba4d5ea8-5b15-431a-87b2-749203e66306.png)

So I'm not 100% sure what is going on here 🤔 . I'm wondering if these responses are cached by the browser. Is it possible to clear the cache for stackblitz.com and refresh?

**Comment by SamVerschueren** [comment]
Ok, I found a bug which might cause the CORS errors. I'll get back to you once we addressed the necessary changes.

**Comment by SamVerschueren** [comment]
@FossPrime Can you check again? We should've updated the configuration. I'm not seeing CORS issues anymore on my end.

**Comment by sombriks** [comment]
hello world project looks ok on chrome now!
![image](https://user-images.githubusercontent.com/556695/197592972-641816b4-c54d-457c-8dc4-5f8d70c6d14c.png)

i just had to uncheck "desktop version" option in menu.

**Comment by sombriks** [comment]
![image](https://user-images.githubusercontent.com/556695/197593718-2c172e5e-2982-43a8-8360-32728b442342.png)

**Comment by FossPrime** [comment]
@SamVerschueren I can confirm desktop mode breaks support, showing the unsupported browser message. Android tablets and some ChromeOS running Chrome for Android user will in ~3 months get served desktop versions of websites by default, if they aren't already being served those. There is a hard user agent check somewhere that serves the origin trial version of StackBlitz, this should instead be a client side feature check. That's, imo, a separate issue that probably merits it's own ticket.

https://blog.google/products/chrome/a-new-look-and-feel-for-chrome-on-android-tablets/

**Comment by SamVerschueren** [comment]
This is interesting, thanks for that information!

> this should instead be a client side feature check

This is impossible to detect client side as the top-level document has to be served with the correct headers in order to be served correctly and be cross origin isolated. Apparently Chrome Desktop on Android does not support that origin trial, but the user agent also doesn't help in detecting it either 🤔 .

I guess for Codeflow it would be ok to always serve `credentialless` mode, as I don't think someone would embed that entire editor on their page. And if they want that, it's also possible if they serve the correct headers themselves.

The main reason the classic StackBlitz editor uses the origin trial is because we would break everyones embeds if we just turned on `credentialless`. I'm bringing this back to the team to see if we can find a solution.

Thanks again for all the information and the help on this issue 🙏 .

**Comment by SamVerschueren** [comment]
We now alwayse use `credentialless` mode in Chrome, except for embedded stackblitzes (because otherwise they break). This means that Android Chrome desktop mode now also works correctly. So all of this should be fixed now. Thanks for letting us know!
