### ISSUE TITLE
[Firefox] Can't load website from "Open in new tab"

### ISSUE THREAD

**Issue by pradana4648** [stackblitz/webcontainer-core#811]
### Describe the bug

When I clicked "Open in new tab" got error it says "Unable to connect"
I think the problem it's about listening port or somewhere in Firefox API that caused error
Trying refresh too but not working

### Link to the blitz that caused the error

https://stackblitz.com/edit/emah-blog?file=README.md

### Steps to reproduce

1. Create project with Docusaurus 
2. Run npm start
3. It show the web from side panel 
4. Click "Open in new tab"

### Expected behavior

Should open the web from other tab in Firefox 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/62380505/192105078-8c861e57-0be3-4bbd-b38a-70fb104fd0c2.png)

### Platform

```
Browser name  = Firefox
Full version  = 105.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0
performance.memory = undefined
Hash = d0cd7a8669bec74204b2f31e5c2487ab3f6a28b6
```

**Comment by SamVerschueren** [comment]
This issue is related to [storage partitioning](https://developer.chrome.com/docs/privacy-sandbox/storage-partitioning/) in Firefox. We're currently actively working on resolving this. We're tracking storage partitioning through #942, so closing this in favour of that issue.
