### ISSUE TITLE
https://stackblitz.com/edit/nativescript-stackblitz-templates-mgrwuj?file=src%2Fapp%2Fitem%2Fitems.component.html&title=NativeScript%20Starter%20Angular

### ISSUE THREAD

**Issue by frunjik** [stackblitz/webcontainer-core#816]
### Describe the bug

A brower on the device opens with:

![image](https://user-images.githubusercontent.com/8170229/192670520-79c6a5db-5a5b-4dff-915f-da6d1806d2f6.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/nativescript-stackblitz-templates-mgrwuj?file=src%2Fapp%2Fitem%2Fitems.component.html&title=NativeScript%20Starter%20Angular

### Steps to reproduce

1. Try to preview the app

### Expected behavior

A working preview

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Additional context

Parity with local: I have not tried because it does not apply ...

**Comment by frunjik** [comment]
https://stackblitz.com/edit/nativescript-stackblitz-templates-mgrwuj?file=src%2Fapp%2Fitem%2Fitems.component.html&title=NativeScript%20Starter%20Angular

**Comment by frunjik** [comment]
I think this may be wrong repo (sorry)

**Comment by SamVerschueren** [comment]
I think the project that you linked is still an old one. We now have NativeScript starters that you can pick from the dashboard.

![image](https://user-images.githubusercontent.com/1913805/223705183-c003524d-d634-434f-8599-83af418cb7bb.png)

If you create an Angular NativeScript project (like [this one](https://stackblitz.com/edit/nativescript-stackblitz-templates-jyci1u)) you will see something that looks like this.

![image](https://user-images.githubusercontent.com/1913805/223705307-82fd0aa7-e79c-4b3d-8349-1a2b25ae35b3.png)

Scan that with your phone and you should be good to go!
