### ISSUE TITLE
The scroll is still vertical

### ISSUE THREAD

**Issue by sandheepp** [stackblitz/webcontainer-core#818]
### Describe the bug

The scroll is vertical

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fcdk-virtual-scroll-horizontal-example.html

### Steps to reproduce

Scroll

### Expected behavior

Horizontal Scroll

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 119065630,
  "usedJSHeapSize": 113862602,
  "jsHeapSizeLimit": 4294705152
}
Hash = bc6680fa6a19b40b511d3d540df9ce55a844166f
```

**Comment by fvsch** [comment]
Hi @sandheepp,

This seems to be an issue with a specific library or with its documentation, and not an issue with StackBlitz. I suggest opening an issue with their own support channels.
