### ISSUE TITLE
Add an option to not persist some files

### ISSUE THREAD

**Issue by sulco** [stackblitz/webcontainer-core#82]
Some files don't need to be persisted, e.g. cache or build folders.

There should be a way to specify "ignore" paths.
Maybe in the `.stackblitzrc` file?

**Comment by jacob-ebey** [comment]
Could the gitignore be used by default? That would lead to nice clean UX for sample repos and general use-cases. Would be nice to have a "toggle ignored" checkbox or something if you need to inspect build output for debugging.

**Comment by HeyGarrison** [comment]
We recently shipped this so closing the issue! ❤️
