### ISSUE TITLE
web container not working

### ISSUE THREAD

**Issue by ajayanand2** [stackblitz/webcontainer-core#822]
### Describe the bug

web container is not displaying anything  

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-tqhkt1?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html

### Steps to reproduce

when i opened the html file 

### Expected behavior

it should show preview

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

not tried on local machine

### Platform

```
Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 77649805,
  "usedJSHeapSize": 68459873,
  "jsHeapSizeLimit": 2066743296
}
Hash = c3f3eab0760382367e86f2a862c18516376c36f4
```

**Comment by SamVerschueren** [comment]
Hi @ajayanand2. This might've been a bug on our side back then when you created the issue. It seems that it's working now on my end.

![image](https://user-images.githubusercontent.com/1913805/223705600-c400f6fa-2f02-4998-a03a-4f4414decbe4.png)
