### ISSUE TITLE
لا يفتح 

### ISSUE THREAD

**Issue by mohammadalhaj2003** [stackblitz/webcontainer-core#823]
### Describe the bug

![Screenshot_20221008-192854_NativeScript Preview](https://user-images.githubusercontent.com/114867867/194717823-d9f2033c-0b1a-4416-9d29-e9a2aea21799.jpg)

### Link to the blitz that caused the error

https://stackblitz.com/edit/nativescript-battery-level-check?file=package.json

### Steps to reproduce

![Screenshot_20221008-192854_NativeScript Preview](https://user-images.githubusercontent.com/114867867/194717839-9e53f617-6cca-4977-bd6b-995aeec819b6.jpg)

### Expected behavior

![Screenshot_20221008-192854_NativeScript Preview](https://user-images.githubusercontent.com/114867867/194717830-03638081-9e34-4b06-adae-b00caffd136e.jpg)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

تظهر عند الربط مع ااجوال 
![Screenshot_20221008-192854_NativeScript Preview](https://user-images.githubusercontent.com/114867867/194717798-57d06ad5-9eab-4949-8a80-7ba3142a64ea.jpg)

### Platform

```
Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.50
performance.memory = {
  "totalJSHeapSize": 88544650,
  "usedJSHeapSize": 78897666,
  "jsHeapSizeLimit": 2172649472
}
Hash = c3f3eab0760382367e86f2a862c18516376c36f4
```

### Additional context

![Screenshot_20221008-192854_NativeScript Preview](https://user-images.githubusercontent.com/114867867/194717834-e38ac61c-31be-48b7-a131-c8d4815882ef.jpg)

**Comment by d3lm** [comment]
Thanks for the report! Without a clear description of the issue and steps to reproduce there is not much we can do. I am going to close this for now, and if you think there's still an issue feel free to file a new issue.
