### ISSUE TITLE
`terminal` query param not working in webpublisher

### ISSUE THREAD

**Issue by ndom91** [stackblitz/webcontainer-core#825]
### Describe the bug

We (next-auth.js.org) have a Docusaurus docs page with the standard "Edit on Github" links at the bottom of each page.

After the vite conf talk today, I tried to emulate the swapping of those links to `pr.new`. 

That worked in general, but our repo is a monorepo. Therefore the default `dev` npm script doesn't start the docs dev server.

After perusing the docs, I saw that you can pass the `terminal` query param to tell it which command to execute. 

Therefore, I'd expect:

```
https://stackblitz.com/~/github.com/nextauthjs/next-auth/edit/main/docs/docs/getting-started/introduction.md?terminal=dev:docs
```

To execute `dev:docs` instead of `dev`. 

However, it still executes `pnpm run dev`.

Is this a known limitation?

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/nextauthjs/next-auth/edit/main/docs/docs/getting-started/introduction.md?terminal=dev:docs

### Steps to reproduce

1. Visit https://stackblitz.com/~/github.com/nextauthjs/next-auth/edit/main/docs/docs/getting-started/introduction.md?terminal=dev:docs
2. Notice that `pnpm run dev` is executed, instead of `pnpm run dev:docs`.

### Expected behavior

`pnpm run dev:docs` as dev command, not `pnpm run dev`.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Linux
- Browser: Brave
- Version: 1.43.89 Chromium: 105.0.5195.102 (Official Build) (64-bit)

**Comment by ggdaltoso** [comment]
Hi, @ndom91!

Thanks for using Web Publisher and for opening this issue!

For now, Web Publisher will follow the current configuration you could have for webcontainer projects, i.e., you can [configure it by using `.stackblitzrc`](https://developer.stackblitz.com/platform/webcontainers/project-config). 

Web Publisher will spawn the command you set in the [`startCommant`](https://developer.stackblitz.com/platform/webcontainers/project-config#startcommand) field. 
The same will be applied when moving to Codeflow IDE.

**Comment by ndom91** [comment]
@ggdaltoso thanks for the quick response. I understand that much from [the docs page](https://developer.stackblitz.com/platform/webcontainers/project-config#with-url-parameters), but I was under the impression that the `termianl` query param was supposed to act in the same manner as the `startCommand`. 

Is that not true for Web Publisher potentially?

**Comment by ggdaltoso** [comment]
What I said doesn't solve your issue, but it might be useful until we don't support the `terminal` query param. 

By saying this:
> Is that not true for Web Publisher potentially?

Not _yet_!

**Comment by ndom91** [comment]
> What I said doesn't solve your issue, but it might be useful until we don't support the `terminal` query param. 
> 
> By saying this:
> > Is that not true for Web Publisher potentially?
> 
> Not _yet_!

Ahhh okay, gotcha. Thanks 😉👍

**Comment by ggdaltoso** [comment]
Hi again, @ndom91 

Web Publisher now supports `terminal` query parameter so I'm going to close this issue for now.
Feel free to reopen it again or even open other one if you'd like to. 

Thanks!
