### ISSUE TITLE
Can not clone remotion-dev/remotion

### ISSUE THREAD

**Issue by JonnyBurger** [stackblitz/webcontainer-core#826]
Just trying out Codeflow:

https://stackblitz.com/~/github.com/remotion-dev/remotion/pull/1192

results in not being able to clone: 

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/1629785/195171409-6ba90d89-4fd9-4c4d-b1d9-c50e404d77d4.png">

It is because https://g.staticblitz.com/v5/h/e/github.com/remotion-dev/remotion/pull/1192 returns a 404.
Possibly it is because that pull request is already merged?

**Comment by jrvidal** [comment]
> It is because https://g.staticblitz.com/v5/h/e/github.com/remotion-dev/remotion/pull/1192 returns a 404.

Yes, that's the case. We do need some better UX for this. Thanks for reporting!

**Comment by Nemikolh** [comment]
Hey @JonnyBurger ! :wave: 

We've modified our internal logic to allow cloning PRs that have been merged. Opening the link you shared now works! :tada:
