### ISSUE TITLE
CodeFlow: Cloning GitHub repo URL doesn't work, only GitHub Repo landing pages URL

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#829]
### Describe the bug

- Cloning `https://github.com/stackblitz/webcontainer-core.git` Will throw an error.
- Cloning `https://github.com/stackblitz/webcontainer-core/tree/asd` instead will work.

The instructions as for the **repository** URL, but it doesn't want the repository URL, it wants a webpage URL.

This doesn't follow https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository guidelines and is **incompatible with the git protocol**. And will surely lead to compatibility problems and headaches down the line.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/tdpowerskills/test-123

### Steps to reproduce

1. Attempt to clone a GitHub git repository into CodeFlow, any repository.
2. eg: https://github.com/stackblitz/webcontainer-core.git

Be greeted with the following error:
![Screenshot from 2022-10-12 11-54-12](https://user-images.githubusercontent.com/876076/195405562-b3308c3b-704d-471d-8e8e-63bd1644ed6f.png)

### Expected behavior

Clone the repository using standard protocols that have been stable for almost two decades and have wide market support.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 35b869fee6c097380f8b2e33563ab4a16c08f57b
WebContainer = ea2f6b48b77806aba8e6fe3b6311530cc7674f64

Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87551751,
  "usedJSHeapSize": 84351271,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by jrvidal** [comment]
:wave: Thanks for the report.

Can you elaborate a bit more on the steps to reproduce? When you say "cloning", do you mean going to a specific `https://stackblitz.com/~/github.com/<owner>/<repo>` URL? Or running the `git` CLI in codeflow itself?

**Comment by FossPrime** [comment]
I meant the URL. This is well known area of interest with codeflow now... So it's not as relevant.
