### ISSUE TITLE
BUG: Port view not updated properly with nodemon

### ISSUE THREAD

**Issue by iAmPriyam** [stackblitz/webcontainer-core#83]
---
name: Bug report
about: Create a report to help us improve
title: 'Node+express app crashes when saves and restarts, connection to port is lost'
labels: ''
assignees: ''

---

**Describe the bug**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-klgvj6?file=controller%2Findex.js

**To Reproduce**
1. Create a node container
2. Create a simple express server, (listening on port 8000)
3. install nodemon as dev dependency
4. run the server using nodemon, works the first time but the connection is then lost

**Expected behavior**
The app works the first time then the connection to the port is lost (seen in left column).  The app should listens on the port continuously but does not responds. It should be reflected in the embeded browser/system.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**
![Server is running but the paths are not working](https://user-images.githubusercontent.com/30063255/119398298-001f6900-bcf5-11eb-9542-05d375bf7e6b.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 84542379,
  usedJSHeapSize: 79203703,
  jsHeapSizeLimit: 2172649472
}

**Additional context**

**Comment by KwintenP** [comment]
Hi!

There is a known bug that the port disappears on reloads. We are aware of this one.

Other than that, `nodemon` should still keep working. This is only a UI regression. 
In the screenshot you've attached, it seems like you changed the url which cause you to see the screen you are seeing.

🙏 for reporting!

**Comment by jrvidal** [comment]
@iAmPriyam This should be fixed by now. Please feel free to re-file if you find any further issues. Thanks!
