### ISSUE TITLE
Yarn workspaces support

### ISSUE THREAD

**Issue by cherniavskii** [stackblitz/webcontainer-core#830]
### Describe the bug

Hey there!
First of all, congrats on Stackblitz Codeflow release! It looks amazing!

I've tried to use it with MUI core repository, where we use yarn v1 workspaces.
But it looks like it's not supported:
```
❯ yarn workspace docs dev
┌─ WARNING ────────────────────────────────────────────────────────────────────────────────────────┐
│ It seems you are trying to use `yarn`. This is a compatibility layer which uses `turbo` instead, │
│ a blazingly fast package manager designed for the web. If you wish to hide this warning, you can │
│ do so by setting `warnings.yarn = false` inside "/home/.turbo/.turborc.json" or use `turbo`      │
│ directly.                                                                                        │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
ERR!: Unknown command `workspace`

Try this: turbo --help

error Command failed with exit code 1
```

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/mui/material-ui

### Steps to reproduce

1. Go to https://stackblitz.com/~/github.com/mui/material-ui
2. Install dependencies: `yarn install`
3. Run dev server: `yarn workspace docs dev`

### Expected behavior

`yarn workspace` command working

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 35b869fee6c097380f8b2e33563ab4a16c08f57b
WebContainer = ea2f6b48b77806aba8e6fe3b6311530cc7674f64

Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 120549378,
  "usedJSHeapSize": 113652982,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by Nemikolh** [comment]
Hey @cherniavskii ! :wave: 

We have support for native yarn and so workspaces are now working! :tada: 

Running `yarn workspace docs dev`, works as well as any `yarn workspace <pkg> run`. I'm going to close this issue, feel free to reopen if I missed something or if you still run into any issues. :smiley:

**Comment by cherniavskii** [comment]
@Nemikolh Thanks, this is awesome!

<img width="1192" alt="Screenshot 2023-03-20 at 20 34 32" src="https://user-images.githubusercontent.com/13808724/226447062-6941e3ba-a98f-4d43-9867-4973f418a8ee.png">
