### ISSUE TITLE
Empty VitePress project hangs forever

### ISSUE THREAD

**Issue by sylwiavargas** [stackblitz/webcontainer-core#838]
### Describe the bug

In Web Publisher from an empty VitePress project, the start command seems running as well but the Preview area still loading.

However, the [Vue.js docs work well here](https://stackblitz.com/~/github.com/vuejs/docs/edit/main/src/guide/introduction.md), also based on VitePress.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/Jinjiang/web-publisher-demo/edit/main/README.md

### Steps to reproduce

1. Go to the link
2. The project hangs forever

### Expected behavior

Web Publisher should load and it hangs forever.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/106.0.0.0 Safari/537.36

**Comment by fvsch** [comment]
It does seem to work in the legacy editor:
https://stackblitz.com/github/Jinjiang/web-publisher-demo?file=package.json

**Comment by Jinjiang** [comment]
Here provide the console log on my device.
[stackblitz.com-1665667295636.log](https://github.com/stackblitz/webcontainer-core/files/9777052/stackblitz.com-1665667295636.log)

Thanks

**Comment by jrvidal** [comment]
This is already fixed :tada:
