### ISSUE TITLE
Trying to run on Qwik Repository

### ISSUE THREAD

**Issue by shairez** [stackblitz/webcontainer-core#839]
### Describe the bug

Cannot install yarn dependencies 

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/BuilderIO/qwik

### Steps to reproduce

1. Go to https://stackblitz.com/~/github.com/BuilderIO/qwik
2. Try to install

### Expected behavior

I should be able to install the dependencies 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 781d7336116100a3cea72283913b570818ac125e
WebContainer = ea2f6b48b77806aba8e6fe3b6311530cc7674f64

Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108054180,
  "usedJSHeapSize": 69273836,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

This looks like an amazing tool!
Thanks for creating it!

**Comment by d3lm** [comment]
Hey @shairez 👋 Good to see you here and thanks for reporting this issue 🙏 The problem here is that qwik uses yarn berry which we don't currently support. We are aware of this and it's definitely on our roadmap to add support for yarn berry. We're talking to the qwik folks to see if there's a way we can work around this issue.

**Comment by shairez** [comment]
Hey brother! long time no speak :)

Awesome, happy to get the ball rolling on this one as I think this is a fantastic tool you guys built!

Keep up the good work! 💪

**Comment by SamVerschueren** [comment]
I tested this today actually (even made a PR to Qwik). So I think we can close this one.
