### ISSUE TITLE
BUG: Cannot create Nx workspaces

### ISSUE THREAD

**Issue by dpsthree** [stackblitz/webcontainer-core#84]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
When attempting to run npx create-nx-workspace. The terminates early with an error: 
NX ERROR  Nx failed to create a workspace.
![image](https://user-images.githubusercontent.com/1540699/119428091-e02a7e00-bcd1-11eb-99c7-0c6ef1d6ade0.png)

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-ett6nq

**To Reproduce**
1. Open a terminal within a stackblitz, Node instance 
2. Issue the command "npx create-nx-workspace"
3. Follow the prompts to create an Angular application

**Expected behavior**
It should complete the command and produce the boiler plate project files.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 59402264,
  usedJSHeapSize: 56654540,
  jsHeapSizeLimit: 4294705152
}

**Comment by d3lm** [comment]
Hey 👋 I have tested this again, and it doesn't seem to be an issue anymore. I can successfully create an Nx workspace via `npx create-nx-workspace`.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/12571019/220565453-916ff16a-9e59-4035-b6b8-db1248915ef2.png">

I am going to close this one, and if think there's still an issue, feel free to comment or open a new issue.
