### ISSUE TITLE
Failing yarn install

### ISSUE THREAD

**Issue by reemardelarosa** [stackblitz/webcontainer-core#840]
### Describe the bug

Unable to yarn install/npm install

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/BuilderIO/qwik/pull/1715

### Steps to reproduce

1. Open [Qwik Repository](https://stackblitz.com/~/github.com/BuilderIO/qwik/pull/1715) in Stackblitz
2. Check the console and wait for the message

```
❯ turbo
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
$ yarn node scripts/tools/preinstall-script.js
┌─ WARNING ────────────────────────────────────────────────────────────────────┐
│ It seems you are trying to use `yarn`. This is a compatibility layer which   │
│ uses `turbo` instead, a blazingly fast package manager designed for the web. │
│ If you wish to hide this warning, you can do so by setting `warnings.yarn =  │
│ false` inside "/home/.turbo/.turborc.json" or use `turbo` directly.          │
└──────────────────────────────────────────────────────────────────────────────┘
ERR!: Unknown command `node`

Try this: turbo --help

error Command failed with exit code 1
┌ [1/4] 🔍  Resolving dependencies
└ 𐄂 Failed
ERR!: Failed to resolve dependencies

error Command failed with exit code 1
```

### Expected behavior

It should run and install dependencies.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 781d7336116100a3cea72283913b570818ac125e
WebContainer = 3e4f172269cb19a250be0dfdff1ab657cb850d0e

Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 298959642,
  "usedJSHeapSize": 277095194,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by d3lm** [comment]
Hey there 👋 If I click on the link you provided and install the dependencies with `pnpm` because that's what that project uses it works fine. Can you provide more information?

**Comment by SamVerschueren** [comment]
Closing this as Qwik uses `pnpm` now which was different at the time this issue was created.

Also, in te mean time, we shipped native support for `yarn`, which we didn't have either back then. So opening the original PR link that was posted also seems to install (albeit it takes a while 😂 ).
