### ISSUE TITLE
tus-node-server cause the terminal freezes up

### ISSUE THREAD

**Issue by felixfong227** [stackblitz/webcontainer-core#844]
### Describe the bug

When trying to install `tus-node-server` will make the terminal freezes up, and that will lead to a failure to run the subsequent command (eg `yarn dev`) thus failing to run the project entirely

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-ibgayg

### Steps to reproduce

1. Run the project
2. Wait for all the packages to be installed
3. Create a terminal tab or watches the default one gets frozen upgets

### Expected behavior

That the project works and functions exactly like a local machine (GitHub Codespace)

1. Open Stackblitz project
2. Wait for all the packages to be installed
3. Wait for `yarn dev` to run

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Windows (Windows 11 Pro 22H2 ) | Linux (Manjaro 21.3.1)
- Browser: Brave 1.44.108 Chromium: 106.0.5249.103

### Additional context

Has disabled the Brave Shields

**Comment by Nemikolh** [comment]
Hi @felixfong227 ! :wave: 

I've reproduce the steps you described and I'm not hitting this issue. I think your might have hit an out of memory error?
For now I'll close this issue, feel free to reopen if you are still facing this issue and you want us to investigate this a bit more.
