### ISSUE TITLE
Closing the Create & Push Branch text box results in a push to main

### ISSUE THREAD

**Issue by LayZeeDK** [stackblitz/webcontainer-core#845]
### Describe the bug

Canceling a *Create & Push Branch* operation results in a push to the `main` branch.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/ngworker/lumberjack-next

### Steps to reproduce

1. I click *Create & Push Branch*.
2. A text box appears, asking for a branch name.
    ![image](https://user-images.githubusercontent.com/6364586/195800425-e33d4bc5-b39a-414e-96b3-0603a4847f3a.png)
3. I cancel the operation by pressing the *Escape* key.
4. Codeflow appears to attempt to push to the `main` branch.
    ![image](https://user-images.githubusercontent.com/6364586/195799349-5c1e475c-d072-4bac-bf90-0e9f4f8430d7.png)
6. With branch protection on the `main` branch of the repo, an error is displayed.
    ![image](https://user-images.githubusercontent.com/6364586/195799457-354d9fa6-0a6d-46ab-afca-c9db4e1074d6.png)
    Command output:
    ```
    > git push origin main:main
    remote: NULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNULNUL
    fatal: unable to access 'https://github.com/ngworker/lumberjack-next': The requested URL returned error: 403
    ```

### Expected behavior

Canceling the operation should not result in any operation.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = c994f4b06d30d4ac09341f7888800531bc4a8e9c
WebContainer = 3e4f172269cb19a250be0dfdff1ab657cb850d0e

Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 105988720,
  "usedJSHeapSize": 97006716,
  "jsHeapSizeLimit": 2112618496
}
```

**Comment by samdenty** [comment]
Thanks for finding this, a fix should be landing soon 👍
