### ISSUE TITLE
npm starts not running the server in browser

### ISSUE THREAD

**Issue by navingenex** [stackblitz/webcontainer-core#849]
### Describe the bug

After npm start i am getting 
Local:            http://localhost:3000
  On Your Network:  http://192.168.1.104:3000
https://webrtc--3000.local.webcontainer.io/
but these urls are not working.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/navingenex/webRTC

### Steps to reproduce

None

### Expected behavior

Should open the app in browser

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/37072571/195985977-388aa8ab-3fbc-48de-b28b-f9c1856f6df9.png)

### Platform

```
Version = 1.67.0
Hash = 38afc2533e9f1c1993b0ec404ee8058cfe0e0c99
WebContainer = 3e4f172269cb19a250be0dfdff1ab657cb850d0e

Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108567690,
  "usedJSHeapSize": 99586946,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

No

**Comment by SamVerschueren** [comment]
It looks like the package used uses something that's not yet implemented on our side. I created an issue internally to track this 👍 .

**Comment by d3lm** [comment]
Hey 👋 I have tried the project you have linked and it seems to work for me. Can you try again verify if you're still seeing the error?
