### ISSUE TITLE
issue with  importing packages referencing esm (Next.js template)

### ISSUE THREAD

**Issue by paulbrie** [stackblitz/webcontainer-core#850]
### Describe the bug

Hi,

I'm not sure, but I have the feeling that the web container with your default Next.js template configuration is not able to import packages which expose esm

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-q8tfpi?file=package.json,pages%2Findex.js

### Steps to reproduce

1. Start container
2. check logs
You should see:
```
...
error - ./node_modules/subjecto/dist/esm/index.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import Subject from "./subject";
| import Inspect from "./inspect";
| export { Subject, Inspect };
...

```

### Expected behavior

No error should appear. It runs well in your React templates and on my local machine.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/3997538/196014760-fa5de4a1-92be-4497-b075-9b1f261cf378.png)

### Platform

```
Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 94290515,
  "usedJSHeapSize": 89548459,
  "jsHeapSizeLimit": 4294705152
}
Hash = 3e4f172269cb19a250be0dfdff1ab657cb850d0e
```

**Comment by SamVerschueren** [comment]
Hi @paulbrie 👋 . Thanks for reaching out. I'm closing this issue as I get the same error when running the project on my local machine. So it's probably something with the setup of that project.

![image](https://user-images.githubusercontent.com/1913805/223707496-65769e4e-86e0-48c4-ae41-a7b91d4dcc24.png)
