### ISSUE TITLE
Codeflow: outdated svelte extension

### ISSUE THREAD

**Issue by sylwiavargas** [stackblitz/webcontainer-core#862]
### Describe the bug

From Dominik: 
> the svelte vscode extenion in codeflow ide is listed as v0.5.0, extension id svelte.svelte-vscode the same extension id on vscodium marketplace has v106.2.0

From Tigur:
> "Svelte for VS Code" in vscode is v106.2.0, but in codeflow it is marked as v0.5.0, which I am assuming is actually svelte2tsx which is currently in the 0.5.x version range.

### Link to the blitz that caused the error

n/a

### Steps to reproduce

n/a

### Expected behavior

updated extension

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

**Comment by dominikg** [comment]
Additional information from TheTiGuR on [discord](https://discord.com/channels/364486390102097930/1030123288376115260/1032113815850070057)

>  "Svelte for VS Code" in vscode is v106.2.0, but in codeflow it is marked as v0.5.0, which I am assuming is actually svelte2tsx which is currently in the 0.5.x version range.

**Comment by samdenty** [comment]
This was due to us building the repo from scratch - and not including the bit that updates the version 
https://github.com/sveltejs/language-tools/blob/cb3a1c17a9f86abe274c2c5f8e9f24f02869d7ba/.github/workflows/DeployExtensionsProd.yml#L28

Should be deployed with a fix soon 👍
