### ISSUE TITLE
Ports not visible in ports view → No way to use external ports

### ISSUE THREAD

**Issue by Explosion-Scratch** [stackblitz/webcontainer-core#863]
### Describe the bug

I can't seem to view ports in port view, this also happens when running `npx browser-sync start --server`

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/explosion-scratch/svelteflowy

### Steps to reproduce

1. Run project with `pnpm i && pnpm dev`
2. It says that it's running on port 8080
3. Port not shown in port view

### Expected behavior

Ports appear in the ports view

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 69b9b1602da27b7f44e9800c223182ce1a037ea8
WebContainer = 3c06ff333fff62d153837b0d0df85b8ed07b008f

Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72169303,
  "usedJSHeapSize": 69225991,
  "jsHeapSizeLimit": 2059403264
}
```

**Comment by Explosion-Scratch** [comment]
1: It opens the `http://localhost:8080`, my localhost. Same with adding `--host`, it just spits out an IP url, but that's my IP and the URL doesn't load.
2: No notifications of open ports
![image](https://user-images.githubusercontent.com/61319150/196937477-08a95d7d-abb4-4a3f-ac0c-f30fe73a6127.png)

3: No errors in devtools
![image](https://user-images.githubusercontent.com/61319150/196937638-82295c61-b0b6-4c18-89f1-92e070278642.png)

**Comment by Explosion-Scratch** [comment]
Update: Enabling third party cookies seems to fix this:

![image](https://user-images.githubusercontent.com/61319150/196941219-86bbf23d-bafc-42d9-8bce-72913e5c6b1a.png)
[Source](https://github.com/orgs/community/discussions/26316)

**Comment by SamVerschueren** [comment]
Oh, it was unclear you where using Brave. We should add that to the `Browser name` in the bug report. Because we have something in our docs about this. https://developer.stackblitz.com/platform/webcontainers/browser-config-brave#allowing-third-party-service-workers

Glad you found out and it is working now.

**Comment by Explosion-Scratch** [comment]
No, I'm not using Brave. I'm using Chrome

**Comment by SamVerschueren** [comment]
Oh really!? Interesting 🤔 . I'll bring this up to the team. Thanks for confirming you are using Chrome!

**Comment by Explosion-Scratch** [comment]
Yes, but this only happens with third party cookies disabled.
