### ISSUE TITLE
BUG: Cannot see if the server is up after using nodemon in the script , also it it(browser) broke completely and not working 

### ISSUE THREAD

**Issue by itsaniketnikam** [stackblitz/webcontainer-core#87]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-86mrve?file=index.js

**To Reproduce**

**Expected behavior**

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 70688561,
  usedJSHeapSize: 66160621,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by KwintenP** [comment]
Hi!

It's a known problem that the port is incorrectly removed from the UI. Someone from our team is actually working on this issue right now :).

I can't repro the server/browser blocking though. Feel free to add more info if you can help me to repro the other issue.

**Comment by itsaniketnikam** [comment]
I wanted mention that browser is not showing the response in get request as
per my code.
Attaching screenshot for your reference

Thanks & Regards,
Aniket Nikam
