### ISSUE TITLE
Hackernews Firebase Client Blocks Forever on StackBlitz

### ISSUE THREAD

**Issue by floodfx** [stackblitz/webcontainer-core#872]
## Summary
It appears that using the Firebase Client to query the HackerNews API on StackBlitz blocks forever.  To demonstrate, I've created the StackBlitz project: https://stackblitz.com/edit/hackernews-firebase-blocked?file=README.md

In the project we attempt to query the Firebase DB in two ways: 1) use the Firebase client and 2) use node-fetch.

There is only a single file: `src/firebase.ts`.

## Fails/Blocks in StackBlitz

Running this project in StackBlitz fails as the Firebase client query does not complete while the direct query does.

## Runs Locally

If you run this project on your local computer it will complete as expected with both the Firebase Client query AND the node-fetch query completing with 500 results.

### Link to the blitz that caused the error

https://stackblitz.com/edit/hackernews-firebase-blocked?file=README.md

### Steps to reproduce

1. Just load the StackBlitz Project: https://stackblitz.com/edit/hackernews-firebase-blocked?file=README.md
2. Notice the direct query returns and the firebase query blocks forever

### Expected behavior

It is expected that the Firebase Client should return just like it does locally.

StackBlitz Output:

```
$ ts-node ./src/firebase.ts
started firebase query
started direct query
waiting...
finished direct query 500
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
```

Local Output:
```bash
> ts-node ./src/firebase.ts

started firebase query
started direct query
waiting...
finished direct query 500
finished firebase query 500
waiting...
done!
```

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 222312099,
  "usedJSHeapSize": 214592591,
  "jsHeapSizeLimit": 4294705152
}
Hash = dfae8564d35fe429a0bab219bd7d77341f3ec782
```

### Additional context

It appears this stopped working over the last 10 days sometime.  The original project that stopped working was working correctly approximately ten days ago.  Original project: https://stackblitz.com/edit/liveviewjs-hackernews?file=README.md

**Comment by floodfx** [comment]
You mean does Firebase client connect over a websocket?  I don't know for sure but it seems like a reasonable guess considering it can push data changes to connected clients.  Did something change on the StackBlitz side to disallow websocket connections?  You should be able to run this same code "locally" and see it working if that is helpful to answer your question.

**Comment by SamVerschueren** [comment]
Yes, I tried it earlier on local and it does seem to work. Maybe Firebase pushed some changes which broke it on WebContainer. I have to dig deeper on this.

**Comment by floodfx** [comment]
Thanks!  LMK if I can be helpful.
