### ISSUE TITLE
Refreshing doesn't retain state

### ISSUE THREAD

**Issue by nandorojo** [stackblitz/webcontainer-core#878]
### Describe the bug

I'm not sure if this is a bug or an intended behavior, but it is a deal breaker for me if it's intended.

Say I edit some files. Then I refresh the page. On local VSCode, all my files I edited are still there & ready to be staged. But on Stackblitz, using Codeflow, when I refresh, all my changes are lost.

Is this expected behavior?

### Link to the blitz that caused the error

Private repo, sorry

### Steps to reproduce

1. Make some changes in a codeflow repo, and save them
2. Don't commit anything
3. Refresh

### Expected behavior

All file changes should still be there.

### Parity with Local

- [ ] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

I couldn't reproduce on VSCode...I can do this locally with stackblitz too if you think this is a bug.

### Platform

- OS: macOS
- Browser: Chrome

**Comment by sylwiavargas** [comment]
Hi @nandorojo! Thank you for raising this. 

For now, the changes you introduce [don't persist between sessions](https://developer.stackblitz.com/codeflow/codeflow-faq#does-my-code-persist-between-sessions) so you need to remember to commit your work often or before closing the browser. 

This is, however, one of the features that we are prioritizing and that's on our product roadmap so stay tuned for the feature announcement 💙
