### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by jimshtepa** [stackblitz/webcontainer-core#88]
---
name: Bug report
about: Create a report to help us improve
title: 'adding 'failure to enable es modules'
labels: ''
assignees: ''

---

**Describe the bug**
Adding "type":"module" to the package.json file doesn't enable es modules and attempt to import libraries doesn't work. No error is displayed in the console log, instead it silently returns empty line

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-promises?file=app.js

**To Reproduce**
1. Go to 'terminal'
2. run 'node app.js'
3. Scroll down to terminal
4. See empty line

**Expected behavior**
a string 'it works'

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 76550322,
  usedJSHeapSize: 68992126,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by KwintenP** [comment]
Hi!

This is a current limitation indeed: https://github.com/stackblitz/webcontainer-core#limitations

We are working on getting this in in the next coming weeks though! 🙏 for reporting.

Duplicate #6
