### ISSUE TITLE
[CodeFlow] Update Volar extension to v1.0

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#880]
# Description

The Volar extension reached 1.0 mid october. The version currently available in CodeFlow is outdated and flags  `<script setup lang="ts">` as invalid. That's the default vite.new/vue-ts script tag.

https://github.com/johnsoncodehk/volar

I'm sure @johnsoncodehk would love to help bring better support for Volar on Stackblitz.

**Comment by johnsoncodehk** [comment]
FYI :)
- https://github.com/johnsoncodehk/volar/pull/1916
- https://github.com/johnsoncodehk/volar/issues/2046#issuecomment-1287825923

**Comment by FossPrime** [comment]
Volar v1+ had been working for weeks... it stopped working in the few days. Possibly with Volar v1.0.24
