### ISSUE TITLE
Socket hang up error when running stackblitz in Chrome 

### ISSUE THREAD

**Issue by Indrajeetsing** [stackblitz/webcontainer-core#883]
### Describe the bug

When i open the stackblitz link in chrome it gives error. It works fine if I open in Microsoft Edge.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Ftable-http-example.ts

### Steps to reproduce

Open the link and try to install dependencies and try to run the project.

### Expected behavior

It should run the project.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots
![image](https://user-images.githubusercontent.com/22735028/198843735-063fff6d-fd34-4125-96a7-76d66c948a92.png)

### Platform

```
Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 88778354,
  "usedJSHeapSize": 85984458,
  "jsHeapSizeLimit": 2172649472
}
Hash = a0ea75dd36396805bd36e49d0b54d86602583e15
```

**Comment by jrvidal** [comment]
@Indrajeetsing This should be fixed now, can you confirm it is working for you?

**Comment by jrvidal** [comment]
Closing this since it seems inactive. Feel free to open a new issue if the problem persists. Thanks!
