### ISSUE TITLE
Astro Project Dev Server does not run on codeflow

### ISSUE THREAD

**Issue by fessehaye** [stackblitz/webcontainer-core#884]
### Describe the bug

`astro dev` runs when you open the link and mentions localhost:3000 but a window is not open and the port is not being detected when viewing the port tab on Stackblitz. `*.astro` files also do not have syntax highlighting compared to when I open the project without codeflow.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/fessehaye/BC-Smash-Events

### Steps to reproduce

1. Go to link attached
2. Open Astro files
3. Notice how there is no highlighting

1. Go to link attached
2. wait for astro dev
3. Notice no browser or port is open

### Expected behavior

Opening the link should run a working local version of my public repo.
Opening astro files should give correct syntax highlighting.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = c7fe78196769b35793fecf40e3093a41e39b005d
WebContainer = a0ea75dd36396805bd36e49d0b54d86602583e15

Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96439631,
  "usedJSHeapSize": 91797235,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Also does not work on Firefox

**Comment by samdenty** [comment]
@fessehaye did you enable the `Astro` extension? when I do that, I get syntax highlighting

https://user-images.githubusercontent.com/13242392/200129433-603c2a2f-afb5-4d92-99a9-6ebce254bd5e.mp4

**Comment by fessehaye** [comment]
Astro is working properly now. Closing this
