### ISSUE TITLE
Yarn install can't import a dependency from another one of our github repos.

### ISSUE THREAD

**Issue by jtfairbank** [stackblitz/webcontainer-core#885]
### Describe the bug

Yarn install can't import a dependency from another one of our github repos.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/distributeaid/distributeaid.org

### Steps to reproduce

1. Run `yarn install` in the terminal.
2. See the error message.

### Expected behavior

I expect `yarn install` to successfully install all dependencies.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![Screenshot from 2022-10-30 21 20 01@2x](https://user-images.githubusercontent.com/529759/198913004-ed53d0d8-8522-487b-be0b-f549318fcc31.png)

### Platform

```
Version = 1.67.0
Hash = c7fe78196769b35793fecf40e3093a41e39b005d
WebContainer = a0ea75dd36396805bd36e49d0b54d86602583e15

Browser name  = Firefox
Full version  = 104.0
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
performance.memory = undefined
```

**Comment by Nemikolh** [comment]
Hi @jtfairbank ! :wave: 

I have a good news, specifying git dependencies with `yarn` using the format `owner/repo` now works in stackblitz :smiley: I tried your project and the installed step worked for me. Let us know if you run into other issues!
