### ISSUE TITLE
TailwindCSS Intellisense not working properly

### ISSUE THREAD

**Issue by sylwiavargas** [stackblitz/webcontainer-core#886]
### Describe the bug

We are unable to get the auto-complete suggestions of classNames while using TailwindCss in Codeflow IDE.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/AnnuCode/auth-form

### Steps to reproduce

1. Open the repo
2. Install the extension
3. Try adding a TailwindCSS class name to see no auto-complete suggestions

### Expected behavior

auto-complete suggestions

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 47585c10a80107bd0379d40d5a66694889640242
WebContainer = a0ea75dd36396805bd36e49d0b54d86602583e15

Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 219526821,
  "usedJSHeapSize": 152320325,
  "jsHeapSizeLimit": 2172649472
}
```

Also, our user reported this issue on:
Browser: Chrome
OS: Windows 10 Home

### Additional context

[Link to the original tweet](https://twitter.com/_AnnuSingh/status/1587070526433857536?s=20&t=ONoT-UHnFSqINZQXD9CHaw)

**Comment by IdacraBackup** [comment]
There is actually a VS Code error that is displayed when trying to enable the TailwindCSS Intellisense extension:

`Loaded postcss v8.4.18: /home/AnnuCode/auth-form/node_modules/postcss
Loaded tailwindcss v3.2.1: /home/AnnuCode/auth-form/node_modules/tailwindcss
[Error - 21:54:16] Tailwind CSS: Cannot read properties of undefined (reading 'modifier')
TypeError: Cannot read properties of undefined (reading 'modifier')
    at api.addVariant (file:///home/AnnuCode/auth-form/node_modules/tailwindcss/lib/lib/setupContextUtils.js:578:40)
    at eval (file:///home/AnnuCode/auth-form/node_modules/tailwindcss/lib/lib/setupContextUtils.js:538:38)
    at eval (file:///home/.codeflow/extensions/vscode-tailwindcss/dist/tailwindServer.js:692:4435)
    at Array.forEach (<anonymous>)
    at XCt (file:///home/.codeflow/extensions/vscode-tailwindcss/dist/tailwindServer.js:692:3920)
    at eval (file:///home/.codeflow/extensions/vscode-tailwindcss/dist/tailwindServer.js:692:288)
    at Generator.next (<anonymous>)
    at i (file:///home/.codeflow/extensions/vscode-tailwindcss/dist/tailwindServer.js:1:1134)`

**Comment by samdenty** [comment]
This should be fixed:

Uploading CleanShot 2022-12-06 at 12.55.03.mp4…

**Comment by IdacraBackup** [comment]
@samdenty did you intend to upload something? I see "Uploading CleanShot 2022-12-06 at 12.55.03.mp4…"

**Comment by samdenty** [comment]
@IdacraBackup sorry, fixed

**Comment by samdenty** [comment]
@IdacraBackup see https://github.com/tailwindlabs/tailwindcss/discussions/9634
