### ISSUE TITLE
Error: Next.js requires React 18.2.0 to be installed.

### ISSUE THREAD

**Issue by propimentel** [stackblitz/webcontainer-core#888]
### Describe the bug

When booting an environment for Next.js from the Home page, the "start" crashes since the Next dependency was updated to 13 but the React version is still set to 17.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs

### Steps to reproduce

1. At the home screen click on the "Boot a fresh environment in milliseconds. -> Popular -> Nextjs".
2. The error will show up in the terminal after the "yarn dev" cmd.

### Expected behavior

The Nextjs project should properly boot.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 177433725,
  "usedJSHeapSize": 161866261,
  "jsHeapSizeLimit": 2172649472
}
Hash = a0ea75dd36396805bd36e49d0b54d86602583e15
```

**Comment by sylwiavargas** [comment]
Hi @propimentel! Thank you for the report.
We updated the starter so now it's Nextjs 13 + React 18 and no errors ✅
