### ISSUE TITLE
Dark Console Text Output in Dark Theme

### ISSUE THREAD

**Issue by jonathansampson** [stackblitz/webcontainer-core#89]
**Describe the bug**

Text being logged to the console is black for both light and dark themes making it difficult to read (likely not possible for many users) when using the dark theme.

**Screenshots**

![image](https://user-images.githubusercontent.com/815158/119510161-ea329800-bd36-11eb-8521-b98a264136b0.png)

![image](https://user-images.githubusercontent.com/815158/119510335-0c2c1a80-bd37-11eb-8644-cb9c86af800f.png)

**Comment by KwintenP** [comment]
Hi!

🙏 for reporting. This does seem like a bug on our end!

**Comment by SamVerschueren** [comment]
This is actually already being tracked here https://github.com/stackblitz/core/issues/1450.
