### ISSUE TITLE
turbo-linux-64/bin/turbo: line 2: a command can only contain words and redirects

### ISSUE THREAD

**Issue by VictorEffectiv** [stackblitz/webcontainer-core#893]
### Describe the bug

i cannot open the tldraw repo using pr.new

![image](https://user-images.githubusercontent.com/100563134/200074887-234bb714-9bba-45d3-9735-8a60f0b08839.png)

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/tldraw/tldraw

### Steps to reproduce

1. Go to 'https://github.com/tldraw/tldraw'
2. type pr.new in front of the url and press enter

### Expected behavior

tldraw monorepo starts without problems

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 1a4deabb18324f3c325cabe933565c73623c5676
WebContainer = a0ea75dd36396805bd36e49d0b54d86602583e15

Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 141070479,
  "usedJSHeapSize": 134640735,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by SamVerschueren** [comment]
Something seems to be going wrong when running `turbo` in StackBlitz. It only seems to build the `@tldraw/tldraw-example` package, while on local it compiles everything.

![image](https://user-images.githubusercontent.com/1913805/224013207-9a806eb0-3d25-4b49-b1e4-05c52c12f5d3.png)
![image](https://user-images.githubusercontent.com/1913805/224013251-30e17f91-5347-4b2c-aa8b-1763ef8cfbd0.png)

**Comment by samdenty** [comment]
This now works, if you kill the terminal once it starts and instead execute:

```bash
yarn install && yarn build  &> /dev/null; yarn start
```

to build all the packages before running the start command
