### ISSUE TITLE
cypress install stuck and crashed my browser instance

### ISSUE THREAD

**Issue by danielrz** [stackblitz/webcontainer-core#894]
### Describe the bug

this [repo](https://github.com/mutoe/vue3-realworld-example-app) is the famous vue 3 real world example.
running the app with stackblitz works well but executing the yarn test:unit command I get this error:

No version of Cypress is installed in: /home/.cache/Cypress/10.9.0/Cypress
Please reinstall Cypress by running: cypress install

And when I run cypress install, it just stuck and after a while it crashes my browser (memory getting high)

![image](https://user-images.githubusercontent.com/3119826/200124622-c5c16b92-9671-4e7e-9c5e-2c197c3dd3fb.png)

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/mutoe/vue3-realworld-example-app

### Steps to reproduce

1. open a new terminal window
2. run yarn test:unit
3. run cypress install

### Expected behavior

it should install cypress successfully and most important, should not crash my browsder (Google Chrome latest version)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 1a4deabb18324f3c325cabe933565c73623c5676
WebContainer = a0ea75dd36396805bd36e49d0b54d86602583e15

Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 319200571,
  "usedJSHeapSize": 303724979,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by dgilsonAfelio** [comment]
That's interesting to understand how run a browser (chrome, electron...) into a webcontainer (already a browser).
Even for Cypress or Karma for example.

**Comment by d3lm** [comment]
Hey 👋 It's not possible to run native apps (e.g. Electron apps) in the browser and consequently in WebContainer. You can, however, use playwright and configure it to use a remote instance of Chrome. See [this blog post](https://medium.com/@jfgreffier/how-to-create-a-sandbox-for-end-to-end-testing-cffe06976308) for example. I am going to close this for now because it's not actionable at this point. There are plans to support Cypress though at some point but I can't speak to an exact timeline.
