### ISSUE TITLE
Modules fail without error

### ISSUE THREAD

**Issue by prettydiff** [stackblitz/webcontainer-core#9]
**Describe the bug**
I have attempted to execute the Node starter demo in Chrome using modules and it does not work.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-v6m1qa

**To Reproduce**
I tried two different approaches:

1. Add `"types": "module"` to the package.json file.
2. Change the file name from `index.js` to `index.mjs`

In both approaches I attempted to execute these code samples:

```javascript
import fs from "fs";
fs.readdir("./", function (err, list) {
  console.log(err);
  console.log("");
  console.log(list.join(", "));
});
```

```javascript
import ("fs").then(
  fs.readdir("./", function (err, list) {
    console.log(err);
    console.log("");
    console.log(list.join(", "));
  })
);
```

**Expected behavior**
Expected output:
```
null

index.js, package-lock.json, package.json
```

The expected output occurs if I use old common JS approach: `let fs = require("fs");`.  In the case of modules nothing outputs to the terminal, not even error messaging.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  **Windows 10** on a desktop
 - Browser [e.g. chrome, safari] **Chrome**
 - Version [e.g. 22] **90**

**Additional context**
The expected Node error messaging does display if not appeasing Node's requirements for supporting modules, which are either rename the file from extension `.js` to `.mjs` or adding the `"types": "module"` to the package.json file.

**Comment by EricSimons** [comment]
Ah yeah, ESM is one of the current limitations of WebContainer's nodejs runtime: https://github.com/stackblitz/webcontainer-core#limitations

Bit tricky to get those parts of v8 to work in-browser :) WIP!

**Comment by KwintenP** [comment]
We currently don't support ESM modules yet. We should have better error handling/warnings though.

Duplicate #6

**Comment by prettydiff** [comment]
WOW, super fast responses.  I just noticed this on the readme.  Thanks.
