### ISSUE TITLE
NestJS-based app only booting occasionally

### ISSUE THREAD

**Issue by michaelbromley** [stackblitz/webcontainer-core#90]
**Describe the bug**
I am attempting to run Vendure (which is a GraphQL server based on NestJS) in the webcontainer: https://stackblitz.com/edit/vendure-test?file=index.js

On running `npm run start` I almost always see the following output:

```
/projects/vendure-test 6s
❯ npm run start
$ node index.js
info 5/25/21, 3:46 PM - [Vendure Server] Bootstrapping Vendure Server (pid: 5)... 

/projects/vendure-test
❯ 
```

i.e. the app starts to bootstrap but then stops, with no error given. Very occasionally it does successfully boot (it happened like 2 times out of 20 attempts), so I suspect there is something internal going wrong and the error is being swallowed - perhaps memory related.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/vendure-test?file=index.js

**To Reproduce**
run `npm run start` in the console

**Expected behavior**
It should successfully bootstrap the app, which would look like:
```
info 25/05/21, 14:51 - [NestApplication] Nest application successfully started
info 25/05/21, 14:51 - [Vendure Server] ================================================
info 25/05/21, 14:51 - [Vendure Server] Vendure server (v1.0.0) now running on port 3000
info 25/05/21, 14:51 - [Vendure Server] ------------------------------------------------
info 25/05/21, 14:51 - [Vendure Server] Shop API:     http://localhost:3000/shop-api
info 25/05/21, 14:51 - [Vendure Server] Admin API:    http://localhost:3000/admin-api
info 25/05/21, 14:51 - [Vendure Server] ================================================
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Brave

**Smartphone (please complete the following information):**
 - Version [e.g. 22] 1.24 (Chromium 90)

**Comment by KwintenP** [comment]
This is a bug indeed 🙏 
Thanks for repoting @michaelbromley!

**Comment by michaelbromley** [comment]
@jrvidal Thanks! This is great, I'm gonna have some fun playing around with this! Would be an amazing showcase of the tech to have a full e2e headless e-commerce solution (Vendure + Next.js Commerce) running entirely in Stackblitz! 

Thanks to the Stackblitz team for this incredible work 💯
