### ISSUE TITLE
I can not install Github Copilot Plugin

### ISSUE THREAD

**Issue by muhammadomais** [stackblitz/webcontainer-core#901]
### Describe the bug

I am not able to install the Github Copilot Plugin. If its a Visual Code than why I dont have access to that

### Link to the blitz that caused the error

https://pr.new/~/github.com/stackblitz/docs/pull/40

### Steps to reproduce

1- Goto : https://github.com/stackblitz/docs/pull/40
2- Gotto plugin
3- In search type cop

### Expected behavior

I should be able to install any plugin i want right, which i have on visual code

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

CodeFlow Screenshoot
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/9904352/202913416-54a03a72-4f0e-4dab-8c08-9912ee7fd168.png">

Visual Code Screen Shoot
![image](https://user-images.githubusercontent.com/9904352/202913444-94eb308c-5716-4057-9eb6-66695619d65d.png)

### Platform

```
Version = 1.67.0
Hash = 3f0da22fd4d64ee969b596d789da2142b5d54de9
WebContainer = 79ba5d6ed4650f43d3d2f1721ce6e5bef04fff66

Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 68502305,
  "usedJSHeapSize": 63044825,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by Nemikolh** [comment]
Hi @muhammadomais! :wave: 

We currently don't support any extension store. [See my comment](https://github.com/stackblitz/webcontainer-core/issues/905#issuecomment-1464148344) on #905
