### ISSUE TITLE
Symlinks no longer working: `ln: EACCES: permission denied, symlink`

### ISSUE THREAD

**Issue by rigor789** [stackblitz/webcontainer-core#907]
### Describe the bug

Hi, we were using symlinks in the `/usr/local/bin` folder to provide "global" commands/shortcuts for NativeScript Preview so users could run `ns preview` to restart the session in case they stopped the process.

To achieve that, we were running 
```bash
ln -s ./node_modules/.bin/preview-cli /usr/local/bin/ns
```
However this started giving us a permission error:
```bash
ln: EACCES: permission denied, symlink './node_modules/.bin/preview-cli' -> '/usr/local/bin/ns'
```

Is this intended? If so, what are our options going forward?

### Link to the blitz that caused the error

https://stackblitz.com/edit/nativescript-stackblitz-templates-sec13z?file=.stackblitzrc

### Steps to reproduce

1. Open linked StackBlitz
2. wait for dependencies to install, and the start command to run
3. see `jsh: command not found: ns`

---

We are adding the symlinks/aliases in the `./node_modules/.bin/setup-nativescript-stackblitz` script that is set as the `startCommand` in the `.stackblitzrc`

### Expected behavior

We would expect the `ns preview` command to work, and call the linked script (`./node_modules/@nativescript/stackblitz/dist/index.js`).

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/879060/204238194-b93d0916-598f-4113-994f-35b0364f55bc.png)

### Platform

- OS: n/a
- Browser: n/a
- Version: n/a

**Comment by jrvidal** [comment]
@rigor789 :wave: Thanks for reporting! Sorry we broke your workflow :disappointed:  This is indeed working "as intended", as we now observe file permissions in WebContainer.

You can create the symlink in `<project>/node_modules/.bin` and it should work. Would that mitigate the problem?

**Comment by SamVerschueren** [comment]
As @jrvidal mentioned. Binaries that are put in the `node_modules/.bin` directory are automatically picked up. So writing the `ns` binary to `node_modules/.bin/ns` should fix the issue.

**Comment by rigor789** [comment]
Thanks for the update, will try linking to `.bin` instead (seems like these are now added to the "PATH").

I believe that should work going forward 👍

However we do have quite a number of user projects that use the previous commands, and no easy way to update them (we only provide the templates), so any prior projects will be stuck. The script that creates the symlinks comes from `@nativescript/stackblitz` on npm (currently set to `0.0.5` in the project 
templates). Since the version is pinned, even if we release a patch, old projects will fail to run.
 
Using a version range would've helped, but in that case the package-lock would still force the older version unless manually deleted/updated.

Do you think write access to `/usr/local/bin` would be considered? I believe most unix systems already allow writing to it without `sudo`.

**Comment by d3lm** [comment]
> I believe most unix systems already allow writing to it without `sudo`.

Hm I am not sure. FWIW, I am on macOS and I can't write to `/usr/local/bin`. I think for that to work you'd have to change the permissions, which many users do, especially on macOS with homebrew, or use `sudo`.

**Comment by rigor789** [comment]
@d3lm ah that might be the case, I do have Homebrew. For my `/usr/local/bin` folder I'm the owner, and it's in the admin group:
```bash
$ ls -al /usr/local
...
drwxrwxr-x  286 rigor789  admin   8.9K Nov 17 15:00 bin
...
```

And `/usr/bin`:
```
drwxr-xr-x  1012 root  wheel    32K Aug 24 10:59 bin
```

Not sure if these were changed by brew or come like this by default?

**Comment by rigor789** [comment]
Linking to `node_modules/.bin` works if anyone runs into this. For older projects that we cannot update, we'll just recommend people to update manually if necessary.
