### ISSUE TITLE
Update Required

### ISSUE THREAD

**Issue by rogadev** [stackblitz/webcontainer-core#909]
### Describe the bug

Using pre-`+layout.svelte` version of SvelteKit in demo project. Minor update required including filenames changed to match current convention.

GOOD FIRST ISSUE.

### Link to the blitz that caused the error

https://stackblitz.com/edit/daisyui-sveltekit?file=src%2Fapp.css

### Steps to reproduce

1. Go to stack blitz link and see for yourself.

### Expected behavior

Follow SvelteKit docs and update. (Link to the update with information on how to run migration script.)[https://github.com/sveltejs/kit/discussions/5774] Follow these steps to fix.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90400817,
  "usedJSHeapSize": 79196325,
  "jsHeapSizeLimit": 4294705152
}
Hash = 9c9dcc6595e0cd7e762bc7a4fa3b63b76489d957
```

**Comment by d3lm** [comment]
Hey there 👋 Thanks for reporting this issue. The project you've linked seems to be a user project so you'd need to contact the owner to change it. Our official SvelteKit started is updated, so I am going to close this one. If you're running into any more issues, feel free to open a new one.
