### ISSUE TITLE
Unable to install storybook using cli

### ISSUE THREAD

**Issue by IanVS** [stackblitz/webcontainer-core#911]
### Describe the bug

I wanted to use stackblitz to reproduce an issue in storybook, but running `npx sb@next init` in a vite repo resulted in an error:

```
     ERR!: Unknown command `info`

Try this: turbo --help
```

I think this is because the script is trying to call `npm info`, which it seems turbo does not wrap.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-djt1kk?file=index.html&terminal=dev

### Steps to reproduce

in the terminal, run `npx sb@next init`

### Expected behavior

Storybook should be installed.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 73033141,
  "usedJSHeapSize": 69778093,
  "jsHeapSizeLimit": 4294705152
}
Hash = 0478c85eccde42845cdffe4745a763e1f3cb6e82
```

**Comment by d3lm** [comment]
Hey there 👋 Thanks for reporting this issue. I can confirm that the `info` command is currently no implemented. You could work around the issue if you use `pnpx`. We have full support for `pnpm` and `yarn`, but not yet `npm`. We are working on that but I can't speak to an exact timeline for npm.

**Comment by jrvidal** [comment]
Feel free to track progress for `npm` in https://github.com/stackblitz/webcontainer-core/issues/1070!
