### ISSUE TITLE
Slidev project doesn't work with Firefox but works with Chrome

### ISSUE THREAD

**Issue by edimitchel** [stackblitz/webcontainer-core#913]
### Describe the bug

I tried to create a reproduction link for a slidev issue. But I get an issue on firefox which is probably tight to the way SB is doing FS for Firefox.

Here two reproduction links which is mostly about auto installer which is not working because it doesn't detect presence of packages installed:

 - https://stackblitz.com/edit/slidev-eqt8eb?file=package.json
 - https://stackblitz.com/edit/slidev-jx9jwl?file=package.json

On Chrome no issue is detect.

I raised the issue on slidev for more details: https://github.com/slidevjs/slidev/issues/780

### Link to the blitz that caused the error

https://stackblitz.com/edit/slidev-eqt8eb?file=package.json
https://stackblitz.com/edit/slidev-jx9jwl?file=package.json

### Steps to reproduce

Just run the stackblitz and see that on the first repro link that slidev package is not detected.
On the second, issue is about slidev theme not detected and tried to install it globally with npm.

### Expected behavior

Just work like Chrome does

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Firefox
- Version: 107

**Comment by edimitchel** [comment]
I think it's correlated with pnpm: "jsh: command not found: command"

**Comment by d3lm** [comment]
Hey 👋 Thanks for reporting this issue. It does look like there is some issue with Firefox. We have to investigate, or maybe you have some more info that could be useful?

Also, the `command` command should be implemented at this point so that shouldn't be an issue anymore 🤔

**Comment by jrvidal** [comment]
:wave: @edimitchel I'm revisiting this issue and:
* The first repro link fails in all Chrome, Firefox, and locally as a native Node project.
* The second repro link works fine for me in both Chrome and Firefox.

Have you found more issues with Slidev on FF?

**Comment by edimitchel** [comment]
I confirmed that the issue is not reproductible anymore, is there any explanation ? Firefox update ? Stackblitz Web Containers fix ?
