### ISSUE TITLE
Failed to load config

### ISSUE THREAD

**Issue by noxidsoft** [stackblitz/webcontainer-core#914]
### Describe the bug

`~/projects/vitejs-vite-ezrycf
❯ npm install && npm run dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/4] 🔍  Resolving dependencies
└ Completed in 0.112s
┌ [2/4] 🚚  Fetching dependencies
│ info pruneDeps Excluding 14 dependencies. For more information use `--verbose`.
└ Completed in 2.187s
┌ [3/4] 🔗  Linking dependencies
└ Completed in 0.402s
info security We found `install` scripts which turbo skips for security reasons. For more information see https://turbo.sh/install-scripts.
└─ esbuild@0.15.17
info Some packages were automatically replaced with polyfills. For more information see https://turbo.sh/polyfills.
└─ esbuild@0.15.17 => esbuild-wasm@0.15.17

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 2.738s
$ vite
failed to load config from /home/projects/vitejs-vite-ezrycf/vite.config.js
error when starting dev server:
file:///home/projects/vitejs-vite-ezrycf/node_modules/@vitejs/plugin-vue/dist/index.mjs:2
import { isCSSRequest, normalizePath as normalizePath$1, transformWithEsbuild, formatPostcssSourceMap, createFilter } from 'vite';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
    at async loadConfigFromBundledFile (file://file:///home/projects/vitejs-vite-ezrycf/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62879:21)
    at async loadConfigFromFile (file://file:///home/projects/vitejs-vite-ezrycf/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62764:28)
    at async resolveConfig (file://file:///home/projects/vitejs-vite-ezrycf/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62388:28)
    at async createServer (file://file:///home/projects/vitejs-vite-ezrycf/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:61688:20)

~/projects/vitejs-vite-ezrycf`

I'm on a Windows 10 (latest) with Chrome browser (latest).

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-ezrycf?file=index.html&terminal=dev

### Steps to reproduce

Scroll down to Trying Vite online - https://v2.vitejs.dev/guide/#browser-support
I chose Javascript -> Vue, which opens the link with broken startup message(s).

Failed to run start command.

### Expected behavior

Start command runs, without errors and tool is ready to use.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/729135/205538535-e2ddcf10-c05a-4b6f-9639-c8816ac7b7ae.png)

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80478448,
  "usedJSHeapSize": 65348016,
  "jsHeapSizeLimit": 4294705152
}
Hash = b6c96f782a49b3e017dca41830943768f8acbe40
```

**Comment by fvsch** [comment]
Thanks for the report @noxidsoft. This seems to be an upstream issue with the Vite project and their example using the `@vitejs/plugin-vue` plugin:
https://github.com/vitejs/vite/issues/11190
