### ISSUE TITLE
terminal dies after running a test with vitest

### ISSUE THREAD

**Issue by steve-py96** [stackblitz/webcontainer-core#921]
### Describe the bug

Just opening the reproduction link crashes the terminal after a ran test (it doesn't take any further inputs anymore)

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-smyhuu?file=package.json&terminal=test

### Steps to reproduce

1. open the link
2. let the test finish
3. try to do anything in the terminal or try to open a new one

### Expected behavior

* terminal still works
* new terminal is openable

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 126934464,
  "usedJSHeapSize": 100054432,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6ebe18b1e1db1833797e3e4eb6ff802c375ee61b
```

### Additional context

(stackblitz rocks <3)

**Comment by SamVerschueren** [comment]
Thanks @steve-py96 for this report. It might be a bug introduced by a recent release. I'll look into it but can't offer any timing on what this might be fixed.

**Comment by d3lm** [comment]
Hey @steve-py96 👋 I have tested your project again and it doesn't seem to be no longer an issue. Can you confirm this?

**Comment by d3lm** [comment]
Nice. Thanks for confirming 🙏
