### ISSUE TITLE
SBOX_FATAL_MEMORY_EXCEEDED

### ISSUE THREAD

**Issue by evanlong0926** [stackblitz/webcontainer-core#922]
### Describe the bug

浏览器页面崩溃

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-kun5yb?file=app.vue

### Steps to reproduce

1. 刷新浏览器
2. 等待资源加载

### Expected behavior

1. 完成依赖安装
2. 资源加载完成并显示页面

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![微信截图_20221217141401](https://user-images.githubusercontent.com/52912949/208228235-05976a7c-870f-438b-bf8b-0f56656c55a0.png)

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101514556,
  "usedJSHeapSize": 72724704,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6ebe18b1e1db1833797e3e4eb6ff802c375ee61b
```

**Comment by AbdealiLoKo** [comment]
I also get the same issue with: https://stackblitz.com/edit/node-angular-transloco
Just open the link and `npm install` works fine. But the `npm start` crashes the tab

![image](https://user-images.githubusercontent.com/2200743/208434915-eb277a12-d64b-43ea-b032-ec798bb33474.png)

I use:
OS: Windows 10
CPU: i7-1065G7
RAM: 16GB
Chrome: 108.0.5359.99

**Comment by angelhdzmultimedia** [comment]
Same here. After many years using StackBlitz, now I'm getting this error.
Don't know what else to do to fix it. 😪

**Comment by angelhdzmultimedia** [comment]
### Update

It looks like after a while of using it, memory gets bloated.
I refreshed it, and now it's working (until it happens again).

**Comment by SamVerschueren** [comment]
WebContainer does use quite a bit of memory. We're having plans to improve this in the future. But apparently Chrome crashes with that error if Chrome itself runs out of memory. The only thing that might help at this point is if you would disable some/all extensions and make sure you don't open multiple StackBlitz projects at the same time.

Here's some additional information https://www.chromestory.com/2020/06/sbox-fatal-memory-exceeded/

**Comment by angelhdzmultimedia** [comment]
> WebContainer does use quite a bit of memory. We're having plans to improve this in the future. But apparently Chrome crashes with that error if Chrome itself runs out of memory. The only thing that might help at this point is if you would disable some/all extensions and make sure you don't open multiple StackBlitz projects at the same time.
> 
> Here's some additional information https://www.chromestory.com/2020/06/sbox-fatal-memory-exceeded/

Thank you for your time and for your so helpful response. Wishing you health, peace, and success.

**Comment by SamVerschueren** [comment]
Going to close this issue as I think there's not much we can do on our end.
