### ISSUE TITLE
ENOENT: no such file or directory, open '/home/projects/nuxt-starter-kun5yb/node_modules/.vite/deps_temp/package.json'

### ISSUE THREAD

**Issue by evanlong0926** [stackblitz/webcontainer-core#923]
### Describe the bug

ENOENT: no such file or directory, open '/home/projects/nuxt-starter-kun5yb/node_modules/.vite/deps_temp/package.json'

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-kun5yb?file=app.vue

### Steps to reproduce

1. 进入项目
2. 等待资源加载，等待加载完成
3. 刷新几次

### Expected behavior

它应该能找到 `package.json`

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76188674,
  "usedJSHeapSize": 68865262,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6ebe18b1e1db1833797e3e4eb6ff802c375ee61b
```

**Comment by SamVerschueren** [comment]
Thanks for creating this issue @evanlong0926. I created an internal ticket and linked this issue.

**Comment by evanlong0926** [comment]
这个问题好像被解决了，我也没有发现什么问题存在
