### ISSUE TITLE
BUG: Not all local files are visible in the file explorer, lots of empty folders

### ISSUE THREAD

**Issue by nksaraf** [stackblitz/webcontainer-core#93]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-fzv5ay?file=package.json

**To Reproduce**

**Expected behavior**

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**
<img width="247" alt="Screen Shot 2021-05-26 at 4 50 34 AM" src="https://user-images.githubusercontent.com/11255148/119580397-297fd980-bd75-11eb-98e9-839d76cd256e.png">
<img width="271" alt="Screen Shot 2021-05-26 at 4 51 09 AM" src="https://user-images.githubusercontent.com/11255148/119580428-3ac8e600-bd75-11eb-86ea-a4080db07c13.png">

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 100769721,
  usedJSHeapSize: 85591977,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by KwintenP** [comment]
Hi!

This is indeed not completely correct. Since this implementation is very alpha, we only allow uploading certain files. We need to make some changes to how they are handled internally to allow uploading all files. 

The fact that `.ts` files are not uploaded is a bug though. 🙏 for reporting!!

**Comment by jrvidal** [comment]
This should be fixed now :tada: Thanks for the report.
