### ISSUE TITLE
Sample page not rendering google map

### ISSUE THREAD

**Issue by mattratliff** [stackblitz/webcontainer-core#930]
### Describe the bug

When I load the following page an error is presented when trying to load the map

### Link to the blitz that caused the error

https://stackblitz.com/github/googlemaps/js-samples/tree/sample-event-simple?file=README.md

### Steps to reproduce

Go to page and let the page load to view the error

### Expected behavior

That it works correctly

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/54595565/210142555-b7af73a9-daf3-44da-8f8e-26e7a48c184c.png)

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 75261700,
  "usedJSHeapSize": 64329904,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6ebe18b1e1db1833797e3e4eb6ff802c375ee61b
```

**Comment by SamVerschueren** [comment]
Hi @mattratliff. The page describes how you can see what's wrong here.

![image](https://user-images.githubusercontent.com/1913805/216605811-21b6442e-ae28-49c0-bdcb-6d87a9fb8ed0.png)

It links to [this page](https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error). You probably need to whitelist the domain for the provided API key. Google Maps probably allows traffic coming from `localhost`, but we're technically not really localhost (although it only runs on your local machine). There's not much we can do on our side. The [only solution here is to allow the domain](https://developers.google.com/maps/documentation/javascript/get-api-key#restrict_key).
