### ISSUE TITLE
TypeScript in Next.js v13 breaks preview

### ISSUE THREAD

**Issue by vicary** [stackblitz/webcontainer-core#934]
### Describe the bug

After renaming one of the page extensions to `.tsx`, the Next.js dev server will setup TypeScript automatically.

The preview pane stays permanently broken afterwards.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-oq8zan

### Steps to reproduce

1. Fork the stock Next.js template from StackBlitz
2. Rename index.js into index.tsx

### Expected behavior

Preview pane works normally.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/85772/211183843-0935c58e-3963-466d-9ec5-05464031f56d.png)

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 159811791,
  "usedJSHeapSize": 153867275,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8dd2e1d89f7d2e6b43a2b4af08588e58ffd9a2ea
```

**Comment by d3lm** [comment]
Hey 👋 Thanks for reporting your issue. If I click on your project it's missing some files. Can you please update the project to contain all necessary files so the project would work as expected with JS? We can then have another look at it and try to reproduce your issue.

**Comment by vicary** [comment]
@d3lm done, please check again!

**Comment by vicary** [comment]
It should render "Hello World" but the preview pane is blank, using Next 12 and React 17 doesn't have this issue. Only Next 13 and React 18 gives me a blank screen.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/85772/220690437-6912d6c4-51de-4db9-b052-b492edd5ea25.png">

**Comment by d3lm** [comment]
Did you run this locally? Cause I don't see anything on the page either when I run this locally.

**Comment by vicary** [comment]
@d3lm Right, because it was a `<Head>` element. This is an incorrect reproduction script.

The issue was the default Next.js template comes with Next 12 and React 17, I tried to upgrade them to Next 13 and React 18 and it gives me a blank screen.

Now the default Next.js template is already Next 13 and React 18, it also works like normal now. I believe you guys have already fixed it somewhere back then, closing this one.
