### ISSUE TITLE
Blank page in preview

### ISSUE THREAD

**Issue by cdes** [stackblitz/webcontainer-core#935]
### Describe the bug

I just opened https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-tailwindcss?file=README.md and the preview is like this:

<img width="1510" alt="CleanShot 2023-01-08 at 10 31 04@2x" src="https://user-images.githubusercontent.com/1207863/211185388-3af20521-4fb0-4389-a4fc-64ba8eeaab73.png">

### Link to the blitz that caused the error

https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-tailwindcss?file=README.md

### Steps to reproduce

1. visit https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-tailwindcss?file=README.md
2. wait

### Expected behavior

It should build and preview the content

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1510" alt="CleanShot 2023-01-08 at 10 31 04@2x" src="https://user-images.githubusercontent.com/1207863/211185388-3af20521-4fb0-4389-a4fc-64ba8eeaab73.png">

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 109477662,
  "usedJSHeapSize": 86296286,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8dd2e1d89f7d2e6b43a2b4af08588e58ffd9a2ea
```

**Comment by jrvidal** [comment]
:wave: @cdes I can see the preview fine. Do you see any suspicious messages in the devtools? Could it be some cookie-related issue (see https://webcontainers.io/guides/browser-config) ?
