### ISSUE TITLE
Stackblitz cannot find the spago package

### ISSUE THREAD

**Issue by mikesol** [stackblitz/webcontainer-core#938]
### Describe the bug

When doing `pnpm i -D spago purescript && pnpm spago init && pnpm spago install`, I get the following error:

```bash
❯ pnpm i -D spago purescript && pnpm spago init && pnpm spago install
 WARN  deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
 WARN  deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
Already up to date
Progress: resolved 109, reused 87, downloaded 0, added 0, done
Done in 3.2s
Downloading the spago binary failed. Please try reinstalling the spago npm package.
Downloading the spago binary failed. Please try reinstalling the spago npm package.
```

### Link to the blitz that caused the error

https://stackblitz.com/github/mikesol/purescript-webgpu

### Steps to reproduce

Run `pnpm i -D spago purescript && pnpm spago init && pnpm spago install`

### Expected behavior

I'd expect `spago` to kick in, as it does locally & online via gitpod & codespaces.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76
performance.memory = {
  "totalJSHeapSize": 91611874,
  "usedJSHeapSize": 72952338,
  "jsHeapSizeLimit": 4294705152
}
Hash = 66cf64d5daaa658854f44d80ebff4b4ffb72d9a1
```

### Additional context

Thanks for your help!

**Comment by SamVerschueren** [comment]
Hi @mikesol. It does find the spago package, the problem here is that it spawns a native binary under the hood which doesn't work out of the box. It can only work if spago was also compiled to WebAssembly. But we can't just run arbitrary binaries in a web browser unfortunately.
