### ISSUE TITLE
Terminal Bug

### ISSUE THREAD

**Issue by Kavi-ya** [stackblitz/webcontainer-core#939]
### Describe the bug

I can not typing commands in the terminal

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-ffwn51?file=index.js

### Steps to reproduce

Recheck server and terminal problems

### Expected behavior

Server error or network connection problem

### Parity with Local

- [x] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![2](https://user-images.githubusercontent.com/83932877/211972256-52bf4409-03a3-4a6b-9701-a13b19c6edd9.PNG)

### Platform

```
Browser name  = Chrome
Full version  = 109.0.0.0
Major version = 109
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 125727696,
  "usedJSHeapSize": 120337564,
  "jsHeapSizeLimit": 2172649472
}
Hash = 66cf64d5daaa658854f44d80ebff4b4ffb72d9a1
```

**Comment by SamVerschueren** [comment]
If the terminal doesn't render a prompt, it's because WebContainer couldn't boot. Do you happen to see any errors in the devtools console? That would happen identify the issue.

**Comment by SamVerschueren** [comment]
Closing this for now as we didn't hear back. [This issue](https://github.com/stackblitz/webcontainer-core/issues/952) might be related so if you have additional information feel free to post it there.
