### ISSUE TITLE
component is not working

### ISSUE THREAD

**Issue by FahimeKhandan** [stackblitz/webcontainer-core#946]
### Describe the bug

the vue component named "myComponent" is not rendering properly

### Link to the blitz that caused the error

https://stackblitz.com/edit/vite-vue-3-markdoc-shiki-twoslash?file=vite.config.ts

### Steps to reproduce

you can see <myComponent/> in the live page

### Expected behavior

we expect <myComponent/> to render the vue component

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76725865,
  "usedJSHeapSize": 75455077,
  "jsHeapSizeLimit": 4294705152
}
Hash = f46762818326be16a78de429bec3a3775ca1af32
```

**Comment by SamVerschueren** [comment]
Hi @FahimeKhandan. I ran the project locally and it's the same result. So I don't think this has anything to do with StackBlitz. Did you try to run this locally?

![image](https://user-images.githubusercontent.com/1913805/214790123-2a8521a6-008c-4043-bf50-1447acd0239f.png)

**Comment by FahimeKhandan** [comment]
Yes i did run it locally, not working...

**Comment by SamVerschueren** [comment]
Closing this issue as it's probably something with the setup of that project and has nothing to do with StackBlitz.

**Comment by FahimeKhandan** [comment]
Ok, thanks.
