### ISSUE TITLE
Dropdown is not working in Vue 3 + Tailwind CSS

### ISSUE THREAD

**Issue by Nehasoni988** [stackblitz/webcontainer-core#947]
### Describe the bug

I am trying to run the tailwind CSS dropdown in Vue3, so I opened this already-created StackBlitz demo. Initially, I thought that my example is not working but I copy paste the code of dropdown from the [documentation](https://flowbite.com/docs/components/dropdowns/) but that too is not working.

The problem is that the dropdown is not opening up.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-8rkhr2?file=src%2FApp.vue,package.json

### Steps to reproduce

1. Go to this link- https://stackblitz.com/edit/vitejs-vite-8rkhr2?file=src%2FApp.vue,package.json
2. Try to open any dropdown. (The blue button is copy-pasted from the documentation and the below dropdowns are my code.)
3. You should see that after clicking on the dropdown, it is not opening up.

### Expected behavior

The dropdowns should open normally. 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 116507392,
  "usedJSHeapSize": 112564628,
  "jsHeapSizeLimit": 4294705152
}
Hash = f46762818326be16a78de429bec3a3775ca1af32
```

**Comment by SamVerschueren** [comment]
Hi @Nehasoni988. I have no idea why it's not working, but I downloaded the project to my local machine, installed the dependencies and it's also not working locally. So I don't think this is an issue with StackBlitz, but more with the example itself.

Did the project work locally for you?

**Comment by SamVerschueren** [comment]
Closing this issue as I believe it has nothing to do with StackBlitz or WebContainer as I get the same behaviour when running the project locally.

Feel free to create a new issue or respond to this one if you get different results on local with the same project.
