### ISSUE TITLE
It might be confusing to users that they need to click the save button before their code will actually work in the terminal

### ISSUE THREAD

**Issue by kmwarter** [stackblitz/webcontainer-core#953]
### Describe the bug

The directions in index.js say to just
"// run `node index.js` in the terminal"

Maybe it should say
"// press save button and then do run `node index.js` in the terminal"

Because my code would not run until i pressed the save button in the upper left hand corner. In a time of autosave this took me about 10 minutes to figure out. I would worry about a new programmer thinking there is just something wrong with their code and giving up.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-2wsqwd?file=index.js

### Steps to reproduce

console.log hello world in index.js
Notice that running the run index.js command does not work
press the save button
it does work

### Expected behavior

I would expect the directions to be more clear or perhaps it should not require actually saving for what is currently in the index.js file to be run. 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 109.0.0.0
Major version = 109
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84869690,
  "usedJSHeapSize": 79050838,
  "jsHeapSizeLimit": 4294705152
}
Hash = 531fb2e92e5ccee952ba7d51e833953c98c61706
```

**Comment by SamVerschueren** [comment]
Hi @kmwarter 👋 !

We do give a visual indication that the file is "dirty", just like it does on local.

![image](https://user-images.githubusercontent.com/1913805/217181018-82c6a4f2-5772-46e4-a69f-b791191996c5.png)

If you want, you can also turn on auto-save under settings, and change the compile trigger to `Edit (auto)`.

![image](https://user-images.githubusercontent.com/1913805/217181274-afd8151c-becd-4b75-9c3f-ae8cac655778.png)

**Comment by SamVerschueren** [comment]
While testing this I noticed some weird behaviour with the compile trigger though. The changes will reflect when running `node index.js`, but aren't persisted on our backend. Tracking this bug internally.
