### ISSUE TITLE
Qwik starter: squigglies appear after an edit

### ISSUE THREAD

**Issue by sylwiavargas** [stackblitz/webcontainer-core#955]
### Describe the bug

As soon as I edit and save a file (in this case, `index.tsx`), the editor gets flooded with the red squigglies typically signifying a syntax error. 
<img width="1439" alt="Screen Shot 2023-01-31 at 10 59 51 PM" src="https://user-images.githubusercontent.com/45401242/215903481-eb5908c1-b5d4-4eca-9760-b13a4dfc7043.png">

### Link to the blitz that caused the error

https://stackblitz.com/edit/qwik-starter-cevvhd?file=README.md,src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Go to the starter
2. Open `src/routes/index.tsx`
3. Make an edit and save

### Expected behavior

No squigglies

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

I've checked the project on my local machine
<img width="1022" alt="Screen Shot 2023-01-31 at 11 03 48 PM" src="https://user-images.githubusercontent.com/45401242/215903923-3d86448e-ef86-43fb-a6d2-c9bfbe537dee.png">

### Platform

```
Browser name  = Chrome
Full version  = 109.0.0.0
Major version = 109
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112859450,
  "usedJSHeapSize": 82415618,
  "jsHeapSizeLimit": 2172649472
}
Hash = 522185bb0134fb732ed5ecb9887332d7f888ce1b
```

### Additional context

[First reported here](https://twitter.com/literalPie/status/1620546746505129985?s=20&t=GTQFAZe_dOIZge1RmBTtpQ)

**Comment by HeyGarrison** [comment]
@sylwiavargas Do they eventually go away once the server is built for you?

**Comment by sylwiavargas** [comment]
They don't, sadly. Made an extended video now:

https://user-images.githubusercontent.com/45401242/215905131-4af45666-a90c-4093-ae30-0b7ff8967638.mov

**Comment by SamVerschueren** [comment]
This should be fixed now.
