### ISSUE TITLE
Boot container failed to load

### ISSUE THREAD

**Issue by KeithPrinkey-ops** [stackblitz/webcontainer-core#957]
**Is your feature request related to a problem? Please describe:**

web container doesn't load

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 . Here's an issue that might be related https://github.com/stackblitz/webcontainer-core/issues/952.
