### ISSUE TITLE
I Cant use Screaming frog

### ISSUE THREAD

**Issue by agracia-foticos** [stackblitz/webcontainer-core#959]
### Describe the bug

When i crawl this url 
https://nuxtstartersz58za-ha2j--3000.local-credentialless.webcontainer.io

with screaming frog, returns 404

![image](https://user-images.githubusercontent.com/77386602/217178020-fdab7dfe-075c-4810-93fc-540711a68198.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-sz58za?file=README.md

### Steps to reproduce

1. Do crawler with screaming frog
2. returns 404 first page

### Expected behavior

returns 404

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 109.0.0.0
Major version = 109
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58374855,
  "usedJSHeapSize": 55613319,
  "jsHeapSizeLimit": 2172649472
}
Hash = 2913a9f2fedb71678a44d5a6b5e0b08a6f00d17f
```

**Comment by SamVerschueren** [comment]
Hi @agracia-foticos 👋 . That is correct, this is not possible. The thing is that the "server" we spin up only runs in your browser that you use. This means that if you would start an Express.js server, it's also not possible to use something like Postman or curl to send requests to that server.

This is not something that can be fixed, we are limited to the sandbox of the browser and we can't expose that to the outside unfortunately.
