### ISSUE TITLE
Install package globally to reuse command without npx (like in local)

### ISSUE THREAD

**Issue by RawZ06** [stackblitz/webcontainer-core#96]
### **Is your feature request related to a problem? Please describe.**
Create a global npm repository to install packages globally and have all commands without npx in the project. 
For example, if I dev nestjs project, i would like "nest" command globally to be more efficient. 

### **Describe the solution you'd like**
Create hidden folder inside the project, with a second node_modules and package.json, and all dependencies installed with "-g" flag, will be installed here. 
Add this folder in the path for all command can be used in the terminal.

### **Describe alternatives you've considered**
Before that, use npx to execute commands installed in the current project and don't reinstall it each time

**Comment by SamVerschueren** [comment]
Hi @RawZ06! We talked with each other in Discord about this one. This feature just landed in production so feel free to try it out. In a Next.js project you can now run `next dev` directly without npx 🙏 .

Happy coding!
