### ISSUE TITLE
New Terminal

### ISSUE THREAD

**Issue by XFrineX** [stackblitz/webcontainer-core#962]
### Describe the bug

when I click new terminal, it doesn't allow me to run commands

### Link to the blitz that caused the error

https://stackblitz.com/edit/frine-is-super-cool-and-his-bot-is-as-well?file=package.json,.eslintrc.json,config.json,.gitignore,index.js

### Steps to reproduce

1. got to the bottom of the screen
2. see terminal?
3. click the "+"
4. There
5. it wont let me run anything

### Expected behavior

When I click new, it would allow me to run commands

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90814295,
  "usedJSHeapSize": 77665303,
  "jsHeapSizeLimit": 2020605952
}
Hash = 927bd077ab89da68c6338c4363cc22e79cccb4ef
```

**Comment by SamVerschueren** [comment]
Is there any error in the DevTools? That might help to know what's going wrong.

**Comment by SamVerschueren** [comment]
Closing this due to lack of information. Feel free to open a new issue if you still run into this 🙏 .
