### ISSUE TITLE
Angular Sample Project stuck on Running start command

### ISSUE THREAD

**Issue by MeganBurns** [stackblitz/webcontainer-core#964]
Following the Angular tutorial to generate a ready-made project in Stackblitz. When clicking the link to generate the sample project Stackblitz is stuck on the 'running start command' and the preview pane does not load. Tried generating it in Chrome and Edge, was stuck idling in both browsers.
https://angular.io/start#create-the-sample-project

![image](https://user-images.githubusercontent.com/56340299/218941239-778560fd-cfb6-4208-b66c-7ae815f913ec.png)

**Comment by MeganBurns** [comment]
Hi @Nemikolh,

Thank you for the response.

I believe it is an issue with the proxy server I have been accessing StackBlitz from.

I'm happy to close the issue.

**Comment by Nemikolh** [comment]
No problem! Feel free to reopen if you think there might be more to it. 👍
