### ISSUE TITLE
Codeflow: `Git: Unknown subcommand: rename` when creating a new branch

### ISSUE THREAD

**Issue by Jutanium** [stackblitz/webcontainer-core#967]
### Describe the bug

Creating a new branch errors the editor with `Git: Unknown subcommand: rename`
(See steps to reproduce and screenshot)

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/withastro/docs

### Steps to reproduce

- Open Codeflow via pr.new
- Make changes
- GitHub tab says "Ready to make changes?" Hit the Open a new PR button
- Codeflow tells me I don't have write access to the repo (actually, I do). Offers to create a branch on my GitHub account, press the button

### Expected behavior

- Since I have write access to the repo, it should let me create a branch _on_ the repo
- If I create a new branch, don't crash

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/4033662/219797419-618c080b-7b39-473e-b83b-4b71a495b6dc.png">

### Platform

```
Version = 1.72.0
Hash = e6aaaf1b03dbb6d61cf3d7d4587c2cb175785891
WebContainer = 927bd077ab89da68c6338c4363cc22e79cccb4ef

Browser name  = Chrome
Full version  = 110.0.0.0
Major version = 110
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 118930860,
  "usedJSHeapSize": 111608172,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by Jutanium** [comment]
Console output: [stackblitz.com-1676670589967.log](https://github.com/stackblitz/webcontainer-core/files/10771900/stackblitz.com-1676670589967.log)

**Comment by HeyGarrison** [comment]
hey @Jutanium! Does Astro org allow REST API access for StackBlitz OAuth app? (you can check that [here](https://github.com/settings/connections/applications/edf57e21e7a45ecb97d2))

**Comment by SamVerschueren** [comment]
@HeyGarrison I think this has to do with the fact we currently don't support the `git rename` command, rather than something with the API access.

@Jutanium We currently don't have support yet for `git rename`. I'll create a ticket internally to track this. Thanks for reporting!

**Comment by SamVerschueren** [comment]
Oh, maybe it has something to do with the REST API (sorry, my bad). Like @HeyGarrison said, make sure to check that page to see if the settings are correct.

But separate from that, we should support `git rename` as well.

**Comment by samdenty** [comment]
we shipped support for `git remote rename`, not sure if this fixed the issue @Jutanium
