### ISSUE TITLE
BUG: environment variables don't work in terminal

### ISSUE THREAD

**Issue by connorjclark** [stackblitz/webcontainer-core#97]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**

Type in terminal:

```
/projects/nextjs-hde56y
❯ echo $CHROME_PATH
Cannot read property 'replace' of undefined

/projects/nextjs-hde56y
❯ echo $ASDWQE
Cannot read property 'replace' of undefined

/projects/nextjs-hde56y
❯ echo $HOME
Cannot read property 'replace' of undefined

/projects/nextjs-hde56y
❯ echho $PATHH
Cannot read property 'replace' of undefined

/projects/nextjs-hde56y
❯ echho $PATH
Cannot read property 'replace' of undefined

```

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 84237848,
  usedJSHeapSize: 79113420,
  jsHeapSizeLimit: 4294705152
}

**Comment by SamVerschueren** [comment]
Hi @connorjclark! You are right, this does not work right now. We have the `env` command where you can see the environment variables. Setting environment variables work though, like `HELLO=world env` will show you that `HELLO` is set.

As in the other issue for the `time` command, we are planning to add more features to the shell implementation, as well as this one.

**Comment by jrvidal** [comment]
FWIW we've haphazardly fixed the spurious errors like `Cannot read property 'replace' of undefined`.

**Comment by kirjavascript** [comment]
Support for shell variables has now been added to webcontainer - you should be able to run things like `echo $HOME` and `echo $PATH` and have it work!
