### ISSUE TITLE
Control which binaries are downloaded

### ISSUE THREAD

**Issue by Rich-Harris** [stackblitz/webcontainer-core#972]
**Is your feature request related to a problem? Please describe:**

Looking at the network tab when initialising a WebContainer, I see this:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1162160/220225966-36b2c0b3-c566-48f7-b9a3-1007107e52a8.png">

A sizeable proportion of the total data transferred when setting up a WebContainer appears to be the `pnpm` and `yarn` binaries. In a constrained environment like learn.svelte.dev, where users don't have access to the terminal, they are unused. It would be good for performance if we had the ability to control what was downloaded.

**Describe the solution you'd like:**

Without having a better understanding of how everything actually works it's hard to suggest an API, but something like this perhaps?

```js
const instance = await WebContainer.boot({
  commands: ['node', 'turbo', 'chmod', 'touch']
});

const process = await instance.spawn('yarn'); // throws helpful error
```

As an aside, I couldn't find documentation on what commands are available — is there a list somewhere?

**Comment by jrvidal** [comment]
:wave: Thanks for the report. Who is the initiator of those requests? FWIW I would expect them to come from some `<link rel="preload">` tags.

**Comment by Rich-Harris** [comment]
The initiator is `headless` — when I click on that, it reveals that they are indeed from `<link rel="preload">`:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/1162160/220358054-fb0e6089-a654-46a8-b79b-e60ee4dfd980.png">

**Comment by dominikg** [comment]
It could also be nice to have a mode where commands are lazily downloaded on first use. 

Yes, this could limit offline mode, but if they are never used anyways, the traffic is avoided altogether.

**Comment by jrvidal** [comment]
We've disabled lazy-loading for API consumers for now :tada:

**Comment by Rich-Harris** [comment]
woo! an uncached load of https://learn.svelte.dev/tutorial/welcome-to-svelte is down to 1.88MB 🥳
