### ISSUE TITLE
Using WebContainers in chrome extensions

### ISSUE THREAD

**Issue by JulienVanelian** [stackblitz/webcontainer-core#977]
Can WebContainers be used in a chrome extension? 
If so, what would be the steps?

Thanks

**Comment by SamVerschueren** [comment]
Hey @JulienVanelian! That's an interesting idea for sure! I don't really know if it would be possible, maybe just give it a try and see if it works? As long as you're able to load in the WebContainer API package, I guess it should technically work.

**Comment by SamVerschueren** [comment]
Closing this as it's not related to a bug or feature request regarding WebContainers.
