### ISSUE TITLE
how to change registry of npm

### ISSUE THREAD

**Issue by abchexuzheng** [stackblitz/webcontainer-core#981]
show we use private package in webcontainer

**Comment by SamVerschueren** [comment]
Duplicate of #21. It's currently not yet possible. It's on our roadmap but I can't give an estimation on when it will be supported.

**Comment by dxw0127** [comment]
+1

**Comment by drfattytuna** [comment]
+1

**Comment by SamVerschueren** [comment]
@foreverzmy Please read the linked issue instead https://github.com/stackblitz/webcontainer-core/issues/21#issuecomment-1857842039
