### ISSUE TITLE
how to change the host of localhost server

### ISSUE THREAD

**Issue by abchexuzheng** [stackblitz/webcontainer-core#982]
https://localhost5173-3ca0--5173.local-corp.webcontainer.io/
when i create a vite server , i can visit it on this host,but couse CORS i want to change the host like *****.com

**Comment by SamVerschueren** [comment]
Hi @abchexuzheng 👋 . The host can not be changed to something random as that's part of how we can make the server work in your browser. If you want to enable cors and you own the server, you could add `webcontainer.io` to the whitelisted domain. If you don't own the server, then the only option is to use something like the [Allow CORS](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en-GB) Chrome extension.

**Comment by kc0tlh** [comment]
@abchexuzheng are you attempting to connect to a private NPM registry? This is a feature of our [Enterprise plan](https://stackblitz.com/enterprise) and I would be happy to share more info if relevant!
