### ISSUE TITLE
Can I change the host of webContainer node server

### ISSUE THREAD

**Issue by abchexuzheng** [stackblitz/webcontainer-core#983]
![image](https://user-images.githubusercontent.com/20961278/222403394-b4d15464-f8b4-475f-b18f-2297fc271be4.png)

I want to download some file by using nodejs in webContainer,but i have the CORS problem, Can I change the origin of nodejs

**Comment by SamVerschueren** [comment]
Please continue the discussion in #982.

As explained there, no it's not possible. The only way you can work around this is by setting up a proxy yourself (by using Cloudflare Workers or AWS Lambda Functions). Or by using the [Allow Cors](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en-GB) Chrome plugin.

**Comment by abchexuzheng** [comment]
> Please continue the discussion in #982.
> 
> As explained there, no it's not possible. The only way you can work around this is by setting up a proxy yourself (by using Cloudflare Workers or AWS Lambda Functions). Or by using the [Allow Cors](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en-GB) Chrome plugin.

![image](https://user-images.githubusercontent.com/20961278/222411298-56f11f5b-8196-4f88-aa39-1bf352651101.png)

you mean i can startup a html server just like the image, but how i can make webcontainer to use my website and get the hash code
