### ISSUE TITLE
Listen for file system changes

### ISSUE THREAD

**Issue by paoloricciuti** [stackblitz/webcontainer-core#988]
**Is your feature request related to a problem? Please describe:**
With the current api there's no way to run code when some file/folder get's added or removed from the virtual file system. This can happen for example by running a command. If you want to show a FileSystem tree in your UI it's important to keep it in sync with the virtual file system and sometimes running the sync after a command run it's not enaugh (for example there are long running processes that generate files and you want those to be visible in the UI).

**Describe the solution you'd like:**
Add a webcontainer.fs.watch command that receive a callback that runs whenever the filesystem changes.

**Describe alternatives you've considered:**
Right now i'm running a parallel task with chokidar and i manually parse the logs from chokidar but that's not a wonderful solution at all and it's very risky.

**Comment by SamVerschueren** [comment]
Hey @paoloricciuti 👋 . Yes, we currently don't expose a way to watch a file or folder with WebContainer API but that's definitely a valid feature request. I created an internal ticket to track this.

**Comment by paoloricciuti** [comment]
> Hey @paoloricciuti 👋 . Yes, we currently don't expose a way to watch a file or folder with WebContainer API but that's definitely a valid feature request. I created an internal ticket to track this.

Thank you very much, it would be very much appreciated

**Comment by WNemencha** [comment]
This could do the job maybe? https://github.com/wheatjs/webcontainer-reactive-fs

**Comment by kirjavascript** [comment]
Hi :wave:. `fs.watch` is now available inthe WebContainer API as of version 1.1.8 :tada: 

https://webcontainers.io/api#%E2%96%B8-watch
