### ISSUE TITLE
BUG: HttpError: Failed to fetch dependencies

### ISSUE THREAD

**Issue by critesjosh** [stackblitz/webcontainer-core#99]
---
name: Bug report
about: Create a report to help us improve
title: 'HttpError: Failed to fetch dependencies'
labels: ''
assignees: ''

---

**Describe the bug**
I run `yarn` in the project root with the following `package.json`:

```
{
  "name": "webpage",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "watchify index.js -o static/bundle.js & lite-server"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@celo/contractkit": "^1.1.0",
    "watchify": "^4.0.0",
    "web3": "^1.3.5"
  },
  "devDependencies": {
    "browserify": "^17.0.0",
    "lite-server": "^2.6.1"
  }
}
```

and get this error: 

```
warn preInstall No repository field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 0.352s
┌ [2/3] 🚚  Fetching dependencies
└ 𐄂 Failed
HttpError: Failed to fetch dependencies

error Command failed with exit code 1
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/celo-tx-lesson?file=webpage%2Fpackage.json

**To Reproduce**
1. Go to https://stackblitz.com/edit/celo-tx-lesson
2. `cd` into the webpage directory
3. run `yarn` in the terminal

**Expected behavior**
the packages should install

**Version of webcontainer**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 538266974,
  usedJSHeapSize: 521884186,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by KwintenP** [comment]
Hi!

It seems like you changed the blitz after reporting this issue. There doesn't seem to be a `webpage` directory.

I do see that now it fails for another reason. 

```ERR!: No git binary found in $PATH```

We do indeed not yet have git support in the terminal (it's coming soon!). I wonder what tries to use the git binary though as we don't execute postInstall scripts by default. I'll take a look.

In the meantime, can you update the blitz to reflect the initial error? 🙏 !

**Comment by critesjosh** [comment]
Maybe I forgot to save it after I added the `webpage` directory. It should be there now.

**Comment by critesjosh** [comment]
<img width="1148" alt="Screen Shot 2021-05-28 at 9 37 50 AM" src="https://user-images.githubusercontent.com/18372439/119992339-7263a800-bf98-11eb-96e5-071043f0b76c.png">

Looks like it was a problem with the `contractkit` package. I removed it and it worked.

**Comment by d3lm** [comment]
Yep, indeed. Something is failing on the server side when `@celo/contractkit` is added as a dependencies. In particular, it's `@celo/utils` which has some dependencies, e.g. `country-list` which return with `Bad Request`. This seems to be a bug. Thanks for reporting the issue.

**Comment by d3lm** [comment]
Hey 👋 I have tested your project again with both `yarn` and `npm` and it seems to work now. We also recently released support for native npm and we have deprecated `turbo` (our in-house package manager we used before in place of `npm`).

Can you check again?
