### ISSUE TITLE
Serve in COEP `credentialless` mode when browser supports it. 

### ISSUE THREAD

**Issue by nicksrandall** [stackblitz/webcontainer-core#993]
I could do this myself if I was able to self host (#991) but until then, it would be great if the webcontainer iframe could be served with `COEP: credentialless` on browsers that support it and then fallback to `require-corp` for all other browsers. 

Sounds like this was being looked into based on: https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/#:~:text=Ideally%2C%20all%20browsers,require%2Dcorp.

**Comment by nicksrandall** [comment]
Looks like this is already supported on stackblitz. Is there a way to enable this?

**Comment by SamVerschueren** [comment]
Currently there's no way to enable this, but you're right that this is a sensible thing to add an option for. I'll create a ticket for it and link this issue so we can keep you updated.

**Comment by nicksrandall** [comment]
It would be great if the iframe URL could also serve the origin trial headaer for Firefox so that firefox can opt into the behavior as well.

**Comment by jrvidal** [comment]
In [@webcontainer/api@1.1.0](https://www.npmjs.com/package/@webcontainer/api/v/1.1.0), `WebContainer#boot()` now takes a `coep` parameter that you can set to `credentialless`. Does this solver you issue @nicksrandall ?

**Comment by nicksrandall** [comment]
Yes, that works for me. Thank you!
