### ISSUE TITLE
When I drag n drop folder for uploading, it instead forks the project

### ISSUE THREAD

**Issue by vedmant** [stackblitz/webcontainer-core#996]
### Describe the bug

When I drag n drop folder for uploading, it instead forks the project

https://user-images.githubusercontent.com/5052406/224380193-c73d4f55-0f35-4121-a675-485198feb1ae.mp4

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-cnflwp?file=README.md

### Steps to reproduce

Drag n drop the folder into files list

### Expected behavior

Should upload the folder

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

https://user-images.githubusercontent.com/5052406/224380193-c73d4f55-0f35-4121-a675-485198feb1ae.mp4

### Platform

```
Browser name  = Chrome
Full version  = 104.0.0.0
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72134621,
  "usedJSHeapSize": 66640065,
  "jsHeapSizeLimit": 4294705152
}
Hash = 9bdac2de468a4854f7bacb85c771c93d5676829b
```

**Comment by ykmsd** [comment]
Hi @vedmant, thanks for reporting this! This issue should be fixed now, please let us know if you still encounter it 🙏

**Comment by FossPrime** [comment]
@ykmsd Any chance the March 24th fix could have caused https://github.com/stackblitz/core/issues/1762 to make a comeback?

CloudFlow is refusing to take Drag-N-Drop uploads. Individual files, multiple files, folders, they all fail.

![Screenshot 2023-06-02 00 49 42](https://github.com/stackblitz/webcontainer-core/assets/876076/4c3f9073-3e8e-4604-8c2a-8716ae0258a1)
